// Generated by tools/world-audio/prepare.mjs from tools/world-audio/voices.json. Do not edit by hand.
// Each line: [bank, offset, duration, speaker]; offsets and durations are seconds within the bank's sprite under
// public/assets/audio/voice/. `lines` are the spoken lines the game plays (src/content/voice.ts); `story` voices the
// text-first dialogue (src/content/dialogue.ts) by its string keys, for a future conversation interface.

export const VOICE_AUDIO = {
  "version": 2,
  "base": "assets/audio/voice/",
  "banks": {
    "hero-1": {
      "file": "voice-hero-1",
      "speaker": "hero",
      "set": "spoken",
      "duration": 6.9473,
      "lines": 1
    },
    "hero-2": {
      "file": "voice-hero-2",
      "speaker": "hero",
      "set": "spoken",
      "duration": 11.5713,
      "lines": 2
    },
    "hero-3": {
      "file": "voice-hero-3",
      "speaker": "hero",
      "set": "spoken",
      "duration": 7.8813,
      "lines": 2
    },
    "hero-4": {
      "file": "voice-hero-4",
      "speaker": "hero",
      "set": "spoken",
      "duration": 9.4933,
      "lines": 2
    },
    "hero-5": {
      "file": "voice-hero-5",
      "speaker": "hero",
      "set": "spoken",
      "duration": 8.656,
      "lines": 2
    },
    "hero-6": {
      "file": "voice-hero-6",
      "speaker": "hero",
      "set": "spoken",
      "duration": 7.8707,
      "lines": 2
    },
    "hero-7": {
      "file": "voice-hero-7",
      "speaker": "hero",
      "set": "spoken",
      "duration": 11.6513,
      "lines": 3
    },
    "hero-8": {
      "file": "voice-hero-8",
      "speaker": "hero",
      "set": "spoken",
      "duration": 11.098,
      "lines": 3
    },
    "hero-9": {
      "file": "voice-hero-9",
      "speaker": "hero",
      "set": "spoken",
      "duration": 11.1533,
      "lines": 3
    },
    "hero-10": {
      "file": "voice-hero-10",
      "speaker": "hero",
      "set": "spoken",
      "duration": 11.7527,
      "lines": 3
    },
    "hero-11": {
      "file": "voice-hero-11",
      "speaker": "hero",
      "set": "spoken",
      "duration": 12.0087,
      "lines": 3
    },
    "hero-12": {
      "file": "voice-hero-12",
      "speaker": "hero",
      "set": "spoken",
      "duration": 9.0967,
      "lines": 2
    },
    "hero-13": {
      "file": "voice-hero-13",
      "speaker": "hero",
      "set": "spoken",
      "duration": 9.4907,
      "lines": 2
    },
    "hero-14": {
      "file": "voice-hero-14",
      "speaker": "hero",
      "set": "spoken",
      "duration": 10.206,
      "lines": 2
    },
    "hero-15": {
      "file": "voice-hero-15",
      "speaker": "hero",
      "set": "spoken",
      "duration": 11.222,
      "lines": 2
    },
    "hero-16": {
      "file": "voice-hero-16",
      "speaker": "hero",
      "set": "spoken",
      "duration": 11.1847,
      "lines": 2
    },
    "hero-17": {
      "file": "voice-hero-17",
      "speaker": "hero",
      "set": "spoken",
      "duration": 9.7473,
      "lines": 2
    },
    "hero-18": {
      "file": "voice-hero-18",
      "speaker": "hero",
      "set": "spoken",
      "duration": 9.6747,
      "lines": 2
    },
    "hero-19": {
      "file": "voice-hero-19",
      "speaker": "hero",
      "set": "spoken",
      "duration": 8.5467,
      "lines": 2
    },
    "hero-20": {
      "file": "voice-hero-20",
      "speaker": "hero",
      "set": "spoken",
      "duration": 11.562,
      "lines": 5
    },
    "hero-21": {
      "file": "voice-hero-21",
      "speaker": "hero",
      "set": "spoken",
      "duration": 10.1813,
      "lines": 6
    },
    "hero-22": {
      "file": "voice-hero-22",
      "speaker": "hero",
      "set": "spoken",
      "duration": 11.1553,
      "lines": 6
    },
    "hero-23": {
      "file": "voice-hero-23",
      "speaker": "hero",
      "set": "spoken",
      "duration": 11.8353,
      "lines": 7
    },
    "hero-24": {
      "file": "voice-hero-24",
      "speaker": "hero",
      "set": "spoken",
      "duration": 10.752,
      "lines": 7
    },
    "hero-25": {
      "file": "voice-hero-25",
      "speaker": "hero",
      "set": "spoken",
      "duration": 10.3547,
      "lines": 7
    },
    "hero-26": {
      "file": "voice-hero-26",
      "speaker": "hero",
      "set": "spoken",
      "duration": 7.6707,
      "lines": 5
    },
    "caravan_master-1": {
      "file": "voice-caravan_master-1",
      "speaker": "caravan_master",
      "set": "spoken",
      "duration": 9.6833,
      "lines": 1
    },
    "caravan_master-2": {
      "file": "voice-caravan_master-2",
      "speaker": "caravan_master",
      "set": "spoken",
      "duration": 7.104,
      "lines": 1
    },
    "caravan_master-3": {
      "file": "voice-caravan_master-3",
      "speaker": "caravan_master",
      "set": "spoken",
      "duration": 10.136,
      "lines": 1
    },
    "caravan_master-4": {
      "file": "voice-caravan_master-4",
      "speaker": "caravan_master",
      "set": "spoken",
      "duration": 12.6833,
      "lines": 1
    },
    "caravan_master-5": {
      "file": "voice-caravan_master-5",
      "speaker": "caravan_master",
      "set": "spoken",
      "duration": 11.0007,
      "lines": 1
    },
    "caravan_master-6": {
      "file": "voice-caravan_master-6",
      "speaker": "caravan_master",
      "set": "spoken",
      "duration": 9.7093,
      "lines": 1
    },
    "caravan_master-7": {
      "file": "voice-caravan_master-7",
      "speaker": "caravan_master",
      "set": "spoken",
      "duration": 7.5573,
      "lines": 1
    },
    "caravan_master-8": {
      "file": "voice-caravan_master-8",
      "speaker": "caravan_master",
      "set": "spoken",
      "duration": 10.5667,
      "lines": 2
    },
    "caravan_master-9": {
      "file": "voice-caravan_master-9",
      "speaker": "caravan_master",
      "set": "spoken",
      "duration": 11.2247,
      "lines": 3
    },
    "rillford_reeve-1": {
      "file": "voice-rillford_reeve-1",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 11.6,
      "lines": 1
    },
    "rillford_reeve-2": {
      "file": "voice-rillford_reeve-2",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 8.2933,
      "lines": 1
    },
    "rillford_reeve-3": {
      "file": "voice-rillford_reeve-3",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 6.582,
      "lines": 1
    },
    "rillford_reeve-4": {
      "file": "voice-rillford_reeve-4",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 8.472,
      "lines": 1
    },
    "rillford_reeve-5": {
      "file": "voice-rillford_reeve-5",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 5.5253,
      "lines": 1
    },
    "rillford_reeve-6": {
      "file": "voice-rillford_reeve-6",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 8.6587,
      "lines": 1
    },
    "rillford_reeve-7": {
      "file": "voice-rillford_reeve-7",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 11.2407,
      "lines": 1
    },
    "rillford_reeve-8": {
      "file": "voice-rillford_reeve-8",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 6.9547,
      "lines": 1
    },
    "rillford_reeve-9": {
      "file": "voice-rillford_reeve-9",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 7.5767,
      "lines": 1
    },
    "rillford_reeve-10": {
      "file": "voice-rillford_reeve-10",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 10.0887,
      "lines": 1
    },
    "rillford_reeve-11": {
      "file": "voice-rillford_reeve-11",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 11.0933,
      "lines": 2
    },
    "rillford_reeve-12": {
      "file": "voice-rillford_reeve-12",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 8.8893,
      "lines": 3
    },
    "rillford_reeve-13": {
      "file": "voice-rillford_reeve-13",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 10.452,
      "lines": 3
    },
    "rillford_reeve-14": {
      "file": "voice-rillford_reeve-14",
      "speaker": "rillford_reeve",
      "set": "spoken",
      "duration": 10.6033,
      "lines": 4
    },
    "spring_steward-1": {
      "file": "voice-spring_steward-1",
      "speaker": "spring_steward",
      "set": "spoken",
      "duration": 13.3607,
      "lines": 1
    },
    "spring_steward-2": {
      "file": "voice-spring_steward-2",
      "speaker": "spring_steward",
      "set": "spoken",
      "duration": 7.7653,
      "lines": 1
    },
    "spring_steward-3": {
      "file": "voice-spring_steward-3",
      "speaker": "spring_steward",
      "set": "spoken",
      "duration": 7.0167,
      "lines": 1
    },
    "spring_steward-4": {
      "file": "voice-spring_steward-4",
      "speaker": "spring_steward",
      "set": "spoken",
      "duration": 11.0107,
      "lines": 1
    },
    "spring_steward-5": {
      "file": "voice-spring_steward-5",
      "speaker": "spring_steward",
      "set": "spoken",
      "duration": 12.766,
      "lines": 1
    },
    "spring_steward-6": {
      "file": "voice-spring_steward-6",
      "speaker": "spring_steward",
      "set": "spoken",
      "duration": 8.4987,
      "lines": 1
    },
    "spring_steward-7": {
      "file": "voice-spring_steward-7",
      "speaker": "spring_steward",
      "set": "spoken",
      "duration": 10.4167,
      "lines": 1
    },
    "spring_steward-8": {
      "file": "voice-spring_steward-8",
      "speaker": "spring_steward",
      "set": "spoken",
      "duration": 9.848,
      "lines": 1
    },
    "spring_steward-9": {
      "file": "voice-spring_steward-9",
      "speaker": "spring_steward",
      "set": "spoken",
      "duration": 8.68,
      "lines": 1
    },
    "spring_steward-10": {
      "file": "voice-spring_steward-10",
      "speaker": "spring_steward",
      "set": "spoken",
      "duration": 11.2293,
      "lines": 3
    },
    "spring_steward-11": {
      "file": "voice-spring_steward-11",
      "speaker": "spring_steward",
      "set": "spoken",
      "duration": 4.836,
      "lines": 2
    },
    "quarry_foreman-1": {
      "file": "voice-quarry_foreman-1",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 9.7413,
      "lines": 1
    },
    "quarry_foreman-2": {
      "file": "voice-quarry_foreman-2",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 7.8293,
      "lines": 1
    },
    "quarry_foreman-3": {
      "file": "voice-quarry_foreman-3",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 9.3627,
      "lines": 1
    },
    "quarry_foreman-4": {
      "file": "voice-quarry_foreman-4",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 11.2987,
      "lines": 1
    },
    "quarry_foreman-5": {
      "file": "voice-quarry_foreman-5",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 7.798,
      "lines": 1
    },
    "quarry_foreman-6": {
      "file": "voice-quarry_foreman-6",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 7.822,
      "lines": 1
    },
    "quarry_foreman-7": {
      "file": "voice-quarry_foreman-7",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 7.8593,
      "lines": 1
    },
    "quarry_foreman-8": {
      "file": "voice-quarry_foreman-8",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 7.7813,
      "lines": 1
    },
    "quarry_foreman-9": {
      "file": "voice-quarry_foreman-9",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 5.9047,
      "lines": 1
    },
    "quarry_foreman-10": {
      "file": "voice-quarry_foreman-10",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 9.782,
      "lines": 2
    },
    "quarry_foreman-11": {
      "file": "voice-quarry_foreman-11",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 9.892,
      "lines": 3
    },
    "quarry_foreman-12": {
      "file": "voice-quarry_foreman-12",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 11.6027,
      "lines": 4
    },
    "quarry_foreman-13": {
      "file": "voice-quarry_foreman-13",
      "speaker": "quarry_foreman",
      "set": "spoken",
      "duration": 5.6667,
      "lines": 2
    },
    "maintenance_worker-1": {
      "file": "voice-maintenance_worker-1",
      "speaker": "maintenance_worker",
      "set": "spoken",
      "duration": 8.48,
      "lines": 1
    },
    "maintenance_worker-2": {
      "file": "voice-maintenance_worker-2",
      "speaker": "maintenance_worker",
      "set": "spoken",
      "duration": 8.0773,
      "lines": 1
    },
    "maintenance_worker-3": {
      "file": "voice-maintenance_worker-3",
      "speaker": "maintenance_worker",
      "set": "spoken",
      "duration": 9.0347,
      "lines": 2
    },
    "maintenance_worker-4": {
      "file": "voice-maintenance_worker-4",
      "speaker": "maintenance_worker",
      "set": "spoken",
      "duration": 10,
      "lines": 1
    },
    "maintenance_worker-5": {
      "file": "voice-maintenance_worker-5",
      "speaker": "maintenance_worker",
      "set": "spoken",
      "duration": 8.808,
      "lines": 1
    },
    "maintenance_worker-6": {
      "file": "voice-maintenance_worker-6",
      "speaker": "maintenance_worker",
      "set": "spoken",
      "duration": 8.6,
      "lines": 1
    },
    "maintenance_worker-7": {
      "file": "voice-maintenance_worker-7",
      "speaker": "maintenance_worker",
      "set": "spoken",
      "duration": 11.07,
      "lines": 2
    },
    "maintenance_worker-8": {
      "file": "voice-maintenance_worker-8",
      "speaker": "maintenance_worker",
      "set": "spoken",
      "duration": 9.916,
      "lines": 3
    },
    "maintenance_worker-9": {
      "file": "voice-maintenance_worker-9",
      "speaker": "maintenance_worker",
      "set": "spoken",
      "duration": 3.7093,
      "lines": 1
    },
    "estate_steward-1": {
      "file": "voice-estate_steward-1",
      "speaker": "estate_steward",
      "set": "spoken",
      "duration": 10.606,
      "lines": 2
    },
    "estate_steward-2": {
      "file": "voice-estate_steward-2",
      "speaker": "estate_steward",
      "set": "spoken",
      "duration": 7.2133,
      "lines": 1
    },
    "estate_steward-3": {
      "file": "voice-estate_steward-3",
      "speaker": "estate_steward",
      "set": "spoken",
      "duration": 8.0133,
      "lines": 1
    },
    "estate_steward-4": {
      "file": "voice-estate_steward-4",
      "speaker": "estate_steward",
      "set": "spoken",
      "duration": 10.326,
      "lines": 2
    },
    "estate_steward-5": {
      "file": "voice-estate_steward-5",
      "speaker": "estate_steward",
      "set": "spoken",
      "duration": 5.8187,
      "lines": 1
    },
    "estate_steward-6": {
      "file": "voice-estate_steward-6",
      "speaker": "estate_steward",
      "set": "spoken",
      "duration": 9.92,
      "lines": 2
    },
    "estate_steward-7": {
      "file": "voice-estate_steward-7",
      "speaker": "estate_steward",
      "set": "spoken",
      "duration": 6.4987,
      "lines": 2
    },
    "ash_recorder-1": {
      "file": "voice-ash_recorder-1",
      "speaker": "ash_recorder",
      "set": "spoken",
      "duration": 11.5067,
      "lines": 1
    },
    "ash_recorder-2": {
      "file": "voice-ash_recorder-2",
      "speaker": "ash_recorder",
      "set": "spoken",
      "duration": 8.48,
      "lines": 1
    },
    "ash_recorder-3": {
      "file": "voice-ash_recorder-3",
      "speaker": "ash_recorder",
      "set": "spoken",
      "duration": 9.254,
      "lines": 1
    },
    "ash_recorder-4": {
      "file": "voice-ash_recorder-4",
      "speaker": "ash_recorder",
      "set": "spoken",
      "duration": 6.7207,
      "lines": 1
    },
    "ash_recorder-5": {
      "file": "voice-ash_recorder-5",
      "speaker": "ash_recorder",
      "set": "spoken",
      "duration": 7.734,
      "lines": 1
    },
    "ash_recorder-6": {
      "file": "voice-ash_recorder-6",
      "speaker": "ash_recorder",
      "set": "spoken",
      "duration": 11.622,
      "lines": 2
    },
    "ash_recorder-7": {
      "file": "voice-ash_recorder-7",
      "speaker": "ash_recorder",
      "set": "spoken",
      "duration": 11.6707,
      "lines": 3
    },
    "ash_recorder-8": {
      "file": "voice-ash_recorder-8",
      "speaker": "ash_recorder",
      "set": "spoken",
      "duration": 2.7153,
      "lines": 1
    },
    "shrine_warden-1": {
      "file": "voice-shrine_warden-1",
      "speaker": "shrine_warden",
      "set": "spoken",
      "duration": 7.7573,
      "lines": 1
    },
    "shrine_warden-2": {
      "file": "voice-shrine_warden-2",
      "speaker": "shrine_warden",
      "set": "spoken",
      "duration": 7.4213,
      "lines": 1
    },
    "shrine_warden-3": {
      "file": "voice-shrine_warden-3",
      "speaker": "shrine_warden",
      "set": "spoken",
      "duration": 5.64,
      "lines": 1
    },
    "shrine_warden-4": {
      "file": "voice-shrine_warden-4",
      "speaker": "shrine_warden",
      "set": "spoken",
      "duration": 8.5573,
      "lines": 1
    },
    "shrine_warden-5": {
      "file": "voice-shrine_warden-5",
      "speaker": "shrine_warden",
      "set": "spoken",
      "duration": 8.7973,
      "lines": 1
    },
    "shrine_warden-6": {
      "file": "voice-shrine_warden-6",
      "speaker": "shrine_warden",
      "set": "spoken",
      "duration": 11.3933,
      "lines": 3
    },
    "shrine_warden-7": {
      "file": "voice-shrine_warden-7",
      "speaker": "shrine_warden",
      "set": "spoken",
      "duration": 10.1047,
      "lines": 3
    },
    "mill_hand-1": {
      "file": "voice-mill_hand-1",
      "speaker": "mill_hand",
      "set": "spoken",
      "duration": 8.95,
      "lines": 1
    },
    "mill_hand-2": {
      "file": "voice-mill_hand-2",
      "speaker": "mill_hand",
      "set": "spoken",
      "duration": 7.3767,
      "lines": 1
    },
    "mill_hand-3": {
      "file": "voice-mill_hand-3",
      "speaker": "mill_hand",
      "set": "spoken",
      "duration": 7.5413,
      "lines": 1
    },
    "mill_hand-4": {
      "file": "voice-mill_hand-4",
      "speaker": "mill_hand",
      "set": "spoken",
      "duration": 6.3707,
      "lines": 1
    },
    "mill_hand-5": {
      "file": "voice-mill_hand-5",
      "speaker": "mill_hand",
      "set": "spoken",
      "duration": 10.1947,
      "lines": 2
    },
    "mill_hand-6": {
      "file": "voice-mill_hand-6",
      "speaker": "mill_hand",
      "set": "spoken",
      "duration": 10.21,
      "lines": 4
    },
    "mill_hand-7": {
      "file": "voice-mill_hand-7",
      "speaker": "mill_hand",
      "set": "spoken",
      "duration": 10.07,
      "lines": 4
    },
    "quarry_hand-1": {
      "file": "voice-quarry_hand-1",
      "speaker": "quarry_hand",
      "set": "spoken",
      "duration": 10.648,
      "lines": 2
    },
    "quarry_hand-2": {
      "file": "voice-quarry_hand-2",
      "speaker": "quarry_hand",
      "set": "spoken",
      "duration": 7.3893,
      "lines": 1
    },
    "quarry_hand-3": {
      "file": "voice-quarry_hand-3",
      "speaker": "quarry_hand",
      "set": "spoken",
      "duration": 6.608,
      "lines": 1
    },
    "quarry_hand-4": {
      "file": "voice-quarry_hand-4",
      "speaker": "quarry_hand",
      "set": "spoken",
      "duration": 10.3553,
      "lines": 2
    },
    "quarry_hand-5": {
      "file": "voice-quarry_hand-5",
      "speaker": "quarry_hand",
      "set": "spoken",
      "duration": 10.0893,
      "lines": 3
    },
    "quarry_hand-6": {
      "file": "voice-quarry_hand-6",
      "speaker": "quarry_hand",
      "set": "spoken",
      "duration": 9.68,
      "lines": 3
    },
    "quarry_hand-7": {
      "file": "voice-quarry_hand-7",
      "speaker": "quarry_hand",
      "set": "spoken",
      "duration": 7.4087,
      "lines": 3
    },
    "village_baker-1": {
      "file": "voice-village_baker-1",
      "speaker": "village_baker",
      "set": "spoken",
      "duration": 6.9227,
      "lines": 1
    },
    "village_baker-2": {
      "file": "voice-village_baker-2",
      "speaker": "village_baker",
      "set": "spoken",
      "duration": 7.6587,
      "lines": 1
    },
    "village_baker-3": {
      "file": "voice-village_baker-3",
      "speaker": "village_baker",
      "set": "spoken",
      "duration": 6.8807,
      "lines": 1
    },
    "village_baker-4": {
      "file": "voice-village_baker-4",
      "speaker": "village_baker",
      "set": "spoken",
      "duration": 7.496,
      "lines": 1
    },
    "village_baker-5": {
      "file": "voice-village_baker-5",
      "speaker": "village_baker",
      "set": "spoken",
      "duration": 10.9793,
      "lines": 2
    },
    "village_baker-6": {
      "file": "voice-village_baker-6",
      "speaker": "village_baker",
      "set": "spoken",
      "duration": 11.2667,
      "lines": 4
    },
    "village_baker-7": {
      "file": "voice-village_baker-7",
      "speaker": "village_baker",
      "set": "spoken",
      "duration": 11.486,
      "lines": 4
    },
    "village_baker-8": {
      "file": "voice-village_baker-8",
      "speaker": "village_baker",
      "set": "spoken",
      "duration": 5.304,
      "lines": 2
    },
    "story-caravan_master-1": {
      "file": "voice-story-caravan_master-1",
      "speaker": "caravan_master",
      "set": "story",
      "duration": 21.7927,
      "lines": 1
    },
    "story-caravan_master-2": {
      "file": "voice-story-caravan_master-2",
      "speaker": "caravan_master",
      "set": "story",
      "duration": 10.144,
      "lines": 1
    },
    "story-caravan_master-3": {
      "file": "voice-story-caravan_master-3",
      "speaker": "caravan_master",
      "set": "story",
      "duration": 16.518,
      "lines": 1
    },
    "story-caravan_master-4": {
      "file": "voice-story-caravan_master-4",
      "speaker": "caravan_master",
      "set": "story",
      "duration": 3.79,
      "lines": 1
    },
    "story-caravan_master-5": {
      "file": "voice-story-caravan_master-5",
      "speaker": "caravan_master",
      "set": "story",
      "duration": 12.8833,
      "lines": 1
    },
    "story-hero-1": {
      "file": "voice-story-hero-1",
      "speaker": "hero",
      "set": "story",
      "duration": 9.246,
      "lines": 7
    },
    "story-hero-2": {
      "file": "voice-story-hero-2",
      "speaker": "hero",
      "set": "story",
      "duration": 10.544,
      "lines": 5
    },
    "story-hero-3": {
      "file": "voice-story-hero-3",
      "speaker": "hero",
      "set": "story",
      "duration": 8.9393,
      "lines": 3
    },
    "story-hero-4": {
      "file": "voice-story-hero-4",
      "speaker": "hero",
      "set": "story",
      "duration": 12.028,
      "lines": 4
    },
    "story-hero-5": {
      "file": "voice-story-hero-5",
      "speaker": "hero",
      "set": "story",
      "duration": 9.6367,
      "lines": 7
    },
    "story-hero-6": {
      "file": "voice-story-hero-6",
      "speaker": "hero",
      "set": "story",
      "duration": 10.3573,
      "lines": 5
    },
    "story-hero-7": {
      "file": "voice-story-hero-7",
      "speaker": "hero",
      "set": "story",
      "duration": 11.616,
      "lines": 5
    },
    "story-hero-8": {
      "file": "voice-story-hero-8",
      "speaker": "hero",
      "set": "story",
      "duration": 12.062,
      "lines": 6
    },
    "story-hero-9": {
      "file": "voice-story-hero-9",
      "speaker": "hero",
      "set": "story",
      "duration": 11.4173,
      "lines": 7
    },
    "story-hero-10": {
      "file": "voice-story-hero-10",
      "speaker": "hero",
      "set": "story",
      "duration": 11.504,
      "lines": 5
    },
    "story-hero-11": {
      "file": "voice-story-hero-11",
      "speaker": "hero",
      "set": "story",
      "duration": 9.4207,
      "lines": 3
    },
    "story-hero-12": {
      "file": "voice-story-hero-12",
      "speaker": "hero",
      "set": "story",
      "duration": 11.3527,
      "lines": 6
    },
    "story-hero-13": {
      "file": "voice-story-hero-13",
      "speaker": "hero",
      "set": "story",
      "duration": 10.1733,
      "lines": 4
    },
    "story-hero-14": {
      "file": "voice-story-hero-14",
      "speaker": "hero",
      "set": "story",
      "duration": 11.1007,
      "lines": 6
    },
    "story-hero-15": {
      "file": "voice-story-hero-15",
      "speaker": "hero",
      "set": "story",
      "duration": 11.1913,
      "lines": 8
    },
    "story-hero-16": {
      "file": "voice-story-hero-16",
      "speaker": "hero",
      "set": "story",
      "duration": 11.6627,
      "lines": 8
    },
    "story-hero-17": {
      "file": "voice-story-hero-17",
      "speaker": "hero",
      "set": "story",
      "duration": 11.738,
      "lines": 6
    },
    "story-hero-18": {
      "file": "voice-story-hero-18",
      "speaker": "hero",
      "set": "story",
      "duration": 10.6907,
      "lines": 6
    },
    "story-hero-19": {
      "file": "voice-story-hero-19",
      "speaker": "hero",
      "set": "story",
      "duration": 1.67,
      "lines": 1
    },
    "story-rillford_reeve-1": {
      "file": "voice-story-rillford_reeve-1",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 14.9073,
      "lines": 1
    },
    "story-rillford_reeve-2": {
      "file": "voice-story-rillford_reeve-2",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 15.5793,
      "lines": 1
    },
    "story-rillford_reeve-3": {
      "file": "voice-story-rillford_reeve-3",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 16.424,
      "lines": 1
    },
    "story-rillford_reeve-4": {
      "file": "voice-story-rillford_reeve-4",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 10.918,
      "lines": 1
    },
    "story-rillford_reeve-5": {
      "file": "voice-story-rillford_reeve-5",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 1.4887,
      "lines": 1
    },
    "story-rillford_reeve-6": {
      "file": "voice-story-rillford_reeve-6",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 20.3227,
      "lines": 1
    },
    "story-rillford_reeve-7": {
      "file": "voice-story-rillford_reeve-7",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 13.5467,
      "lines": 1
    },
    "story-rillford_reeve-8": {
      "file": "voice-story-rillford_reeve-8",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 14.992,
      "lines": 1
    },
    "story-rillford_reeve-9": {
      "file": "voice-story-rillford_reeve-9",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 10.9147,
      "lines": 1
    },
    "story-rillford_reeve-10": {
      "file": "voice-story-rillford_reeve-10",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 11.614,
      "lines": 1
    },
    "story-rillford_reeve-11": {
      "file": "voice-story-rillford_reeve-11",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 12.6773,
      "lines": 1
    },
    "story-rillford_reeve-12": {
      "file": "voice-story-rillford_reeve-12",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 15.024,
      "lines": 1
    },
    "story-rillford_reeve-13": {
      "file": "voice-story-rillford_reeve-13",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 13.838,
      "lines": 1
    },
    "story-rillford_reeve-14": {
      "file": "voice-story-rillford_reeve-14",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 13.1413,
      "lines": 1
    },
    "story-rillford_reeve-15": {
      "file": "voice-story-rillford_reeve-15",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 15.118,
      "lines": 1
    },
    "story-rillford_reeve-16": {
      "file": "voice-story-rillford_reeve-16",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 11.2427,
      "lines": 1
    },
    "story-rillford_reeve-17": {
      "file": "voice-story-rillford_reeve-17",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 12.5493,
      "lines": 1
    },
    "story-rillford_reeve-18": {
      "file": "voice-story-rillford_reeve-18",
      "speaker": "rillford_reeve",
      "set": "story",
      "duration": 17.0613,
      "lines": 1
    },
    "story-spring_steward-1": {
      "file": "voice-story-spring_steward-1",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 17.9393,
      "lines": 1
    },
    "story-spring_steward-2": {
      "file": "voice-story-spring_steward-2",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 12.662,
      "lines": 1
    },
    "story-spring_steward-3": {
      "file": "voice-story-spring_steward-3",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 3.8993,
      "lines": 1
    },
    "story-spring_steward-4": {
      "file": "voice-story-spring_steward-4",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 10.3153,
      "lines": 1
    },
    "story-spring_steward-5": {
      "file": "voice-story-spring_steward-5",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 14.8487,
      "lines": 1
    },
    "story-spring_steward-6": {
      "file": "voice-story-spring_steward-6",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 16.3867,
      "lines": 1
    },
    "story-spring_steward-7": {
      "file": "voice-story-spring_steward-7",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 15.456,
      "lines": 1
    },
    "story-spring_steward-8": {
      "file": "voice-story-spring_steward-8",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 19.232,
      "lines": 1
    },
    "story-spring_steward-9": {
      "file": "voice-story-spring_steward-9",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 16.8833,
      "lines": 1
    },
    "story-spring_steward-10": {
      "file": "voice-story-spring_steward-10",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 13.4267,
      "lines": 1
    },
    "story-spring_steward-11": {
      "file": "voice-story-spring_steward-11",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 13.0907,
      "lines": 1
    },
    "story-spring_steward-12": {
      "file": "voice-story-spring_steward-12",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 13.0833,
      "lines": 1
    },
    "story-spring_steward-13": {
      "file": "voice-story-spring_steward-13",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 14.3013,
      "lines": 1
    },
    "story-spring_steward-14": {
      "file": "voice-story-spring_steward-14",
      "speaker": "spring_steward",
      "set": "story",
      "duration": 12.4753,
      "lines": 1
    },
    "story-quarry_foreman-1": {
      "file": "voice-story-quarry_foreman-1",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 15.1393,
      "lines": 1
    },
    "story-quarry_foreman-2": {
      "file": "voice-story-quarry_foreman-2",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 12.622,
      "lines": 1
    },
    "story-quarry_foreman-3": {
      "file": "voice-story-quarry_foreman-3",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 0.8513,
      "lines": 1
    },
    "story-quarry_foreman-4": {
      "file": "voice-story-quarry_foreman-4",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 15.1387,
      "lines": 1
    },
    "story-quarry_foreman-5": {
      "file": "voice-story-quarry_foreman-5",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 16.2667,
      "lines": 1
    },
    "story-quarry_foreman-6": {
      "file": "voice-story-quarry_foreman-6",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 12.214,
      "lines": 1
    },
    "story-quarry_foreman-7": {
      "file": "voice-story-quarry_foreman-7",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 13.9767,
      "lines": 1
    },
    "story-quarry_foreman-8": {
      "file": "voice-story-quarry_foreman-8",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 7.3893,
      "lines": 1
    },
    "story-quarry_foreman-9": {
      "file": "voice-story-quarry_foreman-9",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 8.742,
      "lines": 1
    },
    "story-quarry_foreman-10": {
      "file": "voice-story-quarry_foreman-10",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 15.3153,
      "lines": 1
    },
    "story-quarry_foreman-11": {
      "file": "voice-story-quarry_foreman-11",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 12.7653,
      "lines": 1
    },
    "story-quarry_foreman-12": {
      "file": "voice-story-quarry_foreman-12",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 10.0487,
      "lines": 1
    },
    "story-quarry_foreman-13": {
      "file": "voice-story-quarry_foreman-13",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 8.7627,
      "lines": 1
    },
    "story-quarry_foreman-14": {
      "file": "voice-story-quarry_foreman-14",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 9.7313,
      "lines": 1
    },
    "story-quarry_foreman-15": {
      "file": "voice-story-quarry_foreman-15",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 9.518,
      "lines": 1
    },
    "story-quarry_foreman-16": {
      "file": "voice-story-quarry_foreman-16",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 9.3653,
      "lines": 1
    },
    "story-quarry_foreman-17": {
      "file": "voice-story-quarry_foreman-17",
      "speaker": "quarry_foreman",
      "set": "story",
      "duration": 11.3093,
      "lines": 1
    },
    "story-maintenance_worker-1": {
      "file": "voice-story-maintenance_worker-1",
      "speaker": "maintenance_worker",
      "set": "story",
      "duration": 17.8107,
      "lines": 1
    },
    "story-maintenance_worker-2": {
      "file": "voice-story-maintenance_worker-2",
      "speaker": "maintenance_worker",
      "set": "story",
      "duration": 13.4193,
      "lines": 1
    },
    "story-maintenance_worker-3": {
      "file": "voice-story-maintenance_worker-3",
      "speaker": "maintenance_worker",
      "set": "story",
      "duration": 11.3047,
      "lines": 1
    },
    "story-maintenance_worker-4": {
      "file": "voice-story-maintenance_worker-4",
      "speaker": "maintenance_worker",
      "set": "story",
      "duration": 11.7713,
      "lines": 2
    },
    "story-maintenance_worker-5": {
      "file": "voice-story-maintenance_worker-5",
      "speaker": "maintenance_worker",
      "set": "story",
      "duration": 20.7573,
      "lines": 1
    },
    "story-maintenance_worker-6": {
      "file": "voice-story-maintenance_worker-6",
      "speaker": "maintenance_worker",
      "set": "story",
      "duration": 24.1947,
      "lines": 1
    },
    "story-maintenance_worker-7": {
      "file": "voice-story-maintenance_worker-7",
      "speaker": "maintenance_worker",
      "set": "story",
      "duration": 4.678,
      "lines": 1
    },
    "story-maintenance_worker-8": {
      "file": "voice-story-maintenance_worker-8",
      "speaker": "maintenance_worker",
      "set": "story",
      "duration": 15.3073,
      "lines": 1
    },
    "story-maintenance_worker-9": {
      "file": "voice-story-maintenance_worker-9",
      "speaker": "maintenance_worker",
      "set": "story",
      "duration": 20.934,
      "lines": 1
    },
    "story-maintenance_worker-10": {
      "file": "voice-story-maintenance_worker-10",
      "speaker": "maintenance_worker",
      "set": "story",
      "duration": 10.254,
      "lines": 1
    },
    "story-estate_steward-1": {
      "file": "voice-story-estate_steward-1",
      "speaker": "estate_steward",
      "set": "story",
      "duration": 10.9733,
      "lines": 1
    },
    "story-estate_steward-2": {
      "file": "voice-story-estate_steward-2",
      "speaker": "estate_steward",
      "set": "story",
      "duration": 9.9573,
      "lines": 1
    },
    "story-estate_steward-3": {
      "file": "voice-story-estate_steward-3",
      "speaker": "estate_steward",
      "set": "story",
      "duration": 5.1733,
      "lines": 1
    },
    "story-estate_steward-4": {
      "file": "voice-story-estate_steward-4",
      "speaker": "estate_steward",
      "set": "story",
      "duration": 7.1333,
      "lines": 1
    },
    "story-estate_steward-5": {
      "file": "voice-story-estate_steward-5",
      "speaker": "estate_steward",
      "set": "story",
      "duration": 7.44,
      "lines": 1
    },
    "story-ash_recorder-1": {
      "file": "voice-story-ash_recorder-1",
      "speaker": "ash_recorder",
      "set": "story",
      "duration": 11.456,
      "lines": 1
    },
    "story-ash_recorder-2": {
      "file": "voice-story-ash_recorder-2",
      "speaker": "ash_recorder",
      "set": "story",
      "duration": 3.392,
      "lines": 1
    },
    "story-ash_recorder-3": {
      "file": "voice-story-ash_recorder-3",
      "speaker": "ash_recorder",
      "set": "story",
      "duration": 12.4107,
      "lines": 1
    },
    "story-ash_recorder-4": {
      "file": "voice-story-ash_recorder-4",
      "speaker": "ash_recorder",
      "set": "story",
      "duration": 11.9953,
      "lines": 1
    },
    "story-ash_recorder-5": {
      "file": "voice-story-ash_recorder-5",
      "speaker": "ash_recorder",
      "set": "story",
      "duration": 8.8827,
      "lines": 1
    },
    "story-shrine_warden-1": {
      "file": "voice-story-shrine_warden-1",
      "speaker": "shrine_warden",
      "set": "story",
      "duration": 11.5947,
      "lines": 1
    },
    "story-shrine_warden-2": {
      "file": "voice-story-shrine_warden-2",
      "speaker": "shrine_warden",
      "set": "story",
      "duration": 9.6387,
      "lines": 2
    },
    "story-shrine_warden-3": {
      "file": "voice-story-shrine_warden-3",
      "speaker": "shrine_warden",
      "set": "story",
      "duration": 11.9767,
      "lines": 1
    },
    "story-shrine_warden-4": {
      "file": "voice-story-shrine_warden-4",
      "speaker": "shrine_warden",
      "set": "story",
      "duration": 17.8407,
      "lines": 1
    },
    "story-shrine_warden-5": {
      "file": "voice-story-shrine_warden-5",
      "speaker": "shrine_warden",
      "set": "story",
      "duration": 9.0013,
      "lines": 2
    },
    "story-shrine_warden-6": {
      "file": "voice-story-shrine_warden-6",
      "speaker": "shrine_warden",
      "set": "story",
      "duration": 11.654,
      "lines": 1
    },
    "story-mill_hand-1": {
      "file": "voice-story-mill_hand-1",
      "speaker": "mill_hand",
      "set": "story",
      "duration": 8.622,
      "lines": 1
    },
    "story-mill_hand-2": {
      "file": "voice-story-mill_hand-2",
      "speaker": "mill_hand",
      "set": "story",
      "duration": 9.088,
      "lines": 1
    },
    "story-mill_hand-3": {
      "file": "voice-story-mill_hand-3",
      "speaker": "mill_hand",
      "set": "story",
      "duration": 6.3653,
      "lines": 1
    },
    "story-mill_hand-4": {
      "file": "voice-story-mill_hand-4",
      "speaker": "mill_hand",
      "set": "story",
      "duration": 8.5147,
      "lines": 1
    },
    "story-quarry_hand-1": {
      "file": "voice-story-quarry_hand-1",
      "speaker": "quarry_hand",
      "set": "story",
      "duration": 12.8427,
      "lines": 1
    },
    "story-quarry_hand-2": {
      "file": "voice-story-quarry_hand-2",
      "speaker": "quarry_hand",
      "set": "story",
      "duration": 7.8293,
      "lines": 1
    },
    "story-quarry_hand-3": {
      "file": "voice-story-quarry_hand-3",
      "speaker": "quarry_hand",
      "set": "story",
      "duration": 9.344,
      "lines": 1
    },
    "story-quarry_hand-4": {
      "file": "voice-story-quarry_hand-4",
      "speaker": "quarry_hand",
      "set": "story",
      "duration": 8.8613,
      "lines": 1
    },
    "story-quarry_hand-5": {
      "file": "voice-story-quarry_hand-5",
      "speaker": "quarry_hand",
      "set": "story",
      "duration": 10.968,
      "lines": 1
    },
    "story-village_baker-1": {
      "file": "voice-story-village_baker-1",
      "speaker": "village_baker",
      "set": "story",
      "duration": 11.04,
      "lines": 1
    },
    "story-village_baker-2": {
      "file": "voice-story-village_baker-2",
      "speaker": "village_baker",
      "set": "story",
      "duration": 10.2433,
      "lines": 1
    },
    "story-village_baker-3": {
      "file": "voice-story-village_baker-3",
      "speaker": "village_baker",
      "set": "story",
      "duration": 5.9707,
      "lines": 1
    },
    "story-village_baker-4": {
      "file": "voice-story-village_baker-4",
      "speaker": "village_baker",
      "set": "story",
      "duration": 9.2,
      "lines": 1
    },
    "story-village_baker-5": {
      "file": "voice-story-village_baker-5",
      "speaker": "village_baker",
      "set": "story",
      "duration": 9.6427,
      "lines": 1
    },
    "trail_hunter-1": {
      "file": "voice-trail_hunter-1",
      "speaker": "trail_hunter",
      "set": "spoken",
      "duration": 10.5653,
      "lines": 1
    }
  },
  "lines": {
    "hero.arrival": [
      "hero-1",
      0.08,
      6.78733,
      "hero"
    ],
    "hero.arrival.bell": [
      "hero-2",
      0.08,
      5.92267,
      "hero"
    ],
    "hero.place.lantern_point": [
      "hero-2",
      6.08267,
      5.40867,
      "hero"
    ],
    "hero.place.deepwood": [
      "hero-3",
      0.08,
      3.56067,
      "hero"
    ],
    "hero.place.overlook": [
      "hero-3",
      3.72067,
      4.08067,
      "hero"
    ],
    "hero.place.rillford": [
      "hero-4",
      0.08,
      4.864,
      "hero"
    ],
    "hero.place.ford": [
      "hero-4",
      5.024,
      4.38933,
      "hero"
    ],
    "hero.place.spring_shrine": [
      "hero-5",
      0.08,
      3.29333,
      "hero"
    ],
    "hero.place.sluice": [
      "hero-5",
      3.45333,
      5.12267,
      "hero"
    ],
    "hero.place.quarry": [
      "hero-6",
      0.08,
      5.102,
      "hero"
    ],
    "hero.place.the_cut": [
      "hero-6",
      5.262,
      2.52867,
      "hero"
    ],
    "hero.place.archive": [
      "hero-7",
      0.08,
      5.18667,
      "hero"
    ],
    "hero.blade": [
      "hero-7",
      5.34667,
      4.39467,
      "hero"
    ],
    "hero.beast": [
      "hero-7",
      9.82133,
      1.75,
      "hero"
    ],
    "hero.wounded.1": [
      "hero-8",
      0.08,
      2.07,
      "hero"
    ],
    "hero.wounded.2": [
      "hero-8",
      2.23,
      3.96333,
      "hero"
    ],
    "hero.respawn.1": [
      "hero-8",
      6.27333,
      4.74467,
      "hero"
    ],
    "hero.respawn.2": [
      "hero-9",
      0.08,
      1.68,
      "hero"
    ],
    "hero.victory": [
      "hero-9",
      1.84,
      3.73667,
      "hero"
    ],
    "hero.settled": [
      "hero-9",
      5.65667,
      5.41667,
      "hero"
    ],
    "hero.night": [
      "hero-10",
      0.08,
      3.75733,
      "hero"
    ],
    "hero.dawn": [
      "hero-10",
      3.91733,
      4.078,
      "hero"
    ],
    "hero.rescued": [
      "hero-10",
      8.07533,
      3.59733,
      "hero"
    ],
    "hero.shortcut": [
      "hero-11",
      0.08,
      4.44533,
      "hero"
    ],
    "hero.rite": [
      "hero-11",
      4.60533,
      4.11267,
      "hero"
    ],
    "hero.gate.stabilized": [
      "hero-11",
      8.798,
      3.13067,
      "hero"
    ],
    "hero.gate.jammed": [
      "hero-12",
      0.08,
      3.58667,
      "hero"
    ],
    "hero.inspect.arrival_wreckage": [
      "hero-12",
      3.74667,
      5.27,
      "hero"
    ],
    "hero.inspect.templar_waymarker": [
      "hero-13",
      0.08,
      4.38133,
      "hero"
    ],
    "hero.inspect.dry_channel": [
      "hero-13",
      4.54133,
      4.86933,
      "hero"
    ],
    "hero.inspect.spring_sediment": [
      "hero-14",
      0.08,
      6.23733,
      "hero"
    ],
    "hero.inspect.town_diversion": [
      "hero-14",
      6.39733,
      3.72867,
      "hero"
    ],
    "hero.inspect.quarry_seep": [
      "hero-15",
      0.08,
      5.27533,
      "hero"
    ],
    "hero.inspect.sluice_crack": [
      "hero-15",
      5.43533,
      5.70667,
      "hero"
    ],
    "hero.inspect.inspection_log": [
      "hero-16",
      0.08,
      6.26133,
      "hero"
    ],
    "hero.inspect.wetland_fish": [
      "hero-16",
      6.42133,
      4.68333,
      "hero"
    ],
    "hero.inspect.saltward_kit": [
      "hero-17",
      0.08,
      6.04533,
      "hero"
    ],
    "hero.item.archive_key": [
      "hero-17",
      6.20533,
      3.462,
      "hero"
    ],
    "hero.item.votive_reed": [
      "hero-18",
      0.08,
      4.32267,
      "hero"
    ],
    "hero.item.sluice_brace": [
      "hero-18",
      4.48267,
      5.112,
      "hero"
    ],
    "hero.item.gate_wrench": [
      "hero-19",
      0.08,
      4.00267,
      "hero"
    ],
    "hero.item.coin": [
      "hero-19",
      4.16267,
      4.304,
      "hero"
    ],
    "hero.item.healing_herb": [
      "hero-20",
      0.08,
      3.67733,
      "hero"
    ],
    "hero.item.shore_apple": [
      "hero-20",
      3.83733,
      3.208,
      "hero"
    ],
    "hero.ask.where": [
      "hero-20",
      7.12533,
      1.04333,
      "hero"
    ],
    "hero.ask.bell": [
      "hero-20",
      8.24867,
      1.51533,
      "hero"
    ],
    "hero.ask.work": [
      "hero-20",
      9.844,
      1.638,
      "hero"
    ],
    "hero.ask.ashore": [
      "hero-21",
      0.08,
      1.598,
      "hero"
    ],
    "hero.ask.road": [
      "hero-21",
      1.758,
      1.502,
      "hero"
    ],
    "hero.ask.water": [
      "hero-21",
      3.34,
      1.734,
      "hero"
    ],
    "hero.ask.who": [
      "hero-21",
      5.154,
      1.29867,
      "hero"
    ],
    "hero.ask.places": [
      "hero-21",
      6.53267,
      2.32267,
      "hero"
    ],
    "hero.ask.choose": [
      "hero-21",
      8.93533,
      1.166,
      "hero"
    ],
    "hero.ask.diversion": [
      "hero-22",
      0.08,
      3.25933,
      "hero"
    ],
    "hero.ask.failing": [
      "hero-22",
      3.41933,
      1.57933,
      "hero"
    ],
    "hero.ask.gate": [
      "hero-22",
      5.07867,
      0.99267,
      "hero"
    ],
    "hero.ask.accord": [
      "hero-22",
      6.15133,
      1.48867,
      "hero"
    ],
    "hero.ask.rite": [
      "hero-22",
      7.72,
      1.528,
      "hero"
    ],
    "hero.ask.wait": [
      "hero-22",
      9.328,
      1.74733,
      "hero"
    ],
    "hero.ask.marchers": [
      "hero-23",
      0.08,
      1.68333,
      "hero"
    ],
    "hero.ask.lever": [
      "hero-23",
      1.84333,
      1.84867,
      "hero"
    ],
    "hero.ask.ila": [
      "hero-23",
      3.772,
      1.30733,
      "hero"
    ],
    "hero.ask.down": [
      "hero-23",
      5.15933,
      1.60333,
      "hero"
    ],
    "hero.ask.gully": [
      "hero-23",
      6.84267,
      1.74467,
      "hero"
    ],
    "hero.ask.close": [
      "hero-23",
      8.66733,
      1.83733,
      "hero"
    ],
    "hero.ask.from": [
      "hero-23",
      10.58467,
      1.17067,
      "hero"
    ],
    "hero.ask.stay": [
      "hero-24",
      0.08,
      1.05667,
      "hero"
    ],
    "hero.ask.reserve": [
      "hero-24",
      1.21667,
      1.584,
      "hero"
    ],
    "hero.ask.sufficient": [
      "hero-24",
      2.88067,
      0.90467,
      "hero"
    ],
    "hero.ask.owns": [
      "hero-24",
      3.86533,
      1.48,
      "hero"
    ],
    "hero.ask.late": [
      "hero-24",
      5.42533,
      1.81133,
      "hero"
    ],
    "hero.ask.write": [
      "hero-24",
      7.31667,
      1.37133,
      "hero"
    ],
    "hero.ask.witness": [
      "hero-24",
      8.768,
      1.904,
      "hero"
    ],
    "hero.ask.me": [
      "hero-25",
      0.08,
      1.70467,
      "hero"
    ],
    "hero.ask.archive": [
      "hero-25",
      1.86467,
      1.61667,
      "hero"
    ],
    "hero.ask.see": [
      "hero-25",
      3.56133,
      1.03733,
      "hero"
    ],
    "hero.ask.templar": [
      "hero-25",
      4.67867,
      1.36333,
      "hero"
    ],
    "hero.ask.mill": [
      "hero-25",
      6.122,
      1.61067,
      "hero"
    ],
    "hero.ask.grain": [
      "hero-25",
      7.81267,
      1.2,
      "hero"
    ],
    "hero.ask.built": [
      "hero-25",
      9.09267,
      1.182,
      "hero"
    ],
    "hero.ask.darin": [
      "hero-26",
      0.08,
      2.15,
      "hero"
    ],
    "hero.ask.sleep": [
      "hero-26",
      2.31,
      1.248,
      "hero"
    ],
    "hero.ask.help": [
      "hero-26",
      3.638,
      0.81867,
      "hero"
    ],
    "hero.ask.bake": [
      "hero-26",
      4.53667,
      1.214,
      "hero"
    ],
    "hero.ask.village": [
      "hero-26",
      5.83067,
      1.76,
      "hero"
    ],
    "joss.where": [
      "caravan_master-1",
      0.08,
      9.52333,
      "caravan_master"
    ],
    "joss.ashore": [
      "caravan_master-2",
      0.08,
      6.944,
      "caravan_master"
    ],
    "joss.bell": [
      "caravan_master-3",
      0.08,
      9.976,
      "caravan_master"
    ],
    "joss.work": [
      "caravan_master-4",
      0.08,
      12.52333,
      "caravan_master"
    ],
    "joss.road": [
      "caravan_master-5",
      0.08,
      10.84067,
      "caravan_master"
    ],
    "joss.roads": [
      "caravan_master-6",
      0.08,
      9.54933,
      "caravan_master"
    ],
    "joss.beast": [
      "caravan_master-7",
      0.08,
      7.39733,
      "caravan_master"
    ],
    "joss.after": [
      "caravan_master-8",
      0.08,
      6.49933,
      "caravan_master"
    ],
    "joss.idle": [
      "caravan_master-8",
      6.65933,
      3.82733,
      "caravan_master"
    ],
    "joss.bark.horse": [
      "caravan_master-9",
      0.08,
      2.96,
      "caravan_master"
    ],
    "joss.bark.fog": [
      "caravan_master-9",
      3.12,
      3.456,
      "caravan_master"
    ],
    "joss.bark.lamp": [
      "caravan_master-9",
      6.656,
      4.48867,
      "caravan_master"
    ],
    "mara.intro": [
      "rillford_reeve-1",
      0.08,
      11.44,
      "rillford_reeve"
    ],
    "mara.water": [
      "rillford_reeve-2",
      0.08,
      8.13333,
      "rillford_reeve"
    ],
    "mara.who": [
      "rillford_reeve-3",
      0.08,
      6.422,
      "rillford_reeve"
    ],
    "mara.places": [
      "rillford_reeve-4",
      0.08,
      8.312,
      "rillford_reeve"
    ],
    "mara.channel": [
      "rillford_reeve-5",
      0.08,
      5.36533,
      "rillford_reeve"
    ],
    "mara.choose": [
      "rillford_reeve-6",
      0.08,
      8.49867,
      "rillford_reeve"
    ],
    "mara.diversion": [
      "rillford_reeve-7",
      0.08,
      11.08067,
      "rillford_reeve"
    ],
    "mara.hear": [
      "rillford_reeve-8",
      0.08,
      6.79467,
      "rillford_reeve"
    ],
    "mara.after.rillford": [
      "rillford_reeve-9",
      0.08,
      7.41667,
      "rillford_reeve"
    ],
    "mara.after.quarry": [
      "rillford_reeve-10",
      0.08,
      9.92867,
      "rillford_reeve"
    ],
    "mara.after.rotation": [
      "rillford_reeve-11",
      0.08,
      7.616,
      "rillford_reeve"
    ],
    "mara.bark.bucket": [
      "rillford_reeve-11",
      7.776,
      3.23733,
      "rillford_reeve"
    ],
    "mara.bark.bread": [
      "rillford_reeve-12",
      0.08,
      3.008,
      "rillford_reeve"
    ],
    "mara.bark.morning": [
      "rillford_reeve-12",
      3.168,
      2.86733,
      "rillford_reeve"
    ],
    "mara.bark.short": [
      "rillford_reeve-12",
      6.11533,
      2.694,
      "rillford_reeve"
    ],
    "mara.scene.cansee": [
      "rillford_reeve-13",
      0.08,
      3.11533,
      "rillford_reeve"
    ],
    "mara.scene.counting": [
      "rillford_reeve-13",
      3.27533,
      4.166,
      "rillford_reeve"
    ],
    "mara.scene.hear": [
      "rillford_reeve-13",
      7.52133,
      2.85067,
      "rillford_reeve"
    ],
    "mara.scene.broken": [
      "rillford_reeve-14",
      0.08,
      2.07467,
      "rillford_reeve"
    ],
    "mara.scene.three": [
      "rillford_reeve-14",
      2.23467,
      3.54133,
      "rillford_reeve"
    ],
    "mara.scene.share": [
      "rillford_reeve-14",
      5.856,
      2.91733,
      "rillford_reeve"
    ],
    "mara.bark.where": [
      "rillford_reeve-14",
      8.85333,
      1.67,
      "rillford_reeve"
    ],
    "edda.intro": [
      "spring_steward-1",
      0.08,
      13.20067,
      "spring_steward"
    ],
    "edda.failing": [
      "spring_steward-2",
      0.08,
      7.60533,
      "spring_steward"
    ],
    "edda.gate": [
      "spring_steward-3",
      0.08,
      6.85667,
      "spring_steward"
    ],
    "edda.accord": [
      "spring_steward-4",
      0.08,
      10.85067,
      "spring_steward"
    ],
    "edda.rite.ask": [
      "spring_steward-5",
      0.08,
      12.606,
      "spring_steward"
    ],
    "edda.rite": [
      "spring_steward-6",
      0.08,
      8.33867,
      "spring_steward"
    ],
    "edda.log": [
      "spring_steward-7",
      0.08,
      10.25667,
      "spring_steward"
    ],
    "edda.after.rotation": [
      "spring_steward-8",
      0.08,
      9.688,
      "spring_steward"
    ],
    "edda.after": [
      "spring_steward-9",
      0.08,
      8.52,
      "spring_steward"
    ],
    "edda.bark.patience": [
      "spring_steward-10",
      0.08,
      3.768,
      "spring_steward"
    ],
    "edda.bark.reeds": [
      "spring_steward-10",
      3.928,
      3.448,
      "spring_steward"
    ],
    "edda.bark.blessed": [
      "spring_steward-10",
      7.456,
      3.69333,
      "spring_steward"
    ],
    "edda.bark.light": [
      "spring_steward-11",
      0.08,
      2.44067,
      "spring_steward"
    ],
    "edda.bark.quiet": [
      "spring_steward-11",
      2.60067,
      2.15533,
      "spring_steward"
    ],
    "darin.intro": [
      "quarry_foreman-1",
      0.08,
      9.58133,
      "quarry_foreman"
    ],
    "darin.wait": [
      "quarry_foreman-2",
      0.08,
      7.66933,
      "quarry_foreman"
    ],
    "darin.marchers": [
      "quarry_foreman-3",
      0.08,
      9.20267,
      "quarry_foreman"
    ],
    "darin.ila": [
      "quarry_foreman-4",
      0.08,
      11.13867,
      "quarry_foreman"
    ],
    "darin.lever": [
      "quarry_foreman-5",
      0.08,
      7.638,
      "quarry_foreman"
    ],
    "darin.seep": [
      "quarry_foreman-6",
      0.08,
      7.662,
      "quarry_foreman"
    ],
    "darin.safe": [
      "quarry_foreman-7",
      0.08,
      7.69933,
      "quarry_foreman"
    ],
    "darin.after.quarry": [
      "quarry_foreman-8",
      0.08,
      7.62133,
      "quarry_foreman"
    ],
    "darin.after.rotation": [
      "quarry_foreman-9",
      0.08,
      5.74467,
      "quarry_foreman"
    ],
    "darin.after.rillford": [
      "quarry_foreman-10",
      0.08,
      6.382,
      "quarry_foreman"
    ],
    "darin.bark.count": [
      "quarry_foreman-10",
      6.542,
      3.16,
      "quarry_foreman"
    ],
    "darin.bark.stack": [
      "quarry_foreman-11",
      0.08,
      2.28333,
      "quarry_foreman"
    ],
    "darin.bark.edge": [
      "quarry_foreman-11",
      2.44333,
      4.13133,
      "quarry_foreman"
    ],
    "darin.bark.ledgers": [
      "quarry_foreman-11",
      6.65467,
      3.15733,
      "quarry_foreman"
    ],
    "darin.scene.blocks": [
      "quarry_foreman-12",
      0.08,
      4.17133,
      "quarry_foreman"
    ],
    "darin.scene.well": [
      "quarry_foreman-12",
      4.33133,
      2.15,
      "quarry_foreman"
    ],
    "darin.scene.contract": [
      "quarry_foreman-12",
      6.56133,
      1.91,
      "quarry_foreman"
    ],
    "darin.scene.load": [
      "quarry_foreman-12",
      8.55133,
      2.97133,
      "quarry_foreman"
    ],
    "darin.scene.used": [
      "quarry_foreman-13",
      0.08,
      2.71733,
      "quarry_foreman"
    ],
    "darin.bark.contract": [
      "quarry_foreman-13",
      2.87733,
      2.70933,
      "quarry_foreman"
    ],
    "ila.ledge": [
      "maintenance_worker-1",
      0.08,
      8.32,
      "maintenance_worker"
    ],
    "ila.down": [
      "maintenance_worker-2",
      0.08,
      7.91733,
      "maintenance_worker"
    ],
    "ila.notnow": [
      "maintenance_worker-3",
      0.08,
      4.86933,
      "maintenance_worker"
    ],
    "ila.waiting": [
      "maintenance_worker-3",
      5.02933,
      3.92533,
      "maintenance_worker"
    ],
    "ila.saw": [
      "maintenance_worker-4",
      0.08,
      9.84,
      "maintenance_worker"
    ],
    "ila.close": [
      "maintenance_worker-5",
      0.08,
      8.648,
      "maintenance_worker"
    ],
    "ila.from": [
      "maintenance_worker-6",
      0.08,
      8.44,
      "maintenance_worker"
    ],
    "ila.stay": [
      "maintenance_worker-7",
      0.08,
      5.80267,
      "maintenance_worker"
    ],
    "ila.villain": [
      "maintenance_worker-7",
      5.96267,
      5.02733,
      "maintenance_worker"
    ],
    "ila.bark.hello": [
      "maintenance_worker-8",
      0.08,
      2.19267,
      "maintenance_worker"
    ],
    "ila.bark.down": [
      "maintenance_worker-8",
      2.35267,
      3.326,
      "maintenance_worker"
    ],
    "ila.bark.bench": [
      "maintenance_worker-8",
      5.75867,
      4.07733,
      "maintenance_worker"
    ],
    "ila.bark.cheerful": [
      "maintenance_worker-9",
      0.08,
      3.54933,
      "maintenance_worker"
    ],
    "oren.intro": [
      "estate_steward-1",
      0.08,
      7.61667,
      "estate_steward"
    ],
    "oren.reserve": [
      "estate_steward-1",
      7.77667,
      2.74933,
      "estate_steward"
    ],
    "oren.reserve.truth": [
      "estate_steward-2",
      0.08,
      7.05333,
      "estate_steward"
    ],
    "oren.owns": [
      "estate_steward-3",
      0.08,
      7.85333,
      "estate_steward"
    ],
    "oren.late": [
      "estate_steward-4",
      0.08,
      6.56333,
      "estate_steward"
    ],
    "oren.date": [
      "estate_steward-4",
      6.72333,
      3.52267,
      "estate_steward"
    ],
    "oren.after.quarry": [
      "estate_steward-5",
      0.08,
      5.65867,
      "estate_steward"
    ],
    "oren.after": [
      "estate_steward-6",
      0.08,
      6.368,
      "estate_steward"
    ],
    "oren.bark.columns": [
      "estate_steward-6",
      6.528,
      3.312,
      "estate_steward"
    ],
    "oren.bark.counting": [
      "estate_steward-7",
      0.08,
      4.01867,
      "estate_steward"
    ],
    "oren.bark.date": [
      "estate_steward-7",
      4.17867,
      2.24,
      "estate_steward"
    ],
    "sel.intro": [
      "ash_recorder-1",
      0.08,
      11.34667,
      "ash_recorder"
    ],
    "sel.write": [
      "ash_recorder-2",
      0.08,
      8.32,
      "ash_recorder"
    ],
    "sel.witness": [
      "ash_recorder-3",
      0.08,
      9.094,
      "ash_recorder"
    ],
    "sel.me": [
      "ash_recorder-4",
      0.08,
      6.56067,
      "ash_recorder"
    ],
    "sel.pattern": [
      "ash_recorder-5",
      0.08,
      7.574,
      "ash_recorder"
    ],
    "sel.after": [
      "ash_recorder-6",
      0.08,
      7.688,
      "ash_recorder"
    ],
    "sel.bark.ink": [
      "ash_recorder-6",
      7.848,
      3.694,
      "ash_recorder"
    ],
    "sel.bark.hour": [
      "ash_recorder-7",
      0.08,
      4.17333,
      "ash_recorder"
    ],
    "sel.bark.river": [
      "ash_recorder-7",
      4.33333,
      3.534,
      "ash_recorder"
    ],
    "sel.bark.dark": [
      "ash_recorder-7",
      7.94733,
      3.64333,
      "ash_recorder"
    ],
    "sel.bark.write": [
      "ash_recorder-8",
      0.08,
      2.55533,
      "ash_recorder"
    ],
    "tolan.intro": [
      "shrine_warden-1",
      0.08,
      7.59733,
      "shrine_warden"
    ],
    "tolan.archive": [
      "shrine_warden-2",
      0.08,
      7.26133,
      "shrine_warden"
    ],
    "tolan.see": [
      "shrine_warden-3",
      0.08,
      5.48,
      "shrine_warden"
    ],
    "tolan.templar": [
      "shrine_warden-4",
      0.08,
      8.39733,
      "shrine_warden"
    ],
    "tolan.guard": [
      "shrine_warden-5",
      0.08,
      8.63733,
      "shrine_warden"
    ],
    "tolan.after": [
      "shrine_warden-6",
      0.08,
      6.82733,
      "shrine_warden"
    ],
    "tolan.bark.hey": [
      "shrine_warden-6",
      6.98733,
      1.59533,
      "shrine_warden"
    ],
    "tolan.bark.hands": [
      "shrine_warden-6",
      8.66267,
      2.65067,
      "shrine_warden"
    ],
    "tolan.bark.lock": [
      "shrine_warden-7",
      0.08,
      4.00867,
      "shrine_warden"
    ],
    "tolan.bark.along": [
      "shrine_warden-7",
      4.16867,
      3.19467,
      "shrine_warden"
    ],
    "tolan.bark.lamp": [
      "shrine_warden-7",
      7.44333,
      2.58133,
      "shrine_warden"
    ],
    "bess.intro": [
      "mill_hand-1",
      0.08,
      8.79,
      "mill_hand"
    ],
    "bess.mill": [
      "mill_hand-2",
      0.08,
      7.21667,
      "mill_hand"
    ],
    "bess.grain": [
      "mill_hand-3",
      0.08,
      7.38133,
      "mill_hand"
    ],
    "bess.built": [
      "mill_hand-4",
      0.08,
      6.21067,
      "mill_hand"
    ],
    "bess.after.rillford": [
      "mill_hand-5",
      0.08,
      5.77067,
      "mill_hand"
    ],
    "bess.after": [
      "mill_hand-5",
      5.93067,
      4.184,
      "mill_hand"
    ],
    "bess.bark.grain": [
      "mill_hand-6",
      0.08,
      2.48267,
      "mill_hand"
    ],
    "bess.bark.morning": [
      "mill_hand-6",
      2.64267,
      3.118,
      "mill_hand"
    ],
    "bess.scene.dry": [
      "mill_hand-6",
      5.84067,
      1.75267,
      "mill_hand"
    ],
    "bess.scene.counting": [
      "mill_hand-6",
      7.67333,
      2.45667,
      "mill_hand"
    ],
    "bess.scene.listen": [
      "mill_hand-7",
      0.08,
      3.2,
      "mill_hand"
    ],
    "bess.scene.promise": [
      "mill_hand-7",
      3.36,
      2.016,
      "mill_hand"
    ],
    "bess.bark.wheel": [
      "mill_hand-7",
      5.456,
      2.782,
      "mill_hand"
    ],
    "bess.bark.evening": [
      "mill_hand-7",
      8.318,
      1.672,
      "mill_hand"
    ],
    "pell.intro": [
      "quarry_hand-1",
      0.08,
      4.50667,
      "quarry_hand"
    ],
    "pell.ila": [
      "quarry_hand-1",
      4.66667,
      5.90133,
      "quarry_hand"
    ],
    "pell.darin": [
      "quarry_hand-2",
      0.08,
      7.22933,
      "quarry_hand"
    ],
    "pell.sleep": [
      "quarry_hand-3",
      0.08,
      6.448,
      "quarry_hand"
    ],
    "pell.after.rotation": [
      "quarry_hand-4",
      0.08,
      6.25667,
      "quarry_hand"
    ],
    "pell.after.quarry": [
      "quarry_hand-4",
      6.41667,
      3.85867,
      "quarry_hand"
    ],
    "pell.bark.dust": [
      "quarry_hand-5",
      0.08,
      3.34467,
      "quarry_hand"
    ],
    "pell.bark.done": [
      "quarry_hand-5",
      3.50467,
      2.61667,
      "quarry_hand"
    ],
    "pell.scene.dry": [
      "quarry_hand-5",
      6.20133,
      3.808,
      "quarry_hand"
    ],
    "pell.scene.uphill": [
      "quarry_hand-6",
      0.08,
      4.664,
      "quarry_hand"
    ],
    "pell.scene.says": [
      "quarry_hand-6",
      4.824,
      2.05867,
      "quarry_hand"
    ],
    "pell.scene.count": [
      "quarry_hand-6",
      6.96267,
      2.63733,
      "quarry_hand"
    ],
    "pell.bark.nothing": [
      "quarry_hand-7",
      0.08,
      2.84,
      "quarry_hand"
    ],
    "pell.bark.load": [
      "quarry_hand-7",
      3,
      1.85067,
      "quarry_hand"
    ],
    "pell.bark.night": [
      "quarry_hand-7",
      4.93067,
      2.398,
      "quarry_hand"
    ],
    "hesper.intro": [
      "village_baker-1",
      0.08,
      6.76267,
      "village_baker"
    ],
    "hesper.help": [
      "village_baker-2",
      0.08,
      7.49867,
      "village_baker"
    ],
    "hesper.bake": [
      "village_baker-3",
      0.08,
      6.72067,
      "village_baker"
    ],
    "hesper.village": [
      "village_baker-4",
      0.08,
      7.336,
      "village_baker"
    ],
    "hesper.after.rillford": [
      "village_baker-5",
      0.08,
      5.65067,
      "village_baker"
    ],
    "hesper.after": [
      "village_baker-5",
      5.81067,
      5.08867,
      "village_baker"
    ],
    "hesper.bark.step": [
      "village_baker-6",
      0.08,
      3.34933,
      "village_baker"
    ],
    "hesper.bark.barrel": [
      "village_baker-6",
      3.50933,
      2,
      "village_baker"
    ],
    "hesper.bark.ovens": [
      "village_baker-6",
      5.58933,
      2.64,
      "village_baker"
    ],
    "hesper.bark.queue": [
      "village_baker-6",
      8.30933,
      2.87733,
      "village_baker"
    ],
    "hesper.scene.word": [
      "village_baker-7",
      0.08,
      2.614,
      "village_baker"
    ],
    "hesper.scene.flour": [
      "village_baker-7",
      2.774,
      3.744,
      "village_baker"
    ],
    "hesper.scene.quick": [
      "village_baker-7",
      6.598,
      2.62933,
      "village_baker"
    ],
    "hesper.scene.loaves": [
      "village_baker-7",
      9.30733,
      2.09867,
      "village_baker"
    ],
    "hesper.scene.warm": [
      "village_baker-8",
      0.08,
      2.92267,
      "village_baker"
    ],
    "hesper.bark.dough": [
      "village_baker-8",
      3.08267,
      2.14133,
      "village_baker"
    ],
    "rowan.bark.supplies": [
      "trail_hunter-1",
      0.08,
      10.40533,
      "trail_hunter"
    ]
  },
  "story": {
    "d.joss_intro": [
      "story-caravan_master-1",
      0.08,
      21.63267,
      "caravan_master"
    ],
    "d.joss_bell": [
      "story-caravan_master-2",
      0.08,
      9.984,
      "caravan_master"
    ],
    "d.joss_work": [
      "story-caravan_master-3",
      0.08,
      16.358,
      "caravan_master"
    ],
    "d.joss_hub": [
      "story-caravan_master-4",
      0.08,
      3.63,
      "caravan_master"
    ],
    "d.joss_after": [
      "story-caravan_master-5",
      0.08,
      12.72333,
      "caravan_master"
    ],
    "d.joss_intro#0": [
      "story-hero-1",
      0.08,
      1.51,
      "hero"
    ],
    "d.joss_intro#1": [
      "story-hero-1",
      1.67,
      1.55,
      "hero"
    ],
    "d.joss_intro#2": [
      "story-hero-1",
      3.3,
      1.46667,
      "hero"
    ],
    "d.joss_work#0": [
      "story-hero-1",
      4.84667,
      0.76333,
      "hero"
    ],
    "d.joss_hub#2": [
      "story-hero-1",
      5.69,
      0.782,
      "hero"
    ],
    "d.joss_after#0": [
      "story-hero-1",
      6.552,
      0.82667,
      "hero"
    ],
    "d.mara_intro#0": [
      "story-hero-1",
      7.45867,
      1.70733,
      "hero"
    ],
    "d.mara_intro#1": [
      "story-hero-2",
      0.08,
      3.30933,
      "hero"
    ],
    "d.mara_intro#2": [
      "story-hero-2",
      3.46933,
      1.016,
      "hero"
    ],
    "d.mara_cause#0": [
      "story-hero-2",
      4.56533,
      3.39733,
      "hero"
    ],
    "d.mara_cause#1": [
      "story-hero-2",
      8.04267,
      1.488,
      "hero"
    ],
    "d.mara_offer#0": [
      "story-hero-2",
      9.61067,
      0.85333,
      "hero"
    ],
    "d.mara_hub#0": [
      "story-hero-3",
      0.08,
      2.19467,
      "hero"
    ],
    "d.mara_hub#1": [
      "story-hero-3",
      2.35467,
      2.26733,
      "hero"
    ],
    "d.mara_hub#2": [
      "story-hero-3",
      4.702,
      4.15733,
      "hero"
    ],
    "d.mara_hub#3": [
      "story-hero-4",
      0.08,
      3.11267,
      "hero"
    ],
    "d.mara_hub#4": [
      "story-hero-4",
      3.27267,
      4.13933,
      "hero"
    ],
    "d.mara_hub#5": [
      "story-hero-4",
      7.492,
      2.70133,
      "hero"
    ],
    "d.mara_hub#6": [
      "story-hero-4",
      10.27333,
      1.67467,
      "hero"
    ],
    "d.mara_hub#7": [
      "story-hero-5",
      0.08,
      0.71267,
      "hero"
    ],
    "d.mara_needs#0": [
      "story-hero-5",
      0.87267,
      1.126,
      "hero"
    ],
    "d.mara_diversion#0": [
      "story-hero-5",
      2.07867,
      1.486,
      "hero"
    ],
    "d.mara_rotation#0": [
      "story-hero-5",
      3.64467,
      2.206,
      "hero"
    ],
    "d.mara_ledger#0": [
      "story-hero-5",
      5.93067,
      1.35,
      "hero"
    ],
    "d.mara_hide#0": [
      "story-hero-5",
      7.36067,
      0.67,
      "hero"
    ],
    "d.mara_jammed#0": [
      "story-hero-5",
      8.11067,
      1.446,
      "hero"
    ],
    "d.mara_report_rillford#0": [
      "story-hero-6",
      0.08,
      3.34733,
      "hero"
    ],
    "d.mara_report_rillford#1": [
      "story-hero-6",
      3.50733,
      2.22733,
      "hero"
    ],
    "d.mara_after_rillford#0": [
      "story-hero-6",
      5.81467,
      1.734,
      "hero"
    ],
    "d.mara_after_law#0": [
      "story-hero-6",
      7.62867,
      0.88333,
      "hero"
    ],
    "d.edda_intro#0": [
      "story-hero-6",
      8.592,
      1.68533,
      "hero"
    ],
    "d.edda_intro#1": [
      "story-hero-7",
      0.08,
      2.10733,
      "hero"
    ],
    "d.edda_spring#0": [
      "story-hero-7",
      2.26733,
      0.96333,
      "hero"
    ],
    "d.edda_hub#0": [
      "story-hero-7",
      3.31067,
      1.88333,
      "hero"
    ],
    "d.edda_hub#1": [
      "story-hero-7",
      5.274,
      2.88,
      "hero"
    ],
    "d.edda_hub#2": [
      "story-hero-7",
      8.234,
      3.302,
      "hero"
    ],
    "d.edda_hub#3": [
      "story-hero-8",
      0.08,
      2.862,
      "hero"
    ],
    "d.edda_hub#4": [
      "story-hero-8",
      3.022,
      1.646,
      "hero"
    ],
    "d.edda_hub#5": [
      "story-hero-8",
      4.748,
      3.518,
      "hero"
    ],
    "d.edda_hub#6": [
      "story-hero-8",
      8.346,
      0.93067,
      "hero"
    ],
    "d.edda_sluice#0": [
      "story-hero-8",
      9.35667,
      0.91267,
      "hero"
    ],
    "d.edda_admits#0": [
      "story-hero-8",
      10.34933,
      1.63267,
      "hero"
    ],
    "d.edda_archive_yes#0": [
      "story-hero-9",
      0.08,
      1.31267,
      "hero"
    ],
    "d.edda_rite#0": [
      "story-hero-9",
      1.47267,
      1.48533,
      "hero"
    ],
    "d.edda_consent#0": [
      "story-hero-9",
      3.038,
      1.798,
      "hero"
    ],
    "d.edda_jammed#0": [
      "story-hero-9",
      4.916,
      1.22733,
      "hero"
    ],
    "d.darin_intro#0": [
      "story-hero-9",
      6.22333,
      1.61933,
      "hero"
    ],
    "d.darin_intro#1": [
      "story-hero-9",
      7.92267,
      1.82467,
      "hero"
    ],
    "d.darin_cause#0": [
      "story-hero-9",
      9.82733,
      1.51,
      "hero"
    ],
    "d.darin_cause#1": [
      "story-hero-10",
      0.08,
      1.294,
      "hero"
    ],
    "d.darin_hub#0": [
      "story-hero-10",
      1.454,
      2.07533,
      "hero"
    ],
    "d.darin_hub#1": [
      "story-hero-10",
      3.60933,
      3.014,
      "hero"
    ],
    "d.darin_hub#2": [
      "story-hero-10",
      6.70333,
      2.328,
      "hero"
    ],
    "d.darin_hub#3": [
      "story-hero-10",
      9.11133,
      2.31267,
      "hero"
    ],
    "d.darin_hub#4": [
      "story-hero-11",
      0.08,
      2.69667,
      "hero"
    ],
    "d.darin_hub#5": [
      "story-hero-11",
      2.85667,
      3.68867,
      "hero"
    ],
    "d.darin_hub#6": [
      "story-hero-11",
      6.62533,
      2.71533,
      "hero"
    ],
    "d.darin_hub#7": [
      "story-hero-12",
      0.08,
      4.67267,
      "hero"
    ],
    "d.darin_cut#0": [
      "story-hero-12",
      4.83267,
      1.238,
      "hero"
    ],
    "d.darin_humiliate#0": [
      "story-hero-12",
      6.15067,
      0.92867,
      "hero"
    ],
    "d.darin_mediate#0": [
      "story-hero-12",
      7.15933,
      0.982,
      "hero"
    ],
    "d.darin_rotation_ledger#0": [
      "story-hero-12",
      8.22133,
      1.14733,
      "hero"
    ],
    "d.darin_rotation_pay#0": [
      "story-hero-12",
      9.44867,
      1.824,
      "hero"
    ],
    "d.darin_rotation_pay#1": [
      "story-hero-13",
      0.08,
      1.942,
      "hero"
    ],
    "d.darin_report_rillford#0": [
      "story-hero-13",
      2.102,
      4.414,
      "hero"
    ],
    "d.darin_report_rillford#1": [
      "story-hero-13",
      6.596,
      1.814,
      "hero"
    ],
    "d.darin_report_quarry#0": [
      "story-hero-13",
      8.49,
      1.60333,
      "hero"
    ],
    "d.darin_report_rotation#0": [
      "story-hero-14",
      0.08,
      1.92,
      "hero"
    ],
    "d.ila_stranded#0": [
      "story-hero-14",
      2.08,
      1.75533,
      "hero"
    ],
    "d.ila_stranded#1": [
      "story-hero-14",
      3.91533,
      2.312,
      "hero"
    ],
    "d.ila_gate#0": [
      "story-hero-14",
      6.30733,
      1.60533,
      "hero"
    ],
    "d.ila_free_fight#0": [
      "story-hero-14",
      7.99267,
      1.06733,
      "hero"
    ],
    "d.ila_free_router#0": [
      "story-hero-14",
      9.14,
      1.88067,
      "hero"
    ],
    "d.ila_free_router#1": [
      "story-hero-15",
      0.08,
      1.886,
      "hero"
    ],
    "d.ila_free_router#2": [
      "story-hero-15",
      2.046,
      0.93933,
      "hero"
    ],
    "d.ila_testimony#0": [
      "story-hero-15",
      3.06533,
      1.902,
      "hero"
    ],
    "d.ila_hub#0": [
      "story-hero-15",
      5.04733,
      1.94467,
      "hero"
    ],
    "d.ila_hub#1": [
      "story-hero-15",
      7.072,
      1.19733,
      "hero"
    ],
    "d.ila_hub#2": [
      "story-hero-15",
      8.34933,
      0.838,
      "hero"
    ],
    "d.ila_after#0": [
      "story-hero-15",
      9.26733,
      0.838,
      "hero"
    ],
    "d.oren_intro#0": [
      "story-hero-15",
      10.18533,
      0.926,
      "hero"
    ],
    "d.oren_intro#1": [
      "story-hero-16",
      0.08,
      1.68867,
      "hero"
    ],
    "d.oren_reserve#0": [
      "story-hero-16",
      1.84867,
      1.838,
      "hero"
    ],
    "d.oren_hub#0": [
      "story-hero-16",
      3.76667,
      1.55733,
      "hero"
    ],
    "d.oren_hub#1": [
      "story-hero-16",
      5.404,
      0.718,
      "hero"
    ],
    "d.oren_after_quarry#0": [
      "story-hero-16",
      6.202,
      0.76067,
      "hero"
    ],
    "d.sel_intro#0": [
      "story-hero-16",
      7.04267,
      1.262,
      "hero"
    ],
    "d.sel_intro#1": [
      "story-hero-16",
      8.38467,
      1.46467,
      "hero"
    ],
    "d.sel_doom#0": [
      "story-hero-16",
      9.92933,
      1.65333,
      "hero"
    ],
    "d.harrow_intro#0": [
      "story-hero-17",
      0.08,
      1.52,
      "hero"
    ],
    "d.harrow_intro#1": [
      "story-hero-17",
      1.68,
      1.726,
      "hero"
    ],
    "d.harrow_hub#0": [
      "story-hero-17",
      3.486,
      3.04,
      "hero"
    ],
    "d.harrow_hub#1": [
      "story-hero-17",
      6.606,
      2.56267,
      "hero"
    ],
    "d.harrow_hub#3": [
      "story-hero-17",
      9.24867,
      1.022,
      "hero"
    ],
    "d.harrow_key#0": [
      "story-hero-17",
      10.35067,
      1.30733,
      "hero"
    ],
    "d.harrow_train#0": [
      "story-hero-18",
      0.08,
      1.97333,
      "hero"
    ],
    "d.harrow_train#1": [
      "story-hero-18",
      2.13333,
      3.28,
      "hero"
    ],
    "d.harrow_train#2": [
      "story-hero-18",
      5.49333,
      0.95533,
      "hero"
    ],
    "d.harrow_hub2#1": [
      "story-hero-18",
      6.52867,
      1.91,
      "hero"
    ],
    "d.bess_default#0": [
      "story-hero-18",
      8.51867,
      0.814,
      "hero"
    ],
    "d.bess_quarry#0": [
      "story-hero-18",
      9.41267,
      1.198,
      "hero"
    ],
    "d.pell_rotation#0": [
      "story-hero-19",
      0.08,
      1.51,
      "hero"
    ],
    "d.mara_intro": [
      "story-rillford_reeve-1",
      0.08,
      14.74733,
      "rillford_reeve"
    ],
    "d.mara_cause": [
      "story-rillford_reeve-2",
      0.08,
      15.41933,
      "rillford_reeve"
    ],
    "d.mara_directions": [
      "story-rillford_reeve-3",
      0.08,
      16.264,
      "rillford_reeve"
    ],
    "d.mara_offer": [
      "story-rillford_reeve-4",
      0.08,
      10.758,
      "rillford_reeve"
    ],
    "d.mara_hub": [
      "story-rillford_reeve-5",
      0.08,
      1.32867,
      "rillford_reeve"
    ],
    "d.mara_needs": [
      "story-rillford_reeve-6",
      0.08,
      20.16267,
      "rillford_reeve"
    ],
    "d.mara_diversion": [
      "story-rillford_reeve-7",
      0.08,
      13.38667,
      "rillford_reeve"
    ],
    "d.mara_rotation": [
      "story-rillford_reeve-8",
      0.08,
      14.832,
      "rillford_reeve"
    ],
    "d.mara_ledger": [
      "story-rillford_reeve-9",
      0.08,
      10.75467,
      "rillford_reeve"
    ],
    "d.mara_hide": [
      "story-rillford_reeve-10",
      0.08,
      11.454,
      "rillford_reeve"
    ],
    "d.mara_jammed": [
      "story-rillford_reeve-11",
      0.08,
      12.51733,
      "rillford_reeve"
    ],
    "d.mara_report_rillford": [
      "story-rillford_reeve-12",
      0.08,
      14.864,
      "rillford_reeve"
    ],
    "d.mara_report_quarry": [
      "story-rillford_reeve-13",
      0.08,
      13.678,
      "rillford_reeve"
    ],
    "d.mara_report_rotation": [
      "story-rillford_reeve-14",
      0.08,
      12.98133,
      "rillford_reeve"
    ],
    "d.mara_after_rillford": [
      "story-rillford_reeve-15",
      0.08,
      14.958,
      "rillford_reeve"
    ],
    "d.mara_after_quarry": [
      "story-rillford_reeve-16",
      0.08,
      11.08267,
      "rillford_reeve"
    ],
    "d.mara_after_rotation": [
      "story-rillford_reeve-17",
      0.08,
      12.38933,
      "rillford_reeve"
    ],
    "d.mara_after_law": [
      "story-rillford_reeve-18",
      0.08,
      16.90133,
      "rillford_reeve"
    ],
    "d.edda_intro": [
      "story-spring_steward-1",
      0.08,
      17.77933,
      "spring_steward"
    ],
    "d.edda_spring": [
      "story-spring_steward-2",
      0.08,
      12.502,
      "spring_steward"
    ],
    "d.edda_hub": [
      "story-spring_steward-3",
      0.08,
      3.73933,
      "spring_steward"
    ],
    "d.edda_flow": [
      "story-spring_steward-4",
      0.08,
      10.15533,
      "spring_steward"
    ],
    "d.edda_sluice": [
      "story-spring_steward-5",
      0.08,
      14.68867,
      "spring_steward"
    ],
    "d.edda_admits": [
      "story-spring_steward-6",
      0.08,
      16.22667,
      "spring_steward"
    ],
    "d.edda_archive_yes": [
      "story-spring_steward-7",
      0.08,
      15.296,
      "spring_steward"
    ],
    "d.edda_rite": [
      "story-spring_steward-8",
      0.08,
      19.072,
      "spring_steward"
    ],
    "d.edda_consent": [
      "story-spring_steward-9",
      0.08,
      16.72333,
      "spring_steward"
    ],
    "d.edda_caught": [
      "story-spring_steward-10",
      0.08,
      13.26667,
      "spring_steward"
    ],
    "d.edda_jammed": [
      "story-spring_steward-11",
      0.08,
      12.93067,
      "spring_steward"
    ],
    "d.edda_after_rillford": [
      "story-spring_steward-12",
      0.08,
      12.92333,
      "spring_steward"
    ],
    "d.edda_after_quarry": [
      "story-spring_steward-13",
      0.08,
      14.14133,
      "spring_steward"
    ],
    "d.edda_after_rotation": [
      "story-spring_steward-14",
      0.08,
      12.31533,
      "spring_steward"
    ],
    "d.darin_intro": [
      "story-quarry_foreman-1",
      0.08,
      14.97933,
      "quarry_foreman"
    ],
    "d.darin_cause": [
      "story-quarry_foreman-2",
      0.08,
      12.462,
      "quarry_foreman"
    ],
    "d.darin_hub": [
      "story-quarry_foreman-3",
      0.08,
      0.69133,
      "quarry_foreman"
    ],
    "d.darin_seep": [
      "story-quarry_foreman-4",
      0.08,
      14.97867,
      "quarry_foreman"
    ],
    "d.darin_cut": [
      "story-quarry_foreman-5",
      0.08,
      16.10667,
      "quarry_foreman"
    ],
    "d.darin_brace": [
      "story-quarry_foreman-6",
      0.08,
      12.054,
      "quarry_foreman"
    ],
    "d.darin_contract": [
      "story-quarry_foreman-7",
      0.08,
      13.81667,
      "quarry_foreman"
    ],
    "d.darin_humiliate": [
      "story-quarry_foreman-8",
      0.08,
      7.22933,
      "quarry_foreman"
    ],
    "d.darin_mediate": [
      "story-quarry_foreman-9",
      0.08,
      8.582,
      "quarry_foreman"
    ],
    "d.darin_rotation_ledger": [
      "story-quarry_foreman-10",
      0.08,
      15.15533,
      "quarry_foreman"
    ],
    "d.darin_rotation_pay": [
      "story-quarry_foreman-11",
      0.08,
      12.60533,
      "quarry_foreman"
    ],
    "d.darin_report_rillford": [
      "story-quarry_foreman-12",
      0.08,
      9.88867,
      "quarry_foreman"
    ],
    "d.darin_report_quarry": [
      "story-quarry_foreman-13",
      0.08,
      8.60267,
      "quarry_foreman"
    ],
    "d.darin_report_rotation": [
      "story-quarry_foreman-14",
      0.08,
      9.57133,
      "quarry_foreman"
    ],
    "d.darin_after_rillford": [
      "story-quarry_foreman-15",
      0.08,
      9.358,
      "quarry_foreman"
    ],
    "d.darin_after_quarry": [
      "story-quarry_foreman-16",
      0.08,
      9.20533,
      "quarry_foreman"
    ],
    "d.darin_after_rotation": [
      "story-quarry_foreman-17",
      0.08,
      11.14933,
      "quarry_foreman"
    ],
    "d.ila_stranded": [
      "story-maintenance_worker-1",
      0.08,
      17.65067,
      "maintenance_worker"
    ],
    "d.ila_gate": [
      "story-maintenance_worker-2",
      0.08,
      13.25933,
      "maintenance_worker"
    ],
    "d.ila_free_fight": [
      "story-maintenance_worker-3",
      0.08,
      11.14467,
      "maintenance_worker"
    ],
    "d.ila_free_shortcut": [
      "story-maintenance_worker-4",
      0.08,
      10.32533,
      "maintenance_worker"
    ],
    "d.ila_free_router": [
      "story-maintenance_worker-4",
      10.48533,
      1.206,
      "maintenance_worker"
    ],
    "d.ila_testimony": [
      "story-maintenance_worker-5",
      0.08,
      20.59733,
      "maintenance_worker"
    ],
    "d.ila_testimony_shortcut": [
      "story-maintenance_worker-6",
      0.08,
      24.03467,
      "maintenance_worker"
    ],
    "d.ila_hub": [
      "story-maintenance_worker-7",
      0.08,
      4.518,
      "maintenance_worker"
    ],
    "d.ila_procedure": [
      "story-maintenance_worker-8",
      0.08,
      15.14733,
      "maintenance_worker"
    ],
    "d.ila_who": [
      "story-maintenance_worker-9",
      0.08,
      20.774,
      "maintenance_worker"
    ],
    "d.ila_after": [
      "story-maintenance_worker-10",
      0.08,
      10.094,
      "maintenance_worker"
    ],
    "d.oren_intro": [
      "story-estate_steward-1",
      0.08,
      10.81333,
      "estate_steward"
    ],
    "d.oren_reserve": [
      "story-estate_steward-2",
      0.08,
      9.79733,
      "estate_steward"
    ],
    "d.oren_hub": [
      "story-estate_steward-3",
      0.08,
      5.01333,
      "estate_steward"
    ],
    "d.oren_after_quarry": [
      "story-estate_steward-4",
      0.08,
      6.97333,
      "estate_steward"
    ],
    "d.oren_after_other": [
      "story-estate_steward-5",
      0.08,
      7.28,
      "estate_steward"
    ],
    "d.sel_intro": [
      "story-ash_recorder-1",
      0.08,
      11.296,
      "ash_recorder"
    ],
    "d.sel_hub": [
      "story-ash_recorder-2",
      0.08,
      3.232,
      "ash_recorder"
    ],
    "d.sel_records": [
      "story-ash_recorder-3",
      0.08,
      12.25067,
      "ash_recorder"
    ],
    "d.sel_doom": [
      "story-ash_recorder-4",
      0.08,
      11.83533,
      "ash_recorder"
    ],
    "d.sel_after": [
      "story-ash_recorder-5",
      0.08,
      8.72267,
      "ash_recorder"
    ],
    "d.harrow_intro": [
      "story-shrine_warden-1",
      0.08,
      11.43467,
      "shrine_warden"
    ],
    "d.harrow_hub": [
      "story-shrine_warden-2",
      0.08,
      1.32067,
      "shrine_warden"
    ],
    "d.harrow_open": [
      "story-shrine_warden-2",
      1.48067,
      8.078,
      "shrine_warden"
    ],
    "d.harrow_key": [
      "story-shrine_warden-3",
      0.08,
      11.81667,
      "shrine_warden"
    ],
    "d.harrow_train": [
      "story-shrine_warden-4",
      0.08,
      17.68067,
      "shrine_warden"
    ],
    "d.harrow_trained": [
      "story-shrine_warden-5",
      0.08,
      7.73133,
      "shrine_warden"
    ],
    "d.harrow_hub2": [
      "story-shrine_warden-5",
      7.89133,
      1.03,
      "shrine_warden"
    ],
    "d.harrow_caretaker": [
      "story-shrine_warden-6",
      0.08,
      11.494,
      "shrine_warden"
    ],
    "d.bess_default": [
      "story-mill_hand-1",
      0.08,
      8.462,
      "mill_hand"
    ],
    "d.bess_rillford": [
      "story-mill_hand-2",
      0.08,
      8.928,
      "mill_hand"
    ],
    "d.bess_quarry": [
      "story-mill_hand-3",
      0.08,
      6.20533,
      "mill_hand"
    ],
    "d.bess_rotation": [
      "story-mill_hand-4",
      0.08,
      8.35467,
      "mill_hand"
    ],
    "d.pell_default": [
      "story-quarry_hand-1",
      0.08,
      12.68267,
      "quarry_hand"
    ],
    "d.pell_rillford": [
      "story-quarry_hand-2",
      0.08,
      7.66933,
      "quarry_hand"
    ],
    "d.pell_quarry": [
      "story-quarry_hand-3",
      0.08,
      9.184,
      "quarry_hand"
    ],
    "d.pell_rotation": [
      "story-quarry_hand-4",
      0.08,
      8.70133,
      "quarry_hand"
    ],
    "d.pell_caretaker": [
      "story-quarry_hand-5",
      0.08,
      10.808,
      "quarry_hand"
    ],
    "d.hesper_default": [
      "story-village_baker-1",
      0.08,
      10.88,
      "village_baker"
    ],
    "d.hesper_rillford": [
      "story-village_baker-2",
      0.08,
      10.08333,
      "village_baker"
    ],
    "d.hesper_quarry": [
      "story-village_baker-3",
      0.08,
      5.81067,
      "village_baker"
    ],
    "d.hesper_rotation": [
      "story-village_baker-4",
      0.08,
      9.04,
      "village_baker"
    ],
    "d.hesper_caretaker": [
      "story-village_baker-5",
      0.08,
      9.48267,
      "village_baker"
    ],
    "d.joss_bell#0": [
      "story-hero-1",
      1.67,
      1.55,
      "hero"
    ],
    "d.joss_bell#1": [
      "story-hero-1",
      3.3,
      1.46667,
      "hero"
    ],
    "d.joss_hub#0": [
      "story-hero-1",
      0.08,
      1.51,
      "hero"
    ],
    "d.joss_hub#1": [
      "story-hero-1",
      1.67,
      1.55,
      "hero"
    ],
    "d.mara_directions#0": [
      "story-hero-1",
      4.84667,
      0.76333,
      "hero"
    ],
    "d.mara_jammed#1": [
      "story-hero-5",
      0.08,
      0.71267,
      "hero"
    ],
    "d.mara_report_quarry#0": [
      "story-hero-6",
      0.08,
      3.34733,
      "hero"
    ],
    "d.mara_report_quarry#1": [
      "story-hero-6",
      3.50733,
      2.22733,
      "hero"
    ],
    "d.mara_report_rotation#0": [
      "story-hero-6",
      0.08,
      3.34733,
      "hero"
    ],
    "d.mara_report_rotation#1": [
      "story-hero-6",
      3.50733,
      2.22733,
      "hero"
    ],
    "d.mara_after_rillford#1": [
      "story-hero-5",
      0.08,
      0.71267,
      "hero"
    ],
    "d.mara_after_quarry#0": [
      "story-hero-6",
      5.81467,
      1.734,
      "hero"
    ],
    "d.mara_after_quarry#1": [
      "story-hero-5",
      0.08,
      0.71267,
      "hero"
    ],
    "d.mara_after_rotation#0": [
      "story-hero-6",
      5.81467,
      1.734,
      "hero"
    ],
    "d.mara_after_rotation#1": [
      "story-hero-5",
      0.08,
      0.71267,
      "hero"
    ],
    "d.edda_flow#0": [
      "story-hero-2",
      9.61067,
      0.85333,
      "hero"
    ],
    "d.edda_caught#0": [
      "story-hero-5",
      0.87267,
      1.126,
      "hero"
    ],
    "d.edda_after_rillford#0": [
      "story-hero-8",
      8.346,
      0.93067,
      "hero"
    ],
    "d.edda_after_quarry#0": [
      "story-hero-8",
      8.346,
      0.93067,
      "hero"
    ],
    "d.edda_after_rotation#0": [
      "story-hero-8",
      8.346,
      0.93067,
      "hero"
    ],
    "d.darin_hub#8": [
      "story-hero-5",
      0.08,
      0.71267,
      "hero"
    ],
    "d.darin_seep#0": [
      "story-hero-1",
      4.84667,
      0.76333,
      "hero"
    ],
    "d.darin_brace#0": [
      "story-hero-1",
      4.84667,
      0.76333,
      "hero"
    ],
    "d.darin_contract#0": [
      "story-hero-2",
      9.61067,
      0.85333,
      "hero"
    ],
    "d.darin_report_quarry#1": [
      "story-hero-13",
      6.596,
      1.814,
      "hero"
    ],
    "d.darin_report_rotation#1": [
      "story-hero-13",
      6.596,
      1.814,
      "hero"
    ],
    "d.darin_after_rillford#0": [
      "story-hero-5",
      0.08,
      0.71267,
      "hero"
    ],
    "d.darin_after_quarry#0": [
      "story-hero-5",
      0.08,
      0.71267,
      "hero"
    ],
    "d.darin_after_rotation#0": [
      "story-hero-5",
      0.08,
      0.71267,
      "hero"
    ],
    "d.ila_free_shortcut#0": [
      "story-hero-14",
      7.99267,
      1.06733,
      "hero"
    ],
    "d.ila_testimony_shortcut#0": [
      "story-hero-15",
      3.06533,
      1.902,
      "hero"
    ],
    "d.ila_procedure#0": [
      "story-hero-8",
      9.35667,
      0.91267,
      "hero"
    ],
    "d.ila_who#0": [
      "story-hero-1",
      4.84667,
      0.76333,
      "hero"
    ],
    "d.oren_after_other#0": [
      "story-hero-16",
      6.202,
      0.76067,
      "hero"
    ],
    "d.sel_intro#2": [
      "story-hero-2",
      3.46933,
      1.016,
      "hero"
    ],
    "d.sel_hub#0": [
      "story-hero-16",
      7.04267,
      1.262,
      "hero"
    ],
    "d.sel_hub#1": [
      "story-hero-16",
      8.38467,
      1.46467,
      "hero"
    ],
    "d.sel_hub#2": [
      "story-hero-5",
      0.08,
      0.71267,
      "hero"
    ],
    "d.sel_records#0": [
      "story-hero-1",
      4.84667,
      0.76333,
      "hero"
    ],
    "d.sel_after#0": [
      "story-hero-5",
      0.08,
      0.71267,
      "hero"
    ],
    "d.harrow_intro#2": [
      "story-hero-2",
      3.46933,
      1.016,
      "hero"
    ],
    "d.harrow_hub#2": [
      "story-hero-17",
      1.68,
      1.726,
      "hero"
    ],
    "d.harrow_open#0": [
      "story-hero-1",
      4.84667,
      0.76333,
      "hero"
    ],
    "d.harrow_trained#0": [
      "story-hero-1",
      4.84667,
      0.76333,
      "hero"
    ],
    "d.harrow_hub2#0": [
      "story-hero-17",
      0.08,
      1.52,
      "hero"
    ],
    "d.harrow_hub2#2": [
      "story-hero-16",
      5.404,
      0.718,
      "hero"
    ],
    "d.harrow_caretaker#0": [
      "story-hero-5",
      0.87267,
      1.126,
      "hero"
    ],
    "d.harrow_caretaker#1": [
      "story-hero-2",
      3.46933,
      1.016,
      "hero"
    ],
    "d.bess_rillford#0": [
      "story-hero-5",
      7.36067,
      0.67,
      "hero"
    ],
    "d.bess_rotation#0": [
      "story-hero-5",
      7.36067,
      0.67,
      "hero"
    ],
    "d.pell_default#0": [
      "story-hero-10",
      0.08,
      1.294,
      "hero"
    ],
    "d.pell_rillford#0": [
      "story-hero-18",
      9.41267,
      1.198,
      "hero"
    ],
    "d.pell_quarry#0": [
      "story-hero-15",
      9.26733,
      0.838,
      "hero"
    ],
    "d.pell_caretaker#0": [
      "story-hero-1",
      4.84667,
      0.76333,
      "hero"
    ],
    "d.hesper_default#0": [
      "story-hero-7",
      2.26733,
      0.96333,
      "hero"
    ],
    "d.hesper_rillford#0": [
      "story-hero-1",
      4.84667,
      0.76333,
      "hero"
    ],
    "d.hesper_quarry#0": [
      "story-hero-18",
      9.41267,
      1.198,
      "hero"
    ],
    "d.hesper_rotation#0": [
      "story-hero-5",
      7.36067,
      0.67,
      "hero"
    ],
    "d.hesper_caretaker#0": [
      "story-hero-5",
      0.87267,
      1.126,
      "hero"
    ],
    "d.rowan_default": [
      "trail_hunter-1",
      0.08,
      10.40533,
      "trail_hunter"
    ],
    "d.rowan_default#0": [
      "story-hero-1",
      4.84667,
      0.76333,
      "hero"
    ]
  }
} as const;

export type VoiceBank = keyof typeof VOICE_AUDIO.banks;
export type VoiceLineId = keyof typeof VOICE_AUDIO.lines;
export type StoryLineId = keyof typeof VOICE_AUDIO.story;
