// Generated by tools/world-audio/prepare.mjs from tools/world-audio/plan.json. Do not edit by hand.
// Offsets and durations are seconds in the 48 kHz sprites and loops under public/assets/audio/world/.

export const WORLD_AUDIO = {
  "version": 1,
  "base": "assets/audio/world/",
  "banks": {
    "steps": {
      "file": "bank-steps",
      "duration": 29.5707,
      "clips": {
        "step.grass": [
          [0.06, 0.33667],
          [0.45667, 0.31],
          [0.82667, 0.334],
          [1.22067, 0.34733],
          [1.628, 0.32867],
          [2.01667, 0.206],
          [2.28267, 0.28867],
          [2.63133, 0.334],
          [3.02533, 0.33667],
          [3.422, 0.17933]
        ],
        "step.dirt": [
          [3.66133, 0.278],
          [3.99933, 0.25133],
          [4.31067, 0.26733],
          [4.638, 0.21667],
          [4.91467, 0.27],
          [5.24467, 0.29133],
          [5.596, 0.28333],
          [5.93933, 0.23]
        ],
        "step.stone": [
          [6.22933, 0.29133],
          [6.58067, 0.33133],
          [6.972, 0.19267],
          [7.22467, 0.23],
          [7.51467, 0.29667],
          [7.87133, 0.30467],
          [8.236, 0.33667],
          [8.63267, 0.25667],
          [8.94933, 0.32867],
          [9.338, 0.222]
        ],
        "step.wood": [
          [9.62, 0.518],
          [10.198, 0.422],
          [10.68, 0.446],
          [11.186, 0.33933],
          [11.58533, 0.36867],
          [12.014, 0.35],
          [12.424, 0.35],
          [12.834, 0.36333],
          [13.25733, 0.41933]
        ],
        "step.sand": [
          [13.73667, 0.21067],
          [14.00733, 0.29933],
          [14.36667, 0.20867],
          [14.63533, 0.286],
          [14.98133, 0.286],
          [15.32733, 0.20333],
          [15.59067, 0.19533],
          [15.846, 0.35533],
          [16.26133, 0.20067]
        ],
        "step.water": [
          [16.522, 0.4],
          [16.982, 0.62],
          [17.662, 0.57],
          [18.292, 0.64],
          [18.992, 0.66],
          [19.712, 0.34],
          [20.112, 0.34]
        ],
        "step.gravel": [
          [20.512, 0.31],
          [20.882, 0.27267],
          [21.21467, 0.41933],
          [21.694, 0.28867],
          [22.04267, 0.374],
          [22.47667, 0.32067],
          [22.85733, 0.406],
          [23.32333, 0.28333],
          [23.66667, 0.29933],
          [24.026, 0.23]
        ],
        "step.run": [
          [24.316, 0.29867],
          [24.67467, 0.38467],
          [25.11933, 0.28333],
          [25.46267, 0.31533],
          [25.838, 0.438],
          [26.336, 0.37133],
          [26.76733, 0.29933],
          [27.12667, 0.31],
          [27.49667, 0.294]
        ],
        "land": [[27.85067, 0.95], [28.86067, 0.65]]
      }
    },
    "combat": {
      "file": "bank-combat",
      "duration": 38.1573,
      "clips": {
        "swing": [
          [0.06, 0.20867],
          [0.32867, 0.65667],
          [1.04533, 0.21933],
          [1.32467, 0.25133],
          [1.636, 0.32867],
          [2.02467, 0.18733],
          [2.272, 0.45933],
          [2.79133, 0.222]
        ],
        "swing.heavy": [[3.07333, 1.91733]],
        "hit.flesh": [[5.05067, 0.558], [5.66867, 1.00067]],
        "hit.block": [[6.72933, 0.28], [7.06933, 1.214], [8.34333, 0.56867]],
        "hit.parry": [[8.972, 0.45], [9.482, 1.85]],
        "hit.punch": [[11.392, 0.32533], [11.77733, 0.37933], [12.21667, 0.40333]],
        "voice.hurt": [[12.68, 0.296], [13.036, 0.23], [13.326, 0.39533], [13.78133, 0.542]],
        "voice.death": [[14.38333, 2.50933]],
        "voice.breath": [[16.95267, 1.77867], [18.79133, 0.646], [19.49733, 0.28067], [19.838, 0.494], [20.392, 0.47267]],
        "beast.growl": [[20.92467, 1.31267], [22.29733, 2.61667], [24.974, 1.646]],
        "beast.attack": [[26.68, 4]],
        "beast.hurt": [[30.74, 3.272]],
        "bandit.shout": [[34.072, 0.832], [34.964, 0.45667], [35.48067, 2.61667]]
      }
    },
    "items": {
      "file": "bank-items",
      "duration": 30.9907,
      "clips": {
        "item.coins": [[0.06, 0.99267], [1.11267, 1.75267]],
        "item.coin": [[2.92533, 0.60533]],
        "item.metal": [[3.59067, 0.76867], [4.41933, 1.31533]],
        "item.sword.draw": [[5.79467, 1.40267]],
        "item.sword.sheathe": [[7.25733, 0.632]],
        "item.cloth": [[7.94933, 2.98133]],
        "item.satchel": [[10.99067, 3.97867]],
        "item.herb": [[15.02933, 3.79733]],
        "item.eat": [[18.88667, 4.56267]],
        "item.poultice": [[23.50933, 3.272]],
        "item.page": [[26.84133, 1.352]],
        "item.map": [[28.25333, 2.67733]]
      }
    },
    "world": {
      "file": "bank-world",
      "duration": 47.796,
      "clips": {
        "door.open": [[0.06, 3.84267]],
        "door.close": [[3.96267, 1.752]],
        "shutter.break": [[5.77467, 2.54133]],
        "lever": [[8.376, 2.368]],
        "gate": [[10.804, 3.54133]],
        "sluice": [[14.40533, 4.728]],
        "water.surge": [[19.19333, 6]],
        "bell.big": [[25.25333, 7.272]],
        "bell.small": [[32.58533, 5]],
        "rite": [[37.64533, 5]],
        "wood.impact": [[42.70533, 0.76067], [43.526, 1.35]],
        "wood.lift": [[44.936, 2.8]]
      }
    },
    "nature": {
      "file": "bank-nature",
      "duration": 40.204,
      "clips": {
        "gull": [[0.06, 1.25], [1.37, 1.31], [2.74, 1.04]],
        "songbird": [[3.84, 2.73067], [6.63067, 3.41667]],
        "smallbird": [[10.10733, 2.518]],
        "crow": [[12.68533, 2.39467], [15.14, 1.63267]],
        "owl": [[16.83267, 3.60267]],
        "woodpecker": [[20.49533, 1.95467]],
        "frog": [[22.51, 1.77133], [24.34133, 1.97133]],
        "dog": [[26.37267, 0.51], [26.94267, 0.33133], [27.334, 0.75267], [28.14667, 0.318]],
        "chicken": [[28.52467, 1.61067]],
        "rooster": [[30.19533, 2.30667]],
        "horse": [[32.562, 4.896]],
        "creak": [[37.518, 0.58467], [38.16267, 1.42467], [39.64733, 0.49667]]
      }
    },
    "people": {
      "file": "bank-people",
      "duration": 45.1947,
      "clips": {
        "work.hammer": [
          [0.06, 0.19267],
          [0.31267, 0.206],
          [0.57867, 0.23],
          [0.86867, 0.23267],
          [1.16133, 0.20333],
          [1.42467, 0.19],
          [1.67467, 0.20867],
          [1.94333, 0.20333]
        ],
        "work.saw": [[2.20667, 4.89333]],
        "work.sweep": [[7.16, 0.69133], [7.91133, 0.726], [8.69733, 0.622], [9.37933, 0.486], [9.92533, 0.46733], [10.45267, 0.47]],
        "work.chisel": [
          [10.98267, 0.30467],
          [11.34733, 0.29933],
          [11.70667, 0.326],
          [12.09267, 0.334],
          [12.48667, 0.37667],
          [12.92333, 0.25133]
        ],
        "work.knead": [[13.23467, 3.80533]],
        "work.quill": [[17.1, 4.94933]],
        "work.bucket": [[22.10933, 4.792]],
        "work.sack": [[26.96133, 2.944]],
        "voice.murmur": [[29.96533, 4.1], [34.12533, 4.1], [38.28533, 4.1]],
        "voice.cough": [[42.44533, 0.66667], [43.172, 1.07], [44.302, 0.83267]]
      }
    }
  },
  "loops": {
    "sea": {
      "file": "loop-sea",
      "duration": 24.6502,
      "channels": 2,
      "sourceLevelDb": -19.7
    },
    "forest_day": {
      "file": "loop-forest_day",
      "duration": 24.6502,
      "channels": 2,
      "sourceLevelDb": -42.5
    },
    "forest_night": {
      "file": "loop-forest_night",
      "duration": 24.6502,
      "channels": 2,
      "sourceLevelDb": -30.2
    },
    "meadow_day": {
      "file": "loop-meadow_day",
      "duration": 24.6502,
      "channels": 2,
      "sourceLevelDb": -19.6
    },
    "village_day": {
      "file": "loop-village_day",
      "duration": 24.6502,
      "channels": 2,
      "sourceLevelDb": -37.4
    },
    "village_night": {
      "file": "loop-village_night",
      "duration": 14.65,
      "channels": 2,
      "sourceLevelDb": -43
    },
    "cliff_wind": {
      "file": "loop-cliff_wind",
      "duration": 19.65,
      "channels": 2,
      "sourceLevelDb": -19
    },
    "interior": {
      "file": "loop-interior",
      "duration": 14.65,
      "channels": 2,
      "sourceLevelDb": -51.3
    },
    "cut": {
      "file": "loop-cut",
      "duration": 14.65,
      "channels": 2,
      "sourceLevelDb": -44.6
    },
    "brook": {
      "file": "loop-brook",
      "duration": 14.65,
      "channels": 1,
      "sourceLevelDb": -20.1
    },
    "mill": {
      "file": "loop-mill",
      "duration": 14.65,
      "channels": 1,
      "sourceLevelDb": -15
    },
    "quarry": {
      "file": "loop-quarry",
      "duration": 19.65,
      "channels": 1,
      "sourceLevelDb": -28.8
    },
    "spring": {
      "file": "loop-spring",
      "duration": 11.65,
      "channels": 1,
      "sourceLevelDb": -33.3
    },
    "marsh": {
      "file": "loop-marsh",
      "duration": 14.65,
      "channels": 1,
      "sourceLevelDb": -33
    },
    "fire": {
      "file": "loop-fire",
      "duration": 11.65,
      "channels": 1,
      "sourceLevelDb": -33.1
    },
    "hall_drone": {
      "file": "loop-hall_drone",
      "duration": 9.65,
      "channels": 2,
      "sourceLevelDb": -13.3
    }
  },
  "music": {
    "vale_1": {
      "file": "music-vale_1",
      "duration": 30,
      "channels": 2,
      "kind": "piece",
      "mood": "vale",
      "sourceLevelDb": -10.7
    },
    "vale_2": {
      "file": "music-vale_2",
      "duration": 30,
      "channels": 2,
      "kind": "piece",
      "mood": "vale",
      "sourceLevelDb": -30.9
    },
    "wild_1": {
      "file": "music-wild_1",
      "duration": 30,
      "channels": 2,
      "kind": "piece",
      "mood": "wild",
      "sourceLevelDb": -15.1
    },
    "wild_2": {
      "file": "music-wild_2",
      "duration": 30,
      "channels": 2,
      "kind": "piece",
      "mood": "wild",
      "sourceLevelDb": -12.8
    },
    "wild_3": {
      "file": "music-wild_3",
      "duration": 30,
      "channels": 2,
      "kind": "piece",
      "mood": "wild",
      "sourceLevelDb": -13.8
    },
    "night_1": {
      "file": "music-night_1",
      "duration": 30,
      "channels": 2,
      "kind": "piece",
      "mood": "night",
      "sourceLevelDb": -26.5
    },
    "night_2": {
      "file": "music-night_2",
      "duration": 29.584,
      "channels": 2,
      "kind": "piece",
      "mood": "night",
      "sourceLevelDb": -11.5
    },
    "sacred": {
      "file": "music-sacred",
      "duration": 30,
      "channels": 2,
      "kind": "piece",
      "mood": "sacred",
      "sourceLevelDb": -20.6
    },
    "danger": {
      "file": "music-danger",
      "duration": 19.5,
      "channels": 2,
      "sourceLevelDb": -16.6,
      "kind": "loop",
      "mood": "danger"
    },
    "combat": {
      "file": "music-combat",
      "duration": 19.7,
      "channels": 2,
      "sourceLevelDb": -16.4,
      "kind": "loop",
      "mood": "combat"
    },
    "sting_discover": {
      "file": "music-sting_discover",
      "duration": 4.2933,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -8.8
    },
    "sting_victory": {
      "file": "music-sting_victory",
      "duration": 3.5733,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -24
    },
    "sting_death": {
      "file": "music-sting_death",
      "duration": 4.4907,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -18.1
    },
    "sting_quest": {
      "file": "music-sting_quest",
      "duration": 5,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -11.5
    },
    "sting_lute": {
      "file": "music-sting_lute",
      "duration": 7.7093,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -10.6
    }
  }
} as const;

export type WorldAudioManifest = typeof WORLD_AUDIO;
export type BankId = keyof typeof WORLD_AUDIO.banks;
export type LoopId = keyof typeof WORLD_AUDIO.loops;
export type MusicId = keyof typeof WORLD_AUDIO.music;
