// Generated by tools/world-audio/prepare.mjs from tools/world-audio/plan.json. Do not edit by hand.
// Offsets and durations are seconds in the 48 kHz sprites and loops under public/assets/audio/world/.

export const WORLD_AUDIO = {
  "version": 1,
  "base": "assets/audio/world/",
  "banks": {
    "steps": {
      "file": "bank-steps",
      "duration": 30.9,
      "clips": {
        "step.grass": [
          [0.06, 1.05933],
          [1.17933, 0.414],
          [1.65333, 0.30467],
          [2.018, 0.46733],
          [2.54533, 0.36867],
          [2.974, 0.38733],
          [3.42133, 0.39]
        ],
        "step.dirt": [
          [3.87133, 0.134],
          [4.06533, 0.21667],
          [4.342, 0.15533],
          [4.55733, 0.18733],
          [4.80467, 0.206],
          [5.07067, 0.25133],
          [5.382, 0.13667],
          [5.57867, 0.17933],
          [5.818, 0.15267],
          [6.03067, 0.102]
        ],
        "step.stone": [
          [6.19267, 0.23],
          [6.48267, 0.486],
          [7.02867, 0.438],
          [7.52667, 0.34467],
          [7.93133, 0.28333],
          [8.27467, 0.294],
          [8.62867, 0.27],
          [8.95867, 0.294]
        ],
        "step.wood": [
          [9.31267, 0.37933],
          [9.752, 0.366],
          [10.178, 0.33133],
          [10.56933, 0.374],
          [11.00333, 0.342],
          [11.40533, 0.33933],
          [11.80467, 0.44067],
          [12.30533, 0.518],
          [12.88333, 0.326]
        ],
        "step.sand": [
          [13.26933, 0.342],
          [13.67133, 0.27],
          [14.00133, 0.254],
          [14.31533, 0.28067],
          [14.656, 0.77933],
          [15.49533, 0.286],
          [15.84133, 0.294],
          [16.19533, 0.342],
          [16.59733, 0.69133]
        ],
        "step.water": [
          [17.34867, 0.46],
          [17.86867, 0.54],
          [18.46867, 0.55],
          [19.07867, 0.4],
          [19.53867, 0.5],
          [20.09867, 0.42],
          [20.57867, 0.53]
        ],
        "step.gravel": [
          [21.16867, 0.33933],
          [21.568, 0.31533],
          [21.94333, 0.39267],
          [22.396, 0.34733],
          [22.80333, 0.35533],
          [23.21867, 0.31267],
          [23.59133, 0.382],
          [24.03333, 0.29133],
          [24.38467, 0.32333]
        ],
        "step.run": [
          [24.768, 0.28067],
          [25.10867, 0.438],
          [25.60667, 0.28867],
          [25.95533, 0.438],
          [26.45333, 0.27533],
          [26.78867, 0.438],
          [27.28667, 0.31533],
          [27.662, 0.238]
        ],
        "land": [[27.96, 0.98], [29, 0.8], [29.86, 0.98]]
      }
    },
    "combat": {
      "file": "bank-combat",
      "duration": 41.8947,
      "clips": {
        "swing": [[0.06, 0.46467], [0.58467, 0.286], [0.93067, 0.25133], [1.242, 0.37133], [1.67333, 0.28067]],
        "swing.heavy": [[2.014, 2.05867]],
        "hit.flesh": [[4.13267, 0.47267], [4.66533, 0.48867], [5.214, 1.638]],
        "hit.block": [[6.912, 0.44867], [7.42067, 0.398], [7.87867, 0.37667]],
        "hit.parry": [[8.31533, 1.2], [9.57533, 1.35]],
        "hit.punch": [[10.98533, 0.84867]],
        "voice.hurt": [[11.894, 0.41333], [12.36733, 0.34467], [12.772, 0.42733], [13.25933, 0.42733]],
        "voice.death": [[13.74667, 2.58933]],
        "voice.breath": [
          [16.396, 0.26933],
          [16.72533, 0.23533],
          [17.02067, 0.32333],
          [17.404, 0.30467],
          [17.76867, 1.00333],
          [18.832, 0.53133],
          [19.42333, 0.414]
        ],
        "beast.growl": [[19.89733, 1.87533], [21.83267, 2.61667]],
        "beast.attack": [[24.50933, 3.16533]],
        "beast.hurt": [[27.73467, 2.33067]],
        "bandit.shout": [[30.12533, 0.534], [30.71933, 2.166], [32.94533, 0.48333]],
        "hero.hurt": [[33.48867, 0.43467], [33.98333, 0.48067], [34.524, 0.48867], [35.07267, 0.45667]],
        "hero.breath": [
          [35.58933, 0.29333],
          [35.94267, 0.24067],
          [36.24333, 0.318],
          [36.62133, 0.31533],
          [36.99667, 1.00867],
          [38.06533, 0.55533],
          [38.68067, 0.446]
        ],
        "hero.death": [[39.18667, 2.648]]
      }
    },
    "items": {
      "file": "bank-items",
      "duration": 34.9787,
      "clips": {
        "item.coins": [[0.06, 1.07267], [1.19267, 1.11533], [2.368, 0.534]],
        "item.coin": [[2.962, 0.84]],
        "item.metal": [[3.862, 0.926], [4.848, 1.02467], [5.93267, 1.214]],
        "item.sword.draw": [[7.20667, 1.31733]],
        "item.sword.sheathe": [[8.584, 0.744]],
        "item.cloth": [[9.388, 2.952]],
        "item.satchel": [[12.4, 3.77067]],
        "item.herb": [[16.23067, 3.82933]],
        "item.eat": [[20.12, 4.824]],
        "item.poultice": [[25.004, 3.80267]],
        "item.page": [[28.86667, 3.45867]],
        "item.map": [[32.38533, 2.53333]]
      }
    },
    "world": {
      "file": "bank-world",
      "duration": 45.8387,
      "clips": {
        "door.open": [[0.06, 3.83733]],
        "door.close": [[3.95733, 1.008]],
        "shutter.break": [[5.02533, 2.576]],
        "lever": [[7.66133, 1.83467]],
        "gate": [[9.556, 3.35467]],
        "sluice": [[12.97067, 4.07733]],
        "water.surge": [[17.108, 5.97067]],
        "bell.big": [[23.13867, 7.65333]],
        "bell.small": [[30.852, 5]],
        "rite": [[35.912, 5]],
        "wood.impact": [[40.972, 0.94467], [41.97667, 0.85933]],
        "wood.lift": [[42.896, 2.88267]]
      }
    },
    "nature": {
      "file": "bank-nature",
      "duration": 39.322,
      "clips": {
        "gull": [[0.06, 0.75], [0.87, 2.55], [3.48, 1.1], [4.64, 1.1]],
        "songbird": [[5.8, 2.696], [8.556, 3.518]],
        "smallbird": [[12.134, 0.69133], [12.88533, 2.518]],
        "crow": [[15.46333, 2.768], [18.29133, 0.50467], [18.856, 0.45933]],
        "owl": [[19.37533, 2.104]],
        "woodpecker": [[21.53933, 2.00267]],
        "frog": [[23.602, 2.01067], [25.67267, 0.44333]],
        "dog": [[26.176, 0.19533], [26.43133, 1.45133], [27.94267, 0.446]],
        "chicken": [[28.44867, 1.61667]],
        "rooster": [[30.12533, 2.34133]],
        "horse": [[32.52667, 4.848]],
        "creak": [[37.43467, 1.82733]]
      }
    },
    "people": {
      "file": "bank-people",
      "duration": 48.4093,
      "clips": {
        "work.hammer": [
          [0.06, 0.19533],
          [0.31533, 0.23267],
          [0.608, 0.20067],
          [0.86867, 0.21933],
          [1.148, 0.27267],
          [1.48067, 0.254],
          [1.79467, 0.26733],
          [2.122, 0.254]
        ],
        "work.saw": [[2.436, 4.82133]],
        "work.sweep": [
          [7.31733, 0.44867],
          [7.826, 0.48333],
          [8.36933, 0.48333],
          [8.91267, 0.46467],
          [9.43733, 0.48067],
          [9.978, 1.21667]
        ],
        "work.chisel": [
          [11.25467, 0.286],
          [11.60067, 0.28867],
          [11.94933, 0.182],
          [12.19133, 0.182],
          [12.43333, 0.174],
          [12.66733, 0.27267],
          [13, 0.15],
          [13.21, 0.15267]
        ],
        "work.knead": [[13.42267, 4.06133]],
        "work.quill": [[17.544, 4.96]],
        "work.bucket": [[22.564, 4.56]],
        "work.sack": [[27.184, 4.776]],
        "voice.murmur": [[32.02, 4.1], [36.18, 4.1], [40.34, 4.1]],
        "voice.cough": [[44.5, 0.99733], [45.55733, 1.14467], [46.762, 1.58733]]
      }
    },
    "water": {
      "file": "bank-water",
      "duration": 39.7387,
      "clips": {
        "water.wave": [[0.06, 5.704]],
        "water.rock": [[5.824, 4.45333]],
        "water.splash.big": [[10.33733, 3.328]],
        "water.splash.small": [[13.72533, 0.846], [14.63133, 0.84333]],
        "water.swim": [[15.53467, 1.81067], [17.40533, 1.81667]],
        "water.wade": [[19.282, 1.21667], [20.55867, 0.886], [21.50467, 0.63533], [22.2, 0.49667]],
        "water.enter": [[22.75667, 3.05333]],
        "water.exit": [[25.87, 4.42667]],
        "water.knock": [[30.35667, 1.21667], [31.63333, 1.21667], [32.91, 0.742]],
        "water.bubbles": [[33.712, 2.90667]],
        "water.fish": [[36.67867, 3]]
      }
    },
    "crafted": {
      "file": "bank-crafted",
      "duration": 52.7814,
      "clips": {
        "bell.town": [[0.06, 6.99733], [7.11733, 7]],
        "bell.peal": [[14.17733, 4.2], [18.43733, 4.2], [22.69733, 4.19733]],
        "chime": [[26.95467, 3], [30.01467, 3], [33.07467, 3], [36.13467, 3], [39.19467, 3]],
        "cricket": [
          [42.25467, 0.13333],
          [42.448, 0.10133],
          [42.60933, 0.13333],
          [42.80267, 0.16533],
          [43.028, 0.09867],
          [43.18667, 0.136]
        ],
        "bubble": [
          [43.38267, 0.01887],
          [43.46154, 0.0216],
          [43.54315, 0.02452],
          [43.62767, 0.02754],
          [43.71521, 0.03069],
          [43.8059, 0.03394],
          [43.89983, 0.03729],
          [43.99712, 0.04423]
        ],
        "heart": [[44.10135, 0.75], [44.91135, 0.75]],
        "rite.bowl": [[45.72135, 7]]
      }
    }
  },
  "loops": {
    "sea": {
      "file": "loop-sea",
      "duration": 24.6502,
      "channels": 2,
      "sourceLevelDb": -19.8
    },
    "forest_day": {
      "file": "loop-forest_day",
      "duration": 24.6502,
      "channels": 2,
      "sourceLevelDb": -38
    },
    "forest_night": {
      "file": "loop-forest_night",
      "duration": 24.6502,
      "channels": 2,
      "sourceLevelDb": -23.3
    },
    "meadow_day": {
      "file": "loop-meadow_day",
      "duration": 24.6502,
      "channels": 2,
      "sourceLevelDb": -17.9
    },
    "village_day": {
      "file": "loop-village_day",
      "duration": 24.6502,
      "channels": 2,
      "sourceLevelDb": -36.1
    },
    "village_night": {
      "file": "loop-village_night",
      "duration": 14.65,
      "channels": 2,
      "sourceLevelDb": -30.8
    },
    "cliff_wind": {
      "file": "loop-cliff_wind",
      "duration": 19.65,
      "channels": 2,
      "sourceLevelDb": -17.4
    },
    "interior": {
      "file": "loop-interior",
      "duration": 14.65,
      "channels": 2,
      "sourceLevelDb": -53.6
    },
    "cut": {
      "file": "loop-cut",
      "duration": 14.65,
      "channels": 2,
      "sourceLevelDb": -41.9
    },
    "brook": {
      "file": "loop-brook",
      "duration": 14.65,
      "channels": 1,
      "sourceLevelDb": -22.3
    },
    "mill": {
      "file": "loop-mill",
      "duration": 14.65,
      "channels": 1,
      "sourceLevelDb": -18
    },
    "quarry": {
      "file": "loop-quarry",
      "duration": 19.65,
      "channels": 1,
      "sourceLevelDb": -22.3
    },
    "spring": {
      "file": "loop-spring",
      "duration": 11.65,
      "channels": 1,
      "sourceLevelDb": -35.7
    },
    "marsh": {
      "file": "loop-marsh",
      "duration": 14.65,
      "channels": 1,
      "sourceLevelDb": -27.3
    },
    "fire": {
      "file": "loop-fire",
      "duration": 11.65,
      "channels": 1,
      "sourceLevelDb": -35.5
    },
    "hall_drone": {
      "file": "loop-hall_drone",
      "duration": 9.65,
      "channels": 2,
      "sourceLevelDb": -12.1
    },
    "surf": {
      "file": "loop-surf",
      "duration": 21.65,
      "channels": 2,
      "sourceLevelDb": -19.6
    },
    "surf_rocks": {
      "file": "loop-surf_rocks",
      "duration": 19.65,
      "channels": 2,
      "sourceLevelDb": -23.5
    },
    "sea_far": {
      "file": "loop-sea_far",
      "duration": 19.65,
      "channels": 2,
      "sourceLevelDb": -20
    },
    "lap": {
      "file": "loop-lap",
      "duration": 14.65,
      "channels": 1,
      "sourceLevelDb": -27.4
    },
    "rapids": {
      "file": "loop-rapids",
      "duration": 14.65,
      "channels": 1,
      "sourceLevelDb": -15.5
    },
    "underwater": {
      "file": "loop-underwater",
      "duration": 15.65,
      "channels": 2,
      "sourceLevelDb": -19.7
    }
  },
  "music": {
    "vale_1": {
      "file": "music-vale_1",
      "duration": 74.184,
      "channels": 2,
      "kind": "piece",
      "mood": "vale",
      "sourceLevelDb": -16.3,
      "origin": "generated"
    },
    "vale_2": {
      "file": "music-vale_2",
      "duration": 73.7627,
      "channels": 2,
      "kind": "piece",
      "mood": "vale",
      "sourceLevelDb": -17.2,
      "origin": "generated"
    },
    "wild_1": {
      "file": "music-wild_1",
      "duration": 73.9253,
      "channels": 2,
      "kind": "piece",
      "mood": "wild",
      "sourceLevelDb": -16.7,
      "origin": "generated"
    },
    "wild_2": {
      "file": "music-wild_2",
      "duration": 73.9067,
      "channels": 2,
      "kind": "piece",
      "mood": "wild",
      "sourceLevelDb": -15.7,
      "origin": "generated"
    },
    "wild_3": {
      "file": "music-wild_3",
      "duration": 71.936,
      "channels": 2,
      "kind": "piece",
      "mood": "wild",
      "sourceLevelDb": -21.1,
      "origin": "generated"
    },
    "night_1": {
      "file": "music-night_1",
      "duration": 72.856,
      "channels": 2,
      "kind": "piece",
      "mood": "night",
      "sourceLevelDb": -21.4,
      "origin": "generated"
    },
    "night_2": {
      "file": "music-night_2",
      "duration": 70.9013,
      "channels": 2,
      "kind": "piece",
      "mood": "night",
      "sourceLevelDb": -16.2,
      "origin": "generated"
    },
    "sacred": {
      "file": "music-sacred",
      "duration": 72.8533,
      "channels": 2,
      "kind": "piece",
      "mood": "sacred",
      "sourceLevelDb": -29.4,
      "origin": "generated"
    },
    "danger": {
      "file": "music-danger",
      "duration": 38.18,
      "channels": 2,
      "sourceLevelDb": -29,
      "kind": "loop",
      "mood": "danger",
      "origin": "generated"
    },
    "combat": {
      "file": "music-combat",
      "duration": 36.8,
      "channels": 2,
      "sourceLevelDb": -14.4,
      "kind": "loop",
      "mood": "combat",
      "origin": "generated"
    },
    "sting_discover": {
      "file": "music-sting_discover",
      "duration": 5.1707,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -17.8,
      "origin": "generated"
    },
    "sting_victory": {
      "file": "music-sting_victory",
      "duration": 5.2293,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -14.2,
      "origin": "generated"
    },
    "sting_death": {
      "file": "music-sting_death",
      "duration": 4.8933,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -17.8,
      "origin": "generated"
    },
    "sting_quest": {
      "file": "music-sting_quest",
      "duration": 5.5787,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -21.1,
      "origin": "generated"
    },
    "sting_lute": {
      "file": "music-sting_lute",
      "duration": 7.0533,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -19,
      "origin": "generated"
    },
    "vale_3": {
      "file": "music-vale_3",
      "duration": 72.488,
      "channels": 2,
      "kind": "piece",
      "mood": "vale",
      "sourceLevelDb": -17.4,
      "origin": "generated"
    },
    "wild_4": {
      "file": "music-wild_4",
      "duration": 71.4293,
      "channels": 2,
      "kind": "piece",
      "mood": "wild",
      "sourceLevelDb": -18.1,
      "origin": "generated"
    },
    "night_3": {
      "file": "music-night_3",
      "duration": 71.1413,
      "channels": 2,
      "kind": "piece",
      "mood": "night",
      "sourceLevelDb": -27.5,
      "origin": "generated"
    },
    "sacred_2": {
      "file": "music-sacred_2",
      "duration": 72.4373,
      "channels": 2,
      "kind": "piece",
      "mood": "sacred",
      "sourceLevelDb": -19,
      "origin": "generated"
    },
    "danger_2": {
      "file": "music-danger_2",
      "duration": 27.5,
      "channels": 2,
      "sourceLevelDb": -21.7,
      "kind": "loop",
      "mood": "danger",
      "origin": "generated"
    },
    "combat_2": {
      "file": "music-combat_2",
      "duration": 32,
      "channels": 2,
      "sourceLevelDb": -14.8,
      "kind": "loop",
      "mood": "combat",
      "origin": "generated"
    },
    "theme_vale": {
      "file": "music-theme_vale",
      "duration": 84.232,
      "channels": 2,
      "kind": "piece",
      "mood": "vale",
      "sourceLevelDb": -16.9,
      "origin": "composed",
      "title": "Rillford at Work"
    },
    "theme_wild": {
      "file": "music-theme_wild",
      "duration": 72.3467,
      "channels": 2,
      "kind": "piece",
      "mood": "wild",
      "sourceLevelDb": -16.6,
      "origin": "composed",
      "title": "The Deepwood"
    },
    "theme_night": {
      "file": "music-theme_night",
      "duration": 66.768,
      "channels": 2,
      "kind": "piece",
      "mood": "night",
      "sourceLevelDb": -20.7,
      "origin": "composed",
      "title": "Embers"
    },
    "theme_sacred": {
      "file": "music-theme_sacred",
      "duration": 77.3173,
      "channels": 2,
      "kind": "piece",
      "mood": "sacred",
      "sourceLevelDb": -13.8,
      "origin": "composed",
      "title": "The Spring"
    },
    "danger_watch": {
      "file": "music-danger_watch",
      "duration": 20,
      "channels": 2,
      "kind": "loop",
      "mood": "danger",
      "sourceLevelDb": -17.7,
      "origin": "composed",
      "title": "Something Watches"
    },
    "battle_ford": {
      "file": "music-battle_ford",
      "duration": 19.5918,
      "channels": 2,
      "kind": "loop",
      "mood": "combat",
      "sourceLevelDb": -15.2,
      "origin": "composed",
      "title": "Steel at the Ford"
    },
    "sting_victory_theme": {
      "file": "music-sting_victory_theme",
      "duration": 6.4,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -14.3,
      "origin": "composed",
      "title": "A Fight Won"
    },
    "sting_fall_theme": {
      "file": "music-sting_fall_theme",
      "duration": 12.0427,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -18.8,
      "origin": "composed",
      "title": "The Fall"
    },
    "sting_quest_theme": {
      "file": "music-sting_quest_theme",
      "duration": 7.0187,
      "channels": 2,
      "kind": "sting",
      "mood": "sting",
      "sourceLevelDb": -20.3,
      "origin": "composed",
      "title": "A Step of the Story"
    },
    "place_coast": {
      "file": "music-place_coast",
      "duration": 12.2143,
      "channels": 2,
      "kind": "sting",
      "mood": "place",
      "sourceLevelDb": -19.4,
      "origin": "composed",
      "title": "The Grey Strand"
    },
    "place_wood": {
      "file": "music-place_wood",
      "duration": 12.2143,
      "channels": 2,
      "kind": "sting",
      "mood": "place",
      "sourceLevelDb": -19.2,
      "origin": "composed",
      "title": "Into the Deepwood"
    },
    "place_vale": {
      "file": "music-place_vale",
      "duration": 9.472,
      "channels": 2,
      "kind": "sting",
      "mood": "place",
      "sourceLevelDb": -18.8,
      "origin": "composed",
      "title": "The Vale Opens"
    },
    "place_stone": {
      "file": "music-place_stone",
      "duration": 10.688,
      "channels": 2,
      "kind": "sting",
      "mood": "place",
      "sourceLevelDb": -18.9,
      "origin": "composed",
      "title": "Cut Stone"
    },
    "place_sacred": {
      "file": "music-place_sacred",
      "duration": 10.7333,
      "channels": 2,
      "kind": "sting",
      "mood": "place",
      "sourceLevelDb": -17.6,
      "origin": "composed",
      "title": "Holy Water"
    },
    "place_light": {
      "file": "music-place_light",
      "duration": 5.6373,
      "channels": 2,
      "kind": "sting",
      "mood": "place",
      "sourceLevelDb": -23,
      "origin": "composed",
      "title": "Lantern Point"
    }
  },
  "songs": {
    "drought_bell": {
      "file": "song-drought_bell",
      "duration": 119.904,
      "channels": 1,
      "title": "The Drought Bell",
      "sourceLevelDb": -11.6
    },
    "bread_and_water": {
      "file": "song-bread_and_water",
      "duration": 118.4453,
      "channels": 1,
      "title": "Bread and Water",
      "sourceLevelDb": -11.9
    },
    "wanderers_air": {
      "file": "song-wanderers_air",
      "duration": 70.8613,
      "channels": 1,
      "title": "The Wanderer's Air",
      "sourceLevelDb": -21.2
    },
    "hearthsmoke": {
      "file": "song-hearthsmoke",
      "duration": 38.2187,
      "channels": 1,
      "title": "Hearthsmoke",
      "sourceLevelDb": -18.6
    },
    "salt_and_rope": {
      "file": "song-salt_and_rope",
      "duration": 58.6347,
      "channels": 1,
      "title": "Salt and Rope",
      "sourceLevelDb": -23.9
    }
  }
} as const;

export type WorldAudioManifest = typeof WORLD_AUDIO;
export type BankId = keyof typeof WORLD_AUDIO.banks;
export type LoopId = keyof typeof WORLD_AUDIO.loops;
export type MusicId = keyof typeof WORLD_AUDIO.music;
export type SongId = keyof typeof WORLD_AUDIO.songs;
