/**
 * The provenance classification every Meshy entry in the distributed model ledger (public/model-licenses.json) carries
 * (A73, correcting A72). A Meshy source is exactly one of:
 *
 *   ael-generated-meshy-pro   generated by the project through its own Meshy API calls, with the task ids recorded
 *                             (furniture, resident rigs, resident motion); paid-plan Customer Output (terms section 3.2)
 *   meshy-community-download  downloaded from the Meshy Community, made by another creator; the 3D model is CC0 1.0
 *                             (section 3.3(a)), any other Community content such as images CC BY-NC 4.0 (section 3.3(b))
 *   unresolved                supplied as a file with no record of who generated it or where it came from
 *
 * A `Meshy_AI_<name>_<timestamp>_<stage>.glb` filename is what Meshy's own export produces for any account and for
 * Community downloads alike, so it is not evidence of who generated a model. Nothing is classified by guesswork: a
 * supplied source moves out of `unresolved` only when COMMUNITY_SOURCES or AEL_GENERATED_SUPPLIED records the evidence.
 *
 * The record scripts (tools/meshy-rig/record.mjs, tools/meshy-furniture/record.mjs, tools/hero/record.mjs) use these
 * values for the entries they write; tools/model-ledger/classify-meshy.mjs applies them to the whole ledger.
 */
import fs from 'node:fs';

export const MESHY_TERMS_URL = 'https://www.meshy.ai/terms-of-use';
export const MESHY_TERMS_UPDATED = '2026-09-19';
export const MESHY_PLAN = 'Meshy Pro (paid)';

export const AEL_GENERATED = 'ael-generated-meshy-pro';
export const COMMUNITY = 'meshy-community-download';
export const UNRESOLVED = 'unresolved';
export const CLASSIFICATIONS = [AEL_GENERATED, COMMUNITY, UNRESOLVED];

export const MESHY_PAID_STATUS = 'meshy-paid-plan-output';
export const MESHY_COMMUNITY_STATUS = 'meshy-community-cc0';
export const MESHY_UNRESOLVED_STATUS = 'unresolved-meshy-provenance';

export const CREATOR_NOT_RECORDED = 'creator not recorded';

/** Section 3.3 of the Meshy terms of use (Last Updated: September 19, 2026), quoted. */
export const MESHY_COMMUNITY_TERMS = 'You agree that, if You upload, post, submit, or otherwise make available any image or other content on the Meshy Community page (collectively, "Community Content"), such Community Content is licensed to the public and other users of the Meshy Community page as follows: (a) Customer Output, including 3D models, is licensed under the Creative Commons Zero (CC0) 1.0 Universal Public Domain Dedication (the "CC0 License"); and (b) all other Community Content, including images You upload, is licensed under the Creative Commons Attribution-NonCommercial 4.0 International license (the "CC BY-NC 4.0 License").';

/**
 * Supplied sources with recorded Community evidence: { [sourceId]: { creator, listingUrl, evidence } }. Empty: no
 * listing URL, creator name or embedded author metadata is recorded for any supplied source yet. Add an entry only
 * from a recorded listing or the owner's confirmation; never infer one.
 */
export const COMMUNITY_SOURCES = {};

/** Supplied sources with recorded evidence of generation by the project under Meshy Pro: { [sourceId]: evidence }. */
export const AEL_GENERATED_SUPPLIED = {
  'wanderer-meshy71': 'Generated by Ael\'s account under Meshy Pro on 9 October 2026: Meshy multi-image to 3D, model meshy-7.1 (2k geometry, 4k PBR textures, A-pose), task id 01a120c8-22b6-72d4-8c60-2b2451b7edfd; the source hash and how it was fitted to the rig are recorded in docs/engineering/main-hero-assets.json (tools/hero/rework-hero.mjs).',
};

/** The evidence for the sources the project generated through its own Meshy API calls. */
const generatedEvidence = (id) => {
  if (id.startsWith('furniture-')) return 'Generated through the project\'s own Meshy API calls (tools/meshy-furniture/generate.mjs, text to 3D, 8 October 2026); the preview and refine task ids and the prompt are recorded in public/models/furniture/manifest.json.';
  if (id === 'resident-motion') return 'Generated through the project\'s own Meshy API calls (tools/meshy-rig/meshy.mjs, animation library and text to motion, 8 October 2026); each clip\'s task id and date are recorded in public/models/npcs/motion/clips.json.';
  if (id === 'resident-rigs') return 'Generated through the project\'s own Meshy API calls (tools/meshy-rig/meshy.mjs, automatic rigging, 8 October 2026); each rig file records its rigging task id (ledger generatedRigs).';
  return null;
};

/** Why each family of supplied sources stays unresolved: what the record shows and what it lacks. */
const unresolvedEvidence = (id) => {
  const family = id.startsWith('npc-') ? 'resident' : id.startsWith('animal-') ? 'animal' : id.startsWith('tree-') || id === 'solitary-pine' || id === 'ancient-guardian' ? 'tree'
    : id.startsWith('wanderer-') ? 'wanderer' : 'scenery';
  const lacks = 'The source record names the owner as supplier only; no Meshy task id from the project\'s generation, no Community listing URL, no creator name and no author or generator metadata are recorded, and the original file is not in the repository. A Meshy_AI_* export filename does not show who generated a model.';
  const notes = {
    resident: 'Supplied Meshy resident GLB (docs/engineering/meshy-npc-assets.json: "Owner supplied these Meshy GLBs").',
    animal: 'Supplied Meshy animal GLB (docs/engineering/meshy-animal-assets.json); the prepared file embeds only Tervain preparation metadata.',
    tree: 'Supplied Meshy tree GLB (owner-supplied per its tree record).',
    wanderer: 'Supplied Meshy hero GLB (owner-supplied per its hero record).',
    scenery: 'Supplied Meshy scenery GLB (owner-supplied per its record).',
  };
  return `${notes[family]} ${lacks}`;
};

/** The provenance of one Meshy source: { classification, evidence, creator?, listingUrl? }. */
export function meshyProvenance(id) {
  const generated = generatedEvidence(id);
  if (generated) return { classification: AEL_GENERATED, evidence: generated };
  if (AEL_GENERATED_SUPPLIED[id]) return { classification: AEL_GENERATED, evidence: AEL_GENERATED_SUPPLIED[id] };
  const community = COMMUNITY_SOURCES[id];
  if (community) return {
    classification: COMMUNITY, evidence: community.evidence,
    creator: community.creator || CREATOR_NOT_RECORDED, listingUrl: community.listingUrl ?? null,
  };
  return { classification: UNRESOLVED, evidence: unresolvedEvidence(id) };
}

/** The license record of a Meshy source the project generated under Meshy Pro. */
export const meshyProLicense = () => ({
  spdx: null,
  version: null,
  evidenceStatus: MESHY_PAID_STATUS,
  plan: MESHY_PLAN,
  confirmation: 'Generated through the project\'s own Meshy API calls (task ids recorded); the owner confirmed on 9 October 2026 that the project\'s own Meshy generation used Meshy Pro.',
  confirmedAt: '2026-10-09',
  terms: `Meshy terms of use (${MESHY_TERMS_URL}), Last Updated ${MESHY_TERMS_UPDATED}, section 3.2: paid-plan Customer Output. See serviceRules.`,
});

/** The license record of a source downloaded from the Meshy Community. */
export const meshyCommunityLicense = ({ creator, listingUrl }) => ({
  spdx: 'CC0-1.0',
  version: '1.0',
  evidenceStatus: MESHY_COMMUNITY_STATUS,
  creator: creator || CREATOR_NOT_RECORDED,
  listingUrl: listingUrl ?? null,
  terms: `Meshy terms of use (${MESHY_TERMS_URL}), Last Updated ${MESHY_TERMS_UPDATED}, section 3.3(a): Customer Output posted on the Meshy Community, including 3D models, is CC0 1.0. Any other Community content used with it (such as an uploaded image) is CC BY-NC 4.0 under section 3.3(b), which requires attribution and allows no commercial use.`,
  attribution: 'CC0 requires no attribution; the creator is credited anyway where known.',
});

/** The license record of a supplied source whose origin is not established. */
export const meshyUnresolvedLicense = () => ({
  spdx: null,
  version: null,
  evidenceStatus: MESHY_UNRESOLVED_STATUS,
  creator: CREATOR_NOT_RECORDED,
  terms: `Not determined. If the project generated it under Meshy Pro: Meshy terms (${MESHY_TERMS_URL}, Last Updated ${MESHY_TERMS_UPDATED}) section 3.2, paid-plan Customer Output. If it was downloaded from the Meshy Community: the 3D model is CC0 1.0 under section 3.3(a), and any other Community content used with it, such as images, is CC BY-NC 4.0 (attribution, non-commercial) under section 3.3(b); the creator should then be credited. If it came from a free-plan account: CC BY 4.0 with Meshy credit (section 3.2).`,
});

/** The license record of a source, by its provenance. */
export function meshySourceLicense(id) {
  const provenance = meshyProvenance(id);
  if (provenance.classification === AEL_GENERATED) return meshyProLicense();
  if (provenance.classification === COMMUNITY) return meshyCommunityLicense(provenance);
  return meshyUnresolvedLicense();
}

/** The license record of a shipped file derived from a Meshy source. */
export function meshyAssetLicense(id) {
  const { classification } = meshyProvenance(id);
  if (classification === AEL_GENERATED) return { spdx: null, version: null, evidenceStatus: MESHY_PAID_STATUS, plan: MESHY_PLAN };
  if (classification === COMMUNITY) return { spdx: 'CC0-1.0', version: '1.0', evidenceStatus: MESHY_COMMUNITY_STATUS };
  return { spdx: null, version: null, evidenceStatus: MESHY_UNRESOLVED_STATUS };
}

/** Kept for the record scripts that only write project-generated output (furniture, rigs, motion). */
export const meshyProAssetLicense = () => meshyAssetLicense('resident-motion');

export const MESHY_RIGHTS_BOUNDARY = 'Meshy paid-plan Customer Output generated by the project (Meshy terms section 3.2). This records the applicable terms branch; it is not a commercial-clearance certificate and does not clear the rights of any input model, third-party input, trademark, publicity or separately recorded rights.';
export const MESHY_UNRESOLVED_BOUNDARY = 'Provenance unresolved: who generated this source, or whether it was downloaded from the Meshy Community, is not recorded. Its license is not determined and no clearance of any kind is recorded.';
export const MESHY_COMMUNITY_BOUNDARY = 'Downloaded from the Meshy Community: the 3D model is CC0 1.0 (section 3.3(a)). Any other Community content used with it is CC BY-NC 4.0 (section 3.3(b)). CC0 does not clear trademark, publicity or third-party input rights.';

/** Inputs of project-generated output whose own provenance is unresolved. */
const INPUT_NOTES = {
  'resident-rigs': 'Each rig was generated from a supplied resident model; the rig follows the project\'s own Meshy Pro generation, but the input model keeps its own (unresolved) provenance, recorded under its npc-* source.',
  'wanderer-meshy71': 'Generated from front, side and back renders of the previous wanderer in his bind pose (the mesh drawn from A69, source wanderer-historical), which keeps its own (unresolved) provenance; the shipped file also carries the A45 skeleton and clips, recorded under wanderer-animated.',
  'resident-motion': 'The clips were generated on a Meshy automatic rig of a supplied resident (estate-steward, source npc-1004193030); the clips follow the project\'s own Meshy Pro generation, while that resident model keeps its own (unresolved) provenance.',
};

/** What the animated hero's source carries beyond Meshy output, recorded apart from its provenance. */
export const WANDERER_SEPARATE_RIGHTS = [{
  component: 'Mixamo-named skeleton and animation content in the supplied animated source',
  evidenceStatus: 'pending-source-rights',
  note: 'Separate from the Meshy provenance question. Its separate source rights are not independently established.',
}];

export const meshyServiceRules = () => ({
  source: MESHY_TERMS_URL,
  termsUpdated: MESHY_TERMS_UPDATED,
  termsLastUpdatedAsPublished: 'Last Updated: September 19, 2026',
  sections: ['2.9', '3.1', '3.2', '3.3', '7.2'],
  classifications: {
    [AEL_GENERATED]: 'Generated by the project through its own Meshy API calls under Meshy Pro (task ids recorded): section 3.2 paid-plan Customer Output.',
    [COMMUNITY]: 'Downloaded from the Meshy Community, made by another creator: section 3.3(a) CC0 1.0 for the 3D model; section 3.3(b) CC BY-NC 4.0 for any other Community content.',
    [UNRESOLVED]: 'Origin not recorded; no license branch is asserted.',
  },
  paidOutput: 'Section 3.2 (Ownership of User Content; Rights Granted to Meshy): customers on a paid Meshy plan may keep their User Content private; as between Meshy and those customers, and to the extent possible under applicable law, they own their Customer Output. Customers grant Meshy a non-exclusive, royalty-free, worldwide license to use User Content as necessary to provide the Service and as otherwise permitted under the terms.',
  freeOutput: 'Section 3.2: free-plan output is owned by Meshy and made available to free-plan customers under CC BY 4.0, with credit to Meshy.',
  communityOutput: MESHY_COMMUNITY_TERMS,
  communityLicenseToMeshy: 'Section 3.3 also grants Meshy a non-exclusive, royalty-free, worldwide, perpetual, irrevocable and sublicensable license to Community Content for providing, operating, developing, improving, marketing and commercializing its services.',
  nonCommercialFlag: 'CC BY-NC 4.0 (section 3.3(b)) requires attribution and permits no commercial use. No source in this ledger is recorded under it, but any Community image or other non-model Community content used with a model would carry it.',
  serviceAssets: 'Section 3.1 (Meshy’s Intellectual Property): Meshy owns the Service; Service Assets are licensed only to the extent incorporated into and necessary to use the Customer Output.',
  training: 'Section 2.9: Meshy may use non-Enterprise customers’ inputs and outputs to train, validate, test or improve its Services.',
  disclaimers: 'Section 7.2 (Disclaimers): Customer Output is provided as is and may be inaccurate; Meshy does not guarantee that it is unique or unlike existing 3D models, and it may not qualify for intellectual-property protection.',
  boundary: 'This records terms branches and the evidence for each source. It does not certify commercial clearance, which remains unsettled until the unresolved sources are confirmed.',
});

/** Applies the provenance classification to every Meshy source, rig and derived file in the ledger. */
export function classifyMeshy(ledger) {
  ledger.serviceRules = meshyServiceRules();
  const meshy = new Set();
  for (const [id, source] of Object.entries(ledger.sources)) {
    if (source.generationService !== 'Meshy') continue;
    meshy.add(id);
    const provenance = meshyProvenance(id);
    source.provenance = provenance;
    source.license = meshySourceLicense(id);
    source.rightsBoundary = provenance.classification === AEL_GENERATED ? MESHY_RIGHTS_BOUNDARY
      : provenance.classification === COMMUNITY ? MESHY_COMMUNITY_BOUNDARY : MESHY_UNRESOLVED_BOUNDARY;
    if (provenance.classification === UNRESOLVED) source.creator = 'Not recorded';
    if (provenance.classification === COMMUNITY) source.creator = provenance.creator;
    if (INPUT_NOTES[id]) source.inputProvenance = INPUT_NOTES[id];
    if (id === 'wanderer-animated') source.separateRights = WANDERER_SEPARATE_RIGHTS;
  }
  for (const asset of ledger.assets) if (meshy.has(asset.sourceId)) asset.license = meshyAssetLicense(asset.sourceId);
  return ledger;
}

/** Writes JSON as the ledger and manifests are kept: two-space indents, and characters beyond ASCII escaped. */
export const writeJson = (file, value) => fs.writeFileSync(file,
  `${JSON.stringify(value, null, 2).replace(/[\u0080-￿]/g, (c) => `\\u${c.charCodeAt(0).toString(16).padStart(4, '0')}`)}\n`);
export const writeLedger = writeJson;
