/** Generated by prepare_shared_crt_bootstrap.py from admitted SharedBase receipts.
 * Syntax grants no current memory, callback authority or successful execution. */
export interface SharedCommandLineInstruction { readonly address:string; readonly bytes:string; readonly instruction:string; }
const rows: readonly (readonly string[])[] = [
  [
    "100c0a0f",
    "55",
    "PUSH EBP"
  ],
  [
    "100c0a10",
    "8bec",
    "MOV EBP,ESP"
  ],
  [
    "100c0a12",
    "51",
    "PUSH ECX"
  ],
  [
    "100c0a13",
    "8b4d10",
    "MOV ECX,dword ptr [EBP + 0x10]"
  ],
  [
    "100c0a16",
    "53",
    "PUSH EBX"
  ],
  [
    "100c0a17",
    "33c0",
    "XOR EAX,EAX"
  ],
  [
    "100c0a19",
    "394508",
    "CMP dword ptr [EBP + 0x8],EAX"
  ],
  [
    "100c0a1c",
    "56",
    "PUSH ESI"
  ],
  [
    "100c0a1d",
    "8907",
    "MOV dword ptr [EDI],EAX"
  ],
  [
    "100c0a1f",
    "8bf2",
    "MOV ESI,EDX"
  ],
  [
    "100c0a21",
    "8b550c",
    "MOV EDX,dword ptr [EBP + 0xc]"
  ],
  [
    "100c0a24",
    "c70101000000",
    "MOV dword ptr [ECX],0x1"
  ],
  [
    "100c0a2a",
    "7409",
    "JZ 0x100c0a35"
  ],
  [
    "100c0a2c",
    "8b5d08",
    "MOV EBX,dword ptr [EBP + 0x8]"
  ],
  [
    "100c0a2f",
    "83450804",
    "ADD dword ptr [EBP + 0x8],0x4"
  ],
  [
    "100c0a33",
    "8913",
    "MOV dword ptr [EBX],EDX"
  ],
  [
    "100c0a35",
    "8945fc",
    "MOV dword ptr [EBP + -0x4],EAX"
  ],
  [
    "100c0a38",
    "803e22",
    "CMP byte ptr [ESI],0x22"
  ],
  [
    "100c0a3b",
    "7510",
    "JNZ 0x100c0a4d"
  ],
  [
    "100c0a3d",
    "33c0",
    "XOR EAX,EAX"
  ],
  [
    "100c0a3f",
    "3945fc",
    "CMP dword ptr [EBP + -0x4],EAX"
  ],
  [
    "100c0a42",
    "b322",
    "MOV BL,0x22"
  ],
  [
    "100c0a44",
    "0f94c0",
    "SETZ AL"
  ],
  [
    "100c0a47",
    "46",
    "INC ESI"
  ],
  [
    "100c0a48",
    "8945fc",
    "MOV dword ptr [EBP + -0x4],EAX"
  ],
  [
    "100c0a4b",
    "eb3c",
    "JMP 0x100c0a89"
  ],
  [
    "100c0a4d",
    "ff07",
    "INC dword ptr [EDI]"
  ],
  [
    "100c0a4f",
    "85d2",
    "TEST EDX,EDX"
  ],
  [
    "100c0a51",
    "7408",
    "JZ 0x100c0a5b"
  ],
  [
    "100c0a53",
    "8a06",
    "MOV AL,byte ptr [ESI]"
  ],
  [
    "100c0a55",
    "8802",
    "MOV byte ptr [EDX],AL"
  ],
  [
    "100c0a57",
    "42",
    "INC EDX"
  ],
  [
    "100c0a58",
    "89550c",
    "MOV dword ptr [EBP + 0xc],EDX"
  ],
  [
    "100c0a5b",
    "8a1e",
    "MOV BL,byte ptr [ESI]"
  ],
  [
    "100c0a5d",
    "0fb6c3",
    "MOVZX EAX,BL"
  ],
  [
    "100c0a60",
    "50",
    "PUSH EAX"
  ],
  [
    "100c0a61",
    "46",
    "INC ESI"
  ],
  [
    "100c0a62",
    "e860150100",
    "CALL 0x100d1fc7"
  ],
  [
    "100c0a67",
    "85c0",
    "TEST EAX,EAX"
  ],
  [
    "100c0a69",
    "59",
    "POP ECX"
  ],
  [
    "100c0a6a",
    "7413",
    "JZ 0x100c0a7f"
  ],
  [
    "100c0a6c",
    "ff07",
    "INC dword ptr [EDI]"
  ],
  [
    "100c0a6e",
    "837d0c00",
    "CMP dword ptr [EBP + 0xc],0x0"
  ],
  [
    "100c0a72",
    "740a",
    "JZ 0x100c0a7e"
  ],
  [
    "100c0a74",
    "8b4d0c",
    "MOV ECX,dword ptr [EBP + 0xc]"
  ],
  [
    "100c0a77",
    "8a06",
    "MOV AL,byte ptr [ESI]"
  ],
  [
    "100c0a79",
    "ff450c",
    "INC dword ptr [EBP + 0xc]"
  ],
  [
    "100c0a7c",
    "8801",
    "MOV byte ptr [ECX],AL"
  ],
  [
    "100c0a7e",
    "46",
    "INC ESI"
  ],
  [
    "100c0a7f",
    "84db",
    "TEST BL,BL"
  ],
  [
    "100c0a81",
    "8b550c",
    "MOV EDX,dword ptr [EBP + 0xc]"
  ],
  [
    "100c0a84",
    "8b4d10",
    "MOV ECX,dword ptr [EBP + 0x10]"
  ],
  [
    "100c0a87",
    "7432",
    "JZ 0x100c0abb"
  ],
  [
    "100c0a89",
    "837dfc00",
    "CMP dword ptr [EBP + -0x4],0x0"
  ],
  [
    "100c0a8d",
    "75a9",
    "JNZ 0x100c0a38"
  ],
  [
    "100c0a8f",
    "80fb20",
    "CMP BL,0x20"
  ],
  [
    "100c0a92",
    "7405",
    "JZ 0x100c0a99"
  ],
  [
    "100c0a94",
    "80fb09",
    "CMP BL,0x9"
  ],
  [
    "100c0a97",
    "759f",
    "JNZ 0x100c0a38"
  ],
  [
    "100c0a99",
    "85d2",
    "TEST EDX,EDX"
  ],
  [
    "100c0a9b",
    "7404",
    "JZ 0x100c0aa1"
  ],
  [
    "100c0a9d",
    "c642ff00",
    "MOV byte ptr [EDX + -0x1],0x0"
  ],
  [
    "100c0aa1",
    "8365fc00",
    "AND dword ptr [EBP + -0x4],0x0"
  ],
  [
    "100c0aa5",
    "803e00",
    "CMP byte ptr [ESI],0x0"
  ],
  [
    "100c0aa8",
    "0f84e9000000",
    "JZ 0x100c0b97"
  ],
  [
    "100c0aae",
    "8a06",
    "MOV AL,byte ptr [ESI]"
  ],
  [
    "100c0ab0",
    "3c20",
    "CMP AL,0x20"
  ],
  [
    "100c0ab2",
    "7404",
    "JZ 0x100c0ab8"
  ],
  [
    "100c0ab4",
    "3c09",
    "CMP AL,0x9"
  ],
  [
    "100c0ab6",
    "7506",
    "JNZ 0x100c0abe"
  ],
  [
    "100c0ab8",
    "46",
    "INC ESI"
  ],
  [
    "100c0ab9",
    "ebf3",
    "JMP 0x100c0aae"
  ],
  [
    "100c0abb",
    "4e",
    "DEC ESI"
  ],
  [
    "100c0abc",
    "ebe3",
    "JMP 0x100c0aa1"
  ],
  [
    "100c0abe",
    "803e00",
    "CMP byte ptr [ESI],0x0"
  ],
  [
    "100c0ac1",
    "0f84d0000000",
    "JZ 0x100c0b97"
  ],
  [
    "100c0ac7",
    "837d0800",
    "CMP dword ptr [EBP + 0x8],0x0"
  ],
  [
    "100c0acb",
    "7409",
    "JZ 0x100c0ad6"
  ],
  [
    "100c0acd",
    "8b4508",
    "MOV EAX,dword ptr [EBP + 0x8]"
  ],
  [
    "100c0ad0",
    "83450804",
    "ADD dword ptr [EBP + 0x8],0x4"
  ],
  [
    "100c0ad4",
    "8910",
    "MOV dword ptr [EAX],EDX"
  ],
  [
    "100c0ad6",
    "ff01",
    "INC dword ptr [ECX]"
  ],
  [
    "100c0ad8",
    "33db",
    "XOR EBX,EBX"
  ],
  [
    "100c0ada",
    "43",
    "INC EBX"
  ],
  [
    "100c0adb",
    "33c9",
    "XOR ECX,ECX"
  ],
  [
    "100c0add",
    "eb02",
    "JMP 0x100c0ae1"
  ],
  [
    "100c0adf",
    "46",
    "INC ESI"
  ],
  [
    "100c0ae0",
    "41",
    "INC ECX"
  ],
  [
    "100c0ae1",
    "803e5c",
    "CMP byte ptr [ESI],0x5c"
  ],
  [
    "100c0ae4",
    "74f9",
    "JZ 0x100c0adf"
  ],
  [
    "100c0ae6",
    "803e22",
    "CMP byte ptr [ESI],0x22"
  ],
  [
    "100c0ae9",
    "7526",
    "JNZ 0x100c0b11"
  ],
  [
    "100c0aeb",
    "f6c101",
    "TEST CL,0x1"
  ],
  [
    "100c0aee",
    "751f",
    "JNZ 0x100c0b0f"
  ],
  [
    "100c0af0",
    "837dfc00",
    "CMP dword ptr [EBP + -0x4],0x0"
  ],
  [
    "100c0af4",
    "740c",
    "JZ 0x100c0b02"
  ],
  [
    "100c0af6",
    "8d4601",
    "LEA EAX,[ESI + 0x1]"
  ],
  [
    "100c0af9",
    "803822",
    "CMP byte ptr [EAX],0x22"
  ],
  [
    "100c0afc",
    "7504",
    "JNZ 0x100c0b02"
  ],
  [
    "100c0afe",
    "8bf0",
    "MOV ESI,EAX"
  ],
  [
    "100c0b00",
    "eb0d",
    "JMP 0x100c0b0f"
  ],
  [
    "100c0b02",
    "33c0",
    "XOR EAX,EAX"
  ],
  [
    "100c0b04",
    "33db",
    "XOR EBX,EBX"
  ],
  [
    "100c0b06",
    "3945fc",
    "CMP dword ptr [EBP + -0x4],EAX"
  ],
  [
    "100c0b09",
    "0f94c0",
    "SETZ AL"
  ],
  [
    "100c0b0c",
    "8945fc",
    "MOV dword ptr [EBP + -0x4],EAX"
  ],
  [
    "100c0b0f",
    "d1e9",
    "SHR ECX,0x1"
  ],
  [
    "100c0b11",
    "85c9",
    "TEST ECX,ECX"
  ],
  [
    "100c0b13",
    "7412",
    "JZ 0x100c0b27"
  ],
  [
    "100c0b15",
    "49",
    "DEC ECX"
  ],
  [
    "100c0b16",
    "85d2",
    "TEST EDX,EDX"
  ],
  [
    "100c0b18",
    "7404",
    "JZ 0x100c0b1e"
  ],
  [
    "100c0b1a",
    "c6025c",
    "MOV byte ptr [EDX],0x5c"
  ],
  [
    "100c0b1d",
    "42",
    "INC EDX"
  ],
  [
    "100c0b1e",
    "ff07",
    "INC dword ptr [EDI]"
  ],
  [
    "100c0b20",
    "85c9",
    "TEST ECX,ECX"
  ],
  [
    "100c0b22",
    "75f1",
    "JNZ 0x100c0b15"
  ],
  [
    "100c0b24",
    "89550c",
    "MOV dword ptr [EBP + 0xc],EDX"
  ],
  [
    "100c0b27",
    "8a06",
    "MOV AL,byte ptr [ESI]"
  ],
  [
    "100c0b29",
    "84c0",
    "TEST AL,AL"
  ],
  [
    "100c0b2b",
    "7455",
    "JZ 0x100c0b82"
  ],
  [
    "100c0b2d",
    "837dfc00",
    "CMP dword ptr [EBP + -0x4],0x0"
  ],
  [
    "100c0b31",
    "7508",
    "JNZ 0x100c0b3b"
  ],
  [
    "100c0b33",
    "3c20",
    "CMP AL,0x20"
  ],
  [
    "100c0b35",
    "744b",
    "JZ 0x100c0b82"
  ],
  [
    "100c0b37",
    "3c09",
    "CMP AL,0x9"
  ],
  [
    "100c0b39",
    "7447",
    "JZ 0x100c0b82"
  ],
  [
    "100c0b3b",
    "85db",
    "TEST EBX,EBX"
  ],
  [
    "100c0b3d",
    "743d",
    "JZ 0x100c0b7c"
  ],
  [
    "100c0b3f",
    "85d2",
    "TEST EDX,EDX"
  ],
  [
    "100c0b41",
    "0fbec0",
    "MOVSX EAX,AL"
  ],
  [
    "100c0b44",
    "50",
    "PUSH EAX"
  ],
  [
    "100c0b45",
    "7423",
    "JZ 0x100c0b6a"
  ],
  [
    "100c0b47",
    "e87b140100",
    "CALL 0x100d1fc7"
  ],
  [
    "100c0b4c",
    "85c0",
    "TEST EAX,EAX"
  ],
  [
    "100c0b4e",
    "59",
    "POP ECX"
  ],
  [
    "100c0b4f",
    "740d",
    "JZ 0x100c0b5e"
  ],
  [
    "100c0b51",
    "8a06",
    "MOV AL,byte ptr [ESI]"
  ],
  [
    "100c0b53",
    "8b4d0c",
    "MOV ECX,dword ptr [EBP + 0xc]"
  ],
  [
    "100c0b56",
    "ff450c",
    "INC dword ptr [EBP + 0xc]"
  ],
  [
    "100c0b59",
    "8801",
    "MOV byte ptr [ECX],AL"
  ],
  [
    "100c0b5b",
    "46",
    "INC ESI"
  ],
  [
    "100c0b5c",
    "ff07",
    "INC dword ptr [EDI]"
  ],
  [
    "100c0b5e",
    "8b4d0c",
    "MOV ECX,dword ptr [EBP + 0xc]"
  ],
  [
    "100c0b61",
    "8a06",
    "MOV AL,byte ptr [ESI]"
  ],
  [
    "100c0b63",
    "ff450c",
    "INC dword ptr [EBP + 0xc]"
  ],
  [
    "100c0b66",
    "8801",
    "MOV byte ptr [ECX],AL"
  ],
  [
    "100c0b68",
    "eb0d",
    "JMP 0x100c0b77"
  ],
  [
    "100c0b6a",
    "e858140100",
    "CALL 0x100d1fc7"
  ],
  [
    "100c0b6f",
    "85c0",
    "TEST EAX,EAX"
  ],
  [
    "100c0b71",
    "59",
    "POP ECX"
  ],
  [
    "100c0b72",
    "7403",
    "JZ 0x100c0b77"
  ],
  [
    "100c0b74",
    "46",
    "INC ESI"
  ],
  [
    "100c0b75",
    "ff07",
    "INC dword ptr [EDI]"
  ],
  [
    "100c0b77",
    "ff07",
    "INC dword ptr [EDI]"
  ],
  [
    "100c0b79",
    "8b550c",
    "MOV EDX,dword ptr [EBP + 0xc]"
  ],
  [
    "100c0b7c",
    "46",
    "INC ESI"
  ],
  [
    "100c0b7d",
    "e956ffffff",
    "JMP 0x100c0ad8"
  ],
  [
    "100c0b82",
    "85d2",
    "TEST EDX,EDX"
  ],
  [
    "100c0b84",
    "7407",
    "JZ 0x100c0b8d"
  ],
  [
    "100c0b86",
    "c60200",
    "MOV byte ptr [EDX],0x0"
  ],
  [
    "100c0b89",
    "42",
    "INC EDX"
  ],
  [
    "100c0b8a",
    "89550c",
    "MOV dword ptr [EBP + 0xc],EDX"
  ],
  [
    "100c0b8d",
    "ff07",
    "INC dword ptr [EDI]"
  ],
  [
    "100c0b8f",
    "8b4d10",
    "MOV ECX,dword ptr [EBP + 0x10]"
  ],
  [
    "100c0b92",
    "e90effffff",
    "JMP 0x100c0aa5"
  ],
  [
    "100c0b97",
    "8b4508",
    "MOV EAX,dword ptr [EBP + 0x8]"
  ],
  [
    "100c0b9a",
    "85c0",
    "TEST EAX,EAX"
  ],
  [
    "100c0b9c",
    "5e",
    "POP ESI"
  ],
  [
    "100c0b9d",
    "5b",
    "POP EBX"
  ],
  [
    "100c0b9e",
    "7403",
    "JZ 0x100c0ba3"
  ],
  [
    "100c0ba0",
    "832000",
    "AND dword ptr [EAX],0x0"
  ],
  [
    "100c0ba3",
    "ff01",
    "INC dword ptr [ECX]"
  ],
  [
    "100c0ba5",
    "c9",
    "LEAVE"
  ],
  [
    "100c0ba6",
    "c3",
    "RET"
  ],
  [
    "100d1fc7",
    "6a04",
    "PUSH 0x4"
  ],
  [
    "100d1fc9",
    "6a00",
    "PUSH 0x0"
  ],
  [
    "100d1fcb",
    "ff74240c",
    "PUSH dword ptr [ESP + 0xc]"
  ],
  [
    "100d1fcf",
    "6a00",
    "PUSH 0x0"
  ],
  [
    "100d1fd1",
    "e833feffff",
    "CALL 0x100d1e09"
  ],
  [
    "100d1fd6",
    "83c410",
    "ADD ESP,0x10"
  ],
  [
    "100d1fd9",
    "c3",
    "RET"
  ],
  [
    "100d1e09",
    "55",
    "PUSH EBP"
  ],
  [
    "100d1e0a",
    "8bec",
    "MOV EBP,ESP"
  ],
  [
    "100d1e0c",
    "83ec10",
    "SUB ESP,0x10"
  ],
  [
    "100d1e0f",
    "ff7508",
    "PUSH dword ptr [EBP + 0x8]"
  ],
  [
    "100d1e12",
    "8d4df0",
    "LEA ECX,[EBP + -0x10]"
  ],
  [
    "100d1e15",
    "e89c56fdff",
    "CALL 0x100a74b6"
  ],
  [
    "100d1e1a",
    "0fb6450c",
    "MOVZX EAX,byte ptr [EBP + 0xc]"
  ],
  [
    "100d1e1e",
    "8b4df4",
    "MOV ECX,dword ptr [EBP + -0xc]"
  ],
  [
    "100d1e21",
    "8a5514",
    "MOV DL,byte ptr [EBP + 0x14]"
  ],
  [
    "100d1e24",
    "8454011d",
    "TEST byte ptr [ECX + EAX*0x1 + 0x1d],DL"
  ],
  [
    "100d1e28",
    "751e",
    "JNZ 0x100d1e48"
  ],
  [
    "100d1e2a",
    "837d1000",
    "CMP dword ptr [EBP + 0x10],0x0"
  ],
  [
    "100d1e2e",
    "7412",
    "JZ 0x100d1e42"
  ],
  [
    "100d1e30",
    "8b4df0",
    "MOV ECX,dword ptr [EBP + -0x10]"
  ],
  [
    "100d1e33",
    "8b89c8000000",
    "MOV ECX,dword ptr [ECX + 0xc8]"
  ],
  [
    "100d1e39",
    "0fb70441",
    "MOVZX EAX,word ptr [ECX + EAX*0x2]"
  ],
  [
    "100d1e3d",
    "234510",
    "AND EAX,dword ptr [EBP + 0x10]"
  ],
  [
    "100d1e40",
    "eb02",
    "JMP 0x100d1e44"
  ],
  [
    "100d1e42",
    "33c0",
    "XOR EAX,EAX"
  ],
  [
    "100d1e44",
    "85c0",
    "TEST EAX,EAX"
  ],
  [
    "100d1e46",
    "7403",
    "JZ 0x100d1e4b"
  ],
  [
    "100d1e48",
    "33c0",
    "XOR EAX,EAX"
  ],
  [
    "100d1e4a",
    "40",
    "INC EAX"
  ],
  [
    "100d1e4b",
    "807dfc00",
    "CMP byte ptr [EBP + -0x4],0x0"
  ],
  [
    "100d1e4f",
    "7407",
    "JZ 0x100d1e58"
  ],
  [
    "100d1e51",
    "8b4df8",
    "MOV ECX,dword ptr [EBP + -0x8]"
  ],
  [
    "100d1e54",
    "836170fd",
    "AND dword ptr [ECX + 0x70],0xfffffffd"
  ],
  [
    "100d1e58",
    "c9",
    "LEAVE"
  ],
  [
    "100d1e59",
    "c3",
    "RET"
  ],
  [
    "100c092a",
    "53",
    "PUSH EBX"
  ],
  [
    "100c092b",
    "33db",
    "XOR EBX,EBX"
  ],
  [
    "100c092d",
    "391d88852f10",
    "CMP dword ptr [0x102f8588],EBX"
  ],
  [
    "100c0933",
    "56",
    "PUSH ESI"
  ],
  [
    "100c0934",
    "57",
    "PUSH EDI"
  ],
  [
    "100c0935",
    "7505",
    "JNZ 0x100c093c"
  ],
  [
    "100c0937",
    "e8180fffff",
    "CALL 0x100b1854"
  ],
  [
    "100c093c",
    "8b3590642f10",
    "MOV ESI,dword ptr [0x102f6490]"
  ],
  [
    "100c0942",
    "33ff",
    "XOR EDI,EDI"
  ],
  [
    "100c0944",
    "3bf3",
    "CMP ESI,EBX"
  ],
  [
    "100c0946",
    "7518",
    "JNZ 0x100c0960"
  ],
  [
    "100c0948",
    "83c8ff",
    "OR EAX,0xffffffff"
  ],
  [
    "100c094b",
    "e99b000000",
    "JMP 0x100c09eb"
  ],
  [
    "100c0950",
    "3c3d",
    "CMP AL,0x3d"
  ],
  [
    "100c0952",
    "7401",
    "JZ 0x100c0955"
  ],
  [
    "100c0954",
    "47",
    "INC EDI"
  ],
  [
    "100c0955",
    "56",
    "PUSH ESI"
  ],
  [
    "100c0956",
    "e82521ffff",
    "CALL 0x100b2a80"
  ],
  [
    "100c095b",
    "59",
    "POP ECX"
  ],
  [
    "100c095c",
    "8d740601",
    "LEA ESI,[ESI + EAX*0x1 + 0x1]"
  ],
  [
    "100c0960",
    "8a06",
    "MOV AL,byte ptr [ESI]"
  ],
  [
    "100c0962",
    "3ac3",
    "CMP AL,BL"
  ],
  [
    "100c0964",
    "75ea",
    "JNZ 0x100c0950"
  ],
  [
    "100c0966",
    "6a04",
    "PUSH 0x4"
  ],
  [
    "100c0968",
    "47",
    "INC EDI"
  ],
  [
    "100c0969",
    "57",
    "PUSH EDI"
  ],
  [
    "100c096a",
    "e8a1e5feff",
    "CALL 0x100aef10"
  ],
  [
    "100c096f",
    "8bf8",
    "MOV EDI,EAX"
  ],
  [
    "100c0971",
    "3bfb",
    "CMP EDI,EBX"
  ],
  [
    "100c0973",
    "59",
    "POP ECX"
  ],
  [
    "100c0974",
    "59",
    "POP ECX"
  ],
  [
    "100c0975",
    "893d4c642f10",
    "MOV dword ptr [0x102f644c],EDI"
  ],
  [
    "100c097b",
    "74cb",
    "JZ 0x100c0948"
  ],
  [
    "100c097d",
    "8b3590642f10",
    "MOV ESI,dword ptr [0x102f6490]"
  ],
  [
    "100c0983",
    "55",
    "PUSH EBP"
  ],
  [
    "100c0984",
    "eb40",
    "JMP 0x100c09c6"
  ],
  [
    "100c0986",
    "56",
    "PUSH ESI"
  ],
  [
    "100c0987",
    "e8f420ffff",
    "CALL 0x100b2a80"
  ],
  [
    "100c098c",
    "8be8",
    "MOV EBP,EAX"
  ],
  [
    "100c098e",
    "45",
    "INC EBP"
  ],
  [
    "100c098f",
    "803e3d",
    "CMP byte ptr [ESI],0x3d"
  ],
  [
    "100c0992",
    "59",
    "POP ECX"
  ],
  [
    "100c0993",
    "742f",
    "JZ 0x100c09c4"
  ],
  [
    "100c0995",
    "6a01",
    "PUSH 0x1"
  ],
  [
    "100c0997",
    "55",
    "PUSH EBP"
  ],
  [
    "100c0998",
    "e873e5feff",
    "CALL 0x100aef10"
  ],
  [
    "100c099d",
    "3bc3",
    "CMP EAX,EBX"
  ],
  [
    "100c099f",
    "59",
    "POP ECX"
  ],
  [
    "100c09a0",
    "59",
    "POP ECX"
  ],
  [
    "100c09a1",
    "8907",
    "MOV dword ptr [EDI],EAX"
  ],
  [
    "100c09a3",
    "744a",
    "JZ 0x100c09ef"
  ],
  [
    "100c09a5",
    "56",
    "PUSH ESI"
  ],
  [
    "100c09a6",
    "55",
    "PUSH EBP"
  ],
  [
    "100c09a7",
    "50",
    "PUSH EAX"
  ],
  [
    "100c09a8",
    "e87c040000",
    "CALL 0x100c0e29"
  ],
  [
    "100c09ad",
    "83c40c",
    "ADD ESP,0xc"
  ],
  [
    "100c09b0",
    "85c0",
    "TEST EAX,EAX"
  ],
  [
    "100c09b2",
    "740d",
    "JZ 0x100c09c1"
  ],
  [
    "100c09b4",
    "53",
    "PUSH EBX"
  ],
  [
    "100c09b5",
    "53",
    "PUSH EBX"
  ],
  [
    "100c09b6",
    "53",
    "PUSH EBX"
  ],
  [
    "100c09b7",
    "53",
    "PUSH EBX"
  ],
  [
    "100c09b8",
    "53",
    "PUSH EBX"
  ],
  [
    "100c09b9",
    "e8e0d6feff",
    "CALL 0x100ae09e"
  ],
  [
    "100c09c1",
    "83c704",
    "ADD EDI,0x4"
  ],
  [
    "100c09c4",
    "03f5",
    "ADD ESI,EBP"
  ],
  [
    "100c09c6",
    "381e",
    "CMP byte ptr [ESI],BL"
  ],
  [
    "100c09c8",
    "75bc",
    "JNZ 0x100c0986"
  ],
  [
    "100c09ca",
    "ff3590642f10",
    "PUSH dword ptr [0x102f6490]"
  ],
  [
    "100c09d0",
    "e8cf9ffeff",
    "CALL 0x100aa9a4"
  ],
  [
    "100c09d5",
    "891d90642f10",
    "MOV dword ptr [0x102f6490],EBX"
  ],
  [
    "100c09db",
    "891f",
    "MOV dword ptr [EDI],EBX"
  ],
  [
    "100c09dd",
    "c70570852f1001000000",
    "MOV dword ptr [0x102f8570],0x1"
  ],
  [
    "100c09e7",
    "33c0",
    "XOR EAX,EAX"
  ],
  [
    "100c09e9",
    "59",
    "POP ECX"
  ],
  [
    "100c09ea",
    "5d",
    "POP EBP"
  ],
  [
    "100c09eb",
    "5f",
    "POP EDI"
  ],
  [
    "100c09ec",
    "5e",
    "POP ESI"
  ],
  [
    "100c09ed",
    "5b",
    "POP EBX"
  ],
  [
    "100c09ee",
    "c3",
    "RET"
  ],
  [
    "100c09ef",
    "ff354c642f10",
    "PUSH dword ptr [0x102f644c]"
  ],
  [
    "100c09f5",
    "e8aa9ffeff",
    "CALL 0x100aa9a4"
  ],
  [
    "100c09fa",
    "891d4c642f10",
    "MOV dword ptr [0x102f644c],EBX"
  ],
  [
    "100c0a00",
    "83c8ff",
    "OR EAX,0xffffffff"
  ],
  [
    "100c0a03",
    "ebe4",
    "JMP 0x100c09e9"
  ],
  [
    "100c0e29",
    "8b4c2404",
    "MOV ECX,dword ptr [ESP + 0x4]"
  ],
  [
    "100c0e2d",
    "53",
    "PUSH EBX"
  ],
  [
    "100c0e2e",
    "33db",
    "XOR EBX,EBX"
  ],
  [
    "100c0e30",
    "3bcb",
    "CMP ECX,EBX"
  ],
  [
    "100c0e32",
    "56",
    "PUSH ESI"
  ],
  [
    "100c0e33",
    "57",
    "PUSH EDI"
  ],
  [
    "100c0e34",
    "7408",
    "JZ 0x100c0e3e"
  ],
  [
    "100c0e36",
    "8b7c2414",
    "MOV EDI,dword ptr [ESP + 0x14]"
  ],
  [
    "100c0e3a",
    "3bfb",
    "CMP EDI,EBX"
  ],
  [
    "100c0e3c",
    "771b",
    "JA 0x100c0e59"
  ],
  [
    "100c0e3e",
    "e88edffeff",
    "CALL 0x100aedd1"
  ],
  [
    "100c0e43",
    "6a16",
    "PUSH 0x16"
  ],
  [
    "100c0e45",
    "5e",
    "POP ESI"
  ],
  [
    "100c0e46",
    "8930",
    "MOV dword ptr [EAX],ESI"
  ],
  [
    "100c0e48",
    "53",
    "PUSH EBX"
  ],
  [
    "100c0e49",
    "53",
    "PUSH EBX"
  ],
  [
    "100c0e4a",
    "53",
    "PUSH EBX"
  ],
  [
    "100c0e4b",
    "53",
    "PUSH EBX"
  ],
  [
    "100c0e4c",
    "53",
    "PUSH EBX"
  ],
  [
    "100c0e4d",
    "e880d3feff",
    "CALL 0x100ae1d2"
  ],
  [
    "100c0e52",
    "83c414",
    "ADD ESP,0x14"
  ],
  [
    "100c0e55",
    "8bc6",
    "MOV EAX,ESI"
  ],
  [
    "100c0e57",
    "eb31",
    "JMP 0x100c0e8a"
  ],
  [
    "100c0e59",
    "8b742418",
    "MOV ESI,dword ptr [ESP + 0x18]"
  ],
  [
    "100c0e5d",
    "3bf3",
    "CMP ESI,EBX"
  ],
  [
    "100c0e5f",
    "7504",
    "JNZ 0x100c0e65"
  ],
  [
    "100c0e61",
    "8819",
    "MOV byte ptr [ECX],BL"
  ],
  [
    "100c0e63",
    "ebd9",
    "JMP 0x100c0e3e"
  ],
  [
    "100c0e65",
    "8bd1",
    "MOV EDX,ECX"
  ],
  [
    "100c0e67",
    "8a06",
    "MOV AL,byte ptr [ESI]"
  ],
  [
    "100c0e69",
    "8802",
    "MOV byte ptr [EDX],AL"
  ],
  [
    "100c0e6b",
    "42",
    "INC EDX"
  ],
  [
    "100c0e6c",
    "46",
    "INC ESI"
  ],
  [
    "100c0e6d",
    "3ac3",
    "CMP AL,BL"
  ],
  [
    "100c0e6f",
    "7403",
    "JZ 0x100c0e74"
  ],
  [
    "100c0e71",
    "4f",
    "DEC EDI"
  ],
  [
    "100c0e72",
    "75f3",
    "JNZ 0x100c0e67"
  ],
  [
    "100c0e74",
    "3bfb",
    "CMP EDI,EBX"
  ],
  [
    "100c0e76",
    "7510",
    "JNZ 0x100c0e88"
  ],
  [
    "100c0e78",
    "8819",
    "MOV byte ptr [ECX],BL"
  ],
  [
    "100c0e7a",
    "e852dffeff",
    "CALL 0x100aedd1"
  ],
  [
    "100c0e7f",
    "6a22",
    "PUSH 0x22"
  ],
  [
    "100c0e81",
    "59",
    "POP ECX"
  ],
  [
    "100c0e82",
    "8908",
    "MOV dword ptr [EAX],ECX"
  ],
  [
    "100c0e84",
    "8bf1",
    "MOV ESI,ECX"
  ],
  [
    "100c0e86",
    "ebc0",
    "JMP 0x100c0e48"
  ],
  [
    "100c0e88",
    "33c0",
    "XOR EAX,EAX"
  ],
  [
    "100c0e8a",
    "5f",
    "POP EDI"
  ],
  [
    "100c0e8b",
    "5e",
    "POP ESI"
  ],
  [
    "100c0e8c",
    "5b",
    "POP EBX"
  ],
  [
    "100c0e8d",
    "c3",
    "RET"
  ]
];
const instructions = new Map<string,SharedCommandLineInstruction>(rows.map(([address,bytes,instruction]) =>
  [address!,Object.freeze({address:address!,bytes:bytes!,instruction:instruction!})]));
export function sharedCommandLineInstruction(address:string):SharedCommandLineInstruction {
  const row=instructions.get(address);if(!row)throw new Error('Unowned SharedBase parser instruction at '+address);return row;
}
