import {
  MENU_SCORE_ACCENTS_BASE64,
  MENU_SCORE_BANDS_BASE64,
  MENU_SCORE_BARS_BASE64,
  MENU_SCORE_RHYTHM_INFO,
} from './menuScoreRhythmData';

/**
 * Random-access musical time for the grove's dance (A32): the measured constant beat grid of The Sovereign's Oath, its
 * bars and eight-bar phrases, a six-band spectrum and its transient accents. Everything is read from the payloads
 * generated by tools/analyze-menu-rhythm.py; nothing here listens to the audio or runs an FFT. Feed it the native
 * score element's currentTime, exactly like sampleMenuScore.
 */

const INFO = MENU_SCORE_RHYTHM_INFO;
const decode = (base64: string) => Uint8Array.from(atob(base64), (c) => c.charCodeAt(0));

export const MENU_BAND_COUNT = 6;
/** Seconds per beat (≈107 BPM), the first beat on the grid, and the grid's layout into bars and phrases. */
export const MENU_BEAT = INFO.beat.period;
export const MENU_FIRST_BEAT = INFO.beat.first;
export const MENU_BEATS_PER_BAR = INFO.beat.beatsPerBar;
export const MENU_BARS_PER_PHRASE = INFO.beat.barsPerPhrase;
const DOWNBEAT = INFO.beat.downbeatBeat;
const PHRASE_BAR = INFO.beat.phraseBar;
const BEATS_PER_PHRASE = MENU_BEATS_PER_BAR * MENU_BARS_PER_PHRASE;

const BANDS = decode(MENU_SCORE_BANDS_BASE64);
const BAND_FRAMES = INFO.bands.frames;
const BAND_RATE = INFO.bands.rate;
const BARS = decode(MENU_SCORE_BARS_BASE64);
const ACCENT_BYTES = decode(MENU_SCORE_ACCENTS_BASE64);
const ACCENT_COUNT = Math.floor(ACCENT_BYTES.length / 3);
const ACCENT_TIME = new Float64Array(ACCENT_COUNT);
const ACCENT_STRENGTH = new Float32Array(ACCENT_COUNT);
for (let i = 0; i < ACCENT_COUNT; i++) {
  ACCENT_TIME[i] = (ACCENT_BYTES[i * 3]! | (ACCENT_BYTES[i * 3 + 1]! << 8)) / 100;
  ACCENT_STRENGTH[i] = ACCENT_BYTES[i * 3 + 2]! / 255;
}
/** How long an accent's glow and push take to fall to 1/e. */
export const MENU_ACCENT_DECAY = 0.2;

export interface MenuRhythmSample {
  /** Beats since the grid's first beat; fractional, negative before it. */
  beat: number;
  /** 0..1 through the current beat. */
  beatPhase: number;
  /** Bars since the first downbeat; fractional. */
  bar: number;
  /** 0..1 through the current bar. */
  barPhase: number;
  /** Eight-bar phrases since the first measured phrase start; fractional, negative before it. */
  phrase: number;
  /** Measured band levels in [0, 1]: sub, bass, low-mid, mid, high-mid, presence. */
  bands: Float32Array;
  /** Recent accents, each decaying from its measured strength: 0 in quiet passages, around 1 on a strong hit. */
  accent: number;
  /** Loudness of the current bar relative to the score (0..1). */
  barLevel: number;
}

export function createMenuRhythmSample(): MenuRhythmSample {
  return { beat: 0, beatPhase: 0, bar: 0, barPhase: 0, phrase: 0, bands: new Float32Array(MENU_BAND_COUNT), accent: 0, barLevel: 0 };
}

const clampTime = (time: number) => (Number.isFinite(time) ? Math.max(0, Math.min(INFO.duration, time)) : 0);

/** Song time of a (fractional) beat number on the grid. */
export function menuBeatTime(beat: number): number {
  return MENU_FIRST_BEAT + beat * MENU_BEAT;
}

/** Song time at which an eight-bar phrase starts (phrase 0 is the first measured start). */
export function menuPhraseTime(phrase: number): number {
  return menuBeatTime(DOWNBEAT + (PHRASE_BAR + phrase * MENU_BARS_PER_PHRASE) * MENU_BEATS_PER_BAR);
}

/** Loudness of a bar (counted from the first downbeat), 0 outside the song. */
export function menuBarLevel(bar: number): number {
  const i = Math.floor(bar);
  return i >= 0 && i < BARS.length ? BARS[i]! / 255 : 0;
}

/** Index of the last accent at or before `time`, or -1. */
function lastAccent(time: number): number {
  let lo = 0;
  let hi = ACCENT_COUNT - 1;
  if (ACCENT_COUNT === 0 || ACCENT_TIME[0]! > time) return -1;
  while (lo < hi) {
    const mid = (lo + hi + 1) >> 1;
    if (ACCENT_TIME[mid]! <= time) lo = mid;
    else hi = mid - 1;
  }
  return lo;
}

/** Calls `fn` for every measured accent in (from, to], in order. Used to deliver impulses on the simulation's steps. */
export function forEachMenuAccent(from: number, to: number, fn: (time: number, strength: number) => void): void {
  if (!(to > from)) return;
  for (let i = lastAccent(from) + 1; i < ACCENT_COUNT && ACCENT_TIME[i]! <= to; i++) fn(ACCENT_TIME[i]!, ACCENT_STRENGTH[i]!);
}

export const MENU_ACCENT_COUNT = ACCENT_COUNT;

/** Source-time rhythm, not a calibrated latency model. Pass a target to sample without allocations. */
export function sampleMenuRhythm(time: number, target?: MenuRhythmSample): MenuRhythmSample {
  const out = target ?? createMenuRhythmSample();
  const t = clampTime(time);
  const beat = (t - MENU_FIRST_BEAT) / MENU_BEAT;
  out.beat = beat;
  out.beatPhase = beat - Math.floor(beat);
  const bar = (beat - DOWNBEAT) / MENU_BEATS_PER_BAR;
  out.bar = bar;
  out.barPhase = bar - Math.floor(bar);
  out.phrase = (beat - DOWNBEAT - PHRASE_BAR * MENU_BEATS_PER_BAR) / BEATS_PER_PHRASE;
  out.barLevel = menuBarLevel(bar);
  const position = t * BAND_RATE;
  const frame = Math.min(BAND_FRAMES - 1, Math.floor(position));
  const next = Math.min(BAND_FRAMES - 1, frame + 1);
  const fraction = position - frame;
  for (let b = 0; b < MENU_BAND_COUNT; b++) {
    const a = BANDS[frame * MENU_BAND_COUNT + b]!;
    out.bands[b] = (a + (BANDS[next * MENU_BAND_COUNT + b]! - a) * fraction) / 255;
  }
  let accent = 0;
  for (let i = lastAccent(t); i >= 0; i--) {
    const age = t - ACCENT_TIME[i]!;
    if (age > MENU_ACCENT_DECAY * 5) break;
    accent += ACCENT_STRENGTH[i]! * Math.exp(-age / MENU_ACCENT_DECAY);
  }
  out.accent = accent;
  return out;
}
