// Generated by tools/analyze-menu-rhythm.py; do not hand-edit the payloads.
// Measured beat grid, accents and spectrum of the approved score for the grove's dance (A32), not invented timings.
// Source authority/provenance: docs/engineering/menu-score.md. No audio samples are embedded here.
export const MENU_SCORE_RHYTHM_INFO = {
  "sourceArchive": "assets/audio/source/the-sovereigns-oath-original.m4a",
  "sourceSha256": "6a2dc57c6e8c68bfa65ab6d1e5ff6cf782f670e28e5121f788c646034e1de8c1",
  "runtimeReference": "public/assets/audio/the-sovereigns-oath.ogg",
  "runtimeSha256": "46d8c5f6492490e8ed521459fde2c588af18f55dff11ab4fbd22e491259fbee8",
  "duration": 214.2,
  "beat": {
    "bpm": 106.9872,
    "period": 0.560815,
    "first": 0.218545,
    "beatsPerBar": 4,
    "downbeatBeat": 0,
    "barsPerPhrase": 8,
    "phraseBar": 7,
    "trackedBeats": 382,
    "trackedRmsResidualSeconds": 0.00844,
    "trackedMaxResidualSeconds": 0.0382,
    "gridAlignment": 2.1268,
    "randomGridAlignment": 0.3876,
    "downbeatScores": [
      4.7509,
      1.5552,
      2.4659,
      3.7891
    ],
    "downbeatMargin": 0.2024,
    "phraseScores": [
      0.2094,
      0.2665,
      0.125,
      0.1561,
      0.1399,
      0.1867,
      0.1289,
      0.5852
    ]
  },
  "bands": {
    "rate": 20,
    "frames": 4285,
    "names": [
      "sub",
      "bass",
      "lowMid",
      "mid",
      "highMid",
      "presence"
    ],
    "hz": [
      [
        40,
        90
      ],
      [
        90,
        200
      ],
      [
        200,
        500
      ],
      [
        500,
        1200
      ],
      [
        1200,
        2800
      ],
      [
        2800,
        5800
      ]
    ],
    "referenceAmplitudes": [
      0.1859029871,
      0.1420348119,
      0.1034491745,
      0.087952292,
      0.0754495818,
      0.0526993272
    ],
    "attackSeconds": 0.04,
    "releaseSeconds": 0.16
  },
  "accents": {
    "count": 550,
    "threshold": "running mean + 1.25 x running deviation + 0.25 (two-second window)",
    "minimumSpacingSeconds": 0.15,
    "strengthReference": "90th percentile of kept peaks"
  },
  "bars": 96,
  "payloadSha256": "89bf3b8ac9097d3ea2216a68c1771b6ee5b51436df6ffadf337dac03650478b2",
  "analysis": {
    "onset": {
      "sampleRate": 24000,
      "channels": 2,
      "windowSamples": 2048,
      "frameHz": 100,
      "bands": "40 log-spaced, 30 Hz-10 kHz",
      "flux": "positive log-power difference; one-second detrend",
      "tempo": "autocorrelation with a 110 BPM log-normal prior; Ellis 2007 dynamic beat tracking; least-squares constant grid refined on the envelope"
    },
    "spectrum": {
      "sampleRate": 12000,
      "channels": 2,
      "windowSamples": 2048,
      "window": "symmetric Hann",
      "timeAlignment": "window centered on source time; zero-padding at ends; not calibrated display/audio latency",
      "noiseFloorDbfs": -65,
      "referencePercentile": 95,
      "compression": "square root"
    },
    "quantization": "bands: unsigned 8-bit interleaved; accents: uint16 centiseconds little-endian + uint8 strength; bars: uint8 bar RMS relative to the 95th percentile",
    "numpyVersion": "2.2.6"
  },
  "credit": "The Sovereign's Oath \u2014 supplied by Ael for Tervain; source metadata discloses creation with Suno."
} as const;

/** Six bands per 20 Hz frame (sub, bass, low-mid, mid, high-mid, presence), unsigned 8-bit. */
export const MENU_SCORE_BANDS_BASE64 =
  'AAAZAAAAAABaHBwYAACEKSkdAACULzMeAACVUjYkM2ibc0dCadS2g1ZPovO3g1NGuu+xh008zuuri0cz0eaoi0Ary+Glij0mw+Chijoiv9meiDcd' +
  'wNedhDMYvs+cfzARusaaezAUtcOXeDEbs7+Pdy8ZsLiGeiwWr61+gSoQsqJ6hSkOs5mBgi0YrJKHfi0YoIqMeiwUn4GQdSoPnXmQcCgLmnGPbCwg' +
  'l2uPdjctk2aOeTcrjWuKeDYmi2yGdTQhh2yFcTEchGuGbS8WgmiJaCwQf2aKZCkMfGSKYSYJemOHXyMGd2ODXCEFcmKGWicRbWGQWSkSaGCQWCgO' +
  'Y2GOWSYKYWOLWSQHXWWIWCIFWmWFVR8EWmSCUx0DWGJ+UhsCVWB4URsCU15zUB8MT1xxUyobS1t/ZjEkRluEbTAkQ1qEbDAjPliKZy8jPlaQYC8j' +
  'PFWTWjEiOlWVVzIiNlSWVjMiNFSVVTMiM1OTUzMiMlSSUDQjMVSTTzgkLlOYTjklLVKeVTgmLVGlWzooLE6wXz4qLUvAYT8uLkjSZUIxLkXlcUQ1' +
  'LUP4gEk4LED9h0g4Kz75gUY3Kz3rd0MzKz3ddEAvLD7TcjwtLT7MbzoqLj7IbTkoLz3FbDcnMD3DaDUnMDzCZDQnMDvEXjQnMDrHWjUoMDvMWDYq' +
  'MDzPWzgrMD3RYDwtLz3UZUAwLz3Xa0MzLj/ZckY3L0HeeEo8LkHjglBALkHrjVVHLkHylVhLLUH0lFdJLUHxj1NGLEDpilNDKz3giFI/KjvZhVA7' +
  'KjjWgkw3KTbZgEc0KTTZfkMyKTPYfkAyKTHehT80Ki/qjD86Ki7xj0M/KyzvjEM/KyvshkI8Kyvof0E5Ky/leEE2KzLjdEE0KzLjcUMzLDPncUc0' +
  'LTLtd0o3LTDyf047LS/2i1JALS/2kFZDLS/xi1RBLS/phU08LS7hh0k3LS7chkUzLS3ZhUQvLS3Zg0EsLS3cfz8qLS3iez8oLS3oeEEnLS3wd0Uo' +
  'LSz5d0gqLSz6dEcpLCv0bkInLCrraz4lKynmazojKyniazkhKivgajgfKS7haDgfKTPkZjcfKT7mZTchNk7oaDomRmrpa0IsX5Lobkw2gq3memZf' +
  'pejknIeI3vjcmn185u/UlXBr5uXNkGRc4t3JiVpQ1dPFglRH2s29e1BB7sK2dUs85b60ckY24LazcUAx2a+2cjwt0a26kjwvy7K5rTwwxaq5sjkt' +
  'vqW4sDQptp63rTEmsZ21qi4kq5q1qC8nqZC5oi4lrYPBnCsjrHrFlSkgpHXGjSkflm7Ikkcvk23HlVg4jmrGklY1jGjIj1EwimbLi0srhGTMiUYn' +
  'gWDMhkAlf13Lgj4jelzKgDsid17MezchdV7RczMfdGDUejIfc2DUijYgcV/ShzUdbV7OgjMZaV3IezEUZVzEcy4RYlq/bSsNXle6aycJV1OzbSMH' +
  'VVGsbSAFVE+mbBwEU0+hjSocUk+eujksUFGauzcpUFaXtjQjUVmTsS8bUluOrSoUUlyJqSgUUVyDpSYUUVt6oSQTUFpwnyERT1lonR8OTlhgnTQe' +
  'TVZZrFIzTFRQrFQxTFFKqVErTE5GpEwjTUpDnkcdTUhDq0QiTURDukIkTUFAtD4hTT8+qTodTT49njUYTD4+mTMVTD1AqEEbTDw5p0MaSzsyokAW' +
  'SjksnjoQSTgnlzUMSDkjjTEJRzoehywGRjsZgScFRDsWfSUDQzsVeCICRUwoczIliJVVd1dNtr1ec1RJwrhba0o7wrZWZEEvwLFRYDolxK5NXDQd' +
  'yqpKVi4WyahFUSsQyahCTCcMy6RCSCUJzKFDRzsuzNR5g4Z88POgmZaL+/Cgk4qA/u6aiIB0/eyUfHZp9+yNcW1e8uiIamZW++ODZmBN+d9+YVpG' +
  '9953XVQ/9NpxWU858M5ta1FI6sJ4oGZd5LqDs2NY2LWIr1tO1LCGplNE0qyDmk1Ay6uUkFNKxqakilRJwqKhgk9Bv5+be0k5u6CSdEQyt6mMe2BW' +
  's8ehqIh3sce7rIZzwsS/pHxnwry2nXBbvbOllWlTuaiYjWNLtaCOgV1EsJyEd1o+qZN6cVQ5oo50b080nYhzb007m4STmV9VlIC3rV9RkH63qVhG' +
  'jHyvolA8i3mkj0o1iHmXgUUuhHuLe0EpgnyCdTwkf319bTkieX17aEAydn14ZVBIcHy7oGFdanfrwWdlZG/5u2VkYGX2r2RiW2HvpGFfV1/pmV5d' +
  'Ul3ok1tbTFrwkVhaRlb5j1VZQFP9iVNYOlD/hFFYNU3/mVBZMUr/s1FcLkX/s1BbLED/rU9bKjv/p1FdKTf/o1NeKDP/oFRgJy//nFViJi3/nFdk' +
  'JSv/pFlkJCn/plpjJCj/pFliJCf/p1pfJCf3qFhbJSbvplRWJSbon1FTJSbgl1BOJCbbkE1LIybXikxJIiXVhUtIISTTgktGICPTgEtFHiHTgUlI' +
  'HB/UiE1OGhzaiExMGBnchktLFxbbhUpKFRLbhkpJJivZiUtIOFHXjExISVTWkFFKYVPZllNNbWXemlZSfnbmonJ3uL3xu6q26+zotqeu+erhqJub' +
  '/eTWm4+J/eDJkIR5+t+9iHps+uOzgHBg8+qqe2hW9uWhdmBN796cb1lF4tuYZ1RB29OVmmlb1M2f1nNe0sWk0WxW0bufwmNNz7KWtllFzqiSp1ZE' +
  'xqCumGlZwZvJi2lVvZfGfmNMt5a5d1tDsZOucVU9s5und3Vjv7SlrZx5xLyxuZhxyr2rqotkyLyhmH9aw7iXi3VSurWRgGxMsLKLeGVGq66EcGBB' +
  'qKh7Zlo8q6VxX1Q2pqNvaVM8nKCemGRMlJvIoGFHkJXFnlg/j5G3lVE3jo2nikswi4uXgUYrioiKdkAnh4V/bTsjg4J1ZTgff4FtXzUbfIRmdToz' +
  'd4heuVdWboZZ015UZoRZ0FtNY4NYxVRGYYJVuk0+YYJnrkk9YIGBn0k/XYCFkUc7W4GFhkMzWIGCez0sVYB+dzstUX52slhPTHts2GJTSXdi119N' +
  'RXNa0lhGQ29UylI/QGxPwVhLPmlLv29hPGZGu3VkO2JCsHloOV8+qX1rOFs6r31qNlg4xI51NFU13Zd7MlIz3o9yMVEx2YRlL08wz3hZLk8ww3FT' +
  'LE8vxnxfKk4uy35cKU4txntVJ00rvnZNJEsqtW9GIkk/tG9SHUU/yX5gGUE1yHxcFT4tw3ZUETwmvnBMDzogumpGEDoezXlUFTkb2oNYGDwX1YBS' +
  'J0EUznxKPU8TxHZFYYFzu5aNytu4tra68PW3qKmo++6wmZmU/uOljo2C/92eiIJz/9yWgXdn/eyPfG9d+vKIeWZT/uZ/cl5K9OF2bFlD69xxa1dF' +
  '4tKFs3Ng3NCi33Jf18mi02lW1sGbwmBO1LiUs1dI0Labomlh0d++mH9z0tnJj3pqzdLCgXFdycy0emhSw8Omc2JPyeCiiIt63/aks56A4e2rsZZ1' +
  '2+Win4xn19qXkYBez9CMhndWxsqCf3FQvch6eGpJucF0cWRDsbxvaV49r7RrYVo6qs+HcHRjuPG4k4Zww+fToXxlvtrOnW9YutDAlWNMssqwiVpD' +
  'q76gf1Q8p7GSdk41qaiFb0kxoaF8aUw2mZl4ZltLlL2ngH9ww+zkn4p+2uP3noN50s/zlnlwwsLniG9msLXcfmZeo6bSdl9Ym5fOcFhTkYnPblNP' +
  'h3zabFBNf3Hna01MdWfzbExNbV78eUtQZFb+fEpQW07/fEhRU0j/gUZSTEL/h0hURTz/jUlZPzf/k05dOjT/mlRdNjP/o1dfMzL/qFpgMTL/pVlf' +
  'LjP/m1dcLDL3klVYKjDwiVBTKS3qgk5PJynnfE1NJSTme0xMJB/rf05LIhvxhVNLIBj4jVhNHRX9k1xQGhP+lFxRFhH+j1tSEhD/i1dQDQ/9iFNN' +
  'DA36hE5KDAz3f0tHEhH3e0pGJDL6d0pFM0H+dkpFPEP/eE1HQkn/fU5KS1H/fldWc6T/j5Wf1+X7maiw9Ovwj5ue/OXpho+L/tzjf4J8+dneenlv' +
  '/dfacnJk9eTYbGpc8+DVaGJU8NnTZVtO49XSZFVI2NDReVdQ0snUwm9gz8TU12xczb3UyWRUybbVtVxNyK/To1hJxMXVl3Zk0OTgk4JpzdzfjHph' +
  'x9HbgW9Xv8rWe2VPu8HTd2ZayOvPoZeA2PnKwKF+2e7Gt5Zz1ue8pIxn0dyxloNdyNKni3lWv86cgXJPuMmSempIssGLcWRCrbuEaWA8qrR9ZV5B' +
  'qOSah4JlwO7LoYVlv9/ZnXlaudTQm21Pt8q/k2NGsMGsiFs/p7abflQ4pa+NdE4yo6mAbEgtnaJ0ZUQplp9sZEU5luOPpnt0zfeX1IN70eqS23xw' +
  'zduK03JjwNGDyGhYtMZ8vV9PrL+FsFtNpraJolhInqyIllNBlqOFiE04kJt/e0cyiJR4k2pSfo9xwIdmc4tqy4JfZ4dkx3pUYYVgv3FKXINctmpG' +
  'VYBXyYNiTXtS1I5iRnVMz4tcQXBGx4VUPGtBvn1NN2Y9vXhOMmE76n5mLlw383xkLFg07XVdKlYx5G1VKFQv2WRNJlIu1G1UJE8t2H1aIUws1HtV' +
  'HkkrzHZNHEcpw29FGkQxumhCGEBBunJVFTw5u3NUEzcwuG9PEDQpsmpIDzEjrWNBDi4fqFw6DCsbo1UzCykXoFEwCSUVm2BHCCITmYprI0dGoLaP' +
  'j5u6rNWz2Lvrvte33r/5utO13br0scyx2Lbmp8WrybLWnr2ju63DlbGZrqmtjaaOoKWihJyDkJ+ffZF5gpebeItzcpLMnYp2ZJDw2oZ5Woz73311' +
  'U4j+1XhvToTxxnNnS4Let2xgVabQq2hebanHn2ZYbqLBmGFRbJq/klxNZpO9i2lYYJrHs52Aasbv6cGclMH6+cSdl7b28sCbkq/q6buYjajf27OR' +
  'h6PTxaeJgp7JtJuAfJrBpZJ2eJa3l4hsc5Kqj35kbpGfinlgarSdjHdhZrCbi29aY6OWh2hSX5mOhWJMXJCIgF1HWIqFeVlCVomEdVU+VImBcVA5' +
  'Uoh4bkw2UYZuak42T4VtaGZVfbnNmIyAqdrxs46As9X7sYp9r837q4d6qsP7poZ4pLj6pId3nLD6qot6kqj+vZCBiaH/156IgJr/7aiNeJT/66eM' +
  'cI/636KKaYrs1piFY4XczI1/XYHOxoR6V33GxX53UXrD0Xp1XJzD6Xh2b57H+XV3cJbO/XR4bYzT/nV4Z4Ta/XN1Ypjy7XNxbcD73HJtgLv+y21l' +
  'gLP2umldfqnorGRWfKDXo15QepnNnFhLeJPFlVNFdY2+j01Ac4m0ikg8cYeqh0U3boukh0xKa6ejjVNWZ6OgiE5KY52agUdAX5aVe0I3XJCQcz4x' +
  'WYyMazsuV4iJZjgqVYKEZDQlVHmAXjIgUnF8Wi8cUoF/cWBintuyqpKb4/Wyq4yR9/qopn9+8vubnnJs7/OMlWZc++iDi15T9t+Cf1tP8dV/dlZJ' +
  '7M17b1FB58d2a0o52cFxbkc4x7xssWhetbZm0nBkpapfzmtdnqBZxmNSmZxTvFlIlZhur1pTmaueoXNooqigkXFioaCcg2lXnZuXeGBKlpqQcVpF' +
  'kreNn4hzudqKuJl9v9eCtJBxu9B6roNjsMdyqnZVp7xspmtJpK5nn2JBn6NimFo6mptckFMzlZZWh0wsj5FSgEYnhZRdo2dSfadq2IRnep9l1n9d' +
  'dJReznZQbIpXw2xDaIFSuWI4Y3lQrlkxYnRSolAqX25RlkkkXWlQjEIdWWROgj0YWIZemGlhjNt52ZOOu+9z4IuFyexr2Xx1yuViz21mxtxaxF9X' +
  'w9FhullRvcZzsVZOt7pzqFFHsq5xn0s/qqRvl0Q2oZxslE5Cl5dowoBsjJNj04Nrg41ez3pieYhZxm9XboJWvWVKaJFXunJWhbpex4tlmLVcw4Ze' +
  'l6tZvXxSkqJWtnFHjJtTsGpLishh1YF/rt1f6IF9uNFZ4nhxs8BT2Wtjp65Oz2BVm55KxV1OkJFIxHNRhYdGwXJMfH9Fu2xEdHlDtGU7a3RCrV42' +
  'XX9hw3dZV5Zs5ohhUY5k4YJVSoNa2HdIQXhRzW09PG9Iw2U1N2lCvmQ3NGU8u2I1MWE4tFwuLFw0rFcuJVYyonhbPYmPqKqaktXfy7ivw9zwybGp' +
  'wdztw6uhvtvkuKOYz9fUqpiMz9C9nYyAyculj4J0v8WVgnpqt7+IenRir7d7cnBbqK6KdG5bnaPdwm1qkZn16GdqhpH84GJlfIz1zl5gcojmulta' +
  'a5XRrVtacrG3pFpYd66omVZRdKekjlJLcKKkhVFIa5+mgGpjfcrNxpuNq9Xl5qaSq8zg3aOPo8La06CMlbbUzZyJhKrMwpeFeaDDt5OBbpm6ro58' +
  'ZZKyp4d4XoyqoYF0W4ekm39yWIrQmIJ9VpLyln97Uon7k3t3Tn/+kHhzS3X/jXdwSWz/i3VvR2b/i3NuRmL/jnJuRV//lXNwRFz/mHpyQlr/lH91' +
  'XKT3n5qereXxv5yl1PDru5CY4OzjrISK6eHXnnx95tbJk3Ry5M68iW5q2sexfmhi1cKqc2Ba1b6jbVlTzLmcaVNMvLOXh1xUs62Rw3Zsq6eIyHNo' +
  'pZ99wGpeoZlxtGFTnJFrqFhLlLCHoWljnsmYnHFnqb6Tlmpgra+KkGBUpqaBiVdJn6R6h2pkpN95rpqPyvNzrJaIze9ro4p3yehkmX1mw95ejnFY' +
  'vdhagmdMt9BVd2FDt8dOblo7s71JZlM0rrdFX00vrbJEXFhTpd1pcpKRpPVtcpCLsPtobH9zz/ljZ29f3fheYmNP0/1bXlpEzPdbWFM91PRbU1A5' +
  '1/VdUE851vFiUFhI4+1qX3Zz4Pqis7W99v286cPK/P+5+b3A/vu58bKz//e32qWn/PO2x52j++y20Le48ue16by76OG047O35Nm097O02tK8+7Ct' +
  '0sy+9K+xysPI/MfMv7jI/sHCtavE97OvrJ/A66eipJa14qCbob2y4NTHtNq69uvuwNW58uDiw9C05MvLvsuq07e3t8igx7a2zu+f2OXW8eee2eXM' +
  '7tqo09W54c+hx8Kn0ceWvbSavryttLKZq7DorMKklaj4prqXhKPkoa+HdqDLmKN9bJ62lqCNY67B4dTJX62/9tLCU6C8+sKtSZW76K6XP4220pyG' +
  'OIm2wpeJNJDquKanMY/5r6CdL47ppZOLLYzXnIV8K4rJmIKBfsrL4LrI2unK9sDH9ObF9bS29OW/7qOh++S03pWQ9uSoy5CJ8+Gk0bCh6tuj76+i' +
  '4dSo66ad28y5+ayg1MTE96aZzL3C9bKjwbrI/Na8srjD/suzpLW+8rahm6+74qORlaqy15yNktey09bPrt+70+/uwda50uHaw86xysi/wcakvLOr' +
  'vMiet7u42u+g0+rZ9eKe2ObR7tWk09K838mexr6ozMCVuK2ZtraXtLOanbC/xcChgqvEwrOYcqe6vKKLZqOruJV+W5+fup6gWKy069TUV6mz+dDI' +
  'S5y097yvQ4+z6KeYOoSr1ZiHSo2jz7uaaaaf8evEcKOZ++W7fa+V8M+ojsmO3b+Zwt6Lzruj1fOw8eHY8/W4+9vS/Py2+cjA/fux8LWu/vmr36Sd' +
  '/vamz52W+vGk3rSu8uql7LOs6uSl57Kl4tyy+LGl1te98qmezNC98LSyw8fL+8rAt7/I+MC1rbPD7LCipaK646KUopys3pyUoteu5c/cteK2997o' +
  'wN217s/Tv9Ww2r68vc6mxK6ruNqhwMPD5vSg0+ba+OSg09/P7tajz8y54cqdw7inzsGWuKqYu7bOsbGbpa3xsrObjafxqqqOeqPcnaKAa6HElZZ3' +
  'Xp+1tqugWqvB6trGVqS7+dG4SZi59byiP4y25aiONYKw0Jl/L4HLwaSUK4fwt7asJ4T7raqgI4LloZmMIIDRmIp9LYvFp5SfpN7P5sHX5ebJ+L3N' +
  '9+nB8K649+m45p2j+eeu1I+T9uWoypiO8OGw7cik5d227Maj39e84saf2c7L99Gl0sbF7MqhysG/3/DPwL672/vqs7i70u3eqLC1xNnLoampusi7' +
  'ma6fs8K3mOii1ubasemh5+rYveae2NrDvOGVx8WsutyLtrWgt+iO08S96viT8tPK+eWc7szD69ib4bq13c2X0aqkxsSUxKedr8KX2ubRmsGX9PjQ' +
  'i72Z7Om+f7yR29SsdbuFxMOcbciI2sm2j+aa9OTHp+Wa/Ny5rOWb9sqnzu2X5rWU4OiM0qWE3OR+w5l23OByuI5s2OJrsoVk0+Noqn9f1NxpoX5k' +
  '1OiXqaSm5+bhycLQ+OD2vbfC/eD9ramx/t7+npyh/9n1j5CT/9Dvg4iI+8zueoKA9sXudnp567/vcnNz47bucG1v2q3ugGtvx6zwsXOGuKn5u3CD' +
  'p5z9t2x+mY7/tWp6joP/tWl5hpz/v3iMntv91IOWtdf74H2Rt8z+6XqPtMD/8n2Qr7X/74WTr9f/5J2z6O751per9tnzyI6a6MbovISL2LPbtHp/' +
  'v6PSq3J1p5nPomxtkpHLmmVkgYvGkl5cdYW/jVlWa3+0iFdVYYnFoZSkXZzutaayVJL6sZygSIj+rI+SP3//qIaIOHn/pX+BMYP/pHt9K4j/qHt6' +
  'JoX/sH56I4D/uIB/IXr/t4SCSJ//tqCrxeT+vau77+P5tpmm8eL1qYiU897vnHuF7NrokXB55NHfhmlv3cbbfWJm1rzWdltd0LPOcVRWy6vEbE5P' +
  'xaW3c1RmwKStoGaGsp6ln154n5Sdl1RlkIyWjExXgoWPgkdPd7iYh3CAmuulmXaHt+OelGdwvtaYj1hbvceTiE1LurmPgl5vwOeWmI+s7e2PlIWf' +
  '8taEh26A4sF9eVxm06t5a05RuZx2YkdKn5Z6YUJFhpF2Xjo4coxvWDIrZIdoVCwfWIJgWUdMT42Xl4+jSZm2pI+iQ4ysl3eGO36chWJpM3KOdVJT' +
  'LGuCaUhIKHqBY0VFJXx9XT05H3lzVzQsHHRpUDkvGW5hT2RZVKaxlaawzt/psa2/8dn5qJ6s9Nn9mo6a+NX4ioGK8dDxf3d+68jvd2525b7xcmZu' +
  '37XxbmBp2KvvbF1l0aPtblpjyp3rjmN1vqTrw2+Jp6D0xWqCj5T5wWh8fYn6v2d6cID8wGl6a7f7z36RluX33n2SsN325nmPsdH57nmPrcP984CT' +
  'qbn87Y+gv+v44qi07eby1p6m69HsyJSX3MDgvYiJyrLRtnx9r6jHrXF0kqTDpmpseaC+n2JiZZq4mFtbVpKwklVVSIynjWNwQ5bYpp+3SJn0qZ6w' +
  'QY78ppSeN4T+o4qRMHz/oYOHKnf/n32BJoT/ont9IoP/qn17Hn//soB7Gnn/uIJ/GHT/tYWGbLj/vaq51ev8wKa18+b4t5Wi8eT2qoaR8N/xn3qD' +
  '6djpknJ45MzljXR13cHhiXFt2LjahGpl1LDPfGJdz6nDdlxXyqa4qHl5w6Sv5pORsZ2m6oyInpSe4YF6jI2X1XZtfYaQyXFrecKN3Zymo+OJ8KOn' +
  'udx+65qWutRz4Y+DuMtr1YR1tcdrzJWR0u992byw8uRz17Sg6tBq1aiN2L1k0Zp8xK9gy41tqKVj3IlyiJ5t9Id4bpNs8IFwWoho6XllSn9k4XFa' +
  'PXtk2YB+PbaJ9LO6ScKD9a2uRbdz7KCWQa9o4JOAP6tg04ZvPqdazYduO6VV26J+PKFQ2p15UZ9M1JRxeLFKyo9trr5kv6CNyuyt08bM8PrU2cHI' +
  '+/Lc0La8/urXwayu/uTOr6Sg/9y+oZuT/9msl5OI+tabkIt789iOi4Nt79aGhnpi5tKBf3Nc3sfDwXWCzrXu7XKQt6H68muJo5Lw4WaAlYjlzWB1' +
  'iofZwGJzidPTvX2RrfHMuHeHveq+smpywOKuqV5hvNegn1tatc+us5qfw97b6ba94M7h77O217nc5rCwyabU3a2ot5bI0Kaemo65wZyTfYius5CF' +
  'Z4GhqIV3WHmYnntsTHGOlnNiQnCPk4yNPaC2qa68N56yn56pMYunk42MLHuXiX91Jm6FgXRkIXJ/em1cHoqEd2dUGoaBcl1JFYB8bFU/E3t0ZlM/' +
  'IHlzd4J8hszCu7S93OHqxqy359n0waKs5NT1vpqk3s73vZWd08f8v4+Zyr/+yY2Wwbj/2I+ZurH/6Zegs6r/+Z6sraT//aSspqP59aSrl6Lt75yk' +
  'fZrh6ZOZZpLY5IyRV4rT4YeMTYrS34eQa8/c45Skmt/i5JCbq9jk7oqUq8/j+YKQqsbi+H2Mqc3h7o+sye7g4o6r69ni1IWW7cnewneD6sDWrWtz' +
  '5L3Mm2Rn3MPEjmZk08i+hGFczce3e1tSyMSvc1ZJw76nb1BCvrihhYWSr8uhpqi6nNeZnpajjdaNkoKFh9OAhXJtgc92eWhdfsxycGdhmtBwa2Ve' +
  'ouZsZWBSpPFoYF1Ls+5mYGJMre53fJKXwPelu8XZ7e2kzr3N+uKo27O7/uCr06Wn/9qpwpqW9t2lvqGX596h3M6539ij2Miy2tGg1MWt0Mmf5dK2' +
  'zMKZ38iuxbuP8NrHsLCN+/PRl6eO8+XBgKCM6dCvcJmG4L2haJWB3L2qbruZ3uzWlr6g3PfUsrui1uLEurqdwsm0vreUsLamu8yTrsrM2tyOtu7V' +
  '7cOKsejF4qyJrNmvzpyHqMaeso+EoryTjYaOts2jbn6lttChV3aqqsORRXGcn7ODNmyKl6V5LXKFt7e3LX2c6tvZK2+p+dXJJWGn7MKsIFie1LGW' +
  'G1GSwaSHF1Kct7WjFVjJucqsE1fIr7ubEla8oqaJDlWvl5R5JHqnnqmoksmr2d3a3sWp5NvR5cCw6cq94sG44Lap3MG30KWY1cG1wbiezb3Rvd+2' +
  'x7jRtdasw7TQtNGtvq7vvM64uarmtMWwsqTYxerWn5rO6fnhhI7C5OzTa4S1ztXCV32lvMOwTI2htNC7cMGyuPLdn76xvfrSt7qquuS5vbWkrM6k' +
  'vrGbnsCYusqavtfD3tCa2ejL6reY2tm/3aSW1MSuypaUxLSgro2RuLagkJ2RwurOepqUwfnMapOTxuq4X4mPvNWiUIGHsMGTRX+Ky9LNQpqq8Orl' +
  'QZi0+93SQaiw78m4TK2k17iiU6mVxqmRWqSHuJ6CXp99rZR2W5p0n4lrWZlqloBhX5JekH1mYpuTnrG3tNHRxMXS6sniwbzE78LetrO18sHTqaim' +
  '7L/JmJyX4sLBjZKL2cK5hYh/1MOqe39y0MCXcXdnyryLZ3BfxreNjXNuu6/P3n+MpKLo9nmHiZfm6G58cozbz2ZwX4XJtmFmV6vBsI2Qg+bArpaX' +
  'r+O6oIOAv96yknFrwNmpiGRcv9Kfg3x4u9i+2Kyu39PQ9Kyu5bbS5amp2qLM1aaiyJS9x6CXq4qqt5qNh4SgqJOCZ32Xm4p3T3eOkYFtPXCFinll' +
  'MGp8hHZkL5KMmaisOqCQo6aqNJGLmpKRLIaCkIJ8I3x2hndqIXZsfnFjO6VsenRnUsBrdXFjY8lmb29iZd9ea3Rnb+dbanprguh/g7O51fWSjr7E' +
  '8+uKgqmo9eqBeZWN7vJ6cIV47et0aHdn5upuYWxZ5OVqWmNO3uBjVFtE29NdTlQ81clXSE410sFSREgvybtOQEMqvrdKPT4ltrNHOTogsalDNjUb' +
  'rJ8/NDIWpZk8MS8Rm5U5LSwMlI82KikJi4ozKCcHhIMvJSQFf3otIyEEfHQqIB8Dcm8nHh0CaWokHBsBYmMhGRkBW10eHhsTUVc+gmRqR09Ty5CR' +
  'O0da4J6YMEBo6KSjKDty8rKwITZw8LWxGjGB+8vJFi2E/tbFEyiB/My5ESR9+LusDyB68KyfCx9/5qqoCiCa+M7PChyf/cvGCiCb/sGzETWU/7qi' +
  'JUqO/bWdZpiZ+Njd0syg9ODh8sWo7tLR+sSw6cPD/MKu27e49MSpyq+v5sCn48/B27qy6eLE1ret4Nm8zbaq8uTFxLOo7t3Bv7mi5NvPytWc5vPl' +
  '6cSV3+fX4a+R1dbHz5+P0ci6tJOLyL+wmqmbzO3dmcOo2frjs72v1+7Wu7quw9fGvbaossO2vLWiqcG7wdqdu+3g6s6VuvrW5rGWtOzA1pyUrdut' +
  'v42Pos6anoObnsuZen3BqtetXnbHpcyhSnC3m7yPOmqhlK2DMmuUlaqZerie4NfUz7uc9tPN3Zub7sW10YGX2rOfvW+OxKOOoGWPtaCNfWPEtbqs' +
  'YV7ZsramS1nMpqWTOVa7npeDLVWrlZGCaqmowtfPzcyl3fPX7L6k6+XL6Luv58y34ry017il2r+xya2f0L205NHCyLm45NbAxLWu3My4v7Gp79zD' +
  'u6yl6da6true49XT0dOa4eTd672U2trN4aWK1cm7zpSG0rqosoqEyrOjnLaT0Onjn8ai3fn2tMCt2eriu7yswtPMvbimsb62vLygqcO/yd6bve7b' +
  '7cyUuffP5rCVsuW71ZuRqtOpvIyKn8WcmoeLzdy+eoSl6/XVYXmj5+XGTHGZ2s6vO2qOxLydNXaIuri2jsia6dvl3cSZ+dfW4bGX78e61KiR27mi' +
  'wKGIyK2SpqN/wd20mMh/yvXSkMiD0vzIj9eFzeqzk+WCu9ihk+x9rNCno/Kcv+nm5eyjzOfe99yp2NjK/dS01ca1/NCxzLal89Kqxa+i586w4NvC' +
  '3cuy3di81cqp2dO4ysen8uPHwcSj69bAutKd5tzR2NmW5OfR6MGR3NjG3ayP0si2yJyNy7mpq5OLxbanmrub2+bjo8So3vTktr+v1+TQvLutwNG9' +
  'vbemr76rusKhqsvM0eCau/Dg78mVtfLQ5q6Wr+K605qTqdCnuIyOn8SZlYShoNygcn7Dp+SiWHfBn9OWRXGvmL+JNmuakq1/NISUqrewlcef59fY' +
  '3byc99DI25qb7MGwzYCV1LGdt26NvqSNmGagsq2YdmLUtMaqXF3TrbygR1rDoqmONle0m5l/L2ipmKKei8Coy97e3sij1d7Z6sGr3c/J58Gz1b62' +
  '4cK0xrGk2cKyvb2k0cC6yeS+yrzHw9mzxLrEwNexvrXW2+HBurDN2ta5tcvHzebf2s2+y+vd4rCyzd3M15inwcq4w4act7uppoSXsLysmb+cwuzd' +
  'qMSdzPbaucGay+TDvMCUvdKsvb6MrsWdus6JwM/K2N2G7N/Z7siK5trO5r6S2Mm627GOzrqoyaSBwq6XtZ94s6OKm51xrJd9h55rpYtxeptlm4Jo' +
  'cZRfkHtiaqd+kLK6nOajoMzXvficl7m6zP2RiKOdzfuFfpKFxPR5eINxvvBxc3ZhtfVqamtUufBmYmJKtO1hW1pDtOVaVmVXr9h1hLCpu+G6xdXX' +
  '7NHkzcnM7sH3xb7C7bz6ubW36cDwqK2t3s3enKSk1dDNl5qbzM69k5KTxcuvj4uMv8Wmh4OGu76ihoiTuM3K3K2/38jj9aC04q3x7oyh1Zjw3H2S' +
  'wIjkyXKFopnXwYWXmt7SvJWjrOHMqoWPuN7FmnZ+udu/kGtxuNa4i29wtdrE06Kr2tfU8qyw67nY6ayr4aHU2aukzpDIzaWcsYa2vqGSjIGssJiK' +
  'bHyko499VXacloZyRG+VjX5pN2iOh3hmU6mdjqS/wd2hkKrK7cSXhpev5aONfoaV1ImBeHiBunh0dW9xlnV0c21scnZ3bmVjV3NyaVtWQ3BqZVNM' +
  'Mm1hYFVNNoyQg5yhoc7PvbzF5MXow7G45bzzwKes4Lj2v5+i1bT7xZiayLL+0pSXvbD/4pOXtaz/8pabrqj/+56hqaH+/qSopJ79/a+0sdLz8brK' +
  '5crj56685K7X4aGr1ZjQ3pefvojN25CXoJ/M2paknNHO3Zelr8zO4pCctsXR74mVtbzT+ISRtLXT84STs9XX5qG84dPa15qw77rbxY2a6KzXtICG' +
  '4KbOonR21aLGlW9uyqfCjW1qw6u+iGZfvaq4hF5UuaexfldLtKKpeWBjr8GogqjD39eigqfE87yWfJSp5qSNdoGO0JWEcXJ4so99bXJyoNB+eJaH' +
  'neh7c4x7o+h1a35oq+RvZHFYqOFoX2hUotuLhaO31+mip7bS8+SeoKe49t2dl5if+tWbjYqJ89GVhoB7582QvY2N3caK3paM0r6E3JKExrt914l6' +
  'vbd20oJvt7eAyqGkw9uRycvQ7syBxb/B6bBywrCs2ZtnvaGXwIxfuJSIoqlywrGons+K3sCrrcuK27SbsMaG06aIsMGAyZl2r7x9wJSCs9iK1rCw' +
  '5s993amm5rBv25yV15ll14+FwYhe04R2on1e0Yp7fnlu46iKYnRt4qN+TW9o25dxPGpi1IplMmdgzoZ3bK6J5bfCy8SE77O85aV36qSk2Ytq5ZSN' +
  'xXhc4IZ7qWxU3IR2hWtZ7KmIZWlY66eATGVU5Zx0OWJP3JFoLV9M04llWKaA07CwwdaI4a+17Mh+3aCf6MN22JKK4L5w0oV51btuy3xty7eQwnxs' +
  'w7OduHlmva+ZrnJcuKuSpWlTtKeJnWJNr66JpJyiytOLwsLC7sF+v7Ox56R1uqKd1Y9vtJKMu4BrroqCoa6Ew7Kpn8uT3LqlrcSQ2a+Srr2K0qCA' +
  'rbaCypJxrLN+xJaPvdaH2bS17Mt42amo6K1r1pyW2Jdh0o6EwYhazYR0oH9fzJiIe3tu36eRXnRs3J+DR25m1pRzNmldz4llLmlfyYiGe7WH3rnH' +
  '1bx/47O75J1z36Oh14Vn3JOLw3Ja2YZ4p5JZ1It6lt1mzpuGk91ixI52jtlbuoBmjtdVsXVbjtJXqIZ9nsqvwcHQ48nX1MHO9cLhyrm+9L7evLCx' +
  '8rnQr6ei6bi7pZ+V3rauoJeK1LWlm4t9zLWblIFyxbOPjHhovbCJg3NkuLOvqqSr0szc2qm77Lfl05Wo5JrjxYSS1IbUsneBvH7AoHV5pbXFm5SX' +
  'rs7MlIyNv8bHiHt5w7vAgG9pxbG3eGxiw6+1ka6syujT2NPS8NjS687H77rQ6Mm+5ajL4Me10J29zsCqq5qxu7afhKGtrqyTZp+kop2ET5qamJF4' +
  'PZOQjIlvNZKLiKOhh+DAm9Xg3dztos/T67P6pcq/45T+qcWx0n//rcGmsnb/tb6hin3/u8Cean3/xM2cUnr/z9KcQnb/2dScNnX/2NKrddf/0NLX' +
  '1/T4xcXK9Nnyure48cntsK6r6r3jqKSg3bbYoamg0b7Pn7elybzHnLWkxLa/mbOhwq+0msGkwKaonsesu7mmtOPEpNeisde3f86XobqaYr6NkKKD' +
  'TKiEgo5xPp2HhqqXOuOzt+HJQvenr82zTv2SnLOVT/iAipt9WOtue4tuYOWboM63WPi0vODBVv2jr8ikV/6RnLCKWPmEipl1aOp+gpyCZfixuOPB' +
  'W/2suNayWf6ZpbqVV/6IkqJ9YPJ5g49qa+aMn8CqZfixyOXMYP2lvM2wX/6YqbSUZP6Nl6F9e/aAhZFshe13eIZefuNxb35UeuFuaXlMeN1rZXdI' +
  'cthrYndMZtd5fquel/Ony+fj4faz5eXt9uu+3tnl+eXB18/d99++zcfW7tq608vr5dPC8uj53svB++T32ca9/eX91MG1//H+0byq/+f3yt+o+Pf9' +
  '6Oqg9f3++Mmb5+/08q6c1eDl5Z2XyNjXyZWWxtvdtr217fX1x8606vzz1cyt3+nf1selzNjP1cCfu8rD0Nmjut/u5fSf0Pb6+NiUyfDn9L2Nvt3S' +
  '6qyCtMvC0qR+q8O7t8vJuOfsvuPduunpz+DQrtnR0dy9nci90NWlj7ivzNKeos7W0/Kj3vHz8t6i8+fj8bet7NXK6Jup4cO01Y2d0biotLHOzNzd' +
  's9rtzezly9newN3Sz9bHssi+z9CyprauzcupobvLzPC4yezw8Oy22+vt++C50ePb+9e0yNfK+Myovsu67cim0dXV48K38vHz2ry48ubt07m2++P6' +
  'zbWw/uT+yLKm+t3zw+Sk8/P86uSa7/L+9cGV5eXt7qqR19XZ4JqIzcbIwpaLzNrTtL2x8PXyyMe26PDq0sWx19vX0sCqxcjD0LijtL25y+Cmvefr' +
  '7Pafyvjw+tWSw+7c9LqIv9vF6al9r8q0zp12rcS5sraU6O7rsNme+O7tvOCa6tvYxdyS3cvFydWGyr60xdWOx9fm2fOZ6/H49Nme9Obk8bKu69PK' +
  '55ir28a00YijysGsr6+t6u3np9uz+frls+iw6vjTvOir2OnAwOaixdqxvuahveHSzPi44Pfy8PC15u/q++e03eTX/uCx09fK+durycy/7daq2tjr' +
  '5M+79O3528m69Obu1Ma4/PH6zb+w/vT7yLqn++j1xeil9vn87uGb8fX+9sOZ4+Lq7q2W2dPU35+N0sfJvqCY2d7ktcu18/X3y9Cz6+/s0s2q29nU' +
  '0sihx8rA0cCatcG6zOuhxu3r8POZ0Prr+9KOxOrW9LuFvtXC5655tcOxyauQq8K/t9rZwObtxujcut3j0OXMp83Lz+CzmL20ztibj7GnyOCbtd7k' +
  '4Pad5/Hz9tSm7eTf8a+04NLG5piu08CwzY6nyLuutb/cz+zovdjozermzdfXvtLSz9S8sb+8zs2hpLCryc2hss3n2/G23/D49eW03+vq/N+y0t3U' +
  '/d2qxs/A9tmduL+v7dSUr7Ci29GNqaiU08iMp7Wew++6yePGq/qvwNKxnv6csrqXlvSJpKSDkOZ7mZR0jNVtj4hmg8tih31af8NbfXlgetqets65' +
  'bfSswdK3Z/ybsLqaY/uKnaOBYu99jJBsct17i6GWb/Wpw9zOY/yivcu4YP6TqrGYXvmGlp1/Zu13hIxuauabqsm7Yvi3yt7OXv2ouMWtXv6WoayP' +
  'Y/WGjZd3ceV9hJaEcPiuvOHTZ/2tvtnHZP6frMCnY/+TmqqMbv2Ijpl3hvCAgI1nhOd4doJbe+Bzb3pSd91wanRMc9hsZHBJadVoYI9xZ+SZoN/W' +
  'yvfIw+Ln8OnXwNjb+uDWt9TT+NrQqdHJ8NbGm8u/6NW/l8K34NW9kLas2tG5iKig1syvg52X0seke5SQzsajjbrEz+vYzdHm8dn03LrS77z41KW6' +
  '5qftw5ak05vWsI6Ws7vPqJyss+fPoZimzObGl4eRz+C6jHt/z9ivgnRzzc+oiKGryvHC1NDh8OfJ8svV98bJ7sjH76/G58e83aC71sGwuZytwril' +
  'j6ista6bbaampaGMVKCbl5R/QpqSi4t0NpOMho6Re+CYnczg2e+NkcjZ9MaAg7O97aR3ep+g345tdo+JwIRtc4h/lJaUcoZ9b5+UbXluVJ+MaG5g' +
  'QZyCY2RUNJZ3YHpyX9esocbOzfPTxsTM8d/fzLq98NPlzrOz68nk0a2r3sLj3aqo07/g86qoyr3c/K2nw7nZ/q6ov7PY/6+tvKzX/7GtucLV+8/Y' +
  '1O3L7tHk89bE58DR77XC4rK+5JzB3qavzIy/3J+msbHG6K6wttDK7qmryMrH9J6iysPD/JOcybq+/ouXx73A96C+0ezI5rXZ8uTL1Km8+tHKxJ+h' +
  '88fBtpGL58WzqoN52cuto4F9z9Kyn315yNCvlnNpw8urjWtbv8WjhWRQvL+ahouXvOiWs9Lh7OGLtNHa9ruCrcDA7aF9oqun3I93lpuTvI+TqrKm' +
  'qNS528m6p+m2276pruiu0a+Ss+Glw5+BtNudt5mMtPWqx8nb6fynyMjT+e+kv7q7+OagsK2n896apKCT6tqTopuS4deQ1K6919KL36y3z8yE2aSk' +
  'yMh+z5qQxMR6w5KIv9iMvMnT3PGJvt3i9dV9vM7N77t3tbu04qlyrKqdyZ53qKOassGu383JvtS368vAzNCu4r2qy8qi1KyVysOXx5yFyMqTwrjB' +
  '2PCRy9jX9N2BxdK78sJ0usae57FrrriH0aRlpKt5qqN207eig6iB7bmpZaV85K+aT59z1KKHPZlqxJZ3N5pwvay1k+KJ19jq4Nl7183Y7LNv07q7' +
  '45dmzqig0oVdxZiKr4FrzbqQiJiE5t2Wap6B39eIVJx50Mx3QppvwL5pOJhstriZhOKPzNXh3POJy8rQ9eJ+xrez8dd1vqSZ6s9ttJWE3suHs6iS' +
  '1NOzzbqizc+yxrKcycisuq+cx76kr7CixbaXq7iwwdiWrtro6u6OqNHh+ct9nLfE8axwkZ6l45ZlhIuLx5GLnqipr9/Q2dbPr/bKy8W3uvS5tq+a' +
  'weiloZ2CwdeSj5F4vdiiq9fGqPSsv+DFkvyesMenhP6OnrCNe/mAjZt3fut7iqWSevm4wuXSbf2zvdfAaP+hqbyfZf2QlaSEaPSBhZJxbuuJpMm7' +
  'Z/moxObSZP2dtM6zZP+QobeWb/+IkaKAhPaAgpNuiut3d4dhg+Rybn5XfOFuaXdQed1sZXJKcdhpX3VTZNN+fbmvn/LAuOno4/HZxODg9+XcvtnX' +
  '993Xs9PO8dbLo8rD6NO/msO44dS8l7iu2dK6jqqi1M2zhJ+X0Mele5ePzMCaeJmcx93Hs8/j49zv18Ta7rz606vC56f1xZes2pnhs4qYvpvNpY2Y' +
  'r9zLoJuow+vClo2WzuW3j32Dztyuh3F1zdKlgoB6yd+5tsfL4vXN6tLR99XM8MfH8bnK68a+5abC4MSzy5yyyLmooaGvuq+gfKiurKORX6WknZeD' +
  'R5+ZkIt3NZaPhoRwRrmVj7nDtOuVkNHl6taGhL/P7K99fKiw45R1dpaWzoNtc4qCp4iLcoaAfpyYcH92X6CSa3VmSJ6IZmpYOJp8YGZUNqqGeaio' +
  'nue8pszY4+LTsMHJ9NLetre78MnfvLCx6MPeyK6r3MHc2rCp0cTZ6bGoysDX8rGoxLrU+7KtwLLS/rasvKzR/r67uuLO9trp69/F683e9LrB5brK' +
  '7J3A362524m/2qOsuY3A2qOqr8bO4aqtwsXN5KCjyb/K7JadybfH9I6YyK/F8YuXxejP5rPO7vjO1avC+tzNxp+n9szGtpOR7sa4qIV/4cWqoH55' +
  '1cutm32BzMquk3V0xsaqjG1lwcCihmRYvrmYgGJauceWqLvE1eeQy93p88qDyNTX7qV8vcO+4412sLKoyn9zpqygqrSb49fGod6p99O9o9yo8MWo' +
  'q9il4rSTrtGh0KWErNGhx7jIyPKs2drv7+ir19fg9uCqysvM8tqmvr636Nags7Co3NWe1MPK0dWd89jbx9KY7dDNwNCQ28i4u82Hyr2nuMuDvLu+' +
  'uOuGz+zs6eB72+zm7sJ11dvR5q9zx8m91KVwt7qts7CGzszDqtek8eXdvtWh7NrNxdGa18e4xcuPxbanxMSGu6+oweqJzubm6umA0/jm9sx2yezR' +
  '7rpwvNq8365qrcmqwKdqs8e5l6mL6e7rd6eL9+fjXKOE5djMSJ5808e2Oph1wLqrXceIw9/nwOiD3PHt7cd34eTW6alw3NG+3ZRo0b+sw4hkybul' +
  'mpaE4evheaSL5PnjXqOG1fPOSqB/xOa7O5x2s9eqRMKGtNzbr+2O1+rz6NuH1+Li7c2Ey9LO68SAv8a64r58r72r2b6Hq8Kp0r2Fqr2nz7aAo7mk' +
  'zap7m7WizJx1l7OjyZp/ptG8u9ugxObHnPKVu8+vhvGEqbWXeeh2mqCCbdlqjpZ8ZNWLsdzFWPOZt9rBUvqKqr+mUfd6naaMW+lukJJ4Wdhsj6aY' +
  'Ve6bu97PUfqXs827Uf6GorKeWPZ3lZyGWOdriIx1VtyJose4UfWludrIT/yXq8OrT/2Em6uRV/J1jph6WONthpZ/V+qetNvFUvmesdK7UP2NoLmf' +
  'Wf6Ak6WJYvZ2iJV4ZO5tf4lrceZmfH9hbOBjdndabNlhb3JUatFeZ29TYspcZJGCa9ilq9bbx/TR5N/o7+Dg4tnf7dfj29PX69Tby8zP497MvMTF' +
  '2uPFt7q+0+O/s6u00OG2qZyuzd6snpKqy9mjlIqmyNausLfPzevn6Mrl6tX49bfS5LT97aC92pz73Y+rxo/pyIagp8Lcx6G6pOvVxpuyu+bKuYue' +
  'yd+/sH+PzNe0qXaFy9GvqJ65yvLD5srm8OXI+MfY7cDG9MDL5Ki+6Lm+05qv0q+xsZelvaeniKWisJ6daKSap5KOUKCSn4aCPpuLl354NJaHkZOl' +
  'gt+ejtnl2+iTh9He88GFgbfC66V6e6Cn25NxdI+QvI14coWIkKCWd3+Ga6aTcnN3UaSLbWdqO6GDaF5fMJx7Z294ZNa1r63KyvPZ3q/I79rj46u9' +
  '68nn4Ka15r7o3qOu3Lnn3aWn0rfr5Kumy7Xu7K+lxrPu9LSkw6/u+7mkwavu/sGkvbvr99jU1+bh6Nng9M7X38nP7bPR2rnA4KDN16u0x5bK1qSv' +
  'qsLR2bTHqtjX3K2+v8/V36Swx8XT456myLvS4Zicxr3V1aq01OzWxbvD8+DXtbaq8MnYp7CS67zSnKOB47XFk5Z62sK9o8G70eG4or64zuKslamc' +
  'zd6jipaHzdacgYh1zc2UiaKyy+aXw+Tp8N+OzeHo8bqHxNDU6Z+Dvb/B2Yt/sLCwuKKSvdXYq9u44vPutuTA3unbyuPA29fC0+C9z8at09q5wcCt' +
  'zOfJ7ezo6ebS+uvq89zT8+Lg8NvR69XX7t/G4MrN4+q52cnM2ua39Ovu0d+x9eTnztan5NDVzc6g1MXGy8iaxr29xtaawezs4+2U0/r698+HyPHq' +
  '8bOAuNvX5aB8q8XHypd7qb/CrsCi5unuq8qu+Ojyv8Op7dffyr2i3cbJzreayre4y8GVxNnm2O2R3/T49NeE2fLl8bd6x+LM6aJxuM+605VrrMKv' +
  'q5GH5+Dmg5Sc+Pb0ZZGW8enhT46O4dXJP4yG0cK4OpSGxs/WltyY7vHz4dOR9e/o7LOM6d7Q5p2G28261ZB7x8Ksso+Bzu7UiqSR8frubKeM7PXc' +
  'VqaG2uTGRaWAw9O0OqR+uMu5heOh6/Dr3Oag+e/o9dyg69/Y+Nil3M3I9tKiz8G489CdvbWn7c2UsaiZ4ciIq56M08F9qZKBzL90o4d2xrxvnH9r' +
  'vrhokndjs7hgiXBbrrNag2lUralVfmJNoqVQeV1Gn5xMc1hBmJpKb1M7k5pHa041k5VDZUkwjI9AYEUthYk+YFFMebJ+mry8aumarczFZfeKn7Kl' +
  'YvV6j5mHbuptgYRwbNhmiJyKYtaM3ePUWuOK9e7fU+J7/OfdUNps/ufbTM5d/+XkSMRv/+rsROmO//n5QvOD/+/nQvJ0+dzSU+1m7c26VONb3MWs' +
  'Ut6E9e7bUOuI/PraXOd6/u/IZuRt/925ZuBk+tGpYdtx79HFovWf7d7u5PCp5NPl9+W02cPV9OG117jI7+CyzrG+5d+yy7PN3Nq36sba1tCw+c7V' +
  '0cim/czUzcKa/9TRy7uQ9tTOxtyW9evx7d+L9Ofq97977dfS7qdz4sa835lv0rmrv5h9yNK7rM6h4vLbs9Og4fbKw86a1+i1y8qTytKjzMWLvMCb' +
  'x9+KvODY6faDyfDT+dZzxeS28rlqwNad5KZluseNyZpstr+Snp2W3+DGeqOZ8d7HX6GT9djITpyK/NXQQZeA/tzXS66F/+HxtOiH/N/56tJ09M/i' +
  '6LBn67/F3ppg4LGryI5d06qfoZF74+fNf6OB9/jJZaN87/K0UKJ44+SeQKBy1tSNPK1+0M65oueU5NPf5N+N38TJ9cSJ2LWw8rWF0Kme662CxJ6R' +
  '4auD3ry616yO9dXK0ayL88vAzKqF/MvIyaZ+/srCxqR59sPBxNSE9+Tt7tJ59d/j8LRr7c7L555j4ry11pFe1K2itZhwz9fEp8iS6fTlssaR5frS' +
  'w8KM2eu6yr6GzNily7p/v8mgxuOGxOze7vB/zfjV+tF2ye659Lpvw9+g7KxpvM2O4qRmvcSf2J9/7NzO0J+H99PEy56E78GxyJ195bGex5t12qaU' +
  'w7eG2cbe4OOF6tPu9shx6MjX8Kdh47q845JW3KulyoZU1LKhrZ987+nWqMV+9vnOt9J26/K4w9Fp3eWixM5cz9WSw81/ztPQ1PGq8ePy8+Kw69rm' +
  '8te0383Q79Wy0r+86Nqsx7Ow3tmu6M/b09O8+PHnzs6y8OjXy8us++bayMWr/uXYxsCk8d7XxeKj9vb07tmc8+7t77iZ5trX5qOY28jF1JeUyLu1' +
  's6eU0dnep9Of8vT2stOc7O7mws6X29bNyMqQyb65ycWJtLa1xuqLxuro7+iD3Pnh9sZ50u3I7690wt2z4aBvssykwpl+yMu3lp6u7/DqdZ+v+ujj' +
  'XZ6m6NTNS5yg2MK5PJmZxbewY8Ke19/ox+Gc8+bw78KY7Nva6qSU4czD35GM1b6uxYeFyLysm5aW7+zkeZ6U+/njX52N8O7MS5yF3dm1O5l9ysmn' +
  'S72Lz9Lft+yh8d/x6tqj6dbh8syn2sfN8camz7e76cajvLCw3sisx+jX1ce33/nX0MWy2O/HzsKoydi3zb+gucKpy72brczSzeWdxvDy8daXzu3p' +
  '77mWxtjV56aVuMnC1JySqryzsa+RxOzap9CZ7vnjtM6Y6fjQxM2T1uW8ysuLv9OtysiDtsq5x+yT6u/r6uaU+evl7NSR8tjT5sqQ28rD2cSNyL+z' +
  'vL+EvbKmpLl4s6ickbRvq56PibFmo5ODfqxdnYx4dKpbm5iRauObx93eZfehwtXQYP2Vs76wZ/6IoaqXcvp8k5uEc/RyiZB3eOxtf4dtc+Rpe39l' +
  'dd5jdHlfddVfbnZbbs1eanx3duCinMDY1va+rMDl8+W+qrDV9N7CqaTH89zBp5i86+G9p5e44d3C5srW19TB+N3U0s257s3I0Miz3r28zsWpxrC1' +
  'y8ikxMnb2e2v4eb19Nms2dvl8byo08bN5qmmy7W70J6ivaqxrcG358rTqd7I+NnVvNrG8MvHydXF37e1zs/Axaipzcy7tbG80fC4rtrd8uivqNTQ' +
  '9MOjnca866uZl7ap2Z2Tj6uZtJihnNG8jKa/w/LUbKa4wOfGU6SpsNKxQKKbo8CgNp+Sm7uvf9ymxuPo2t+p5tvj8Lys5cnM6aKo3rm22pGe062k' +
  'u4yZzqypkaS378i/cam57cGzWaiy2rGiRaeqyKOUOaWfup6Tbd+xzNLf1fa51M7c8+G4yr7K9Ne3vq+38NK0saKp5s+xrp+l3My+6M/L0si89dDI' +
  'zsa05L64zMOt0q6py8CkwqWix8yiwdHh3u6i3er19dWa2Nvj8LeT0cbN5aOOxbi5zJiJua+wrb6p3s3kqte18Nfiu9Su79HXw8+s79HTxcmq7tHO' +
  'w8qk6dHe1fCm3ODx8+Shytbc9M+YvcTE8MKPsraw57mGpq2j3rOWr9jM1a6wwvTZzqqouOfHy6icrdGzyqaPo7+kyKWInb29xt6jvubs79qu1d7i' +
  '8bm008vK6aSwzrq02Jamx62ltpal18fJqLTP8+Tasb7U89fJxc7Q4sa2zdjKz7ekzNbBwbasx+vR2Nrl7+7s39ff+t732c7W9tX10MTM89Tpw7q/' +
  '7N3Xsa+v5tfHp6Sh2NC6o5yUx8mqnpeIt8OXl5J+rruKj413o6/MypaCkprw8JWMgon7+4qIeX3+636AbHf11XZ3ZXTew3BtYG/FsWxkXnC0omdc' +
  'XG+lmGNVWG+Xj19OUWmPiWdYSGGfoKCVPFTj5MvGMUP398jEJjjw78C+HjDe3bm0FyrExa2mESaorp+UDiOVnZKGCx+Hk4V5CBp6jH1tBhVvhHNl' +
  'BBJ6gHNtAxTZqZeUAhH0wqmeAhD8vKObARD+spuXARD/qZeTAQ7/opaPAQv/npWMAAv/nJiKAAr/np6MAAr/pKGNEEz/o6upfMz/o8Pa2ev5nrXL' +
  '9ND2mae488HwkJqp7rjihY+b5rTSgZ2g37bChK6s2rWvgaqn17OcgKml1LCKf6ij0qx/hLKuzeWVkdDf8feOiMLQ+9R6dqOn9LBtaImI55RjXXRw' +
  'y41qd56uot6Zps7fjPaSnrzCf/uBkKOfefRzhI+Ec+doeIN7ceqMlcTTzfmXmMXS8fKFi6qt6+t2gZSO4eJqdoJ1ytNmdIqUquebp8nYk/iZo7/F' +
  'hP2Ilqejefp6iJOIce9tfIN0aeiKjLzPufimodru6/aVk77H5vKEh6ak2+55fpWLyOZvdol5s99pcYBspdlncHliltJja3Rbjc9fZ3BVgshcY21T' +
  'ecF7hZqyqO210tfp5unB4NPk9ODN08TY8t3NzLXO7tzIw6zE5d7D1MPX3NnE8+fv1dK+8OHj0s625dnczsqz4djsysOq0NbswcOs0PP62MOq8Pz9' +
  '3q2j5/Dt1aCd293bxpyRy8vMq6iLxNPUnN2i6/Pzq+Cv5e72ud2t0drmvdmmx8jVwdWctrzJvdShyOTw0tyg7/f55sKV7PDh3q2I3+HJ0qF/z9K2' +
  'uZp7xcu0kpej7vDpc5iy+vv2XJyp7e3lS52a3d7UPJuIyNLEO5+WwerunMeq4vn62rad7/Tt1puR6uHVzIyD2c6/uIR1ycSxlYiO8O7ad5yh+/rc' +
  'X6ad+fHITK2U6t+0Pa2I0tClN62Hy9DLjtWp8PHw29Co++7s4s2q7Nzb4dOq3czI3tqlxcC519ql4NrhztO89vT2ys649O3qycyy6evmx8is5O7w' +
  'xsOj1ufvwMWv6fj73b+q+fX73ayj7+Xr1KSc4tPaxaGQ0MnHqLKLzN/gm+Ki7/b2rOGn5PH0ut2lzt7kwNmfwc3QxdSWsL/GwNebzO3v3deV8Pro' +
  '7MKL6vHR5buA2+C84Lt2yM+v2cBzwsy10b+U7vDqy7+d+u/ryMOU6ePVx8aI2NPGx8V8w8i7wsOXwOnrz8yf5fn557SS8PPo35WG6eDR0YZ218+7' +
  'uoFuxci1nbiU2u/qn9aT7PrhstuJ5e/Hu9t+1dyzwNpxv8ymvteDxNXVxeCm7vPz7dWm9e3q69Kq59vX59ap2sjG4t6jxL+52d6l693n0Ne7+fX4' +
  'zNO48u3oytC06O3mycyu4fjrx8Wn0fH5wsmw7fv94b+p+vv9362i7uzp1aWb4NrVw6OQzczHo7yPzuftmuej7Pj6r+So3vD0ud+my9/gv9qgvszO' +
  'wtOYr8HJvdqg2O3w4daY8/rp5bmN6vDP3KeB2+C5zJ14ys6sr5d90tPLiJWo8vLwapit+/XuVJqk7ubcQ5uW3NbJNpmIydDAV62lyPHtuMWk5/v6' +
  '3quX7PDm15SK5NrOy4h708u7s4N1ysq4jo6X8PDhcp+d+/vaXqqX9fHCTK6O5OCxPqyDzM2nRbSW1drmqteq8/X45Mym8e3o48ul5N3R4dSi1cy/' +
  '3eKbvcK30+SYtdfXuOCVsdrWl9iPq9jWfs6Iq9jWbceBqd7VYcSHr+jaV+ufvOfXUu+UsM67TOqCobadR+J2kqGGRdVtiJd/Q9eSwM6/QfSXwMu6' +
  'RPyJrrWeRPR8m5+GROdxiY1xTdVwk52dSfKWxc3TRfuOub29RPt+pqadRPJwlJGDSOVkhIR0S96Hr8C3Rfahws7AQ/yTsbikQ/mDn6CKR+52jo5z' +
  'Udxxio+MUO2exdDWTfqcv8fIVv6LrLCoVf15mZ6NXfRwiJB5ZupofIZrZeJjcX5hZdhfanlaY9RbZXVVZdFYY3NTYc9WYol/atidotDayOzRx9Dn' +
  '79rdwsfd7NPdsL/R6s7Wm7jG5M7Kj7C73tnCl6q22d26lJ+u1tytipSk1dmgg4uc1dSUe4WX0c6horrb0NPP4tHw6L7i4cHd4abh0qzH1ZfYvJuy' +
  'vpDCqJKmocy7p62+oPDBpKW0te2+mJKdvue3i4GLxN+uf3Z/xNeohqS4x+zGzczk793H3crZ673F08fL36a9w72/zJatsLSzqZKioa+sgaKfl6qi' +
  'Y6qXi5+RTamMgZGCO6Z9eYV1MqJ6dJ63fsqedeLq2siTbt7k6aqBZ8jM35VzY7Cvz4dmYZuVsIRyZ5STiKCUbZGVZ66SZYKDTrKJX3JwPLF+WWdi' +
  'Ma12WXuCZc2ppr3Sy+DLzLfL7cvUxqm86MDYwJ+x47rXvpen3Ljbw5Ki1rfj0pGf0bXk2Y6azrLj4IuVzK3h54uTyqff6pKYxazb48Xc1MrU2dTp' +
  '6bXN08bY4aHIzrXF0pXEy6i3uZHCzKKwoc7I27XDoe7H2qu5tujF2J+svt/D15Oiw9TB1Iuaws7Iy6TFz/DWvLDR8d3Vq6S37MrSm5id5cHIjImJ' +
  '37+2goKA17+nx8vH0MGf5evRzMWW1Nq6ysWOwcamycWDsbKXyMKBqLzCxdGayezu68aKzenl56F5yNPM24ttwL6wyIFita6bqY19t+jFn8SM3PjV' +
  'r9qE2/HBuOB70N6ovt9wwMqUwN1rtcGmvOGT6Orm596b9vDl7teb6eHR6Nya2s294+GVyL6t2uSPxMa10OCU7u/hzN2V6erWytqS1NPCytaLysCw' +
  'ytCDwrepxcyMv+rm3M2HyPn46rZ7v+zm4KVztNnQ0Jxsq8q9tZtrqca6ntSS5O/poemY7/DisuaV3tnLu+GRy8O1wdqLu7Onv9aLut7W1OaJ2PXb' +
  '8M941ezG57dty9ms2KdmvMaWwZ1gsbqTm5t15Ovcd6SF9/fbX6mC6OLES6h71M+vPKZywMOdN6WCttPil82dw/P34MCKwOrp3qR4u9TN1JJrtLuw' +
  'wodjq6yeoYh1y+TJfqCI8PfQY62G6+u6TrKA29ejPrJ5x8OSNbF3ub+8gdaZ5e3s19OV6Ozn5cuS19vS4siOyMu74MmIub2o2s+Drr261tCCsMvM' +
  '08yArsvN0cV7p8rL0Lx2oMvIz7JymM/LysKUk+7w68yOiunr8LN8gtDT5KRwfbW21ZpleJ+buJ5ynbqzluOTyNnOf/eKusSzbvV6pauWYe1tk5Z9' +
  'W99ihol1V9qEv8K7UPSPwsa6TvyBsbGfS/hznJuFS+1mi4hwUdtoi5aUTvGbw8/SSfuVu8K/SP6FqKqfRvh2lZWDSuprhYZwUN5/pryxTfaZwtfI' +
  'T/yOtcOuUP6Aoq2TUPtzjpx+WvVpgI9wWO1idYdlXONfbYFdX9xcaHxXX9hbZHlUXNdZX3xgWdN7hLS/nOfJxdzt49/mx9Tk7NbpuMzZ6tDjpMTO' +
  '6NDUlbvD4t3GkbS73eS9k6mz2uWxiZun1+Klf46c1t2ddoWT1daXeJarzdXBzsvn5M7g6cTf46/n3bDJ2prgx560yozNsJCirpq+p6GuoOLLsLG+' +
  'rO3JqZ2puujAnYuTweG2kHyDxteqgoGPwtq4psPf5eXK1M3c9MbI0cnQ6azCw8LD25y0sbe2wZSjnrCsmJ6dlq2ndqyXi6GYXK2NfpKIRquBdIV7' +
  'Nqd1bH96SbKUb8vZttyfber06sWKZNng5ah7XcDD2ZVtWKenw4llVpaWnYqJZJWcd52aYomQW6aWXHd6RaeOVGlpNKaETmFfM6yXf5+4n+fRvbrd' +
  '49zfva7N583isqW+5MXfqZux4MTaoZSo2cbUm6Kq1MjMlrCx0cXEk7K4z7+9j7e5zra6i7W3zK63iLy+yuC1iMLR8Nyhequ377qObZOY5KKBYoCA' +
  '0pF2WnVysaiPobmxjuafvcq9ePiOrbOiaPZ9mp2HXexviIpxVdxphIqGT+WTwM3QSfiRvMXDR/2AqayiRvdwlpaGSOlkhIVwTdlwnrCkR/SUxdTH' +
  'RfyLtcCvQ/57oKeRRPZujpN4TORkgYl1TeCOt8XJT/aev8bGTfyOrbOpS/x/m5+NUPNyiZF5XOdofYdqW99idYBga9Rdb3paa9JWaXdVaNJWYnVT' +
  'XtNVXnVfW9F7t7vQr+Wk6uvy6Nyx8Ozr5+G25tnf5Oyz2svT3vOuysLL1O+u6uPwzebA+fT7y9298u3uyti56PP6ytK03/H+yMqtz+r/w9Cz7/n/' +
  '48Wq+/j+4LOi7uvu1qqZ3tzew6aKzNTQo76M0+3xm+mk8Pr7seeo4vPuu+Snzd7ewt+hv83Ow9iZscXMv+Cb2u7w5duS9fro57uH6/DQ3ah82eC9' +
  'zZx1xdCxsJZ9yNvQipWn7/XxbJiu+/ruV52n7OzYRp6b2d/GOJuNx9LDXbKlxvLuvsii5Pv64ayV6vLm2ZSI4uDOzId508+4soFzyc+4jY6U7/Hr' +
  'cKKZ+/vgWq2T9e/GSK+K4+C0O62BzNOpR7WW2+TmrNqt9ff449Cr8u7s4c+q5NzX39en1czE2+GhwsO71N2p7urszde5+vD5ytS08+TqydGu7fH4' +
  'ycym6PL2x8Sg2+/8xMyo8vv+476g9/r33quZ6+vm06KQ3drUwJ6GzczFocKK3O/um+yd9fr6seme5PDyvOWcz93aw+CWwsjFw9mQtMPLwOCW2u7w' +
  '6NaN7vrl6MOE4vDJ4r15z+G03r1xttCk2MBxy9zTz76T8PXyy8CU7vLnycKM4OXSycKC0NbAysB6vdG/w8ShyfLt3sOc5fvv5aKO5e/c24mC29vE' +
  'zX9zy82vsodzxNu+n86S6PXrrOGO6vzbueOH4e3AweJ9zdutxuF0s8yoweCsveLm2u/Y3eLv8eTk19fg7uLixMjR6+HXsbrB5uDIpKyw3de3mp+e' +
  'ysyok5aPusCfjI2BrLaXioZ1oK+NioBslKWvpoB7gZLo5n2RbHX45XSNVln10m6EP0HkvGh5LjDKp2NuIiO2ll1iGRqoiVdYEhObgFJPDQ6Qek5G' +
  'CgqGc1RJBweGgJOHBQXP0ru1BATm6r63AwPf3ruwAgLPyrGlAQK2sqOWAQGfm5WGAQGOiYh3AQGCfH1pAAB5c3JeAABxa2pVAA11ZHFiACXXfJaG' +
  'ACX0h5iJAB38gZKFABf+eoiAABT/doF8ABL/c3x4Cx//cnh2ETz/dXZ0Glr/e3d4IHP/gXt/LoH/iZWnZr7/w9Xmyuj119j48OHzzc/s7ujwxMXg' +
  '7ujqvrvY5/HjvL3W2+/a6+vz0ezR7+fyzOvF5eXyyee64fj7x+Gv0/n2wt2uyP382OKr0P/+9MufzPr077aYw+7k3KiRsuXZvaGLqOLXocSb1vf0' +
  'oO2h6v38uvWf1+7uxfWaweDfyvGUsdHRxuuUrOLozfOZ1ff48eCM2Pfl78GHzOnO4K+Cudy9wqZ7qdS2ob+T0vPqneyg8vv5tvKc6PHow/OW1N/Q' +
  'yPCNwNTBx+qNstXaxOmpvvP07tyhuvzt8b2Yte7X5KiPteHAyp2FsNivpJ2JyfTglM2X8Pz2kvCR9P7klPuI5+7InP580+WxpP14wt+6p/um2Pbr' +
  '5vqv4fbp+Pat3OrX9vSq1NvE9PGkzc207u6ZysGj3uGKw7eU0M15uKyHw8FsrqR8tbhjo51zqbBfnZmEntag2Nrc4/On2tTU9+2Zwb619OiLq6yb' +
  '79uAmZ+H49N3i5V4y81ugY5tvcJneYdjt7dgcYFar69ban1Tp6ZXZnldm7uXsr7R0uuy187e8uukwLq+9OmWqami8N2GlpqL6NR8hpF60890e4ls' +
  'xMZscoRhvbllan9XtrFcY3pRrqpVXnVLoqeFlrutv+az0+PY7fKmwsy+9u+Wq7Wi8eaJmKaL6t18h5t61tlzfZRuwtJsdo5kuMhmbohcq8ViaIJX' +
  'nMNfZX9WjL93gbGqnN/Ix+Dn4+Ds0drl99r5ydXe9tf3u8/Y89zoqsnR6ujVncPN4fTMl7vJ2vPGj6y+1u/Bh5+11Oq9f5Wt0+O6epm5y9/duNjr' +
  '5dv139Pp8sH828DX6K3+zqvC0aL0uZywrqPgrZ20nuXbs63OrffSrJ67w/3GoZCnyP27k4SYyPi0iZKWw/LGwtDh3PDi7dzh9dbi7tjY7r3c3tHO' +
  '2q7RyMnBuKe/s8G3j7e9qMC8cMe7nbStV8a1k6ebQ8KvipuNNbumg5OFPrqsgczcruawfPH16NOebOXl6rWRYczI3KOGXLKsv5t9W6OelbOVcazA' +
  'dNOmcaS2WtigaJKbRtWWYoGFNs6KW3Z1MceWe6G5ku7YwMHm4Obt17TY9NP02qjM7sj43J7C5MT935i73MH+5Ji/1sD/6Ze+0r7/7ZO50Lv/9JC1' +
  'zbb/+I2zy6/+9aXOxMj26drx6srn39jv8bDd3Mzf5Z7W3L/OzZPR37PCqJjO5rLKnODT5rTRrfDU5KrEvuzT5KK5xOXS5Jqxxd3R4JewwOXY1bbi' +
  '7fPWxrLU+uPUuKi48+HPqZyh4fHDmI+Pz/uxlqamwP6t3+Xmtv+s7O3isf+m3d3PsP+dxtC8r/+Sr8Cxqv6er+Xpzvikxfj58dufuvbo68GXuOrN' +
  '2bGKtt23uaZ/sNaxm7GW4/PpldyR9/znlvOG8vPPn/x74uO5qP5wzNemrPmEx+LXyP2z5ff07/HA4Pbq9uvD1efW9Om+xdfF8Om1u8655Oyu1/Ha' +
  '2Ous9Pvv0fGr6vHizPCp5vv3yuuo4P79yOSlzvf6xOWy0v3+7tyl0f7788ObyfPr5rOTu+razauLrOLPp7KRvvfxneSo6/37r/Gn4/Twv/KjzeXc' +
  'xvCcu9jMyOqWrc/Iw+ydyvHv7OmT3fvr+cqK1u7T7raFxNy/1quAsNCxsaiDs9fMn9Wl6fPwqein7vHuveui3+HZxu2ay9TIyOqSu8vCw+akuvDt' +
  '3uSkxPv69sidvfjq7a2UvujR2J2Kt9m6tpaFtdS6mreY6vPrl+OY+fvmmPeT8PDNnv2L3eO4p/6CyNipqPiTxuLcy/202ff18PS81e/q9fK7yuDX' +
  '9PC2wtLE8e+tv8Sz5emgtr2j1NKRsbKVx7+Dq6mHuLd5pp59rbFxnpVzoayAw8W3keeo7uzei/ig3tbDivuSxb6miPKFr6yOj+N7naB9jNpzkJVx' +
  'ic9rho5ll8FlfIdclbVidH9Wkq9dbHhOjqRqlKOchdei4OXiffOf3NbMevyTwr+sePaHrKqTfOZ6mJ2Bd92OyM7GcPWq7+PVb/yg2M24cP2RvrWc' +
  'd/KEpqSGgOJ6mqGNeOGe4uTcbvak5d3Rdv2ZycWydP2OsbGXg/GDnqODg+h5jpl0ft1yhJFofdRse4xffc9ndIdYc8xkb4NTa8ljbJh/aM2rqNXa' +
  'wuzm0d/17eD4ztrt8t33wtXl8tzurs7c7OjgnMfS5O/WksLQ3u/LirXI2uzChKrA1+m8gp+41eO4f5ix0drEmcnmzuDu0uL47tH62dPp67z+0b3R' +
  '26/7wau8v6rqraGvn9Ter6/QnfPXs6nIufzPq5q0xP3Hoo+jx/q+mYmWxvW7m7nBxPXd4dzp7unj89re7s3h6dXU4bvY0c7IxrDJuce5n7a8qcK5' +
  'fNK5oLq1YNSxl6qjStCnkJ6UO8mfiZWHMb+bhKa2dNXPjObq09Txi+Po67P7itTW4Zn+j8PFyYr/lLe4pYr/mrG3g6z/o7C8abX/pqe0VLL/qZ+t' +
  'RK7/qpmnOKr/qJmsZdP/qMHm0fL5q73f8uT0qLPM8uDtnKu76+fikaGr5PHWiZ2m3fvPjae31/7Hkp6q1P64jJWc0vysh4+R0fehgIyOzO+kfc3f' +
  '2vSkeO329N2abODk8cSWaMjH4LOVaLCuwauUZ6Wno9y2lrzQofXHlbLEufzCiKCuw/67hZOcxf2xgoyOxPiugam80v2wgbfT8u6gdqS59NOWcZKh' +
  '5cGQboWNyLSJbYOJocidzdDViu+l48/OhfqZybuwgfqMsqmWhOx/npyDgeF9ormrdO+t5Ovhb/up29zLdP6cwcOuePmPqrCVie+ClqKDhet4iJh1' +
  'feJwf5FqetZreYpieNFnc4VbcM5iboNYa8prcbGegeKyt+nj2/XY0+Th9ejnztzY8uLpwdPP8d7iscrD69vToMCz3dDAlLWjzbmui6uUvqykhqGH' +
  'rKWdgZl7oJ+Wf5J1kZLat6KRenv16p6cYWL86pSXSUz+2YqNNTn5woCBJyvjrHl0HCDQnHJoFRfEjWxeDxG9hGdVCwy4fWFOCAm0d3ddKnLAqMDJ' +
  'oNTn5tXn5Mjn8tDc5J3j5cnQ1XjazcLCuVzHtriwkEOvqqqeaTGbopyNTSSLm5F9OBqClYlvKRN9kYJkI1CItbeyLM2w6ujjT/Gq3NTIb/ucwL6q' +
  'f/SMqqyTkeiAmJ6BjeN3i5Z0gdpwgpFpfdNreo1gedFncohZcc1kbYRVa8dxfaGijOKpyOTk3um12Pfo9uS50PHb9ui1xOPT8+6tvdXO6vOkxdXg' +
  '3vGp7vP21fKv7fzv0fat4/v7zvGo4/7+zO2j1vv1xeqr0/784+mm0//+986cy/Xw77eVwO7g2aqNrubVtqSIqeLjndCb4Pf3ou+b7PX9u/eb2uPq' +
  'x/aZxdLay/GVsMnMx+uctejv2/Ca2/j39deP1/Hk8L2Jx+HM3q6DstS8vqd/p863oMea5fHqnO+n+Pv0tfml6Oviwf2f0t3NxvqVwNK+xPGXtN7r' +
  'yu+qwfb58NyivPjw77yZs+rW36eQsd6+w52GrdSvn6yb0fPkl+Cl8vvzr/Cg7vbevveY3d/ExPWQy8+wxe+Mwc2/w/Ou5fHt7u225fvr+ue/2+/Z' +
  '+Oa8yN7G9Oi0tdO46uqswuTT3uay7vfy1uWw6vbs0uWs4/zrz+Ko4f75zN2kzvjyxt2wz/3769yn0/7++cGZzPbu7q2PwOrb16OFr9/LsqGDrt7m' +
  'n9SZ5vX4q+2c6PL9wu+c0uPpye2YwdbXy+qSsc3HxemYw/Hv3/mV4Pvw9u6J2PfZ8ud+yOrB6Ntzt+Su19Rqptyevs9imdKPrMRcjsaFn7ZWhrt9' +
  'ka9ThbFziqhPgqZtgqOGw+PIeuWu7vXcf/ej2dq+gv2TvcKkiPOGprCNjel8k6J7ht9ziJluf9Vsf5Nlfs5nd45dd81jb4hWcslgaoNSa8d0lba0' +
  'o++j2urq5e203O7n9+rA1t3V9um+zs3D9ui3yMCw7+Sqv7ak3dOZta6X0b2Gr6WJxLN3ppt9uKxvnJV0r6lploxppahhjoZfl7Jahn9WjLlWfXhO' +
  'hLVWdXFHfrJWb2xBeLFWamc7dq9SZmI2d6ZOYF4xdZ5NXFwtdJhMWFgqc5BLU1Qmb4tKTk8jboRHSksfbHxDRkYaaXU/QkIWZG47Pz8QYGk4PDwM' +
  'WWQ1OjgJVF4xODUGT1gtNTIFSVIrMi8DRkspLysCQkcoLCgCPkEmKSUBOj0jJyIBNjkgJR8BMjUeIhwBLzIcHhoALC4ZGxgAKCsYGRYAJicWFxUA' +
  'IyQTFiYNHx8ON3ZQFxl7e9CkERjZ1evNDBX05eTMCRD82NzEBwz3wtK4BQnjqMaoBAbHlLeWAwWzhqWEAgOofZV0AQOidYdmAQKebX5cAQGmdIlo' +
  'CQfmw6OLBwf44ZmKBQb9142EAwX+wYR7AwPvrHtvAgLamm9jAQLIi2ZWAQG9gF9MAQG1eFhDAQGyclU9AAGtc4twAADn18yyAAD49NrDAAD98dXA' +
  'AADx3My3AADcxMGpAADBs7KYAACnqaCFAACTnpJzAACFmIlmAAB8lH5bAAB2jXlYABjGi6mIAyPvo8CmAh/6ormkAhr+n6+hARb/nqWeART/nZ2a' +
  'AxP/npaXBRv/pI+WBi3/qouYEUr/rYmcGGz/rZSoNJr/r7/mqOL7wsz35tr0wcPq8djyvLzf9d7utrfX8efss7bU6OTr6drz4N7r+d/73tvt+Nv7' +
  '3tbr9N3+4NHl79z/4M3e4Ob/2ePT3fX/8tXG4vT/8bu74e365q6x4+L4y6eq5OPyqrWy4/b7ps7L7Pz+u9XR6/f/0t3N3+T45d3G19Hw8Nm70s3w' +
  '5+av7/H7+OCd8fXx/cKT5O7f+q+Rz+bP66mSxeHHx6uZ7eXquLq4+vj5usXO/vX9zs7b9uny4NTa7tfk6dTU4tHg4tLH7O726NGy+u3297ij9+js' +
  '8aud8uDd3aic7tPOuKaj8Nvapqi6+/X1sbDK/vzyx7jW8/zl28Ha5vDb6sbW2uPS5s/M7eTy5OS9+uL799Ow/t3w/cyt8tng/squ5dLU+8eu3MzN' +
  '98Go2sTF6bmf6cG86biX6r6v8LaR4rml87CM1LKb8q6Hw62S8q2CtKWG+6l+ppt79616mpJy9bJ3kYpq/Kx0iYFh+6FxhnlZ8J1ugHBS+5hpeGhL' +
  '9JJlcWBE745ia1o+6YteY1M36YhYWk0w3YFSUkYqx3dLSj8ksmtEQjken189OzMWjFQ2NSwQfEsvLycMbkMpKSIJZDokIxwGWjMeHhcFUi0ZGRID' +
  'SygVFA0CRCMRDwkCPB8NCwcBNRsJCAUBLhYHBgQBKBMFBAMBJBAEAwIAIAwDAgEAHAkCAgEAGAYBAQEAFAUBAQEAEQMBAQAADwIBAAAACwIAAAAA' +
  'CAEAAAAABgEAAAAABAEAAAAAAwEAAAAAAgAAAAAAAgAAAAAAAQAAAAAAAQAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' +
  'AAAAAAAA';

/** Accents: per event uint16 centiseconds (little-endian) and uint8 strength. */
export const MENU_SCORE_ACCENTS_BASE64 =
  'AwD/GQD/awBRhwCEwQCN+gBV2AExSgItuALbKANqYANTmAOO0APB6wOGCASoPwT/eATU6ASMHwVbWQVSkAU0yQVBAQZDHgZuOAa9cQZKjQZOqQaN' +
  '4QZ/GAemNAd3UAejbAepiQdopAd8wAfn3AeA+Af5TQiMaQiJoQjG2giwSgkwoAk+ugnCDgp5KgqNYgrKmgrk0Qqc7QqaCgu3JguCQgvcegv/zwtn' +
  '6wuQIwyaWwzqsAxPzAxpAw2SOg3/cg2ijg3Wqg314w3/Gw7/Uw7Fbw7giw7oww7/+w7/NA9lUA9mbA+qpA+C3A/wFBCFMBC/SxD/gxD4vBBqEBGc' +
  'LBGOZBGxgRFWnRHC1RFe8BGKDBKhRBK3YRKqfRJktRJI0RKn7RKRJROvQhNhXBO4lhNxshOAzROp6ROHBRSqPRR7dhRSkhR2rhSM5RToHhXfVRWF' +
  'cRXajRXuxRX/4hWC/hX/NxZyUxaGbhaaphbr3hbtFhePMhe5ThfTahdphhfrohd6vhd99hd/EhiCLhjLZhj/ghh2nhj/1xhK8xiPDxmLRhnnYxld' +
  'fxmNuBlI0xme7xm2DBp0JxrpRBplXxr/mBpssxqtzxqy7BqWBxvEPxvOdxuJlBvOrxvA6Bv/BByOIByyqxz/yByR5BzHAB23OB1+VB2LcB2mqR37' +
  '4B3/GB6LNB69UB6hbR6IiR7ppR5xwR5v+R6PFB+bMR+oaR/+oR/p2R+v9R+kESCrSSDfgSCSuSC91iCc8SC6KSH/RiFpYSH/miGVtiGC0iGJCiLg' +
  'JiKsQSK9eiLoliLBsiLnziKG6iL/BiOJIiP/WiPkdiPhkiP+ryOAyiP/5yPbAiS1OyTMVyS0cyTVqyT/4yTQNiX/UyX/byX1iyX+wyWk/CWZGCaJ' +
  'NCa+Tya/aya3iCaxoyax3Can9yalFCe9MCekTCe8aCe6hCd9vCen2Ce59Ce2ECjGLCjASCirZCiwjijfuCj/1Cj+8Cj/DCn/RCmLfSnAmSmqtSnA' +
  '7Sn/CSqHJSr/XSqieip0lSqlsSpczSrJ6SrgBSu0PSvQWSvrdSvbkSuorSv/ySus5Sv/ASzhHix8OSz/VSzZcSz3jSz7xiy9/izMGy2tNi3Ebi3/' +
  'ii2Ppi3/3y2X+y16Fi6KMy5kTi7Uay7ohi6ovy7D2y6w9y6sEy+TLy/5Sy+KZy/7gy98oC9/uy/z1y/v8y//DzD5RzCifzC2nDCvtzCd8DDjDDFt' +
  'KDH/YDF8fTFzmDGNtDHJzzGS7DHYCDJ/QDKjXDK2eDKhlDKRsDLrzDKP6TLZVzP/dDP/kTPPrDPvyTOxATSTHTTPOTS7VTSucTTZjTSfqTTrxTSK' +
  '4TSm/TTSGTXENTWoUTW3bjXRiTXJpTVkwjWL3jW2+jW6FjaqMjbdTjaKajbjhjZzoja/vja22jbDETflSjfPgjeznjeiuje11zeT8zffDjhyKjjM' +
  'RzhvYjiwfzi7mzistzh/0zig7ziiCzmEQzlSfDlMtDmh6zn/Bzp1JDqYPzr/Wzr/dzrxkjr/zDrIBDuFIDuxPDuhWDuEdDuwkDukrDvByDtz5DuB' +
  'ADy+HDy1ODyaVDyQcTzGjTycqDxpxTyJ4Ty0/Ty5GT2fNT3EUT2nbT3GiD2ZwD3m3D3U+D3sFD7/TT6rhT7Hoj6uvT7B9D7KET+dLT//Zj95gj97' +
  'nT9/uT+l1T+p8T/mDUDSKUB5RUCsYkDDfkC3mkCntUDT0kC+7kDhCkGuJ0GEQUH/XkH6ekHxlkH4z0GbBkLQI0LCP0LLdkLtk0KYrkL/50KFAkP/' +
  'HkP/OkPnVkPzj0OnyENw40PAAESlG0SROES2U0SdcETLi0RlqESTxES44ES0/ESTGEWYNEXJUEWwiEVywEV7+UXIMEafaUZ3hEaPoUaSvkah2Uag' +
  '9UanEEebSEf7gEf6uUf/8UedKUisRUiUYUizmUjGtUiP0Uj/Ckl3J0l2QkmEXUl+eUmUlkm/sUmNzUlc6kmDBkqcIkqrPkrIWkqWdkqhkkqbyUrc' +
  'Akv/HkvFOUvEckulqkugx0uY4kuh/0tgG0zON0xQU0yYikyWp0zJw0yz3kz/+0zQM02ObE1so03/203/E06ZTE5vZ06fhE6koE6fvE6a2E6v9E63' +
  'LE95SE+6ZE+dnE/y1E+ltVCC7VDDJVGXXlHlllGazVFL6lGRBVJfIVJ6O1I+WlJjdVJSqlM1';

/** Bar loudness (RMS relative to the 95th percentile), one byte per bar from the first downbeat. */
export const MENU_SCORE_BARS_BASE64 =
  'hFpzn2PCi8VO4aXfb5eVp4WkyOHZ4e7frdPAx9K8sq+hx8vJzsDTu7XWzv/6/Nrb7dTf2OnYwdjy5Mfj5uLa4u604d3q3b/M4tHIzsri7an/4+n/' +
  '/8z07bv/6YWi/8QB';
