// Generated by tools/analyze-menu-score.py; do not hand-edit the envelope payload.
// Original supplied score → measured spectral controls, not invented musical timings or copied art.
// Source authority/provenance: docs/engineering/menu-score.md. No audio samples are embedded here.
export const MENU_SCORE_FEATURE_INFO = {
  "sourceArchive": "assets/audio/source/the-sovereigns-oath-original.m4a",
  "sourceSha256": "6a2dc57c6e8c68bfa65ab6d1e5ff6cf782f670e28e5121f788c646034e1de8c1",
  "runtimeReference": "public/assets/audio/the-sovereigns-oath.ogg",
  "runtimeSha256": "46d8c5f6492490e8ed521459fde2c588af18f55dff11ab4fbd22e491259fbee8",
  "duration": 214.2,
  "rate": 20,
  "frames": 4285,
  "channels": [
    "energy",
    "bass",
    "mid",
    "treble",
    "onset"
  ],
  "payloadSha256": "f873dd1b0471be4f86d82f5c9a1dea9fbe4f804870ff85d7a6d4dde18af69d93",
  "analysis": {
    "sampleRate": 12000,
    "channels": 2,
    "windowSamples": 2048,
    "window": "symmetric Hann",
    "windowSeconds": 0.17066666666666666,
    "featureHz": 20,
    "hopSeconds": 0.05,
    "timeAlignment": "window centered on source time; zero-padding at ends; not calibrated display/audio latency",
    "bandsHz": [
      [
        40,
        260
      ],
      [
        260,
        2200
      ],
      [
        2200,
        5500
      ]
    ],
    "noiseFloorDbfs": -65,
    "referencePercentile": 95,
    "compression": "square root for energy/bands; linear positive spectral-flux onset",
    "attackSeconds": [
      0.07,
      0.07,
      0.07,
      0.07,
      0.035
    ],
    "releaseSeconds": [
      0.18,
      0.18,
      0.18,
      0.18,
      0.15
    ],
    "quantization": "round to unsigned 8-bit, interleaved energy/bass/mid/treble/onset",
    "referenceAmplitudes": [
      0.218943665,
      0.2106605172,
      0.1252767815,
      0.0713470851,
      0.1250812903
    ],
    "numpyVersion": "2.3.5"
  },
  "credit": "The Sovereign's Oath \u2014 supplied by Ael for Tervain; source metadata discloses creation with Suno."
} as const;

export interface MenuScoreSample {
  energy: number;
  bass: number;
  mid: number;
  treble: number;
  onset: number;
  /** Cumulative energy-weighted seconds; random-access phase, independent of rendering frame rate. */
  motion: number;
}

const ENCODED =
  'IQQQAAM8ED4UH08SZB8kXQ15JyBnCoMrHZFEjj1XspOiSsjLwKhGttrPpUGc3tujO5He3aE1ftzaoDJo2deeLlfX05wrV9PTmihR0c+YJU7MypYm' +
  'QcfGkypFw8KNKj2/vognNbu6hSUwuLeEIi21tYUiM7CuhiIxq6SHIiqloIkhNqKdiR8wn5mIIyiclYsqJJiRiykilY2IJh+RioUjHY+IgyAYjYSC' +
  'HRmKg4IbIYh/ghgahn2CFRmEeoATGIF4fBIWf3V7FyV9c34YIntwfhcaeW58FBZ3bXoRFHVreA0Qc2l2Cg1xaHMIEm9mbwYPbGNrBQxpYWgMC2hd' +
  'ZxcQaFt0IB9qWHwhGWpWfiEUalOAIRJrUYQgEGxPhiAObU6IIAxtTYkgC21MiB8JbEuHIAhsS4cgCG1KiCAHbkmLIQtxR48iDHZGliMMfESfJQ2F' +
  'QqsoE49AuSoamz7KLR+lPdswH6o75jEdqTnjMC6kONguOJw4zSsxljjFKSqROb4nIo45uiUcjDm3JBaKObUjEYk4tCMPiTi0Iw2LOLYkDI04uSQM' +
  'jzm8JQuROb4nCpM5wSkLlTnELAqYOscvCZs7yzMNnzvQNw6kO9c9EKg73kAQqTvhPw2oOt89N6Q52TxGnzjSOTibNsw2MJk1yTQnmDPJMiKYMskw' +
  'G5kxyC8WnDDNMBihMNUzGqQv3DcXpS/bNyqkLtk1RKIu1jM4oC/TMCqfMdEvIp8x0S4boTLTLhekMtgwFagx3TMSqzHiNxGrMeM5E6kz3zhCpUzW' +
  'NUihZskyQZ1yvzA7m3S7LTWadLkqKpt3uSgjnXm7Jx2hecEmGqV8xyYYqYHNJhapgs8mFKd7zSQ9o3HJIjmgb8YhN55zwR8wnXW+HiWceL0dHp57' +
  'vB0Yn3y+HxWigb4jFqiFvygirpK/LzzCo8FPYNrIynHK6OTHa97x6sJgq+/qvFWU6ue4THfn3bVGYOTdr0F+4+WpPYHi4Kc5bN3cpzRd2daoME/V' +
  '0LAwTNLNuTBFzse7LjzKwbsrNcW6uSkywLW3KDW9sLcpM7qstigvuKu4Jja2qLkjKrKhuSIjr5a8LSark700OKmOvTIqp4u9Limmib4qJ6SEvice' +
  'ooC+JBygfr0jGZ96vSIVnni9IRWedr8fFJ91wx8dn3TFIBudcsQeFJtvwBsQl2y7GA2UabcWDJBmshMLjGKtEQmHXagNCINaowoLgVmeBwqCV54Y' +
  'JoRWrCc0h1atKCaGV6onHIRYpyMWglqjHhCAWp8dD31amx0Me1qWGwp4WZEaCHZYjhgGdVeMIBd1VpMwJ3VUkjIdc1OQLRVxUowpEHFRhyQMc1CO' +
  'Jih0T5gpJHROlScccE2NIxZsTYUfEGxNghwUbEyLHiZtTIsdHWxLiBsVaUqEFxBmSX8VC2NIeBEIX0dzDQdcRm4KBlpFaggFV0RmBgR0S2MeFpOA' +
  'aT+LrKxnQIS6umE3c73BWy9nwcBXKWTAwlMja8HHTx9mxcZLG1nFyEcYXsTIRBZWzMhFKkvi1nVitvHrlHju+PWVctn8+pBrwf39imOj/PuEXI76' +
  '+IBVlfn7e0+e+fp2SYb2+XBDevP2aj908PJtSHbr64lcbOTkmltb3tqcVFHY1pdMVtTTkUhN0M6RTknLyZZORMjFk0hExMGPQj7Bvog9OcK8h1JC' +
  'xcGjb27MwrVvZMzJtmdjy8evXk/HwqRYQ8G9mlI5vLiPTjO1tIdJMK+tf0QtqaZ6QCamoXlBNqWfj1JPpZulUkikmaZLOKGWoEMrnJSVPCeYkIk3' +
  'H5SNgTIckIt6LhmNiHUrFoqFczAUj4JxPBWehZ1Na6uLyFVqs4rXVk+yhNdVS6561FNJq3PRUUipbdJQOqpm2k82rV/iTiywWOZNIrNT6E0ctk7u' +
  'TSa6SfdPK71E+k8gvj/6Txm/O/xQFsE4/lETxDX+UxnIMv9UGM0w/1YZ0C7/Vh3RLP9WF88r/1YWyir9VD3DKvRQPLkp600usSniSSOqKdpGG6Mo' +
  '00MYnyfOQRScJ8tAEpkmyD8PmCXHPg2XJcZAE5g0xkQkmULIQyKaRcpCIZpCykIZmT7KQRaZPclAFZlKyEEdnFDIQx2gXctFIaZq0EgpvnvXZEna' +
  'sd+U0+3Z2JTk9uzQibv79sV9of35u3OJ/fmxaoL8/KligPz5olmA+fqbUoT19JZMb+/skUle6uSaYFvm3rhsbOLau2Zg3tezXlDZ0qpWRtTPolND' +
  '0cimYE/Nw7NfSsm/sFlFxbmmUjvCtJ5NNca1nGFTzsGvcoLVyLpvc9fNsmZn1cymXlvPyJxYSMnClFNAwruNTzm7t4ZLNLezfEcttLJzQzayrnJG' +
  'MbCqjVNWr6ekT0+to6ZIQKmgnkE1pJyTOy6fmYk2KpuVfzIklpJ2Lh+Sjm4rGY6KaCkajohqNCORhpBNT5SBplRAk32nUTCQeqJMJo15m0ceiniV' +
  'RCCId5JDIIZ1jz8Zg3SLOhOBc4Y1DoJygjQRh2+YR0WMbK5QQI5osU4ujGWuSiGJYqlHGYZfo0kjg1yiUzCBWaBVJn1Wmlghe1OVWht9UJhaIIVO' +
  'p2Ami0u4ZiiOSbtgHYxHt1YXh0awTRKFRadJHINEqlBAg0StTjSBQ6pJJn1Bo0Mde0CcPhZ7PpxGNH07qFE4gDioTyl/NaZKHnwzokQWfTGePxOB' +
  'MKpHOIUwtUoxhjKzRiSDN65AHYVEpz0cs2ylcHXat7Ga3u3crpHY9u6nhbX79556pf37mHGZ/v2RaIz+/oxhf///hllv/P9/Un/4+HdNavLxdFBb' +
  '7emYZmnp5Lpod+bfuGFg4duvWlfc2KZUTd3VoWFX3eCrcabf4LFtkNzarGV319ahXWbWz5dZUeHbmnGU6u2ufLrw7LN2luvnqW2C5eKdZXbd2pNe' +
  'YNXTi1lPz82DVELIyH1QPcLBdkwywb1xSjPMwnthjNXck26v3NyoZo7Y1apca9HPolJhysiXS03Dv4xFQbu4g0A4tLV6PD6urXQ7MqylcUQrxrCF' +
  'Xo/b2als5OjkxGm95N3CYpfaz71bfc3AuVVswrK1UFS5qLNMRLOcuEg8r5LBRjSuiM1FLLB+2EUptHTlRye5a/BGIr5i90cewlr7SBnGU/1JFstL' +
  '/kwW0UX/UBjXQP9QGds8/1IX3Tn/UxbbN/9SGdU1/VFNyzTyTUq/MelKOLYv4UYrsC3cRCKsKtpDH6on2kMcqyTeQhmtIuRDGLAf6UUUsRzrRiey' +
  'IetHYrE86kZ9sFnmRHCucd1BWq181z9CrH3VPjitg9Q+L7GI0z0nto3YPyK6k95BIMWZ4Uoe3a7jfqju196X6vfs1YzE+/XPgKf9+sl1i/74xmyI' +
  '/vzCY5j++cFbjvv3v1WE9/S+T3Py671KWu3iv1JP6dzRZWzl2NpjYeLV1lxM3s/SVkHczM1TRt/Nymdz4N3Oc5ni28xtfN7UyGVu2M7FXF/byMJe' +
  'VePcxXi76+vMeLHu6cdwjurlvGqD49+xY2nc16heWNTQnVhIzcuUVD/HxI1PNMG+hUwywrp/TTnNy49msNbcp2um2tizY4HW0bBZcM7MpVFhx8SY' +
  'S0+/uo1FQLi1gj9HsrF5Ozysq3A3LrelbDwozsGQZMve4a5z2ujfuG6j4tmzZn/Yz6xfZs7FpFhUxb6gVU29t5tRP7Wulks5raWPRC6mn4Y/JaGX' +
  'jEo/npCjVUaciKtQNJiBqUknk32kQiGReZ0/H5B0qk9Sj260UkSOabFONIlkq0kmhl6kQxyKWqNKNZBVvV9gllDGY0iVTMRgNJFKvlsljUi1Vh2L' +
  'RrNUNIpEt1MziUG0TiaFPq5IHYA8p0EafTqgPRl7N6FINXozoUoreC+eRiB1LJlBF3IqlTwRbieRNg5rJYwxCmgjiS4JaCCGOxZvHoxULJU0nnBF' +
  'vX/IjtLbu+SY3O3P8pix7NTul5Dn0uOTdt7J145e0r/IhkjGtrl9OLutrXQwsKKnbCirl6JnIbaOvmdnwojfaanMgfBmfch78WFewHfnW0i4dNhW' +
  'OLKGzFROrZDDT0Oqjb1KM6WIukYppIO4TCO3hMllhsqd5X3E16nyg7DXp/SDm9Gj7oF1yZ7lfWPBmtl3TriVznA9sJHEaDCpjbpgJaGJrloen4el' +
  'VyeelqJZWZ2Un1NEmIyZTDSRhpRHKIx/jkIfh3qKPhqEeYc6GYJ4gzYUf3Z9MxF8dXYyD5h0dkYptZivZrzNuthrttzA6WqG277raGbXuepnUtSz' +
  '6mdB0aztaTnQpPRuM9Gc+nMx0pX8dy7Rjv54KcyI+XdWw4LudFG6fOJvQLJ312szrHLSaCytb9JnLrOA22dPu4nmaEfBhvFpO8KB+Gk9w3v3ZjzI' +
  'gvZkkcua+2GMzJ74W3HHnO9UXr+X4U5Ot5PSST2vj8lFMqmLwUAoo4e6PB+ehbE4GZmCqTQUmYKkPyKYjqJKRZeMnUIzk4iXOyiPhJE0H4p/jC8Y' +
  'hnyHLRSCeYQpEn50fyYOeW97Iwt1anYgCaBxfkxKyrKle9Tl2ax55fLspm/L+PSeY7b485RZmfb4jFST9PSIUn3w8INObOvsfUlZ5Od5Q0/c3XZB' +
  'QdPQk1xVycOpZUvAtahhNrespFowsKedUjCuophVRq6ooWdjr6ufZlWtqJpfSKqklFU5qaCNTy63p51le8TFqm+nzcumZpTKyaFcdsTAnFJhvbiX' +
  'SE61spFBSa6rijw4qKSDNiuin3wwJp6adSseoJWJQ1GhlqxVY6OSsFFMnoqrSDmXgqQ/LI97nTYkiXWVMR2CcY0sGX1thScUd2l9IhB0ZXUeDZpy' +
  'g1FXuamsgNfRy7d/vdzXs3Wf29itaYXY1KVebdPQn1lkzMmbVlXFwZdQQr27kUo4tbKLQyuwqolDKayioltWqJmvYEWjkq1aN52JqFEpmIGhRx6e' +
  'gaBRRaadq152raSpWF+roaRPRaedn0czrJiZSC66q69spMbDvXigy8O6cYXFvLVmb7uwrVxWsqSmVkaomadVQaGPpU8ymYahRyaSf5s/Ho93lToY' +
  'lHWkUl2YfrxeXZt5ulZElnC0TDKOZ61CJYhgpTochFuiOR6AV582F3xUmjERd0+TLw6CSo9II6Zoq3WLxaXWjuPcxuWLwOHN5Iec4c/dgYTf1tB5' +
  'etzWvnBj1tGsZlLQyp5eQcfEk1g2v7yIUyq/tYxSNsWqx1quy5/jWpbLlfBXccSN6lNUu4bcTz6zhsxQPK2Vu09IqpWuSTmlkqhEMaCOpEEnr4yk' +
  'US7Bpcpvvc+95Xmz1LzjeJTPtd53gMeq2nVivp7Tc0+1lcpwRqyMwm05pIW7aS+ef7RmKJ16rmQnpoG9bHuwlc9reriX1GdbuZbWZUW5ltViN7iW' +
  '1WEruJXWYCO4lddgHbmT2mEauJLcYhe7kdpkF8ue2IOd3crekOjt4duFxPHp1Hqs7+vKcJrt6L9neefltGBp4t6qWlfc2qJTU9jYnExK0dGVRj/L' +
  'xZVTO8S9q2xav7ata0m4rqdkPbGpnlsyrqSUVCuvpZdiZLO0nGltt7SYZFm0spJaSq+si1I6tqiIYEHIwp1/r9fcnHyw3N+Vb5La3I1iftbWhFdp' +
  'z9F7TVvLy3NFS8XIaz5KwMJkOEW7vF0zPL26XEdDxsR3do7P03x3htzcdWiJ4+duWobm72hPdOftZEds5elhQmbk6l0+aebtXD5u6exdSF/t72pl' +
  'evb0oZ62+/rLueX9/Ny30P7+2q68//7QpLD//smhjv79zLmJ/PjXwnj58NS9ZfXr4r578eTmu2Lu3OO7WerU8c965cn0yWTdvu28UdO05LFEz6za' +
  'qzvUs9vGod3H7Nyo48zp04jgzd+/b9vK0K9V4cbGs23w49HR3Pjx09D3+O7QwtDw5MaxnePYu6V/3Mm7pXfWu96woNGu66V7yaTbmF27nMiOR7qW' +
  'u5FGwZrct7LGme65n8WR66t3vIvemVqyhc6LRrKAx4tFt4Pjnpq6g/CXc7eC34lYrYDNfEK4fcF9Pdem267Q69PpvvT16ue02Pry4KWw+/nUmZ37' +
  '98SVhfj2xK9/9u/SsnDy6NKsWu7i5bRd69vmrkno0+W4TOXL8tVu4cLxzVXYuee7Rc6x3ao4zKrSozXSutbErtvJ4dWh3czdyIXbzNOzZtfJxKNO' +
  '4ci/r4zw5NDN4/jy0sr49uzOu8rr4MSrld/St5901MK1rW/Ltci7a8SoyrFQu5/Doj+yl7qUMbiRt59YwJfcwr/Glu6+n8SP6K93uonbnluygMuO' +
  'RrOAxqV1uY/dzJXAj+LJecCZ2bdryazLqGvdy8KooO/i3crB9/HmyvD7+OS+1P383a6v/v3SoKr//seciv79zLKC/PfUtm358dG4XfXr5bpo8eLi' +
  's1ft2uK9VufR8c1u4sftxVXZvOS3Sc+x26o9z6zUpUHXwdzJw+DO6tGs4tDjxIbez9a2aNvMx6lR583DubXz59DR7fnzz83w9+zLvL/s4cGtj+DT' +
  't6Fx28XKpYvVtuWoi9Gq5JxoxaDUkE+6mMKGPb2TwJpzw5jgur7IlPC1k8SN6KZwuYfal1Wxf8uKQ7Z7zJZmun3mqZW9e+qebrZ51o5Sq3fFgj7C' +
  'ecCVYeG44MDZ8Nzmv/b47uCyzPz216Os/PvKl5r8+cOVivn12ayP9u7dsHbz6Nm5Ze/h6sd27NrjwFzn1OPNj+LM6+CB3cLl1WbSuNnFUsiwzLZB' +
  'y63DslrVxdTMwN/Q3dCm4NTTw4Hd08SzYd3RtqhM6dXAvc706tXP8/r1083k9erMwLLp38GykeDQua5428XP07HWvOXZmdK04Mp2ya7Ru13FqcCt' +
  'StCryLig3cHky9znyvLGuevP6bai6+DZo6Dq6MeUjenmuIiC5+atfXfl5aV1b+Pjnm5u4+GYbXnu5qiOnPfzz6zA+/njpMf9/OuZtf7+6I2k//7g' +
  'g5/+/dx6iPz523Rx+PXabnL069poWe3j2mRW6NvbZEjizuNzVNzD6nFJ17PwbTrSpfRqMc+Z9mkp1Jj3eFbcuviBpePE+X6M5MP8fWzjvv59VuO5' +
  '/oBG78b9ms/34/aV9Pnr74nY8uDlfabk0tlyi9W+0Wprx63MZFa8nsddQLGSwVUwp4i6TyalgLFOH62FuYGFuJ3TlJfDoN2IcsSf4H1WxKDhdkHF' +
  'oeBxM8ak420wyKbmayjKpelqIcqk7G4cyqPrcBrfrOmQh+/W7KLi9+vnk+X78+OEuvr13Xi09vDWbYzw6c1mceniyF9W4tvCV0Db1LpQMdTOsEol' +
  'zsmmVyTHxKZuQ7+5o2Y0tKqcWSinnZROHaSSjEgZs5+TaH3BxJ9zq87Lm2OQzMqVVGrIx5BHTs/Ci19F4NWZjNLr65SG9O/rinDQ5d2CXaHVz3tO' +
  'hcS6dkdksqp2Q1OjnHI6PJaQbDAri4ZlKSGLfWM/H5F/jnt2lIalhmWTfpxzS4dzj182fGmCTyh2YnhGIHNnd0MucWd0OyNuZGwxGWphZDAUhVxk' +
  'Rx23hZiEudzDxZzu7uLWj+H38dqDu/j113ix9vDTb5fz69Roeu7l2GJc6d/ZXUXk2NhaNd/R11gq28rYZS3WwuN0S9K06m8+zaLsazHIku5pJsiF' +
  '8Wog0Jn0fIPau/R/luLC931+4sD7fWLhu/1/Tea2/YpJ8dL5n9T36fKU9ffm64jP7drgfKHey9Nyg9C5ympmwqvEY1O3n79bPa2UuFMto4mwTiSj' +
  'galfJ66OvpCauqHVj5DCoN6Ea8Og4HtPw6DgdD3FouBwMMel5W0wyaXpayjKpOtrIMqj7m0cz6Ttcx3muO2ayPPc7J7y+e7pj+D88eWBuPry4Hah' +
  '9+zZbX7x59Rsc+rg0WhY5NrKYUHd1cFZMdjQtlMl1cy1bFDQxs6Dbcu4zoBRwKnIeDy0m79vLbOPtmwpv6TDjKnLwc6SpNTHy4iD0sfDfGDPxblx' +
  'R9rDtYBv6OHDl9zw8MGO9u7ovoHK49i5dpXVx7Nsd8q1u3FxwKXLd2O5lMlwSK+FxWg1pnq/YCetc7tyQLKP0Z6ut5rTm4W1lMyNYq6Pwn9LqIy3' +
  'cjmlirNwOqSIvXhMo4W8djukhbdxOrCXsG1QybOsfoDl1smp0/Lr3Krv+fXdotT8+teYy/38zo6t/v7BhZb8/rN9f/r6p3Nj9vedaFvx85VfT+3s' +
  'jlpA6+S7bY/o1N54reS+73WQ2aznbm3Lnt5mWciW1GZMzbLRfrHVzcx3odrSwmh+19K2W2DUzapUSNnHun2Q49Pdl97p3euV2ebU6JKt3MbijorP' +
  't9iHb8Ckyn9YsJS+dUOjhrNqNJd6qGAqj2+fWCGVbJ53SJmFsZt+m4Wrj16UeqF6SIhtlmg1gGKLWih8YYZUMHtuhU4wemyCRCR2aH08HHJkdzoW' +
  'nWOCYj7En7qU0eHQ2JT08N7jjtDx4OiJsu/c7IWL7NXxg27pzviBV+bH+4RI5cH9iTzjuv6SOeG0/5Q03a/8lGzVqPWPbMya7odcxI3ngEe+guR7' +
  'OsN+4385zaPojqPXu+yIk92/8YJ03b71flrcu/V7SOK/8ZGY6tntlNrw5eiG2O/l4He57OPVapTo38pgc+LcwF9d3di5WEfZ1LFONdXRqUYo0Myh' +
  'QB/Nx6B0T8rErJlyx8GkjF7CvZh3Ur26jGdKuLaBWzy3s3xdPry7eFpgxclzU1zN0W9PWtHVbVFc3NSBgmHr4K23pfXwu7Tp+vjFrOH9+8Kgyv39' +
  'u5ao+vm4opX28MXKh/HqxMhz7OTCx2bn283SYOPWycpV3s7R21/ZvtztWdGt1+VExaDP0zS8lcfDKryNxcJRxJ7b2J/NrODVlc+42cN7zr/KslzP' +
  'wrqmR9nHub+b4t3C09nl47/NzN/Zub+g0siysHfFsquoXbudsr9js4y6xVWqfre3Qp9zrKY0mWqhmSmnaKuxdLJx1s6tuW/kyoW0a9m3Y6dkx6RL' +
  'nly4mTudWLWuYZ1WycJhnVTHtEiXUruhN5JRr5ErrWKsqWjKoMjV2+DNz9vc6tnVzMTp29K5nufZy6p749bHrXHg0NfDc97M1b5Y3MjVvU/Zw+bC' +
  'VNi/37xG1bjhzY3QqfDRgMmW6cZfvIjYt0qxfMeqPLZ7xLZzwZvX27DMrdblns65zdR8zb7BwF3Ov7S0TNnFvc+s4tvH5dnl38fbx97UwsmY0sS5' +
  'u3LKsLS4Z8Wmy9ycw5vT7X68kM/cY7GExMdLq3m3tjuydsDOjrqF4OKcwYjj1ny9j9rCZ7aSyLFXro+6okqmja2VQJ+Ko4k2mYaYfS6ThY9zKJaB' +
  'iW8otIaknHvQuM203+bZ2qrc8OPXn8vv6c6Tr+znxYiK5+G9f27h3LR1UtzZp2pA19WYYTLS0Y1ZJ9HMlmJG0MPLdqTOsOZ0icie5GxmvI/ZY020' +
  'g8hcOriPw395xLXCjKfQxrp7lNHOsWpw0c6nXFLVzaFqTN/Ny4/H597klNzo3eGRyeHT2oyl1MPPhHvDrb99X7KbtHVMo4upazqWfZ9jLYpxllwj' +
  'jWiPXR+QeJ6Qc5KDoZdekXqZhEeHcpBzNX5qhmQpgGV/XiSKf35iYZeVe2BVpaF2X0+xsnNjS7y7cWdJ0sKMn3Lo4Zuz3fTwkJ/k+veGisn49n55' +
  'sPX0dmqn8vFvX5fu72lVhOjqYkx34+RcRGTc3lc+WNXZUjhRz9FNM0LHyUkuO8DBRSo2uLpCJTOxtD8iLqusOx4po6U5GyScnTYYIpSWMxUdjI4w' +
  'EhiGhy0NGH+DKgoYeXsoCBRxcyUGEGprIgQQamQiEA12XF1NSoVSlHlUk0mvjkSbQb6dQZ86ybNBqjTKvDmxMN7OVbQs6dVOsyflzTquI97ALagf' +
  '1rQnrCjPsmC0P+jDoL1P88GBvVD0t1+7T/GvS7xR66tC0Hzn07Llv+Pi7fLg39bp+e3cyMr489O/s/XuyLeP8eXQ0Yzs3Nfmd+jX0d9l5NHZ6WTh' +
  'y9flTeHI0eZl5NXQ87Lm4MrsuuLZw96c18q/03nQtbnLYM6tzdur0rTj4qbWu+HWkNTA1cZt0cHHuFPXwb+5YeHQzNnS5uLO4d3l3cfWvdvPv8aO' +
  'zbu2t27CpLW3Z7qSxsdls4PGvk2pdrqvO5tsrKIvqmemokbElsrJ09bD28jn3M3Uu8rVxMaqlce0tp1vvJ6vmmG1isWwdrB70a9bqm/FnkSdZriP' +
  'NaVfrYwxwYq/xs7Zw8zj8+vZ0t3f6tvSyr/n2sy5luTXxbF24dHS033fzNXeX9zIztdP2cTW4mDYwNLdSty/zuB54dTN7sbk38fmwODWwdaa1Ma9' +
  'xnXOsbi/Ys2vyt230bfc5qzVvdvVkdPAz8Ft0cHCr1PYwry8duLVyd3a5uPI3djk3cHOtNjOuMGGzbmus2fGpb7Rk8GW0umEvYTR3WKydsbKSaZr' +
  't7s4tWqwu1rNosza19/O2Nfp49TRxcnby8S0m9C+t6V3zbK6wIfMtNPgmdKz2N2A0brPz3TQxMK+btfJuLls6NLF3aj06cni6vn0zNbj/PjMxcD7' +
  '+Me1pvnzwLKL8+rO2Yfv487bcOveytli5tbW6WXjz9LeUeTO0OKC5t7O7cLm4MjiuODWwNOQ08W7xW3NsLfBYc2vztuu0bfb36LTvtjNh9HBzbxm' +
  '0MHBrU7ZxL3CjePZyd3c5+TG29Xj3MDPrtfMt8CAyravtWPAoLPOcLmPw9tmsYDAy02mdLS3PZ5qp6Yus3Grs3fLptHO3tvM2Mfc3MzRtbnSwcGl' +
  'icSvs5hmu5ixpWS1h8u8brB4y7RRp22+oj6bZbOUL65jraJPypzC0dXgzsXf8ezczNTZ69/Kxbjp3MS4jubZw7V+4tTSyHfgz9LDZd7L0r9a28Xl' +
  'x23bweG/Wd/F3dGn49nc0tTi2dfEwdvOyrWUzb2/p3DIq7upbMqxzs640LrU2KTSwc/Jg9HFwrxl0cW2s07byLjLoOXdzN/d6+TK3dDn38PNrd7V' +
  'vMCK0sextGzEuaWoV7isnptHraKXjz6jmo+FN6CQhn4sspKYqHrIvK+/0t7apa275+iZl6Lm6o6EnuPjhHWF3t98Z33b3XRcbdncbFNn1tllS1vS' +
  '1WNQYNbNi4Vz4tTArrLv5tup3ffm66PN9ufsnLHz5eSVjO3h1o9w5tzKiVjg176CRdnSs303082qeCvTx6eCNd7I0qO76Nvpndjq2vCPwePO7IKU' +
  '2LzheW7Sr9iGbtDC1JKv1cvLg5rVz8N1dtTOu2pX1821aUjhzdCNu+nd6Jbh7OHnktjm1+KOqtrH14iByrHKgWW4nb56UqmNtHA+nYCqZy+Rc6Jf' +
  'JZdoml0ftYiimKHOw6Ss6N3fmJjf29iOhbHOyYV0gbyzfmdgqp59ZFKbj3xdP46Cd1IugndwSSKCbmtIHKd3kH15ya/Cn9/h1NmY3u3a5JHE7Njq' +
  'iqDp0fGFfubJ94Rj5ML7hVDjvP2HQ+K2/ow44bH/ki7irP+dUefC+LDK6dztpu7n2uaZzODN4Y+a1rneiHfSr96QdtK84JOV18Dhi4TYwOeFade+' +
  '7YFR2rzrg0jhx+ehuufe45vZ6uPeisTn3td7o9/XzG5+2NDCaWPRyb5mUMzFuVw+yMGzUy7DvaxLI8K5pFogz72pnaLa3KSrzd/lmZjE2dqPhJjK' +
  'yIdzcMS0gm9bwbyKgK7Gx4V4mMrMfWqEys12XXTJy3BZZtXGjpZ/5OCns9zx8KSl3PfzoZXD9fWdha3y8Zd7iuzpqYyB5uG7lm7f17qUVtfOuItF' +
  '0ce0gzvSw7OZX9zTv7a74uW6rNTg4LSct9bRroyHzLyogGTItLKWlce8xqCZzL/EloHLv76JX8e+tn5Gy7yvhUPWybypuN7fvafc3t27nMHX0LiQ' +
  'jsq9tYRpv6WzhFy1k8KTWK6Ewo1Bpne9fzCebbdyJKZls3Yrv43GqMPSwc2q8dvSyZrX18nEi6LLucB+dsCivH1gt5DIk16wgMmQRql0xIUzoGq9' +
  'eSWiYbZzILuEvqCo0r/Greri2sGg3OPavJO039e3hY7Z0bF7bNTLsHlfzsauc0nJwalrNcO9omEnwLmaWh3Jt6OJdNbPt6XJ3eGymsrb2qyMqdDL' +
  'poB7x7ageF7EsbOUpcW6xZmcybvDjoDHur6CXsS4tnZFy7eyiVPXyr+qw9/hvaTZ3t26mbvWz7aNiMm7sYNmvaSyiV+0k8COVK2Cv4c/pHW6ey2b' +
  'a7RwIqdmsH87wJTDq8/SxsWo8trSwZrU1ci+ipzJuLp7dMWst3tyxL+1gqnEv612icK9pWptwLydX2XCuZhvXNW4wKat5drarOvy6N6i3fPq2pnA' +
  '8OrPjp/r5MGEfePcuH1k29WwclLU0KZpR87Lm2E4ysWUXi7TwbCOht/U1qLK5t/elMbj2NqDpdjLzXV7zre9cGLKtMCHncrBwYKYzcW8cnzMxbVl' +
  'W8vErl5G2MO4jYjo2tyu4/Ps56j48+nnotXs3+Sdqt/O15SG0LrKjW/BrsKDWrWit3hDqZesbjWejKFmKbWHn4ZS0bm8tdbo3dKw9fTm4qPX8+Ls' +
  'maju2fGRfurM+I1p5cL8i1jiuv2JSuC1/ok/37D/iTnlq/+TN/HI/rTP+OT1rfP88O6g5Pnt6Ja88ubfjpjr3NaSgePW0Jly3dHKmVrYzMSYSdPI' +
  'wJ9D0sS8qD3Qw8TDgMzCwLt0xbewoFa1qKGKQaWWlHcwtIuZkVzIt7+62NnUt6y329qllZbV1ZR/b8/KhXNf1MSoqqPe28G/yefltKqy4+Kkk5Tc' +
  '2pV/dtrOkIpn3dC8v8Tk4ry2teblq52e4OCaiHzY1Ix1bNjKo5+G39zFwNrp6busu+forZaT4uOfhIHa2pJ1cNLSh2lby8mAYFbExXtZVsDAeFZQ' +
  'vLt2V0rOuImPYebVuMjZ8+rO4vb59c/f4/z4z9u6+/fK16L78czlkPjq5vKN9+Pr9W723ur6ZfTa9f1l9Nbw91L32ev7wvvt5v3g+/Hb9tf16s/r' +
  'serexOWI5cjD5oLkw+Lz1OjQ6uzG6Nff2qHm2NLKe+XWxr5e79nJ3c337djt8fv20eTu9/DF1cbs5rnHlOXTscF7483Q4M/l193nw+jd0tmf5d3B' +
  'yHfi27C6WunYss2X8+rQ5+b59dnd9vfw1crT7ebOuJ/l1MOsfeLI18zN49Dr3sjn2d3Uq+XbysKA4tm5tGDp17TCc/Try+Hd+vXS8Pf8+s7q3Pz5' +
  'yOC++fW91Z327cTjj/Ll4fGK8d3i7mjv1+b3ZOzS8vtf7c3r9FHy1+f61Pbs4fzu9uvX89nv5MvlruXYwdaF4MTH1JPgweTmy+TN496749TYy4/g' +
  '08y4beHRwa9Z7tnL2Nf37Nfm6vv0z9ri9u7GyLrp47e6i+PNsbx/4cTZ3tzky+Tvy+XT2OGj49bL1H3h1bvIXunUvd6w8+rU7+z589ri6fbt1c/F' +
  '7OPMvZTlz8K4e+PF4dzf58vw7tHr1OfrsenZ2dyL59rLzHDv2cfbhfft2O3i+/bY7vj9+9Po3/78zN+//PjE1qT58czrl/bp5vWL9eHm8Wvy3Oz4' +
  'au/V9fxd8NDu9lb02+n71fft4/319+3X79zw5c7grefYxdeF48bQ3aLixujsyOfT5uC05tfZzIri1su5auXUv7Rc8N7O2tj479jh9vv0zdHk9e3C' +
  'wbnp4ba0iuTPtLyC487Y3tHo2trYwOjfy8mU5d64um7k26ivV+vauNfH8+3S6eP48tbc3fTs0Me56uHItIrkzMGxeOLH3tnf5dLm4c7m2dbQpOPZ' +
  'w7554NeysVzr1brTr/Xq1Ons+vXU6fr9+s3f3fz8w9S2+Pe2xZzw8K24hOjlpq9v5t2ms2zm4MjNzenowb2x5uayqJXe3KSUctHQmIVZxsONekm7' +
  'uYRxQr2xfG47zbiuqLbb2MCwvOLfsZul3dugiYbUz5J4ZtTCko9i29S8vNnk5beuveTmqJii3d2ZhXzW0ot2btnKq6yh4N/HxNXo5LmrvOPjp5SY' +
  '29iWgHPZy5CHZeHRvMLR6+jBvcvx77Knt+3spJKV5uWZgHfc2Y9yZ9HQhmddych/X1HCw3pZVb69dlVRwbl6Z0/Zvq6qqe3fz8Dq9u/Zufr79tm0' +
  '2fr11a629/DOp5fy7Miig+3nw5lp6OK8kFDj3rOJP9/aqYMx5Newp3Xv49fG3vfu67jv9urupsvt4eSVm+PQ0op13cbNmo7c1MuXs+DdwYab4N22' +
  'eHLd26xuVePXq49n7+PRuNv38eSy9vnw5qrZ8+fko7nn2NmajtjCy5N1yLXEjGa8qbmATa+drXQ6o5KiayyziZyAOc+1rbzQ49unvPTt6Zqn3+jj' +
  'jpGy2taGf4PLvYN3abuvkXZjsKWQaUymnIldOZyUgVIqrYt9YyrOq62izOfWzqvz8+vcoez46uSax/Xm55Wf8d7qk4Ps1vGUbenQ9ZRa58v4lEnl' +
  'xvyXPuTC/Zk068T7u5Ty4fHL5fbw6L3z9Orjrsvr3t+hl+PJ3Jl03sDjoZbeyuadoeLP55SH487pjmjizOmJUOvM5qSC9ebhvOH689un+Prz1JHZ' +
  '9e3JgKvt5rtyi+bftHR04NuxcV3b16xkRdbSplk00c6eUSfVypt/TeHXr8DU6+ytz/Ts7KXB2ebjnK2r2tWSnn7VwqOoitTIxbfF2tDIq63a0sGa' +
  'idfRt4tp3c6ujFnr3L7D1/Xuv8r1+ve6vur69rGyv/bzqaeh8u2lo4nt6Lq5gejgwbdh4tm9rUzc1LaiOtrQrZox4dG1warq577P3e7vub7a6umx' +
  'qbPf3aiWhNnJpJVv18PIwr7bztXHtt7TzryQ3NLDrWjZ0LieTePRuLaX7ujDyOP19L699PHvta3O5+Sqnpjb0qGSdNG/tqyIyLLIt3LApsKuUrSb' +
  't6E9q5CrlC27jKqtbdK7wNbc496/zPfm4Lu51N/Ztaai1MmtlnjLsrekgMSnzrJ5vp7LqFi1lsKbQKuPtowvvYqvmEvXvL7J1OvevMP19e61st7y' +
  '7K2htu3npJOU6OCqnork3MSrf+HYwqZh3dO8pFDYz7elQtfLsqw74tG50rbs6bLP6e/xo7ne6umVoLLd3IiMgtrHnp+G3NDPvuLl38uvyuPgvJqg' +
  '39ysh3zc1Zx9ZOHUuLCw6ObHu9Ds6bmlu+flqJGZ392Yfnre0paPb+HWxcHN6OXDtrjn5rGeneHgoIl32daReGXbzqmnkOXkxMLb8PK4rcXv8KiX' +
  'lujqnIaB4OCRd2/W1oZsWc7Nf2NRxsh6XEvBw3ZWSLy8c1dDz7aTjWnm18XC2/Pr2b72+fXeueD69dqzt/bx0auc8evIpITs58Scb+fiv5NW4t22' +
  'ikTd2aqDNN3Uo4wz59fHv8bw5uO95fTm7qvR79/qmqjj1NmKftzCyoxw2crImrXc2b+Mq97ctX2D3NqscGDe2KZxUOnZxKTP9OziseX68eeq5Pbr' +
  '5qTF7ODgnJTfytCUdc+6x49rwq/BhFW2pLV4P6mYqG0wpo2dZybAmqWjn9nNq8bo6ueeuPXp5ZKgzN/biYuW0ciCfHDBtIx6aLSpknFXq6CNY0Ch' +
  'mIVXMJyPfVEmu5GSiXnaybmz3+3ly6n39uvWoNn16dyZsvLk4JWR7tzllXjq1+qVYefR7pVO5czymETjxvaZOOXC96VB7NLzyNLy6erD9PLp47Tb' +
  '7OHfpq3j0tubgdy+25p12sHinafdyuKVm9/L44533srkiVvkyOOJUvDa4bHW+O3bq/X79taW6fjxzYW+8Ou+dpbp47NxeeLdsHVn3Nisak3X06Ze' +
  'OdHNn1Qqz8mXVSTZyKqhsOTfvM/M6+q3zNfn5K3Ast3ao7KE1sWdrG7TvsXGytbG2cS82MfVtZnVx8ymdtPGwJlZ38W9uI3u48zb5Pfxy9z4+/TE' +
  '09n38r3Hr/PstLuO7+XBz4vr3tnie+fY1Nxf4dPG003az7nIPNzMssZd5tfM49jt6NPc8u3nzMrT5d/AuqTc0bSsfNnDv8OS2cbc4K/eztfant3Q' +
  'yMt32c66vFndzbG4UujYx9vV8ezS3O3z7crP2Ozmvr+u4dqxsYHZxa+9edO30t+bzqvY4nLFoMrYVriWvMpBt4yvvzfLo77cy97Pz+Hy6uHO0Obn' +
  '3ci+u93Tv66K1r65p3bQr9rJtM2m59iPx57dznG8ltC/VbiPwbNDy57Az67h0Mvn7PDoyOLt8ui+1szt5rTLo+jgqcKE4tqpwnXd1qi8XNnSo7hK' +
  '1M6fsz3RypyvNNPIq79e1c7DzKnWz7q3i9DMqaFrycSbjVLFuJCFQsa0sLmay8W6vpnQy6yoeMzJnpNfxMCRgUrDtJSRT8rAubmp08+0rZXS0qSY' +
  'c83NloRcx8KKd0nJuaOridDLu8G22NSurJLU05+Wcs3LkYRZzL+Lh03QwrK7pdnXtLeg3t6lonzb25iRadXUjoJTzcyEdkrGxn9tU8DAemZIubp1' +
  'YD60tHBdOLuteXI907WwsbDp29nD7PTr573l+evqucf36uO0ovTo162H7+XRqXPs4suiWOjgwJxG5N62mTfi3KyWLOjZu7V/8eLeyuD45++83fbg' +
  '96u97dX0nY3lxOSUbd/A3amw3c7apKzf086Ul93VxIh13NW7fljk1LqcdO/i3b3e9u/ute716eys0Ozf46Sn39DTmn7Qu8WTasGwvIxbtqWygUar' +
  'm6l3NqGRoW4rs4qcjUHOta/H0uLbqcX06uWbr97k3pCasNbRhomCyLuEgmu6r5F/YLCmjnJIp52IZzWelYFdJ62Ofmsoy6yuosvj1tWp8/Hl5KLk' +
  '8+Lqnbvw3+yXmO3Y7pN36tL0k2HozfmRTefK/JA958f+kDLnxP6RLOzE/bSH8d71xNfy6ey43+/j5qu+5tfhopLfxN6dd9y/4q6h3MflqJvfyeWd' +
  'h9/K5ZRo3srjjFPnyuGhgvHl3bHh+PLane/37teK0fDo0Huk6+HDdoPm3cKkpOTdv6eY492zknzg3KiBY93an3NN4dieml7r3rvN0fDvvtvU8Oy1' +
  '0MTo5K7Fm97Uo7h028W2za7czdTjzObW1Nay6d7RxJno4sq1fOzgw7Jt9d/g2dj67vDo0v3x7eLJ/fDp26368d/Tk/nu19WD9ujr6p/z4ejofe3c' +
  '2dpp5tnM0FTk1sHKRuvVyuW98urc7N/28dTc2/Hrxcq65d+3vIvfyrK5ed7D2d3f4MPt7sTgxuHho93K1NN93MzFxV7mzcXVpvHk4eXk9/Hd2en0' +
  '7M7Gy+njvriZ4dCxsXjcudfZyNiq6+yt05zi54DFkdPXYLqIxMlIx4a/1Xzbttvq4Ovb4OP37t/W0dzn2srAqd7MvLSB2bjPyK/UrufZptGl5NB5' +
  'x57WwVq7mMazRMeTvLhQ3bnY3NXu3d/s9fft1+Lk+PPP1cH28sbLnfTxur+o7+2vs43m5Kemct7Zoppe19OajlbQzpOETsnIinpFw8GCcT++vHxp' +
  'Pbe4dmI2sa9wXC6rqmtXM6akZ1AyoaFjSi6dnl1GMpiXWUAroJFZTCazmo+cpcK8qbSrzcadnYfKxo+IbsPAgXVXxLWIh1TMs8PExta53t2u2rnm' +
  '3o/as+zpedir9Oxn26Px9HLduPP6q+HC7vGM3cPl4W3XwNjTV9a6yctJ2Lfk2Mbev/LVt+K99smP37zxvXjZuumxX+C24bxg7dbg3dn269ra9vvz' +
  '1NDf+vPSyLz48czDnPXsysuI8ebY2nzv39/dZeza395Z6NXk4Fbp0d3fSu/W3++89Ovd7OH07NTf0u7kys+o4te8xH7dw73Ci9zD387O4Mjkwbbf' +
  'zdqxkt3QzqBt3dDAllbo1si4yPHr0bbj9fLLod3w6sOPt+Teu4OG2si1kXLSt8vEkc2s1tF2yaDZz2LHl+DRWceN6dlR1pTo5pnlyOXp5+7j3dfm' +
  '7N/UwcTi1squkNrEv6N007LbubfPqe62mcug6KdvwpnellK6ktGJPMuTy6Z538jTx9/v5M289/TpxrDb8Oe+qLLr4rWejefbw7aK5NXczoDj0NnK' +
  'YOHN3tFb3snjz07ix9vLSunS3+bJ7+jc4ebu59PT0OfeyMOi3c+8tXjYvcS8nde94svG3cHkvq3byNqritnLzptp3czCl1jp18281/Lr1rjp9u7R' +
  'pNvx6ciSserivoSP5tq5mIHi09PGk9/N1sVw28rQuFTWyMitQNXGvqU038fEx7Pq4tHU1/DszsTV7ObKsLXi2sOfhdvFvp102bnfwsfbve/Ctt7I' +
  '57Kc3c/bn4Dcz82TYefPy7qc8uTe3ef48tza9/nx1tDY9u/OxbD07MW8jvLn1NiP797o7IHu2uDoZuzX6exs6tPv7Fnsz+XoV/Ha5/TO9Ozi8fDz' +
  '6dfh1OrgztKm4NHBxn7dwszRrdzE5uG/4cjj06bezda9g9zPx6xi4M+5qFjr2s7M1/Pt28rr9O3Tutru5casr+LZuKOE3cO9t4TYtN/cu9Wo5t+J' +
  'zJ7Y0mq/lczFUr2Ov71G0aLN3NHi0N/j9O3i2dTn6t7Qw73f1MWzjNnAvrB91bHfz8nTpu/Uns2d5sd0wZXWtle8jseqRM+cyMuw5M/a4uzy59Xc' +
  '7/bqztHR8+rGxKnw5r27i+7g09Sm7Nvn4o7p197dbeTVz85U4NTBv0Lk0r3JeO3f1eTf8u3W2u7w6s3H0+jhxLag4NG6qX3dxM7EvN3D59i94sfm' +
  'zKPgzte/gd7SxbVh5NK7ul7u3dfd2PXs5uXf9ure2czv5c/QpeXcwMZ92My1u2jKvquwVb6yoqRHtauZmEGto5GRNrqdkZdDzLe8xcPd2L6+uebj' +
  'sqmQ4+Gjl3Pd3JeJX9bUjX5Qzs6GdljHxoFuSsDBemlFubp1ZTi9snRxN9W8orWs6t65yOv177u/5/rxvrfH+fO9sKL38LyuivXp3tGg8uHr4H/u' +
  '3OLVZ+jZ1slQ5NbGwEDq1cTTg/Hn1ung9vPR3+fz7cvOyunixcCZ4s+8uHffx9PRtuDL6tyv5c/l0Zjj093BduHU0bRZ6NTIvGby6sfU2vf1wsv2' +
  '9vG3vdvs6K2wqeDWpaZ/17+1un7Ps9XMe8mp0cFavqDCs0SymLSoNLyRraxI1LXE1tPm29DT9O/kz8Tf6d7KtrHf0sCrg9a9vat0z7TWuIDJrdaw' +
  'YMKlyqNIuJ+9lze/mLSVM9e2x8bO69vPzPP17crB6PbvxbbE8u2+rJrw57uqgO3g3M6a6tri03Xm1tbGWuHUyrhH39K+sTnn0r/XnO/ozuzZ9PDJ' +
  '4Nvv6sLPu+TfuMKN3cqvvHDZw8jZttvI2OSq4czX35DiztngeOHN2d9i687W4nn159Pn3/rzytf3+fG+xdvy7bK3qezlp6+F5925w4fi1c/Qdt7Q' +
  'yMRa2M26tkbUy62rNtnJqLRX5tjA2Nfv7MnS4/Hrx8HN6uPCsaLg1LumetzCxr2B2sDjz6Tgx+LGl+HU17eF4dzMqGvn28WnYfPe3MfX+e/uxN78' +
  '8/S+1f3x8ray+vDoq5n27tigke/qy5WB5uDBi3Lb1LeDW9DJq3tKycCgdkDOtMl6m9ai5X++3JHye5XYh/l1c819725ZvnbdZkauccheN6FvuVgv' +
  'l22sUiaOaqBNIYlkmVEfoVysdWa1UNaZxsJC66GawDfrnni3L+CZXakpzY9GmCW4gjWKIah3Kn4enG0hdRmSYxpuFYlcFYkvhmAupmq4eLS9jNyD' +
  'osuX7YJ4zZvxgFrNnPF+Rcye8Hs2zKDweSrNoPJ4JM6g9XkfzqD3ehvbn/aQR+3I9bfT9uTurvT77uqg4fjs45XC8ujWipnt4suTgebewaFo4tq1' +
  'n1Hd16ufQ9rVoqA33NKeqjTr3avIzvXuor7z+PaNnufy7n2EvOThcG+H3cqEkoLZzqu43NrXpai419WWkYzQ0Ip+a83Ff3ZS3cadsLDu46e87Pfx' +
  'l6Hj8++LisDp5354k+PXfod63tOot7Hd2qiuoNzampd+1taOg2PRzIJ0TdzFmLCO7OOw0+T28aG34fTwk53A7eqJipni34F8gNbUe3JxzMt4al/E' +
  'wXRkVLu8cF9KtbRtXD3HrYaSYd/LvMnZ7+bP0/b378/M4Pfwz8W69+/Lv5r268/Tj/Pl6OqN8t/k523t3N3ebOnY3N1m59PU3FjpztzutOrZ5ffH' +
  '6djc8Lbh0NHjkdfFwtZv1rnA1XrawuDq0+HK4Oe94M7W15jez8zIdt3Qv75e5c/N38Pr3Ofsxuzf4eS95tfV1ZvazcfHdta7v8Js1arg4dzUn/Dw' +
  'rNCY4uuBxJPS4WS+jb/YT8mMwuyl2LPe9unizuHp3+DL2ta61sLLxIvQs765b8+j3drIz5zv7bHOmOrkgsaW3dJkv5TLxEzJk8XQeNu04+jf69bm' +
  '7+bx393jzu/i09am7uPFzJHv4dHil+7a6fGV7tbm73Xr1OHpgOjS4Ohx59DX5mbqzeLzx+vZ6vjH6dfg7rLh0NTgjtnFxNdv2LvE4JDbxeLwzOLL' +
  '4Om34M7U2JLe0MnHcd7RvL1e5tDO28zr4OPlze7j3Ny/69/P0J/m3b/Eh+XZucV+5tXd4sjn0eXxmOXQ1uhz4dDH3Fzf0bXTTOTOweqt6dbe9Mvp' +
  '3eDmw+XV2NKi2MrJwHvUt727bNW12t7b3MDo78ngyt/gpd/Q0M193dO+vmDk0b/Tle3Y4Orm9ejh6uX26NnezfPo0NGk8ufDyZDx49Xlo/Dc6/KU' +
  '8Nnl73Xt1+LqherV4ehw6tLY7m7sz+T2ye3b5vvP69jc8bXi0NDij9rEwdZw2bzM4Kjdx+bwt+PN4ein4c/V1oTe0MrFZN7Pvr9b58/X3tTs4OXk' +
  '1Ove3dvA49bPzZXYycG/cta2xM2O1afi587Vnezzm86V3+pzwpDP3lq/i7/ZT86VzuzE3L7j9PHj0OHi3N7K1s+v08HIwITQr8K8e8+i4d7Q0Zzw' +
  '6qfOmejkfMWW2NdfwZTGx0nPlsvisOC/5vHs7tri7uPy39jhxu/jzdSf7OS/y43o4b3VgeLWu9hr2Mm32FrQvLbXUMqzttZKyq283VjLvsbciMzC' +
  'uMRpx7+nrVO/uZmYQ76wj485xrGzt5nPy7q1mtLQq6F3zcqcjVnCwI17RcOzkpRTysK1vrnS066wndLSnpl3zMuQhFnGwIN3Scy6o6mM09O5u7ja' +
  '16ynkNXTnJFszMmPf1HLvIuMTNHDtMO13Nm0u6jf3qWlhNvblpFt1NKKgVjLyoF1SsLCem1AvLp1Zjq2tnBhObOybV8+urBzc0PRtai0pOTazsXp' +
  '8urYv+D16Ne3vvLo0K+b7+XHqYTs5MKocuniu6JY5+Gvm0fk4KOVOOLfmZAu5tutvoHr29bYw+zh483C6drhuqXeztaqe9a9w6Bg1L3AsLHX0sGq' +
  'rd3Vu5mY29WzinPa1Kp/WODTqp956t3OwN/w7dy68e7n2bHO5dvQqZ3XysGhesi0t55nu6qxmFqyo6eLQ6mdm38yoZaPdCaukIydUMesqM/V2Nak' +
  '0fXe3JbA19fUiqqiysZ/lne9sX+SZrOoj5FgraOMgUqnn4VyNqGbfGUoq5Z5dy/FqaivyNvTyK7y6uLQpN3r39Obtujc1JST59jZkXnl1eOQY+TS' +
  '6IxM48/qiDvizeyFL+HK7Ykr5MfruJDn1ubOvebe38S+49bZtZ3ay9Wpd9a51KNi1bzcsa7azNuqot/Q2Z+N3tDXlm3dztWOVOPN06uG6+DUuc7v' +
  '7tCl4u7oy5O+6OPBhJ3l3rJ+gePawLyn4dbM3ong1MDTZ9zTssRM2tOktDrc0aPCa+PSwuHM5uLF3Mnk3r3JsNrTtLWF0MOppGfOsrrIrNK41uS9' +
  '3MfT3qvc0MfNhdvUt7xl4NWuuV/q1M7c2PLn2u7V9uzS5Mj06sjVpPHpvMiL7+a4zoDt4NPnhuvd0OZn59vD1k/j2rrHQuHXs7875NTB4K3n3s3q' +
  'tubhxdyx4Ni6y4/Uy7C7bdG7rL1l1b/L3tDcy9Tuud7Pyd2Y3NG9yXTb0bG8WuLPu9So6eDR5sbr6MzdxObfwM2j2dOyvXnRwai0Y8ywxNqryKfT' +
  '7YnDoMrfZLmbu9BLtJWrxzy/ka7citG1x+7j3dXE4+Lc0rrNvtPKr7aNy7ulpmzHqsDEp8Wi392ZxJ/Z03K9nMzFVbaavLU/wJezvlzUs83f2OTW' +
  '0Ozx69/F39Tp3rrSq+ffr8aP5d2qxYLj3LHKb+LasMpc39etyE3c1KnIQtrRp8s+4dCy5afl5azlyOTlntK63duQupTSzoWmbdG/mbSA1M65ys3Y' +
  '2a+2o9XUnp14zMyPiVrHwIR/SMq6qqyR0dG2tazW1aihhtHRl4tkyMiJeU/IuouNT87EtLu619ixsabZ2KGaftLSkodfy8eFeE3LvZ6ngNLPt8O0' +
  '29eusJnY15+bfNTTkYlezs6GfVDHyH10RsDAeG4+u7pzaUe4tnFlRLa1b2ZCyLGQm3Ldx8jK3e7k3sb39+jgv9716Nu4tPPo0LCY8OfFrIPt5r+n' +
  'aOvms51O6OSnlT3l456OMeTgm5w+6tvHzLTt4+LKxezg47qz5NXbqYvXx8qbZ9O4waVr08rLssjZ08eis9nUvpKP2NSzhGvZ06mHWeXTv7rE7ujX' +
  'vtTw69m2yuvg0q2l3tTFpH3QwLedYsKysZpat6qoj0euo5yDNaWdj3gopZWFdiK9mJ28odPGq97p3+Cf0uHe25G7u9LQg6OIxb56lGm4rImVYq6j' +
  'kIxSp52Nej2gmIZrLJ6UfWIiupOWmHzVwsS64Onh07Du8eHVpc7u4NOdpuvez5aJ59vMnXPk2cilX+HXw6tO3tS/sEPb0b2uOdzOu7VA5tu5wsnq' +
  '7aet8unqlZTT4N+HgKDVzn1zdtPAoaGs1da3tdjb2qmiqNbVmIx8zcuKeV7KvYaCU8++sbel1tawsqHY1qGdeNLRkYhcycWDd0jKuJaaa9HNtrzJ' +
  '2dqsq6bX2JyUetDQjYBby8KCe0vOvqi0oNfVtr223typp5fZ2ZqRddLQjYFaycaDdVLAv3xsS7q3d2ZFtbRxY1Kzs25gSbeybGNHzrCdrJzjzc/X' +
  '5/Hm2ern+OvV4M/37s/YpfftxdKQ9ujW6Zr04ev0jfPd5vJy8Nrk84vt2OLzce3V2PZu79Pn+8zv3uf90e3a3PS249LP6Y/cxb/icdu+zOyy38nm' +
  '9rvm0ODrquTT1NqG4dTKyWfi07/FX+rU1+PZ7+Tl7OHu4t3fyeXYz9Cb2cvAw3XWt8DWjdSn4OvH1J3n9ZTNl9vtb8GSy+NYv4y9207PmM3uyd3C' +
  '4PPy5NLf493gzNbQr9TByMCD0K/Cv3zQouHg0dKc8PCoz5rp5HzGmNjYXsKUxsxJ0ZfP5rjiwejz7u/b5O/j8d/a4cPv4s/VnO7jws6K8N/e57nw' +
  '2u/zmu/Y6Ot+7dbn6ZDr1eXodevR3PCC7dHn98rt3OX7zerX2vCw387O44jZwMDXa9m80eq/3srn9bvl0ODoqOPU09OD4NXGwWTi073BZOnV1uDW' +
  '7eXh4OLt49baxenfxs+l5d21wIvm2b7Un+bU3+qo59Lc8oHk0c7pY+DRv91O39Gy2kzmzsztwenc3+u86Nvc27Lh0tHJjdbGwrtt07XAxoXZvd/j' +
  '3uLK5OfI49LZ2Z/i18jIeeLat71k69jK28Hz6OTi2fnw6NfS+u/jyrj479e7mPLtyq2I6uW7n3zf17CUZtHJp4pOxL2ggkS7spp8N7ynr3tewpXY' +
  'ga3Ffex+hMFl6XditU3ab0mkOsVnNpQstF4phyGnVyF9GZxQGnQTkksVcA6KShOJDJVuTJ8Ny5CjrQvmmoatCeKXaKUH1ZBTmQXBhz+KBK18MXwD' +
  'nHImcgKQaB5pAoZgF2MBfVgSiyJ6XCewbrlyy8qc3Xe+2anudYvYqPRyatWl9G9O06TzbD7SpPJrMNGk9Gop06f2bCfVqvhyJtuq/I9I6bb8yND0' +
  '2/jh9Prt89zn/PLu1cX+9enPqv3z49OV/O3p6ZL55+fzcvfl4PRw9OHj+YTy3tz2avPZ2fuj9+TZ/dP38ND+2vTqxfa86dq38JHjxK/vfOG/0ffU' +
  '587g+8bt29frquziy9yD6+LAzGPv38DZl/Xm3O3g9/Pb5PT17tDW1erfw8eh4cq4woHgwcvhzuXN4fDI7NnZ7K3r4Mrehunhutdn6t+133fx3s3v' +
  'yPTuz+vy8uzI2tfq38LKq+DKvLyE3bnO0qzgu+fp0OnK6ea16tjd05Lp39LBdevfyL5q9N7X39D679nv9Pz31Onr/vrO37z9+cbUo/j3wMiN8Oq3' +
  'vnTj26yyXdXPoqlOycOXoEDIuJOdPd6+wczQ79/LyfT377qy7fjyqqHD8u2ck6vo5ZGJk93XiX9z0cuCdmHGw3tvU727dWhGvLJxZjjSsaSsrunZ' +
  'xcPr9Oy3r/X69Kid1vXwmo2w7OqPgJDi3Yd2dtXRgG5ky8h5aVnCwHNjTLy5bV09zrCVm4Tm18TD4vPsubL4+fWpnuD28pyPqe7tkYON5OKKe3bY' +
  '1YR0Y83LfW1ZxMN4aE+9vHVlQsezj5Fh38TIxtnw4uTH9vfx8MLp+/Puvr/78+S5pvjx1riK9e/Ot3Py7cauWe/pv6dF7Oe6oTfr5LepN/Hf2NW0' +
  '+Ojs19366vbI0fXg9ret6s7rqILjvtypdOLL2rvF6N/RrrXt6sWglO3rupRv7em0kl7z5NDBy/ns6Mfl/PHywN/36eu5vuvY37CS3sPQqXPTucyw' +
  'cMq1xaRaw7C9lka7qrWKN7iirIMtyaC1wJzdy77g5+rlstr26eSiwtPg1pWqnNTBjJ14y7iZr3rGuKCpbMK3mpVOvLORgzq2rYd2K8anmZxs3sfK' +
  'v9zv5OK39/fr7bDe+Of0qbf24fmlk/Tc/Kp289j+ql7y1v6mS/HT/6I88NH/oDHvzf+yUfLN+9m+8+Py2+/z5OzO2+3a6MCw5MjltYjhtuW4e+DG' +
  '6L695tPns6ro1+eqiOjX5qJn6NXkoFvw1+LCv/fr3Lrp+/XXpuH689CVwfXuw4ae8+q5no3z59TPtPPm2uSM8+rO23Dy7b7RVvHurcRH9Oq64qn3' +
  '7NHx1vbxzuXX8enI0bnl2cHBit/Du7p23rne3dniwu/jyOfO6Nem59jaxojm3sq5be/cydCR9+je6OH79Nz0+P341+ri/PjO3rX79sTXnfryzeuY' +
  '+ezf9YX46drxbPfn3fii9ePg/IX04Nj4e/be3PvS+O7V/fT27Mr32+7hvfGt5c+w7IfiwcD1quTJ4PrK69Xd8LHr3dPcjengyMtr69+/xGHz3tni' +
  '2fjv5+L19/Dd0+Lw5s3EuuTUv7eN4MG+yovgwt3l1ObO3vG96NfT5Zrn3sPbdufft9Zh7tvJ68r06Nz12/Tt1+nV7+XP1rXi08XDit28wMB63bbg' +
  '4NbkxPDqxOrU6Niq6t7bxIXp4cy3a/Dey9ag+O3Z69n79tfp7P370eDY/vvJ16r7+sPLm/TyuMN+5+CwuGXY0qeuUszFn6NGxLuXmTrNs7G3g9nG' +
  '2dHh49zOvcDh27yok9rTrJdy0Mqei2DHw5SAVr+7i3hNuLWDcEmxr31pQaqqdmI5u6OPiVzPtMi/2N3Wx7TI3ti3oJrY0qePedLHmYNh1cC5sKXe' +
  '0drEt+Xgy7Ce4t24nHfZ06eNYNXInpBX3cTMyMHm4NPFy+nlwq+m5OGxnInc16OOc9HOl4NhyMSPeVTAvYhySrq4gmxOtbN+ZkC5r4J3P9Gvs7mq' +
  '6dXa0Ov06+3M5/rx78jN/PTowqb689y8kfjw1L559e7JuF7y68CyTO7puqw/7Oa1pjPu4cTLgPTg4uXJ+unx2+H45fjIxvDY87eU58bjrHTkxNy/' +
  'pufb17qx7ebPrJvt6cafd+zpvpVb8ObArX335uDJ4Pvx8ML4+u3uvNzx4eW0rOTN16qE2cDLrXbQvsWrbMq6u51QwrSykT66rKmIMb+jpqFL1LjA' +
  '0dTn3M/a9fHm1cze7+DdvLTq0uewiuXI66524sXvsWvhwvKpU9+/9aJA3r32nDPguvqdOO3C+sHL9uH0v/P78O616/3z5qvN+/Hboqn58NCgiPfx' +
  'yq909vDEqFn08LefRfHvrZg27+2ili7v563Hl/TvtOTM9feq3Ovy8aLGyebgnLKU38uZqnbdyrLBv+TevLq67em3qqDt67Keeu3rqpdc8OiqsID2' +
  '86zA1/n5nq/29vWVntns54+RoePQi41+4se9ucnl4M+52+nkvqeu49+ulofZ1J+Jb9jJpKVu4MrT07jn4s7FtObhva6P4NutnG/Z056NYtDOk4Jf' +
  'yMWLeVbAvIVySbq3gG1HtbN7aj/Bro2MWNq9wcPE7d/dxfH27+e/6vvv5rm9+fDgsKH07dOlierixJts3dK3kFbNxK6HSMG2p308vaygeDTHnsyE' +
  'lNKJ5orE23DzhpLXWfl+b8xG8XZUvTfebECsK8xjNJ4gwF0qlRm4WCKOE7JTG5cPr1keu0vFnafan+K96u3Q8bnw7tPtstDlx+KqndSv0qB3v4zA' +
  'k1yqarKFRplQp3g2jT2ebSqJLphlI6tDrJx/yI/WyuDcxM66xt/SvKae2s6rlHzTyZ6HZ8vElH1Yw72NdU69t4dtSLe0gWlFs7B9ZTjAq4iQTdm+' +
  'u8jU7N/O5PX278zp6fv3xeS9/Pm+3qP99r3okfzw2vSZ/e3a+Xz87Nf8jPro4f6H+eXa+Wv54dr8vvrt1/7c+vPM+dn06sD1tejYsvGK48Kt8X/i' +
  'wc741ejQ2/jC7N3S5aPs48fTfuvivsVk8N/G3LT269/n3fj12tnl9O7NyMTo3b+7leHIt7h84MLT3Nfnz+Hux+3c2Oas7eTJ3Ybs5bvWZ+7hueaR' +
  '8uPP89D08M/q8vLsxtfT6N3AxKLgx7q3fd+71dfL5Mbr58rs1OjYsuze2cSM6uLKtmru4MPBbPbi2eHc+/Hc8Pf9+Njr5P74z9+4/fjD2J/79MLr' +
  'lPns3fWR+Oja+nH35tn9k/Ti4P6F89/Y9m313Nz6y/jt2f3u9/DO+ODx5sDwt+XTseiP4cCx6ozhwtb01+jQ3vPA69vT4J7p4MnPeungv8Jh8d7O' +
  '3cr47+Pj6Pz33tPm+vTSwb/y7Mi0m+fhv6eA29O0mm7NxKmRV7+3oIpLtKyZhEGypJJ+N8adu7So1sHey+rk2c+3wuLZu6KU29KqkXTSzJyFYcnD' +
  'k3tSwLuMdEq5tYVuSbSzf2pHsq96ZznHq5GjceHLv9Ld8ObO6Pf4887d5/v3y9G5+vrGxqj19by+h+vlsbVs3deoq1rQy5+fTMbBlZhAvrqPjju3' +
  's4eGNbGugHs0rKt6cTKopnRoLqOhcGAqoJ9tWSicnWhUJpiYY08ik5JgSiCOjl1FIIqJWkAbhYVWPBiAgFI4G3x8TjQZd3dKMRhxcUYuFmxsQioT' +
  'ZmU/KBFgYDwlDlpaOSINVVQ2HwtPTjMbCktKMRgJRkUuFQdCQSsRBj49KQ8FOjkmCwQ2NSMJAzIxIQYDLy4fBQIsKx0EAjgoIA4EWiNLOymQJ5F4' +
  'fbYxyZ/gzCzlqbfOJfKmjMcf7qBvuhnellWpE8mJQpkOuHszjQusbimECKRjIX4Gn1oanhWkXzW6KdJ0z80p6Xaw0yL0c4LNHfRsZMEX5WRLsBHT' +
  'WzihDcJSK5UKt0oijQevQxqHBqs+F54Gqls5uAzVic/JDOueu88K9aGTxwjtnna5Bt2WWqgEyotImAO5fDeLA6pvK4ECoGQjeQGZWx2BBJJYGqVG' +
  'rXOQwYXXit/Vn+uNp9qn9Ix82qb6imTZpfyITdmo/YY92an+hjLbq/6HKt6t/4sn4K7/lDLqrP/BmvXR+9fn+un1z/n98PHJ3P727MW6/vXqxZz/' +
  '8PXjm//q+vGM/+j883j/5/v5lv/m+fx+/uXy/n3+5O3+pv3t6P/o+uri/dDz4N35puzN2fuL6cHf/avqw+/+vfDN8P2l9Nzn8or36d7ndPrv1uVv' +
  '/e3g8sj+9t/y7f741+jl+vTL4bzy58Tel+/T1u217svr9tX0zPX7u/bX8vWe9+Lu6X/36ublb/rm5vKy++rs8r767OftyPXn4eSp7Nrc2Ybpx+Db' +
  'f+i88O3T7b/49sDxy/TxoPPZ7uuE9uXm4m775ebxqv3r8/i9/vXv9Of+9+Tu0f/72uew/vjT4Zf69M7Ykvjo0NOB9ejPzpHz68nFifLrwLt38eu1' +
  's27z6quos/P1oZyx9PGZkov18JGIgPX4in6K9PWGdXPy64FsXuvvemOO6Ol0Wm3j5G9TaN/gaUxa2t9iRFfT1Vo9QMXBUzYvtK5LMCeinUQqHJGM' +
  'PSQVgnw2HhB0bzAYDWhlKxIKXlslDghVUyAKB05MHAgGRkQYBgQ/PRUFAzg2EQMCMS8NAwEsKgoCASclCAEBIiEGAQEfHQQBABsZAwEAFxYDAAAU' +
  'EgIAABEQAQAADwwBAAALCQEAAAgHAQAABgUAAAAFBAAAAAQDAAAAAwIAAAACAgAAAAIBAAAAAQEAAAABAQAAAAEBAAAAAQAAAAAAAAAAAAAAAAAA' +
  'AAAAAAA=';

// One compact typed-array allocation for the whole score; no per-frame base64 decoding, FFT or media fetch.
const FEATURES = Uint8Array.from(atob(ENCODED), (byte) => byte.charCodeAt(0));

// Integrate the quantized energy once. Speed stays between .55 and1 weighted second/second; a seek reconstructs the
// identical orbit phase immediately. This is derived from the small payload, not another encoded channel.
const MOTION = new Float32Array(MENU_SCORE_FEATURE_INFO.frames);
for (let i = 1; i < MOTION.length; i++) {
  const previousSpeed = 0.55 + 0.45 * FEATURES[(i - 1) * 5]! / 255;
  const speed = 0.55 + 0.45 * FEATURES[i * 5]! / 255;
  MOTION[i] = MOTION[i - 1]! + (previousSpeed + speed) / (2 * MENU_SCORE_FEATURE_INFO.rate);
}
/** Divide motion by this and use integer turns to make orbital phase continuous across the native song loop. */
export const MENU_SCORE_MOTION_LENGTH = MOTION[MOTION.length - 1]!;

function readChannel(frame: number, next: number, fraction: number, channel: number): number {
  const a = FEATURES[frame * 5 + channel]!;
  return (a + (FEATURES[next * 5 + channel]! - a) * fraction) / 255;
}

/** Source-time choreography, not a calibrated physical latency model. Pass a target to sample without allocations. */
export function sampleMenuScore(time: number, target?: MenuScoreSample): MenuScoreSample {
  const t = Number.isFinite(time) ? Math.max(0, Math.min(MENU_SCORE_FEATURE_INFO.duration, time)) : 0;
  const position = t * MENU_SCORE_FEATURE_INFO.rate;
  const frame = Math.min(MENU_SCORE_FEATURE_INFO.frames - 1, Math.floor(position));
  const next = Math.min(MENU_SCORE_FEATURE_INFO.frames - 1, frame + 1);
  const fraction = position - frame;
  const out = target ?? { energy: 0, bass: 0, mid: 0, treble: 0, onset: 0, motion: 0 };
  out.energy = readChannel(frame, next, fraction, 0);
  out.bass = readChannel(frame, next, fraction, 1);
  out.mid = readChannel(frame, next, fraction, 2);
  out.treble = readChannel(frame, next, fraction, 3);
  out.onset = readChannel(frame, next, fraction, 4);
  out.motion = MOTION[frame]! + (MOTION[next]! - MOTION[frame]!) * fraction;
  return out;
}
