import {NativeGameAIHelperAdminType} from '../../src/gothic3/native-game-ai-helper-admin-type';
import {NativeGameAIHelperAdminClassName} from '../../src/gothic3/native-game-ai-helper-admin-class-name';
import {NativeGameLabelClassName} from '../../src/gothic3/native-game-label-class-name';
import {NativeGameLabelType} from '../../src/gothic3/native-game-label-type';
import {expect,it,vi} from 'vitest';
// These run the original instructions in the emulator: about 4â€“5 s each here, so the 5 s default fails under CI load.
vi.setConfig({ testTimeout: 30_000 });
import {createBrowserGameCrtPlatform} from '../../src/gothic3/browser-game-crt-platform';
import {browserGameProcessInputs} from '../../src/gothic3/browser-game-process-inputs';
import {browserGameStartupIoInputs} from '../../src/gothic3/browser-game-startup-io-inputs';
import {browserGameStandardIoInputs} from '../../src/gothic3/browser-game-standard-io-inputs';
import {browserGameArgvNlsInputs} from '../../src/gothic3/browser-game-argv-nls-inputs';
import {nativeVirtualX86CpuSelection} from '../../src/gothic3/native-x86-thread-stack-profile';
import {NativeSharedStaticTls} from '../../src/gothic3/native-shared-static-tls';
import {NativeSharedCrtOwner} from '../../src/gothic3/native-shared-crt';
import {createBrowserGameCrtStartup} from '../../src/gothic3/browser-game-crt-startup';
import {NativeMemoryAdmin,nativeNpcHeapExtension,nativeSceneStartupHeapExtension,nativeClassNameHeapExtension,nativePropertyHeapExtension} from '../../src/gothic3/native-memory-admin';
import {NativeSharedMessageDebug} from '../../src/gothic3/native-shared-message-debug';
import {NativeSharedGuidNull} from '../../src/gothic3/native-shared-guid-null';
import {NativeHeapObjectViews} from '../../src/gothic3/native-heap-views';
import {NativeSharedCrtSecurityCookie} from '../../src/gothic3/native-shared-crt-security-cookie';
import {createBrowserNpcRuntimeAdminOwner} from '../../src/gothic3/native-runtime-platform';
import {NativeGameArenaStatusProperty} from '../../src/gothic3/native-game-arena-status-property';
import {NativeGameArenaEnum} from '../../src/gothic3/native-game-arena-enum';
import {NativeGameFreePointType} from '../../src/gothic3/native-game-freepoint-type';
import {NativeGameFreePointClassName} from '../../src/gothic3/native-game-freepoint-class-name';
import {NativeGameExitTable} from '../../src/gothic3/native-game-crt-exit-table';

function platformFixture(){
 return createBrowserGameCrtPlatform({processInputs:browserGameProcessInputs,
  threadStack:{reservationBytes:4096,pageAlignment:'virtual-page-4096',cpu:nativeVirtualX86CpuSelection},
  startupIo:browserGameStartupIoInputs,standardIo:browserGameStandardIoInputs,argvNls:browserGameArgvNlsInputs,
  setEnvp:{physicalGameHeapCapacity:'round-eight-unknown-padding',heapFree:{outcome:'success'}}});
}
it('retains SharedBase CRT prerequisites on the actual browser platform',()=>{
 const platform=platformFixture();
 const tls=NativeSharedStaticTls.forPlatform(platform);
 if(!tls.known)throw new Error(tls.reason);
 expect(tls.value.loadSharedBase().known).toBe(true);
 const guid=NativeSharedGuidNull.forPlatform(platform);if(!guid.known)throw new Error(guid.reason);
 expect(guid.value.adoptReturnedCrtExecution().known).toBe(false);
 const owner=NativeSharedCrtOwner.forPlatform(platform),result=owner.processAttach();
 expect(result).toEqual({known:true,value:1});
 expect(owner.snapshot().ptdInstalled).toBe(true);
 expect(owner.snapshot().ptdInitialized).toBe(true);
 expect(guid.value.adoptReturnedCrtExecution()).toEqual({known:true,value:undefined});
 const payload=guid.value.guidNullPayload();if(!payload.known)throw new Error(payload.reason);
 expect(payload.value).toBe(owner.snapshot().initializerImages['101ab150']);
 expect(guid.value.adoptReturnedCrtExecution().known).toBe(false);
 expect(guid.value.invokeInitializer().known).toBe(false);
 expect(guid.value.snapshot().executionOrigin).toBe('returned-crt');
 const runtime=createBrowserNpcRuntimeAdminOwner(platform),memory=runtime.memory;
 const game=createBrowserGameCrtStartup(platform,memory);
 expect(game.known).toBe(true);
 if(!game.known)throw new Error(game.reason);
 expect(game.value.attachResult,game.value.attachProgress.setEnvpProgress?.currentPC).toEqual({known:false,
  reason:'crtAttach204677e4: Unowned Unowned original environment CALL at204b26cc: CALL dword ptr [0x207d890c]'});
 const executed=new Set(game.value.attachProgress.setEnvpProgress!.effects.map(effect=>effect.pc));
 for(const pc of ['204b26c0','204b26c3','204b26c8'])expect(executed.has(pc)).toBe(true);
 expect(executed.has('204b26cc')).toBe(false);
 expect(executed.has('204b270c')).toBe(false);
 const aiPropertyId=game.value.crt.imageStorage('aiHelperPropertyId');
 expect(aiPropertyId.bytes.length).toBe(20);
 expect([...aiPropertyId.bytes]).toEqual(Array(20).fill(0));
 expect([...aiPropertyId.knownMask]).toEqual(Array(20).fill(255));
 expect(game.value.crt.imageStorage('aiHelperPropertyIdGuidLiteral').bytes.length).toBe(39);

 for(const pc of ['20072719','20072383','200730dd','204b217a','204b23ca','2007479a','20074403','2007510d','204b241a','2007679e','200763f3','2007710d','204b26aa'])expect(executed.has(pc)).toBe(true);
 const aiWrapper=game.value.crt.imageStorage('aiHelperAdminWrapper');
 const aiVtable=aiWrapper.pointer<{fields:NativeHeapObjectViews;offset:number}>(0).get()!;
 expect(aiVtable.fields).toBe(game.value.crt.imageStorage('aiHelperAdminWrapperVtable'));expect(aiVtable.offset).toBe(0);
 expect([4,8].map(offset=>aiWrapper.readUnsigned(offset))).toEqual([11,0]);
 expect([...aiWrapper.knownMask.subarray(4,12)]).toEqual(Array(8).fill(255));
 expect(aiWrapper).not.toBe(game.value.crt.imageStorage('labelWrapper'));
 expect(executed.has('20077051')).toBe(true);
 expect(executed.has('204b2665')).toBe(true);expect(executed.has('204b2675')).toBe(true);
 const aiType=NativeGameAIHelperAdminType.forCrt(game.value.crt,memory);
 expect(aiType.snapshot()).toMatchObject({entered:true,baseConstructed:true,factoryConstructed:true,registered:true,getterReturned:true});
 expect(aiType.storage.readUnsigned(60)).toBe(1);expect(aiType.fields.readUnsigned(0)).toBe(0x2065a68c);
 expect(aiType.base.readUnsigned(20,1)&1).toBe(1);
 const aiTypePointer=aiWrapper.pointer<{fields:NativeHeapObjectViews;offset:number}>(12).get()!;
 expect(aiTypePointer.fields).toBe(aiType.storage);expect(aiTypePointer.offset).toBe(0);
 expect(aiType.get()).toEqual({known:true,value:aiType.fields});
 const aiState=aiType.snapshot();expect(aiState.callback!.entry).toBe('20549d10');
 expect(aiState.slot!.pointer(0).get()).toBe(aiState.wrapper);
 expect(new NativeHeapObjectViews(aiState.wrapper!,0,4).pointer(0).get()).toBe(aiType.fields);
 const aiFactoryRoot=aiType.fields.pointer<{fields:NativeHeapObjectViews;offset:number}>(28).get()!;
 expect(aiFactoryRoot.offset).toBe(0);expect([32,36].map(offset=>aiType.fields.readUnsigned(offset))).toEqual([1,9]);
 const aiRootWrapper=aiFactoryRoot.fields.pointer<{fields:NativeHeapObjectViews;offset:number}>(0).get()!;
 expect(aiRootWrapper.fields).toBe(aiWrapper);expect(aiRootWrapper.offset).toBe(0);
 const aiNameOwner=NativeGameAIHelperAdminClassName.forCrt(game.value.crt,memory),aiName=aiNameOwner.get();
 expect(aiName.known).toBe(true);if(!aiName.known)throw new Error(aiName.reason);
 expect(aiName.value.text()).toEqual({known:true,value:'eCAIHelperAdmin'});
 expect(aiNameOwner.snapshot().callback!.entry).toBe('20029c94');expect(aiNameOwner.get()).toEqual(aiName);
 const labelType=NativeGameLabelType.forCrt(game.value.crt,memory);
 expect(labelType.snapshot()).toMatchObject({entered:true,baseConstructed:true,factoryConstructed:true,getterReturned:true,registered:true});
 expect(labelType.storage.maskedWord(60,4).value&1).toBe(1);
 expect(labelType.fields.readUnsigned(0)).toBe(0x2065a384);
 expect(labelType.base.readUnsigned(20,1)&1).toBe(1);
 expect([12,16].map(offset=>labelType.base.readUnsigned(offset))).toEqual([0,0]);
 const labelRegistered=labelType.snapshot();
 expect(labelRegistered.callback!.entry).toBe('20549c20');
 expect(new NativeHeapObjectViews(labelRegistered.wrapper!,0,4).pointer(0).get()).toBe(labelType.fields);
 expect(labelRegistered.slot!.pointer(0).get()).toBe(labelRegistered.wrapper);
 const labelNameOwner=NativeGameLabelClassName.forCrt(game.value.crt,memory);
 const labelName=labelNameOwner.get();expect(labelName.known).toBe(true);
 if(!labelName.known)throw new Error(labelName.reason);
 expect(labelName.value.text()).toEqual({known:true,value:'gCAIHelper_Label_PS'});
 expect(labelNameOwner.fields.readUnsigned(8)).toBe(3);
 expect(labelNameOwner.snapshot().callback!.entry).toBe('20007702');
 expect(labelNameOwner.get()).toEqual(labelName);
 expect(labelType.fields.readUnsigned(24)).toBe(0x100ea9c4);
 const labelFactoryRoot=labelType.fields.pointer<{fields:NativeHeapObjectViews;offset:number}>(28).get()!;
 expect(labelFactoryRoot).not.toBeNull();expect(labelFactoryRoot.offset).toBe(0);
 expect([32,36].map(offset=>labelType.fields.readUnsigned(offset))).toEqual([1,9]);
 const labelFactoryWrapper=labelFactoryRoot.fields.pointer<{fields:NativeHeapObjectViews;offset:number}>(0).get()!;
 expect(labelFactoryWrapper.fields).toBe(game.value.crt.imageStorage('labelWrapper'));expect(labelFactoryWrapper.offset).toBe(0);

 expect(labelType.fields.readUnsigned(40,2)).toBe(1);
 expect(labelType.fields.pointer(44).get()).toBe(labelNameOwner.fields.pointer(0).get());
 const labelBefore=[...labelType.storage.bytes];
 expect(labelType.get()).toEqual({known:true,value:labelType.fields});
 expect([...labelType.storage.bytes]).toEqual(labelBefore);
 expect(labelType.storage).not.toBe(game.value.crt.imageStorage('freePointTypeAndGuard'));
 const labelWrapper=game.value.crt.imageStorage('labelWrapper');
 const labelVtable=labelWrapper.pointer<{fields:NativeHeapObjectViews;offset:number}>(0).get()!;
 expect(labelVtable.fields).toBe(game.value.crt.imageStorage('labelWrapperVtable'));
 expect(labelVtable.offset).toBe(0);
 expect([4,8].map(offset=>labelWrapper.readUnsigned(offset))).toEqual([11,0]);
 const labelPointer=labelWrapper.pointer<{fields:NativeHeapObjectViews;offset:number}>(12).get()!;
 expect(labelPointer.fields).toBe(labelType.storage);expect(labelPointer.offset).toBe(0);
 expect([...labelWrapper.knownMask.subarray(4,12)]).toEqual(Array(8).fill(255));
 expect(labelWrapper).not.toBe(game.value.crt.imageStorage('freePointWrapper'));
 expect(executed.has('204b23d5')).toBe(true);
 expect(executed.has('204b23e5')).toBe(true);
 const freePoint=game.value.crt.imageStorage('freePointWrapper');
 const freePointVtable=freePoint.pointer<{fields:NativeHeapObjectViews;offset:number}>(0).get()!;
 expect(freePointVtable.fields).toBe(game.value.crt.imageStorage('freePointWrapperVtable'));
 expect(freePointVtable.offset).toBe(0);
 expect([4,8].map(offset=>freePoint.readUnsigned(offset))).toEqual([11,0]);
 expect([...freePoint.knownMask.subarray(4,12)]).toEqual(Array(8).fill(255));
 const freePointTypePointer=freePoint.pointer<{fields:NativeHeapObjectViews;offset:number}>(12).get()!;
 expect(freePointTypePointer.fields).toBe(game.value.crt.imageStorage('freePointTypeAndGuard'));
 expect(freePointTypePointer.offset).toBe(0);
 expect(game.value.crt.imageStorage('arenaRootWrapper')).not.toBe(freePoint);
 const freePointType=NativeGameFreePointType.forCrt(game.value.crt,memory);
 expect(freePointType.storage.readUnsigned(60)).toBe(1);
 expect(freePointType.fields.readUnsigned(0)).toBe(0x20659f94);
 expect(freePointType.base.pointer(8).get()).toBeNull();
 expect([12,16].map(offset=>freePointType.base.readUnsigned(offset))).toEqual([0,0]);
 expect(freePointType.base.readUnsigned(20,1)&1).toBe(1);
 const freePointState=freePointType.snapshot();
 expect(freePointState).toMatchObject({entered:true,baseConstructed:true,factoryConstructed:true,registered:true,getterReturned:true});
 expect(freePointState.trace).toEqual(['200732ed.type.guard1','200732f9.SharedBase.propertyTypeBase.return','200732ff.type.vtable20659f94','20073309.className.return','20073314.namedFactory.return','2007331f.propertySingleton.return','20073327.RegisterTemplate.return1','20073332.cleanup.registered-result0','2007333f.typeGetter.return']);
 expect(freePointState.slot!.pointer(0).get()).toBe(freePointState.wrapper);
 expect(new NativeHeapObjectViews(freePointState.wrapper!,0,4).pointer(0).get()).toBe(freePointType.fields);
 expect(freePointState.callback).toMatchObject({module:'Game',label:'freePointTypeCleanup',entry:'20549b30'});
 const freePointName=NativeGameFreePointClassName.forCrt(game.value.crt,memory),name=freePointName.get();
 if(!name.known)throw new Error(name.reason);
 expect(name.value.text()).toEqual({known:true,value:'gCAIHelper_FreePoint_PS'});
 expect(freePointName.fields.readUnsigned(8)).toBe(3);
 expect(freePointName.fields.pointer(4).get()).toBeNull();
 expect(freePointName.snapshot().callback).toMatchObject({module:'Game',label:'gameClass204b23c0Destructor',entry:'2002ec53'});
 expect(freePointName.get()).toEqual(name);
 const classResult=freePointName.input.pointer<{fields:NativeHeapObjectViews;offset:number}>(0).get()!;
 expect(classResult.fields).toBe(freePointName.fields);expect(classResult.offset).toBe(0);
 const factoryRoot=freePointType.fields.pointer<{fields:NativeHeapObjectViews;offset:number}>(28).get()!;
 expect(factoryRoot.offset).toBe(0);
 expect(factoryRoot.fields.backing).toMatchObject({requestedBytes:36,capacity:40,freed:false});
 expect([32,36].map(offset=>freePointType.fields.readUnsigned(offset))).toEqual([1,9]);
 const registeredRoot=factoryRoot.fields.pointer<{fields:NativeHeapObjectViews;offset:number}>(0).get()!;
 expect(registeredRoot.fields).toBe(freePoint);expect(registeredRoot.offset).toBe(0);
 expect([...factoryRoot.fields.bytes.subarray(4,36)]).toEqual(Array(32).fill(0));
 expect([...factoryRoot.fields.knownMask.subarray(4,36)]).toEqual(Array(32).fill(255));
 const callbacks=NativeGameExitTable.forCrt(game.value.crt).snapshot().callbackCells;
 expect(callbacks.filter(cell=>cell.callback?.entry==='20549b80')).toHaveLength(1);
 expect(callbacks.filter(cell=>cell.callback?.entry==='20549c50')).toHaveLength(1);
 expect(callbacks.filter(cell=>cell.callback?.entry==='20549d60')).toHaveLength(1);
 expect(callbacks.filter(cell=>cell.callback?.entry==='20549d10')).toHaveLength(1);
 expect(callbacks.filter(cell=>cell.callback?.entry==='20029c94')).toHaveLength(1);
 expect(callbacks.filter(cell=>cell.callback?.entry==='20549c20')).toHaveLength(1);
 expect(callbacks.filter(cell=>cell.callback?.entry==='20007702')).toHaveLength(1);
 expect(callbacks.filter(cell=>cell.callback?.entry==='2002ec53')).toHaveLength(1);
 const freePointBaseString=freePointType.base.pointer(4).get();
 expect(freePointType.get()).toEqual({known:true,value:freePointType.fields});
 expect(freePointType.snapshot().wrapper).toBe(freePointState.wrapper);
 expect(freePointType.base.pointer(4).get()).toBe(freePointBaseString);
 const diagnostic=NativeSharedMessageDebug.forPlatform(platform).snapshot(),locale=diagnostic.formatterLocale!;
 expect(diagnostic.messageOwner).toBe(runtime.message);
 expect(diagnostic.messageGetterReturned).toBe(true);
 expect(runtime.message.snapshot().phase).toBe('ready');
 expect(runtime.message.storage.uint(28)).toBe(1);
 expect(diagnostic.localeReturned).toBe(true);
 expect(locale.pointer(8).get()).toBe(owner.snapshot().ptd);
 expect(locale.pointer(0).get()).toBe(owner.snapshot().ptd!.pointer(0x6c).get());
 expect(locale.pointer(4).get()).toBe(owner.snapshot().ptd!.pointer(0x68).get());
 expect(locale.readUnsigned(12,1)).toBe(1);
 expect(owner.snapshot().ptd!.readUnsigned(0x70)&2).toBe(0);
 const expected="bCPropertyObjectTypeBase::RegisterPropertyTemplate - property 'Status' with valuetype 'bTPropertyContainer<enum gEArenaStatus>' added.";
 expect(diagnostic.formatterOutputCount).toBe(expected.length);
 expect(new TextDecoder().decode(diagnostic.buffer!.bytes.subarray(0,expected.length))).toBe(expected);
 expect(diagnostic.terminatorWritten).toBe(true);
 expect(diagnostic.buffer!.readUnsigned(expected.length,1)).toBe(0);
 expect(diagnostic.formatterReturned).toBe(true);
 expect(diagnostic.messageCallFrame!.pointer(0).get()).toEqual({module:'SharedBase',source:'10049929'});
 expect(diagnostic.messageCallFrame!.pointer<{fields:NativeHeapObjectViews;offset:number}>(8).get()!.fields).toBe(diagnostic.buffer);
 expect([4,12,16,20,24].map(offset=>diagnostic.messageCallFrame!.readUnsigned(offset))).toEqual([1,0,0,0xffffffff,5]);
 expect(diagnostic.messageDispatched).toBe(false);
 expect(diagnostic.messageCallReturned).toBe(true);
 expect(diagnostic.debugReturned).toBe(true);
 const status=NativeGameArenaStatusProperty.forCrt(game.value.crt,memory).snapshot();
 expect(status.propertyRegistered).toBe(true);
 expect(status.temporaryDestroyed).toBe(true);
 expect(status.temporaryName!.snapshot().destroyed).toBe(true);
 expect(status.initializerReturned).toBe(true);
 expect(status.trace).toContain('204b1e44.cleanup.registered');
 expect(status.trace).toContain('204b1e4c.initializer.return');
 const enumOwner=NativeGameArenaEnum.forCrt(game.value.crt,memory),enumState=enumOwner.snapshot();
 expect(enumState.allocation).not.toBeNull();
 expect(new NativeHeapObjectViews(enumState.allocation!,0,12).readUnsigned(0)).toBe(0x20659c74);
 expect(new NativeHeapObjectViews(enumState.allocation!,0,12).readUnsigned(4)).toBe(0x2065902c);
 expect(new NativeHeapObjectViews(enumState.allocation!,0,12).readUnsigned(8)).toBe(0);
 expect(enumState.trace).toContain('1004a1c8.enumBaseConstructor.return');
 const registry=game.value.crt.imageStorage('enumNameRegistry');
 expect(game.value.crt.imageStorage('enumNameRegistryGuard').readUnsigned(0)&1).toBe(1);
 expect([4,8,12].map(offset=>registry.readUnsigned(offset))).toEqual([43,51,2]);
 expect(enumState.bucket).toBeGreaterThanOrEqual(0);
 expect(enumState.bucket).toBeLessThan(43);
 const bucketFields=registry.pointer<{identity:object;bytes:Uint8Array;knownMask:Uint8Array;freed:boolean}>(0).get()!;
 const runningHash=enumState.runningEntryName!.hash();if(!runningHash.known)throw new Error(runningHash.reason);
 const runningBucket=runningHash.value%43;
 expect(new NativeHeapObjectViews(bucketFields,runningBucket*4,4).pointer(0).get()).toBe(enumState.runningNameEntry);
 const oldBucketHead=new NativeHeapObjectViews(bucketFields,enumState.bucket!*4,4).pointer(0).get();
 if(runningBucket===enumState.bucket)expect(new NativeHeapObjectViews(enumState.runningNameEntry!,0,16).pointer(12).get()).toBe(enumState.nameEntry);
 else expect(oldBucketHead).toBe(enumState.nameEntry);
 for(let bucket=0;bucket<51;bucket++)if(bucket!==enumState.bucket&&bucket!==runningBucket)
  expect(new NativeHeapObjectViews(bucketFields,bucket*4,4).readUnsigned(0)).toBe(0);
 expect(new NativeHeapObjectViews(enumState.nameEntry!,0,16).readUnsigned(4)).toBe(0x2065902c);
 expect(new NativeHeapObjectViews(enumState.nameEntry!,0,16).readUnsigned(8)).toBe(0);
 expect(enumState.entryName!.snapshot().destroyed).toBe(false);
 expect(enumState.trace).toContain('2006d54f.enumValue.virtualAssignment.return1');
 const valueRegistry=game.value.crt.imageStorage('enumValueRegistry');
 expect([4,8,12].map(offset=>valueRegistry.readUnsigned(offset))).toEqual([43,51,2]);
 expect(game.value.crt.imageStorage('enumValueRegistryGuard').readUnsigned(0)&1).toBe(1);
 const valueBuckets=valueRegistry.pointer<{identity:object;bytes:Uint8Array;knownMask:Uint8Array;freed:boolean}>(0).get()!;
 expect(valueBuckets).not.toBe(bucketFields);
 expect(enumState.valueBucket).toBe(0);
 expect(new NativeHeapObjectViews(valueBuckets,0,4).pointer(0).get()).toBe(enumState.runningValueEntry);
 expect(new NativeHeapObjectViews(enumState.runningValueEntry!,0,16).pointer(12).get()).toBe(enumState.valueEntry);
 expect(new NativeHeapObjectViews(enumState.runningValueEntry!,0,16).readUnsigned(4)).toBe(1);
 expect(new NativeHeapObjectViews(enumState.valueEntry!,0,16).readUnsigned(4)).toBe(0);
 for(let offset=4;offset<204;offset+=4)expect(new NativeHeapObjectViews(valueBuckets,offset,4).readUnsigned(0)).toBe(0);
 const descriptor=game.value.crt.imageStorage('arenaStatusDescriptor');
 const arrayBacking=descriptor.pointer<{identity:object;bytes:Uint8Array;knownMask:Uint8Array;freed:boolean}>(32).get()!;
 const array=new NativeHeapObjectViews(arrayBacking,0,12);
 expect([array.readUnsigned(4),array.readUnsigned(8)]).toEqual([2,9]);
 const values=array.pointer<{identity:object;bytes:Uint8Array;knownMask:Uint8Array;freed:boolean}>(0).get()!;
 expect(new NativeHeapObjectViews(values,0,4).pointer(0).get()).toBe(enumState.allocation);
 expect(new NativeHeapObjectViews(values,4,4).pointer(0).get()).toBe(enumState.runningAllocation);
 expect(enumState.valueName!.snapshot().destroyed).toBe(false);
 expect(enumState.trace).toContain('200711e6.enumNameRegistry.constructor.return');
 expect(enumState.trace).toContain('200719c5.enumNameRegistry.cleanupRegistered');
 expect(enumState.temporary!.snapshot().destroyed).toBe(true);
 expect(enumState.initializerReturned).toBe(true);
 expect(enumState.valueInserted).toBe(true);
 expect(enumOwner.initialize()).toEqual({known:true,value:undefined});
 expect(enumOwner.snapshot().allocation).toBe(enumState.allocation);
 expect(enumState.runningAllocation).not.toBeNull();
 expect(enumState.runningAllocation).not.toBe(enumState.allocation);
 expect(new NativeHeapObjectViews(enumState.runningAllocation!,0,12).readUnsigned(8)).toBe(1);
 expect(enumState.runningTemporary!.snapshot().destroyed).toBe(true);
 expect(new NativeHeapObjectViews(enumState.runningNameEntry!,0,16).readUnsigned(8)).toBe(1);
 expect(enumState.runningEntryName!.snapshot().destroyed).toBe(false);
 expect(game.value.crt.imageStorage('enumValueScratch').readUnsigned(0)).toBe(0);
 expect(enumState.runningReturned).toBe(true);expect(enumState.runningInserted).toBe(true);
 expect(enumOwner.initializeRunning()).toEqual({known:true,value:undefined});
 expect(enumOwner.snapshot().runningAllocation).toBe(enumState.runningAllocation);
 expect(runtime.message.snapshot().trace).toContain('10049574.message.threshold.return');
 expect(runtime.message.onMessageBelowThreshold(2)).toEqual({known:false,reason:'Unowned MessageAdmin.OnMessage callback loop at 1004951d'});
 expect(runtime.message.onMessageBelowThreshold(0xffffffff)).toEqual({known:true,value:true});
 expect(runtime.message.onMessageBelowThreshold(-1).known).toBe(false);
 expect(owner.processAttach()).toEqual(result);
 expect(owner.snapshot().wholeCrtTraversalCompleted).toBe(false);
},30000);
it('retains output and rejects a changed cookie before returning or writing the terminator',()=>{
 const platform=platformFixture(),tls=NativeSharedStaticTls.forPlatform(platform);
 if(!tls.known)throw new Error(tls.reason);expect(tls.value.loadSharedBase().known).toBe(true);
 const crt=NativeSharedCrtOwner.forPlatform(platform);expect(crt.processAttach()).toEqual({known:true,value:1});
 const diagnostic=NativeSharedMessageDebug.forPlatform(platform),cookie=NativeSharedCrtSecurityCookie.forPlatform(platform);
 const memory=new NativeMemoryAdmin(platform,{extensions:[nativeNpcHeapExtension,nativeSceneStartupHeapExtension,nativeClassNameHeapExtension,nativePropertyHeapExtension]});
 const write=NativeHeapObjectViews.prototype.writeUnsigned;let changed=false;
 try{
  NativeHeapObjectViews.prototype.writeUnsigned=function(offset,value,width=4){
   write.call(this,offset,value,width);
   const state=diagnostic.snapshot();
   if(!changed&&state.formatterFrame&&this===state.buffer&&width===1){changed=true;write.call(cookie.fields,0,0x12345678,4);}
  };
  const game=createBrowserGameCrtStartup(platform,memory);if(!game.known)throw new Error(game.reason);
  expect(game.value.attachResult.known).toBe(false);
  if(game.value.attachResult.known)throw new Error('Changed cookie accepted');
  expect(game.value.attachResult.reason).toContain('security-cookie mismatch at 100b01d2');
 }finally{NativeHeapObjectViews.prototype.writeUnsigned=write;}
 expect(changed).toBe(true);
 const state=diagnostic.snapshot();expect(state.formatterOutputCount).toBeGreaterThan(0);
 expect(state.formatterReturned).toBe(false);expect(state.terminatorWritten).toBe(false);
 expect(state.messageDispatched).toBe(false);
 expect(state.messageCallFrame).toBeNull();
 expect(state.buffer!.knownMask[state.formatterOutputCount!]).toBe(255); // original TLS template stays known
},30000);
