import { hotbarEligible, isItemId, ITEMS } from '../../content/items';
import { S } from '../../content/strings';
import type { ItemId } from '../../game/types';
import { h, visibleControl } from './dom';
import { icon } from './icons';
import { QUICK_SLOT_COUNT, type QuickDrag } from './uiModel';

export function quickDragMoved(startX: number, startY: number, x: number, y: number): boolean {
  return [startX, startY, x, y].every(Number.isFinite) && (x - startX) ** 2 + (y - startY) ** 2 >= 36;
}
export type QuickDrop = { t: 'assign'; slot: number; item: ItemId } | { t: 'swap'; from: number; to: number };
/** Resolve against live bindings at release; a depleted binding can move, but a depleted inventory item cannot bind. */
export function quickDropOperation(value: QuickDrag, slot: number, slots: readonly (ItemId | null)[], inventory: Partial<Record<ItemId, number>>): QuickDrop | null {
  if (!Number.isInteger(slot) || slot < 0 || slot >= QUICK_SLOT_COUNT || !isItemId(value.item) || !hotbarEligible(value.item)) return null;
  if (value.from === null) return (inventory[value.item] ?? 0) > 0 ? { t: 'assign', slot, item: value.item } : null;
  if (!Number.isInteger(value.from) || value.from < 0 || value.from >= QUICK_SLOT_COUNT || value.from === slot || slots[value.from] !== value.item) return null;
  return { t: 'swap', from: value.from, to: slot };
}

interface DragOptions {
  value(): QuickDrag | null;
  scope(): HTMLElement;
  drop(value: QuickDrag, slot: number): void;
}
let cancelActive: (() => void) | null = null;
let clearReleaseClick: (() => void) | null = null;

/** Suppress the click generated by this moved release, never the next intentional press or keyboard activation. */
function suppressReleaseClick() {
  clearReleaseClick?.();
  const clear = () => {
    window.removeEventListener('click', click, true);
    window.removeEventListener('pointerdown', clear, true);
    window.clearTimeout(timer);
    if (clearReleaseClick === clear) clearReleaseClick = null;
  };
  const click = (event: MouseEvent) => {
    if (event.detail === 0) return;
    event.preventDefault(); event.stopImmediatePropagation(); clear();
  };
  const timer = window.setTimeout(clear, 400);
  clearReleaseClick = clear;
  window.addEventListener('click', click, true);
  window.addEventListener('pointerdown', clear, true);
}

/** Pointer capture stays on the actual source; no native HTML drag session can steal its mouse events. */
export function bindQuickDrag(source: HTMLElement, options: DragOptions) {
  source.draggable = false;
  source.classList.add('quick-drag-source');
  source.addEventListener('dragstart', (event) => event.preventDefault());
  source.addEventListener('pointerdown', (down) => {
    if (down.button !== 0 || !down.isPrimary || !visibleControl(source)) return;
    const value = options.value(), scope = options.scope();
    if (!value || !isItemId(value.item) || !hotbarEligible(value.item) || !visibleControl(scope)) return;
    cancelActive?.();
    const pointer = down.pointerId;
    let moved = false;
    let ghost: HTMLElement | null = null;
    let target: HTMLElement | null = null;
    let active = true;
    const valid = () => source.isConnected && scope.isConnected && visibleControl(source) && visibleControl(scope);
    const targetAt = (x: number, y: number) => {
      const element = document.elementFromPoint(x, y)?.closest<HTMLElement>('[data-quick-slot]') ?? null;
      return element && scope.contains(element) && visibleControl(element) && !element.hasAttribute('disabled') ? element : null;
    };
    const highlight = (next: HTMLElement | null) => {
      if (target === next) return;
      target?.classList.remove('is-drop-target'); target = next; target?.classList.add('is-drop-target');
    };
    const finish = (commit: boolean, event?: PointerEvent) => {
      if (!active) return;
      const dropTarget = commit && moved && event && valid() ? targetAt(event.clientX, event.clientY) : null;
      const slot = dropTarget ? Number(dropTarget.dataset.quickSlot) : null;
      active = false;
      window.removeEventListener('pointermove', move, true);
      window.removeEventListener('pointerup', up, true);
      window.removeEventListener('pointercancel', cancelPointer, true);
      window.removeEventListener('blur', cancel);
      window.removeEventListener('keydown', escape, true);
      source.removeEventListener('lostpointercapture', cancelPointer);
      source.classList.remove('is-dragging'); highlight(null); ghost?.remove();
      document.body.classList.remove('quick-drag-active');
      if (cancelActive === cancel) cancelActive = null;
      if (source.hasPointerCapture(pointer)) source.releasePointerCapture(pointer);
      if (moved) suppressReleaseClick();
      // Commands can rebuild the modal only after capture, listeners and visuals have been released.
      if (slot !== null) options.drop(value, slot);
    };
    const cancel = () => finish(false);
    const cancelPointer = (event: PointerEvent) => { if (event.pointerId === pointer) cancel(); };
    const escape = (event: KeyboardEvent) => { if (event.code === 'Escape') cancel(); };
    const move = (event: PointerEvent) => {
      if (event.pointerId !== pointer) return;
      if (!valid() || event.buttons === 0) { cancel(); return; }
      if (!moved && !quickDragMoved(down.clientX, down.clientY, event.clientX, event.clientY)) return;
      if (!moved) {
        moved = true; source.classList.add('is-dragging'); document.body.classList.add('quick-drag-active');
        ghost = h('div', { class: 'quick-drag-ghost', 'aria-hidden': 'true' }, icon(value.item), h('span', {}, S(ITEMS[value.item].nameKey)));
        document.body.append(ghost);
      }
      event.preventDefault();
      if (ghost) {
        const x = Math.max(8, Math.min(event.clientX + 14, window.innerWidth - ghost.offsetWidth - 8));
        const y = Math.max(8, Math.min(event.clientY + 14, window.innerHeight - ghost.offsetHeight - 8));
        ghost.style.transform = `translate3d(${x}px, ${y}px, 0)`;
      }
      highlight(targetAt(event.clientX, event.clientY));
    };
    const up = (event: PointerEvent) => {
      if (event.pointerId !== pointer) return;
      if (moved) event.preventDefault();
      finish(true, event);
    };
    try { source.setPointerCapture(pointer); } catch { return; }
    cancelActive = cancel;
    window.addEventListener('pointermove', move, { capture: true, passive: false });
    window.addEventListener('pointerup', up, true);
    window.addEventListener('pointercancel', cancelPointer, true);
    window.addEventListener('blur', cancel);
    window.addEventListener('keydown', escape, true);
    source.addEventListener('lostpointercapture', cancelPointer);
  });
}
