import { DIALOGUE_STRINGS } from './dialogue';

/**
 * Display text, keyed by stable identifiers so a localization pass touches one table.
 * Everything here is working text for the prototype and carries no canon weight.
 */
export const EN: Record<string, string> = {
  /* ---------- Titles and menus ---------- */
  'game.title': 'Tervain',
  'game.subtitle': 'The Grey Strand · Bellwether Vale',
  'game.tagline': 'A broken sluice. A thirsty vale. One choice for every household.',
  'menu.continue': 'Continue',
  'menu.new': 'New Game',
  'menu.load': 'Load',
  'menu.save': 'Save',
  'menu.settings': 'Settings',
  'menu.controls': 'Controls',
  'menu.about': 'About this build',
  'menu.resume': 'Resume',
  'menu.quit': 'Quit to title',
  'menu.back': 'Back',
  'menu.close': 'Close',
  'menu.confirm': 'Confirm',
  'menu.cancel': 'Cancel',
  'menu.delete': 'Delete',
  'menu.deleteconfirm': 'Press again to delete',
  'menu.newconfirm': 'Start a new game? Your manual slots and quicksave are kept. The Autosave slot is replaced the first time the new game autosaves.',
  'menu.startanyway': 'Start new game',
  'menu.empty': 'Empty slot',
  'menu.slot.auto': 'Autosave',
  'menu.slot.quick': 'Quicksave',
  'menu.slot.slot-1': 'Slot 1',
  'menu.slot.slot-2': 'Slot 2',
  'menu.slot.slot-3': 'Slot 3',
  'menu.loadfailed': 'That save could not be loaded: {reason}',
  'menu.recovered.previous': 'The latest write was damaged, so the previous save was restored.',
  'menu.recovered.temporary': 'An interrupted write was recovered.',
  'menu.saved': 'Game saved ({slot}).',
  'menu.savefailed': 'Could not save: {reason}',
  'menu.loaded': 'Game loaded.',
  'menu.play': 'Click the view to look around · Press Esc to pause',
  'menu.loading': 'Raising the coast and the vale…',
  'menu.webgl': 'Tervain needs WebGL. Try another browser or enable hardware acceleration.',
  'menu.savetime': '{day} · {phase} · {play}',
  'menu.day': 'Day {n}',
  'about.body':
    'This is a browser build of the Tervain vertical-slice prototype: a grey beach under a lighthouse, a walk over open heath, one compact valley and one main dispute, with every model and texture generated in code. It is a test of whether movement, conversation, evidence and a lasting consequence can work together — not a finished game, and not a claim about performance on any device. See docs/engineering/prototype.md for what is real and what is representation.',

  /* ---------- HUD ---------- */
  'hud.health': 'Health',
  'hud.stamina': 'Stamina',
  'hud.exhausted': 'Winded',
  'hud.coin': 'Coin',
  'hud.objective': 'Suggested next step',
  'hud.guidance.off': 'Guidance is off in Settings.',
  'hud.time': 'Day {n} · {time}',
  'hud.saving': 'Saving…',
  'hud.locked': 'Locked',
  'hud.requires': 'Requires:',
  'hud.hold': 'Hold',
  'hud.interrupted': 'Interrupted',
  'hud.threat': 'Wind-up! Block, sidestep or back away.',
  'hud.fallen.title': 'You fall.',
  'hud.fallen.body': 'You wake at the last place you were safe. What you had already done is still done.',
  'hud.fps': '{fps} fps · {ms} ms',
  'hud.captions': 'Captions',

  /* ---------- Prompts ---------- */
  'prompt.talk': 'Talk to {name}',
  'prompt.inspect': 'Inspect',
  'prompt.inspect.dry_channel': 'Inspect the dry household channel',
  'prompt.inspect.spring_sediment': 'Inspect the silt at the spring intake',
  'prompt.inspect.town_diversion': "Follow the village's side channel",
  'prompt.inspect.quarry_seep': 'Follow the quarry seep',
  'prompt.inspect.sluice_crack': 'Inspect the support beside the gate',
  'prompt.inspect.inspection_log': 'Read the inspection log',
  'prompt.inspect.noticeboard': 'Read the noticeboard',
  'prompt.inspect.wetland_fish': 'Look at the wetland shallows',
  'prompt.inspect.saltward_kit': 'Examine the measuring kit',
  'prompt.pickup.quarry_brace': 'Take the spare sluice brace',
  'prompt.pickup.quarry_wrench': 'Take the gate wrench',
  'prompt.pickup.side_path_cache': 'Open the hidden cache',
  'prompt.lever': 'Pull the maintenance lever',
  'prompt.sluice': 'Work the sluice controls',
  'prompt.archive_door.locked': 'Try the archive door',
  'prompt.archive_shutter': 'Force the archive shutter',
  'prompt.ledger': 'Read the rotation ledger',
  'prompt.rite': 'Perform the spring rite',
  'prompt.rite.notaught': 'A shrine basin',
  'prompt.check_channel': 'Check the household channel',
  'prompt.check_mill': 'Check the mill',
  'prompt.mill_note': 'Watch the mill wheel',
  'prompt.close': 'Step back',

  /* ---------- Toasts and interaction results ---------- */
  'toast.journal': 'Journal updated',
  'toast.evidence.observed': 'You noted: {name}',
  'toast.evidence.testimony': 'Reported: {name}',
  'toast.evidence.derived': 'You can now conclude: {name}',
  'toast.evidence.document': 'You found: {name}',
  'toast.item.gain': '+{qty} {name}',
  'toast.item.lose': '−{qty} {name}',
  'toast.place': 'Discovered: {name}',
  'toast.skill': 'Learned: {name}',
  'toast.gate.stable': 'The gate is braced. It holds — but it does not make more water.',
  'toast.gate.jammed': 'The gate jams. Less water than before, and a repair still to do.',
  'toast.surge': 'The gate kicks back. You take a hard knock.',
  'toast.calm': 'The flow settles. The gate should be gentle for a while.',
  'toast.rite.need': 'You need Sister Edda to teach you the rite, and a votive reed.',
  'toast.rite.done': 'The rite is done. The flow will stay calm for about {min} minutes.',
  'toast.archive.locked': 'The door is locked. Sister Edda holds the say; Warden Harrow keeps the key.',
  'toast.archive.open': 'The archive door is open.',
  'toast.archive.forced': 'You force the shutter and slip inside.',
  'toast.archive.sealed_now': 'Behind you, someone nails the archive shut.',
  'toast.archive.sealed': 'The shutter has been nailed shut.',
  'toast.archive.withdrawn': 'Access has been withdrawn.',
  'toast.ledger': 'You read the old rotation ledger.',
  'toast.shortcut': 'The maintenance gate swings open. Somewhere above, someone starts walking.',
  'toast.cleared': 'The thornback is down. The ledge is clear.',
  'toast.shortcut.rescued': 'Ila Rusk is on her way down the old track.',
  'toast.rescued': 'Ila Rusk is safe.',
  'toast.report': 'Word has reached {name}.',
  'toast.settled': 'The valley has a new arrangement. Rewards received.',
  'toast.applying': 'The channels are still finding their level. Give it a little longer.',
  'toast.poultice': 'You feel steadier.',
  'toast.nothing': 'Nothing more to do here.',
  'toast.need.brace': 'You need a brace to set against the cracked support.',
  'toast.need.wrench': 'You need a wrench to turn the gate wheel.',
  'toast.need.understanding': 'You are not sure how to brace it safely. Inspect the support or find someone who knows the gate.',
  'toast.need.payment': 'You cannot afford that.',
  'toast.nowitness': 'That would be an emergency allocation — it lapses unless it is reviewed.',
  'toast.boundary': 'The track ends in rough heath. There is no safe path onward.',
  'toast.noheal': 'You are not hurt.',
  'toast.nopoultice': 'You have no poultice.',
  'toast.settings': 'Settings saved.',
  'toast.bindconflict': '{key} is already used for “{action}”. Press it again to swap the two, or choose another key.',
  'toast.bound': '{action} is now {key}.',
  'toast.warden.hey': 'Hey! Who is there?',
  'toast.unlocked.key': 'You unlock the archive with the borrowed key.',
  'toast.brace.taken': 'Rillford will want this brace back in one piece.',
  'toast.cache': 'A small store of coin, left by someone who never came back for it.',
  'toast.caption.bell': '[The drought bell tolls]',
  'toast.caption.bell.allclear': '[A bright, even peal]',

  'narr.ledger':
    'The ledger is a thick, water-stained book. Page after page records the same arrangement: the mill and its households drew the channel by day, the quarry by night, and a waterkeeper, a reeve and a foreman signed each season’s schedule together. Someone has added, in a smaller hand: “Households gave labor and carried water here too — uncounted.”',

  /* ---------- Sluice panel ---------- */
  'sluice.title': 'The Bellwether sluice',
  'sluice.state.damaged': 'Damaged. The support beside the gate is cracked and the leaf hangs askew.',
  'sluice.state.jammed': 'Jammed. Someone forced the gate and it seized.',
  'sluice.state.stabilized': 'Braced. The gate can be worked safely — but stabilizing does not create more water.',
  'sluice.brace': 'Brace the gate',
  'sluice.brace.desc': 'Set the brace against the cracked support and turn the wheel a quarter at a time. Consumes the brace.',
  'sluice.brace.safe.rite': 'The spring rite is holding the flow calm: this should be gentle.',
  'sluice.brace.safe.procedure': "Ila's procedure: from the downstream side, brace first, quarter turns. This should be gentle.",
  'sluice.brace.unsafe': 'Without the rite or a known procedure the gate may kick back: expect a hard knock.',
  'sluice.force': 'Force the gate open',
  'sluice.force.desc': 'Open it now, without bracing.',
  'sluice.force.warn': 'This could jam the gate and make the shortage worse. The valley will still need it repaired.',
  'sluice.force.confirm': 'Force it anyway',
  'sluice.commit.title': 'Decide how the water is shared',
  'sluice.commit.intro': 'Every choice keeps the minimum flow for drinking and for the wetland. Nothing here makes more water — it only decides who goes without.',
  'sluice.commit.locked': 'Brace the gate first: the gate has to hold before anyone can rely on it.',
  'sluice.commit.confirm': 'Commit to this',
  'sluice.commit.back': 'Not yet',
  'sluice.alloc.rillford': 'Prioritize Rillford',
  'sluice.alloc.quarry': 'Prioritize the quarry',
  'sluice.alloc.rotation': 'Set a witnessed rotation',
  'sluice.alloc.rillford.gain': 'Household channel recovers; the mill returns to restricted service.',
  'sluice.alloc.rillford.cost': 'Quarry operations pause. Foreman Kest and his unpaid crew will be unhappy.',
  'sluice.alloc.rillford.kind': 'Emergency allocation — it lapses unless it is reviewed.',
  'sluice.alloc.quarry.gain': 'Quarry resumes limited work; the estate delivery stays possible.',
  'sluice.alloc.quarry.cost': 'The mill stays closed and households keep rationing. Rillford will protest.',
  'sluice.alloc.quarry.kind': 'Emergency allocation — it lapses unless it is reviewed.',
  'sluice.alloc.rotation.gain': 'Mill and households by day, quarry by night: both get something.',
  'sluice.alloc.rotation.cost': 'Neither meets full demand. Supervision costs labor, and night shifts cost sleep.',
  'sluice.alloc.rotation.kind': 'Recognized under the Accord: witnessed by the reeve, the foreman and the waterkeeper.',
  'sluice.alloc.rotation.need.evidence_both_needs': 'You must have seen both what the village needs and what the quarry needs.',
  'sluice.alloc.rotation.need.consent_mara': 'The reeve has not agreed to a rotation.',
  'sluice.alloc.rotation.need.consent_edda': 'The waterkeeper has not agreed to stand as witness.',
  'sluice.alloc.rotation.need.consent_darin': 'The foreman has not agreed to a rotation.',
  'sluice.alloc.caretaker': 'One decision-maker is gone: a caretaker will stand in, and the rotation carries less weight.',
  'sluice.brace.working': 'Bracing the gate…',

  /* ---------- Noticeboard ---------- */
  'board.title': 'RILLFORD NOTICES',
  'board.bell_drought': 'The drought bell has been rung. Households: one bucket a day at the well until further notice. — M. Venn, Reeve',
  'board.gate_jammed': 'The upper sluice gate has been forced and is jammed. It needs a brace and a careful hand.',
  'board.gate_braced': 'The upper sluice gate is braced. The reeve will announce how the flow is to be shared.',
  'board.alloc_rillford': 'By emergency allocation the household channel and mill take priority. The quarry pauses.',
  'board.alloc_quarry': 'By emergency allocation the quarry takes priority under the estate contract. Households ration.',
  'board.alloc_rotation': 'ROTATION: mill and households by day, quarry by night. Witnessed by the reeve, the foreman and the waterkeeper.',
  'board.alloc_rotation_partial': 'ROTATION: mill and households by day, quarry by night. Witnessed by the decision-makers who remain and by a caretaker standing in for the one who is absent.',
  'board.public_statement': 'A decision-maker is absent. This allocation is recorded here in their place and acknowledged by a caretaker.',
  'board.account_flood_only': 'Account of the shortage: the late-thaw flood damaged the sluice. (Nothing further is recorded.)',
  'board.rotation_witnesses': 'The old rotation is honored. The record is open to anyone who wishes to read it.',
  'board.emergency_expires': 'An emergency allocation lapses unless it is reviewed. Review to be called by the reeve and the waterkeeper.',

  /* ---------- Visible details ---------- */
  'detail.channel_full': 'The household channel runs full.',
  'detail.mill_turning': 'The mill wheel is turning.',
  'detail.quarry_idle': 'The quarry crew is idle and unpaid.',
  'detail.quarry_working': 'Stone is being cut and loaded.',
  'detail.mill_still_queue': 'The mill is still and the well has a queue.',
  'detail.contract_guard': 'A contract guard holds the sluice door.',
  'detail.schedule_posted': 'A rotation schedule is posted.',
  'detail.alternating_work': 'Mill by day, quarry by night.',
  'detail.tired_night_crew': 'The night crew looks tired.',

  /* ---------- Inspect notices ---------- */
  'inspect.dry_channel': 'The channel behind the mill is dry to the mud. Cracked banks, a stranded reed bucket — households have been drawing from the well only.',
  'inspect.spring_sediment': 'Grey flood silt lies thick across the intake channels. The spring itself still wells up — the flow is thin because the channels are choked, not because the spring has failed.',
  'inspect.town_diversion': 'A small side gate above the fields has been cut into the bank, its timbers fresh. It takes a steady share of what reaches the village.',
  'inspect.quarry_seep': 'Water weeps from the quarry cut into the seep channel. The rock nearby is cracked; the cutting has been extended past the old line.',
  'inspect.sluice_crack': 'The stone support beside the gate has fresh fractures, pale against weathered stone. The gate leaf sits askew against it. It would not survive being forced.',
  'inspect.inspection_log': 'The waterkeeper’s inspection log skips the week before the thaw. The next entry was written after the flood.',
  'inspect.noticeboard': 'The noticeboard has several notices.',
  'inspect.wetland_fish': 'Fish nests in the shallows have been left bare and dry along the edge. The wetland is getting less water than it needs.',
  'inspect.saltward_kit': 'A brass measuring level and a marked staff, annotated in an angular southern hand. The notes explain how to read safe operating levels and alternating service periods.',

  /* ---------- Items ---------- */
  'item.coin': 'Coin',
  'item.coin.desc': 'Small change from three regions.',
  'item.sluice_brace': 'Spare sluice brace',
  'item.sluice_brace.desc': "Rillford's spare timber brace, lent to the quarry. Sets against a cracked support.",
  'item.gate_wrench': 'Gate wrench',
  'item.gate_wrench.desc': 'A long iron wrench for turning the sluice wheel. Not used up.',
  'item.archive_key': 'Archive key',
  'item.archive_key.desc': "Warden Harrow's key, borrowed on your word.",
  'item.votive_reed': 'Votive reed',
  'item.votive_reed.desc': 'A blessed reed for the spring rite. There is no second.',
  'item.poultice': 'Poultice',
  'item.poultice.desc': 'Restores some health. Press H to use.',
  'item.league_sash': 'Hearth League sash',
  'item.league_sash.desc': 'Worn by those the village recognizes.',
  'item.contract_band': 'Marcher contract band',
  'item.contract_band.desc': 'Identifies a hand who kept the estate contract running.',
  'item.witness_cord': "Witness's cord",
  'item.witness_cord.desc': 'A woven cord from the rotation signing. Recognized by both sides.',
  'pickup.brace': 'Spare sluice brace',
  'pickup.wrench': 'Gate wrench',
  'pickup.cache': 'Hidden cache',
  'skill.steady_guard': 'Steady Guard',
  'skill.steady_guard.desc': 'Holding the shield costs 40% less stamina.',

  /* ---------- Journal ---------- */
  'journal.title': 'Journal',
  'journal.observed': 'Observed',
  'journal.reported': 'Reported',
  'journal.concluded': 'Concluded',
  'journal.questions': 'Open questions',
  'journal.places': 'Places',
  'journal.people': 'People',
  'journal.status': 'Where things stand',
  'journal.empty': 'Nothing yet.',
  'journal.place.verified': 'Visited',
  'journal.place.claimed': 'Told of (approximate)',
  'journal.place.unknown': 'Unknown',
  'journal.person.met': 'Met',
  'journal.person.unmet': 'Not yet met',
  'journal.person.absent': 'Absent',
  'journal.status.unseen': 'You have just arrived. Something is wrong with the water.',
  'journal.status.investigating': 'You are learning why the water has failed and who needs it.',
  'journal.status.decision_ready': 'The gate holds. It is time to decide how the reduced flow is shared.',
  'journal.status.committed': 'The arrangement is in place. See it reach the village.',
  'journal.status.settled': 'The valley has a settled arrangement, and you have earned your place in it.',
  'journal.lead.bell': 'The drought bell brought you into Rillford. Ask the reeve what has happened.',
  'journal.lead.sluice': 'You came across the damaged sluice above the village. Find out who depends on it.',
  'journal.lead.dry_channel': 'A dry channel behind the mill shows what the village has lost.',
  'journal.lead.spring': 'The spring intake is choked. You began at the source.',
  'journal.lead.diversion': 'You found a side channel drawing water from the village stream.',
  'journal.lead.seep': 'You found a seep in the quarry cut.',
  'journal.lead.worker': 'Someone is stranded at the Cut and needs help.',
  'journal.lead.reeve': 'Reeve Mara Venn told you what has happened to Rillford.',
  'journal.lead.steward': 'Sister Edda Sorn told you about the spring.',
  'journal.lead.quarry_worker': 'The quarry crew is stopped for want of water.',
  'journal.lead.gate': 'You put your hands on the sluice gate.',
  'journal.lead.evidence': 'You found something worth writing down.',
  'journal.ev.dry_channel.observed': 'The household channel behind the mill is dry; Rillford has a real shortage.',
  'journal.ev.dry_channel.reported': 'The reeve says households are down to a bucket a day and the mill stands idle.',
  'journal.ev.reduced_spring_flow.observed': 'Flood silt chokes the spring intake. The flow is thin because the channels are obstructed, not because the spring is failing.',
  'journal.ev.reduced_spring_flow.reported': 'Ila saw silt across the intake and a spring that still wells up: the flow is obstructed.',
  'journal.ev.diversion_and_seep.observed': 'Both a village side gate and quarry seepage draw on the same reduced flow.',
  'journal.ev.diversion_and_seep.reported': 'Both the reeve and the foreman admit their share in the shortage.',
  'journal.ev.cracked_sluice.observed': 'The support beside the sluice gate is cracked. Forcing the gate open is dangerous.',
  'journal.ev.cracked_sluice.reported': 'Sister Edda says the support cracked in the flood and the gate could give way.',
  'journal.ev.rotation_ledger.observed': 'An old ledger shows a rotation between mill and quarry that was once kept and witnessed.',
  'journal.ev.rotation_ledger.reported': 'An old rotation between mill and quarry is said to have existed.',
  'journal.ev.worker_testimony.observed': "Ila Rusk's account of the gate: brace first, quarter turns from downstream.",
  'journal.ev.worker_testimony.reported': 'Ila Rusk says fresh fractures, silt at the intake, and the seep feeding the wrong channel — and how to close the gate safely.',
  'journal.claim.claim_foreman_spring_failing': 'The foreman says the spring is failing.',
  'journal.claim.claim_steward_sediment': 'Sister Edda says sediment, not failure, is choking the spring.',
  'journal.claim.claim_reeve_promised_relief': 'The reeve says she promised more relief than the flow can carry.',
  'journal.claim.claim_reserve_sufficient': 'The estate steward says the repair reserve is sufficient.',
  'journal.claim.reserve_empty': 'The estate steward admits the repair reserve is empty.',
  'journal.claim.edda_admits_deferral': 'Sister Edda admits she deferred the sluice inspection.',
  'journal.claim.reeve_admits_diversion': 'The reeve admits opening a side gate without witnesses.',
  'journal.claim.foreman_admits_seep': 'The foreman admits extending the cutting after permission ran out.',
  'journal.claim.told_ledger': 'The recorder says an old rotation ledger sits in the shrine archive.',
  'journal.obs.saw_seep': 'Water seeps from the quarry cut into the seep channel.',
  'journal.obs.saw_diversion': 'A fresh side gate on the village stream draws off water above the fields.',
  'journal.obs.saw_inspection_gap': 'The sluice inspection log skips the week before the thaw.',
  'journal.obs.saw_fish_nests': 'The wetland shallows are drying at the edge; fish nests lie bare.',
  'journal.obs.saw_saltward_kit': 'A Saltward measuring kit describes safe levels and alternating service periods.',
  'journal.q.spring_failing_or_silted': 'The foreman says the spring is failing. Is it failing — or obstructed? Look at the intake.',
  'journal.q.reserve': 'The steward called the reserve “sufficient”, then admitted it was empty. Who pays for the repair?',
  'journal.q.relief': 'The reeve promised relief the flow cannot carry. What will actually happen if the gate is braced?',
  'journal.c.sediment_not_failure': 'The spring is silted, not failing: the foreman was wrong about the cause.',
  'journal.c.one_diversion_insufficient': 'Closing one diversion cannot restore the former supply.',
  'journal.c.brace_first': 'The gate must be braced before anyone opens it.',
  'journal.c.gate_jammed': 'The gate is jammed. It still needs bracing — and the shortage is worse for now.',
  'journal.c.gate_stable': 'The gate holds. The reduced flow now has to be shared.',
  'journal.c.precedent': 'A rotation has been kept before. It can be again.',
  'journal.c.alloc_rillford': 'You gave Rillford priority. The quarry pays for it.',
  'journal.c.alloc_quarry': 'You gave the quarry priority. The village pays for it.',
  'journal.c.alloc_rotation': 'You set a witnessed rotation. Both sides give something up.',
  'journal.c.emergency_expires': 'Emergency allocations lapse unless reviewed; nobody owns the water for having held the gate.',
  'journal.c.account_misleading': 'The public account leaves out what you found. It is not the whole truth.',
  'journal.c.caretaker_witness': 'A caretaker stood in as witness for an absent decision-maker.',

  /* ---------- Inventory and skills ---------- */
  'inv.title': 'Inventory',
  'inv.empty': 'Nothing carried.',
  'inv.use': 'Use',
  'inv.skills': 'Skills',
  'inv.noskills': 'No training yet. The shrine warden teaches a little.',

  /* ---------- Map ---------- */
  'map.title': 'The Grey Strand and Bellwether Vale',
  'map.you': 'You',
  'map.suggested': 'Suggested next stop',
  'map.approx': 'approximate',
  'map.note': 'Hand-drawn from what you have seen and been told.',
  'place.shore': 'The Grey Strand',
  'place.lantern_point': 'Lantern Point',
  'place.overlook': 'The Overlook',
  'place.rillford': 'Rillford',
  'place.ford': 'The Ford',
  'place.spring_shrine': 'Spring Shrine',
  'place.sluice': 'The Sluice',
  'place.quarry': 'The Quarry',
  'place.the_cut': 'The Cut',
  'place.archive': 'The Archive',

  /* ---------- Dialogue UI ---------- */
  'dlg.continue': 'Continue',
  'dlg.leave': 'Leave',
  'dlg.intent.ask': 'Ask',
  'dlg.intent.offer': 'Offer',
  'dlg.intent.warn': 'Warn',
  'dlg.intent.persuade': 'Persuade',
  'dlg.intent.accuse': 'Accuse',
  'dlg.intent.agree': 'Agree',
  'dlg.intent.leave': 'Leave',
  'dlg.intent.train': 'Train',
  'dlg.intent.commit': 'Commit',
  'dlg.failed': 'That did not work: {reason}',
  'dlg.choose': 'Choose a reply',

  /* ---------- Requirements ---------- */
  'req.evidence': 'You have: {name}',
  'req.fact': 'You have seen or learned: {name}',
  'req.item': 'You carry: {name}',
  'req.item.n': 'You carry {n}× {name}',
  'req.trust': 'They trust you more',
  'req.any': 'One of: {list}',
  'req.not': 'A condition is not yet met',
  'req.anyDefeated': 'You have proven yourself against something dangerous',
  'req.skill': 'You have learned the skill',
  'req.phase': 'The dispute has progressed further',
  'req.generic': 'Something you have not yet done',
  'req.fact.saw_diversion': 'the village side channel',
  'req.fact.saw_seep': 'the quarry seep',
  'req.fact.saw_sluice_damage': 'the damaged sluice',
  'req.fact.saw_inspection_gap': 'the missing inspection entry',
  'req.fact.edda_permission': "Sister Edda's permission",
  'req.fact.darin_humiliated': 'a rift with the foreman',
  'evidence.dry_channel': 'A dry household channel',
  'evidence.reduced_spring_flow': 'Reduced spring flow',
  'evidence.diversion_and_seep': 'Town diversion and quarry seepage',
  'evidence.cracked_sluice': 'A cracked sluice support',
  'evidence.rotation_ledger': 'The old rotation ledger',
  'evidence.worker_testimony': "Ila's testimony",

  /* ---------- Guidance hints ---------- */
  'hint.walk_to_rillford': 'Follow the road down into Rillford.',
  'hint.look_around': 'Talk to the reeve, or look at the channels for yourself.',
  'hint.see_dry_channel': 'Look at the dry channel behind the mill.',
  'hint.see_spring': 'Go up to the spring and look at the intake.',
  'hint.see_sluice': 'Look at the damaged sluice above the village.',
  'hint.see_quarry': 'Visit the quarry and hear the foreman.',
  'hint.get_brace': 'A spare brace and a wrench lie in the quarry yard.',
  'hint.stabilize': 'Bring the brace and wrench to the sluice and set the gate.',
  'hint.decide': 'At the sluice controls, decide how the reduced flow is shared.',
  'hint.check_result': 'Go and see the water reach the village.',
  'hint.settled': 'The valley is settled. Talk to people — or stay a while.',
  'hint.jammed': 'The gate is jammed. Brace it at the sluice.',
  'hint.rescue': 'Someone is stranded at the Cut.',

  /* ---------- Settings ---------- */
  'set.title': 'Settings',
  'set.display': 'Display and comfort',
  'set.text': 'Text size',
  'set.reduced': 'Reduced motion',
  'set.reduced.desc': 'Steadier camera, no shake, calmer foliage, still menu view.',
  'set.contrast': 'High-contrast interface',
  'set.contrast.desc': 'Opaque panels and stronger outlines.',
  'set.effects': 'Reduced effects',
  'set.effects.desc': 'Uses solid surfaces and removes soft interface highlights.',
  'set.brightness': 'Night and shade brightness',
  'set.quality': 'Graphics quality',
  'set.quality.low': 'Low',
  'set.quality.medium': 'Medium',
  'set.quality.high': 'High',
  'set.quality.note': 'Changing quality reloads the valley (your position is kept).',
  'set.guidance': 'Show suggested next step',
  'set.fps': 'Show frame timing',
  'set.barks': 'Show ambient remarks',
  'set.captions': 'Captions for important sounds',
  'set.controls': 'Input',
  'set.sensitivity': 'Look sensitivity',
  'set.invert': 'Invert vertical look',
  'set.toggleSprint': 'Sprint is a toggle',
  'set.toggleBlock': 'Block is a toggle',
  'set.audio': 'Sound',
  'set.vol.master': 'Master',
  'set.vol.music': 'Music',
  'set.vol.effects': 'Effects',
  'set.vol.ambience': 'Ambience',
  'set.vol.dialogue': 'Dialogue',
  'set.bindings': 'Key bindings',
  'set.bindings.hint': 'Select an action, then press a key or mouse button. Controller layout is fixed.',
  'set.reset': 'Reset to defaults',
  'set.press': 'Press a key…',
  'set.unbound': 'Unbound',
  'set.cancelhint': 'Press the new key or button. Esc or a left click cancels.',
  'set.swapped': '{other} now uses {key}.',
  'set.unbound_other': '{other} is now unbound.',

  'action.forward': 'Move forward',
  'action.back': 'Move back',
  'action.left': 'Move left',
  'action.right': 'Move right',
  'action.sprint': 'Sprint',
  'action.jump': 'Jump',
  'action.interact': 'Interact / talk',
  'action.attack': 'Attack',
  'action.heavy': 'Heavy attack',
  'action.block': 'Block',
  'action.dodge': 'Evasive step',
  'action.heal': 'Use poultice',
  'action.journal': 'Journal',
  'action.map': 'Map',
  'action.inventory': 'Inventory',
  'action.camLeft': 'Turn camera left',
  'action.camRight': 'Turn camera right',
  'action.quicksave': 'Quicksave',
  'action.quickload': 'Quickload',
  'action.pause': 'Pause / back',

  'controls.title': 'Controls',
  'controls.pad': 'Controller: left stick move · right stick look · A interact · X attack · Y heavy · B evasive step · LT block · RT sprint · LB jump · RB poultice · Back map · Start pause · D-pad ↑ journal · D-pad ↓ inventory. Menus: D-pad or left stick to move focus, A confirm, B back.',

  /* ---------- Debug ---------- */
  'debug.title': 'Debug and benchmark',
  'debug.note': 'For developers and playtest harnesses. Not part of the ordinary interface.',

  /* ---------- NPC titles and sleeping places ---------- */
  'npc.title.caravan_master': 'Caravan master',
  'npc.title.rillford_reeve': 'Reeve of Rillford · Hearth League',
  'npc.title.spring_steward': 'Waterkeeper of the spring · Templar',
  'npc.title.quarry_foreman': 'Quarry foreman · Marcher contract',
  'npc.title.maintenance_worker': 'Seasonal stoneworker · Rimeward',
  'npc.title.estate_steward': 'Estate steward · Marcher estate',
  'npc.title.ash_recorder': 'Recorder · Ash Witness',
  'npc.title.shrine_warden': 'Shrine warden · Templar',
  'npc.title.mill_hand': 'Mill hand · Rillford',
  'npc.title.quarry_hand': 'Quarry hand',
  'npc.title.village_baker': 'Baker · Rillford',
  'npc.sleeps.wagon': 'Sleeps in his wagon on the strand.',
  'npc.sleeps.reeve': 'Sleeps in the reeve’s house at the east end of the village.',
  'npc.sleeps.steward': 'Sleeps in the cell beside the shrine hall.',
  'npc.sleeps.foreman': 'Sleeps in the crew bunks at the quarry.',
  'npc.sleeps.worker': 'Sleeps at the inn in Rillford, once safe.',
  'npc.sleeps.steward_estate': 'Lodges in the office by the quarry gate.',
  'npc.sleeps.recorder': 'Camps near the ford.',
  'npc.sleeps.warden': 'Sleeps in the guard post beside the shrine hall.',
  'npc.sleeps.mill': 'Lives beside the mill.',
  'npc.sleeps.crew': 'Sleeps in the crew bunks at the quarry.',
  'npc.sleeps.baker': 'Lives above the bakery.',
};

const ALL: Record<string, string> = { ...EN, ...DIALOGUE_STRINGS };

/** Look up display text; missing keys are shown as the key so they are noticed, never silently blank. */
export function S(key: string, params?: Record<string, string | number>): string {
  let t = ALL[key];
  if (t === undefined) {
    if (typeof console !== 'undefined') console.warn(`missing string: ${key}`);
    return key;
  }
  if (params) for (const [k, v] of Object.entries(params)) t = t.replaceAll(`{${k}}`, String(v));
  return t;
}

export function hasString(key: string): boolean {
  return ALL[key] !== undefined;
}
