import { DIALOGUE_STRINGS } from './dialogue';

/**
 * Display text, keyed by stable identifiers so a localization pass touches one table.
 * Everything here is working text for the prototype and carries no canon weight.
 */
export const EN: Record<string, string> = {
  /* ---------- Titles and menus ---------- */
  'game.title': 'Tervain',
  'game.subtitle': 'The Grey Strand · The Deepwood · Bellwether Vale',
  'menu.affiliation': 'Templars of the Hegemony',
  'menu.music.play': 'Play menu music',
  'menu.music.gesture': 'Music starts after a click or key press. Adjust Master and Music in Settings.',
  'game.tagline': 'An empty shore. A forgotten name. A path beneath the old trees.',
  'menu.continue': 'Continue',
  'menu.new': 'New Game',
  'menu.load': 'Load',
  'menu.save': 'Save',
  'menu.settings': 'Settings',
  'menu.controls': 'Controls',
  'menu.about': 'About this build',
  'about.audioLicenses': 'World audio sources and license limits',
  'about.modelLicenses': '3D model credits and licenses',
  'menu.resume': 'Resume',
  'menu.quit': 'Quit to title',
  'menu.back': 'Back',
  'menu.close': 'Close',
  'menu.confirm': 'Confirm',
  'menu.cancel': 'Cancel',
  'menu.delete': 'Delete',
  'menu.deleteconfirm': 'Press again to delete',
  'menu.newconfirm': 'Start a new game? Your manual slots and quicksave are kept. The Autosave slot is replaced the first time the new game autosaves.',
  'menu.startanyway': 'Start new game',
  'menu.empty': 'Empty slot',
  'menu.slot.auto': 'Autosave',
  'menu.slot.quick': 'Quicksave',
  'menu.slot.slot-1': 'Slot 1',
  'menu.slot.slot-2': 'Slot 2',
  'menu.slot.slot-3': 'Slot 3',
  'menu.loadfailed': 'That save could not be loaded: {reason}',
  'menu.recovered.previous': 'The latest write was damaged, so the previous save was restored.',
  'menu.recovered.temporary': 'An interrupted write was recovered.',
  'menu.saved': 'Game saved ({slot}).',
  'menu.savefailed': 'Could not save: {reason}',
  'menu.savedAt': 'Saved {when}',
  'menu.save.slot': 'Save to {slot}',
  'menu.load.slot': 'Load {slot}',
  'menu.delete.slot': 'Delete damaged save in {slot}',
  'menu.deleteconfirm.slot': 'Confirm deletion of damaged save in {slot}',
  'menu.saveUnavailable': 'Your journey is not ready to save. Wait until the view is prepared.',
  'menu.loaded': 'Game loaded.',
  'menu.play': 'Click the view to look around · Press Esc to pause',
  'menu.loading': 'Raising the coast and the deepwood…',
  'loading.title.initial': 'A path beneath the old trees',
  'loading.title.rebuild': 'Returning to the woodland',
  'loading.phase.prepare': 'Preparing your journey',
  'loading.phase.woodland': 'Loading woodland',
  'loading.phase.residents': 'Loading residents',
  'loading.phase.models': 'Loading the landscape',
  'loading.phase.textures': 'Preparing the earth and stone',
  'loading.phase.terrain': 'Building terrain',
  'loading.phase.graphics': 'Preparing the view',
  'loading.phase.settlement': 'Raising the settlement',
  'loading.phase.physics': 'Preparing paths and shelter',
  'loading.phase.navigation': 'Opening woodland trails',
  'loading.count': '{completed} of {total}',
  'loading.rebuild.paused': 'Your journey is paused while the view changes.',
  'loading.tip.label': 'Along the trail',
  'loading.tip.explore': 'Old markers lead inland from the shore. Follow the woodland trail, and record your discoveries in the journal.',
  'loading.tip.hunt': 'One arrow to the head or two to the body brings woodland game down. Step beside your kill with a skinning knife to collect hide and meat.',
  'loading.tip.supplies': 'Rowan keeps a bow, knife and arrows beside the inland trail. Bring him meat for coin, or trade one hide for six arrows.',
  'loading.retry': 'Try again',
  'loading.failure.initial.title': 'Your journey could not begin.',
  'loading.failure.initial.message': 'The woodland could not be prepared. Try again to begin your journey.',
  'loading.failure.rebuild.title': 'The view could not be prepared.',
  'loading.failure.rebuild.message': 'Your journey is paused. Try again to continue.',
  'menu.webgl': 'Tervain needs WebGL. Try another browser or enable hardware acceleration.',
  'menu.savetime': '{day} · {phase} · {play}',
  'menu.day': 'Day {n}',
  'about.body':
    'Tervain {version} is a PC-focused exploration pre-alpha: a solitary arrival with no remembered name, a grey strand, dense old woodland and an inland settlement. Gather provisions, plants and salvage; manage your inventory and an initially empty ten-slot item and weapon bar; explore with a journal and a map that keeps your personal marker. Find the hunter’s supplies beside the inland trail, hunt animals with a bow, and skin your kills for hide and meat. Trade a hide for fresh arrows before returning to the forest. This build combines the world, movement and collision improvements with repaintable skinned characters. The opening uses environmental clues without conversation windows. The earlier water-dispute systems and dialogue graph remain for future work. The Wanderer, residents, animals and selected trees use supplied models adapted for Tervain; original scenery and material work complement them. The menu score is owner-supplied. The sound effects, ambience, score and voices in the world were partly generated with ElevenLabs (elevenlabs.io), and partly composed and synthesized in code for Tervain. Generated sources have recorded paid-plan provenance with service-specific limits. See world-audio-licenses.html for rights and commercial-release boundaries. Steam packaging and minimum PC requirements are not yet established. See docs/engineering/prototype.md for the implemented scope.',

  /* ---------- Silent arrival ---------- */
  'arrival.wake': 'Salt on your lips. No memory of your name, or how you reached this shore.',
  'arrival.controls': '{move} to walk · Click the view to look · {interact} to inspect · {journal} for your journal',
  'observe.caravan_master': 'The traveller checks a worn harness and the road ahead. You watch without interrupting.',
  'observe.rillford_reeve': 'A woman counts water pails beside the square. Her gaze returns to the still mill.',
  'observe.spring_steward': 'A keeper clears leaves from the spring with patient, practiced hands.',
  'observe.quarry_foreman': 'The foreman measures the idle cutting and folds a stained sheet of figures.',
  'observe.maintenance_worker': 'The stranded worker tests each foothold. The old maintenance path leads around the ledge.',
  'observe.estate_steward': 'A well-dressed steward keeps a ledger close and surveys the unloaded stone.',
  'observe.ash_recorder': 'A recorder dries ink beside the crossing, watching the valley rather than the road.',
  'observe.shrine_warden': 'The warden tends the threshold. Old stone and carefully swept roots share the same courtyard.',
  'observe.mill_hand': 'The mill hand watches the dry channel, then the silent wheel.',
  'observe.quarry_hand': 'A labourer rests beside unused tools. Fine pale dust covers the boots.',
  'observe.village_baker': 'The baker works with flour-dusted hands, setting small loaves to cool.',
  'observe.trail_hunter': 'Rowan sorts supplies beneath his lean-to. The butcher’s parcels and drying hides are bound for Rillford; travellers replenish their hunting kit at his bench.',

  /* ---------- HUD ---------- */
  'hud.health': 'Health',
  'hud.stamina': 'Stamina',
  'hud.exhausted': 'Winded',
  'hud.coin': 'Coin',
  'hud.objective': 'Suggested next step',
  'hud.guidance.off': 'Guidance is off in Settings.',
  'hud.time': 'Day {n} · {time}',
  'hud.saving': 'Saving…',
  'hud.locked': 'Locked',
  'hud.requires': 'Requires:',
  'hud.hold': 'Hold',
  'hud.interrupted': 'Interrupted',
  'hud.threat': 'Wind-up! Block, sidestep or back away.',
  'hud.fallen.title': 'You fall.',
  'hud.fallen.body': 'You wake at the last place you were safe. What you had already done is still done.',
  'hud.fps': '{fps} fps · {ms} ms',
  'hud.captions': 'Captions',

  /* ---------- Hunting ---------- */
  'animal.bear': 'Bear',
  'animal.lion': 'Lion',
  'animal.tiger': 'Tiger',
  'animal.wolf': 'Wolf',
  'animal.cat': 'Cat',
  'animal.dog': 'Dog',
  'animal.boar': 'Boar',
  'animal.stag': 'Red deer stag',
  'animal.deer': 'Deer',
  'item.hunting_bow': 'Hunting bow',
  'item.hunting_bow.desc': 'A plain wooden bow. Equip it, aim, draw and release to loose an arrow. One hit to the head or two to the body brings an animal down.',
  'item.arrow': 'Arrows',
  'item.arrow.desc': 'Ammunition for the hunting bow. One arrow is spent per shot. Exchange one animal hide for six arrows at the hunter’s supplies.',
  'item.skinning_knife': 'Skinning knife',
  'item.skinning_knife.desc': 'Keep it in your pack to skin a dead animal. Approach the carcass and choose Skin; collect its hide and meat after three seconds.',
  'item.animal_hide': 'Animal hide',
  'item.animal_hide.desc': 'Taken from a skinned animal. Exchange one hide for six arrows at the hunter’s supplies.',
  'item.raw_meat': 'Raw meat',
  'item.raw_meat.desc': 'Fresh meat wrapped in a scrap of cloth. A provision gathered from the hunt.',
  'pickup.hunter_bow': 'Take the hunting bow',
  'pickup.hunter_knife': 'Take the skinning knife',
  'pickup.hunter_arrows': 'Take the bundle of arrows',
  'hunting.title': 'The hunter’s field notes',
  'hunting.animal': 'animal',
  'hunting.draw': 'Bow draw',
  'hunting.ammo': '{arrows} arrows',
  'hunting.release': 'Release to shoot · {arrows} arrows',
  'hunting.no_arrows': 'No arrows · return to the hunter’s supplies',
  'hunting.bow_hint': '{aim} to aim · hold {draw}, then release to shoot · {arrows} arrows',
  'hunting.guide.controls': 'Equip the bow. Hold {aim} to aim, hold {draw} to draw, then release {draw} to shoot. One arrow to the head or two arrows to the body kills woodland game. Cats, dogs and the saddled caravan deer are protected companions.',
  'hunting.guide.harvest': 'Approach a dead animal with the skinning knife in your pack. Press {skin}, or choose Skin on screen, to skin it. Stay beside it for three seconds to collect its hide and meat. Moving or pressing Skin again cancels.',
  'hunting.guide.supplies': 'A bow, skinning knife and arrows rest on Rowan’s table beside the inland trail. Rowan buys meat for Rillford at two coins a cut; one hide buys six arrows. He trades from dawn until late evening.',
  'hunting.guide.blood': 'Reduced effects in Settings keeps blood subtle.',
  'hunting.skinning': 'Skinning',
  'hunting.skinning_name': 'Skinning {name}',
  'hunting.skin_hint': 'Collect hide and meat · takes 3 seconds',
  'hunting.skin_cancel_hint': 'Stay beside the carcass · move or press Skin again to cancel',
  'hunting.cancel_skin': 'Cancel skinning',
  'hunting.cancelled': 'Skinning interrupted. Nothing was collected.',
  'hunting.headshot': 'Head hit · the animal falls.',
  'hunting.body_hit': 'Body hit · one more arrow will bring it down.',
  'hunting.kill': 'The animal falls. Approach it to skin it.',
  'hunting.skinned': 'Collected hide and meat.',
  'hunting.rank.tracker': 'Rowan nods at your kills · Tracker: better trades, quicker skinning.',
  'hunting.rank.hunter': 'Word of your hunting spreads · Hunter: Rowan pays more for game.',
  'hunting.rank.master': 'Few in Rillford have taken so much game · Master hunter.',
  'hunting.rank.novice': 'Novice hunter.',
  'hunting.restocked': 'One hide traded for six arrows.',
  'hunting.need_bow': 'Equip your hunting bow first.',
  'hunting.need_arrow': 'Your quiver is empty. Trade a hide for arrows at the hunter’s supplies.',
  'hunting.need_knife': 'Take the skinning knife from the hunter’s supplies first.',
  'hunting.animal_alive': 'The animal must be dead before you can skin it.',
  'hunting.already_skinned': 'You have already collected this animal’s hide and meat.',
  'hunting.too_far': 'Step closer to the carcass.',
  'hunting.skin_need_footing': 'Stand on firm ground beside the carcass.',
  'hunting.skin_put_down': 'Put down the held object before skinning.',
  'hunting.skin_release_bow': 'Release the bow before skinning.',
  'hunting.skin_busy': 'Finish your current action before skinning.',
  'hunting.skin_wait': 'Wait for the animal to settle.',
  'hunting.skin_blocked': 'Move around the obstacle to reach the carcass.',
  'hunting.need_hide': 'Bring one animal hide to exchange for six arrows.',
  'hunting.arrow_quiver_full': 'Your quiver is full.',
  'hunting.unknown_animal': 'There is no animal to skin here.',
  'hunting.peaceful_animal': 'Cats and dogs are peaceful companions.',
  'hunting.invalid_animal_hit': 'That arrow did not hit an animal.',
  'hunting.supplies': 'Hunter’s supplies',
  'hunting.objective.kit': 'Take the bow, knife and arrows from Rowan’s table beside the inland trail.',
  'hunting.objective.equip': 'Equip the hunting bow from your inventory or a quick slot.',
  'hunting.objective.hunt': 'Follow the woodland trail. Aim for the head, or land two arrows in the body.',
  'hunting.objective.skin': 'Approach your kill and Skin it to gather hide and meat.',
  'hunting.objective.restock': 'Bring game to Rowan for Rillford; sell meat for coin or trade a hide for six arrows.',
  'prompt.skin': 'Skin {name}',
  'prompt.sell_game_meat': 'Sell game for Rillford · 1 meat → 2 coins',
  'hunting.meat_sold': 'Game delivered for Rillford · +{coin} coins',
  'journal.obs.game_provisions': 'I sold game to Rowan Vale for Rillford’s kitchens. He pays two coins a cut; hides buy replacement arrows at his woodland camp.',
  'hunting.need_meat': 'Bring fresh game from your hunt to Rowan.',
  'hunting.hunter_resting': 'Rowan is resting. Return after dawn.',
  'prompt.hunter_supplies': 'Read the hunter’s field notes',
  'prompt.restock_arrows': 'Trade 1 hide for 6 arrows',
  'prompt.ride': 'Ride the saddled deer',
  'prompt.dismount': 'Dismount',
  'inspect.hunter_supplies': 'A bow rests on the table beside a knife and a bundle of arrows. A note reads: “Draw steadily. Aim for the head. Bring a hide back and take six more arrows.”',
  'board.hunting': 'HUNTER’S SUPPLIES: take the bow, skinning knife and arrows from Rowan’s table beside the inland trail. A hide buys six arrows. One arrow to the head or two to the body will bring an animal down.',

  /* ---------- Prompts ---------- */
  'prompt.talk': 'Observe {name}',
  'prompt.observe': 'Observe {name}',
  'prompt.inspect': 'Inspect',
  'prompt.inspect.arrival_wreckage': 'Inspect the stranded hull',
  'prompt.inspect.templar_waymarker': 'Examine the old trail marker',
  'prompt.inspect.dry_channel': 'Inspect the dry household channel',
  'prompt.inspect.spring_sediment': 'Inspect the silt at the spring intake',
  'prompt.inspect.town_diversion': "Follow the village's side channel",
  'prompt.inspect.quarry_seep': 'Follow the quarry seep',
  'prompt.inspect.sluice_crack': 'Inspect the support beside the gate',
  'prompt.inspect.inspection_log': 'Read the inspection log',
  'prompt.inspect.noticeboard': 'Read the noticeboard',
  'prompt.inspect.wetland_fish': 'Look at the wetland shallows',
  'prompt.inspect.saltward_kit': 'Examine the measuring kit',
  'prompt.pickup.quarry_brace': 'Take the spare sluice brace',
  'prompt.pickup.quarry_wrench': 'Take the gate wrench',
  'prompt.pickup.side_path_cache': 'Open the hidden cache',
  'prompt.pickup.wreck_blade': 'Take the sword from the wreck',
  'prompt.lever': 'Pull the maintenance lever',
  'prompt.sluice': 'Work the sluice controls',
  'prompt.archive_door.locked': 'Try the archive door',
  'prompt.archive_shutter': 'Force the archive shutter',
  'prompt.ledger': 'Read the rotation ledger',
  'prompt.rite': 'Perform the spring rite',
  'prompt.rite.notaught': 'A shrine basin',
  'prompt.check_channel': 'Check the household channel',
  'prompt.check_mill': 'Check the mill',
  'prompt.mill_note': 'Watch the mill wheel',
  'prompt.close': 'Step back',

  /* ---------- Toasts and interaction results ---------- */
  'toast.journal': 'Journal updated',
  'toast.evidence.observed': 'You noted: {name}',
  'toast.evidence.testimony': 'Reported: {name}',
  'toast.evidence.derived': 'You can now conclude: {name}',
  'toast.evidence.document': 'You found: {name}',
  'toast.item.gain': '+{qty} {name}',
  'toast.item.lose': '−{qty} {name}',
  'toast.place': 'Discovered: {name}',
  'toast.skill': 'Learned: {name}',
  'toast.gate.stable': 'The gate is braced. It holds — but it does not make more water.',
  'toast.gate.jammed': 'The gate jams. Less water than before, and a repair still to do.',
  'toast.surge': 'The gate kicks back. You take a hard knock.',
  'toast.calm': 'The flow settles. The gate should be gentle for a while.',
  'toast.rite.need': 'The basin is quiet. Its rite belongs to a later part of your journey.',
  'toast.rite.done': 'The rite is done. The flow will stay calm for about {min} minutes.',
  'toast.archive.locked': 'The archive is locked. The woodland road remains open; entering here is optional.',
  'toast.archive.open': 'The archive door is open.',
  'toast.archive.forced': 'You force the shutter and slip inside.',
  'toast.archive.sealed_now': 'Behind you, someone nails the archive shut.',
  'toast.archive.sealed': 'The shutter has been nailed shut.',
  'toast.archive.withdrawn': 'Access has been withdrawn.',
  'toast.ledger': 'You read the old rotation ledger.',
  'toast.shortcut': 'The maintenance gate swings open. Somewhere above, someone starts walking.',
  'toast.cleared': 'The thornback is down. The ledge is clear.',
  'toast.shortcut.rescued': 'Ila Rusk is on her way down the old track.',
  'toast.rescued': 'Ila Rusk is safe.',
  'toast.report': 'Word has reached {name}.',
  'toast.settled': 'The valley has a new arrangement. Rewards received.',
  'toast.applying': 'The channels are still finding their level. Give it a little longer.',
  'toast.poultice': 'You feel steadier.',
  'toast.nothing': 'Nothing more to do here.',
  'toast.need.brace': 'You need a brace to set against the cracked support.',
  'toast.need.wrench': 'You need a wrench to turn the gate wheel.',
  'toast.need.understanding': 'Inspect the cracked support to understand how to brace it safely.',
  'toast.need.payment': 'You cannot afford that.',
  'toast.nowitness': 'That would be an emergency allocation — it lapses unless it is reviewed.',
  'toast.boundary': 'The track ends in rough heath. There is no safe path onward.',
  'toast.noheal': 'You are not hurt.',
  'toast.nopoultice': 'You have no poultice.',
  'toast.settings': 'Settings saved.',
  'toast.bindconflict': '{key} is already used for “{action}”. Press it again to swap the two, or choose another key.',
  'toast.bound': '{action} is now {key}.',
  'toast.warden.hey': 'Hey! Who is there?',
  'toast.unlocked.key': 'You unlock the archive with the borrowed key.',
  'toast.brace.taken': 'Rillford will want this brace back in one piece.',
  'toast.cache': 'A small store of coin, left by someone who never came back for it.',
  'toast.blade': 'Salt has eaten at it, but the edge still holds. Better than bare hands.',
  'toast.caption.bell': '[The drought bell tolls]',
  'toast.caption.bell.allclear': '[A bright, even peal]',

  'narr.ledger':
    'The ledger is a thick, water-stained book. Page after page records the same arrangement: the mill and its households drew the channel by day, the quarry by night, and a waterkeeper, a reeve and a foreman signed each season’s schedule together. Someone has added, in a smaller hand: “Households gave labor and carried water here too — uncounted.”',

  /* ---------- Sluice panel ---------- */
  'sluice.title': 'The Bellwether sluice',
  'sluice.state.damaged': 'Damaged. The support beside the gate is cracked and the leaf hangs askew.',
  'sluice.state.jammed': 'Jammed. Someone forced the gate and it seized.',
  'sluice.state.stabilized': 'Braced. The gate can be worked safely — but stabilizing does not create more water.',
  'sluice.brace': 'Brace the gate',
  'sluice.brace.desc': 'Set the brace against the cracked support and turn the wheel a quarter at a time. Consumes the brace.',
  'sluice.brace.safe.rite': 'The spring rite is holding the flow calm: this should be gentle.',
  'sluice.brace.safe.procedure': "Ila's procedure: from the downstream side, brace first, quarter turns. This should be gentle.",
  'sluice.brace.unsafe': 'Without the rite or a known procedure the gate may kick back: expect a hard knock.',
  'sluice.force': 'Force the gate open',
  'sluice.force.desc': 'Open it now, without bracing.',
  'sluice.force.warn': 'This could jam the gate and make the shortage worse. The valley will still need it repaired.',
  'sluice.force.confirm': 'Force it anyway',
  'sluice.commit.title': 'Decide how the water is shared',
  'sluice.commit.intro': 'Every choice keeps the minimum flow for drinking and for the wetland. Nothing here makes more water — it only decides who goes without.',
  'sluice.commit.locked': 'Brace the gate first: the gate has to hold before anyone can rely on it.',
  'sluice.commit.confirm': 'Commit to this',
  'sluice.commit.back': 'Not yet',
  'sluice.alloc.rillford': 'Prioritize Rillford',
  'sluice.alloc.quarry': 'Prioritize the quarry',
  'sluice.alloc.rotation': 'Set a witnessed rotation',
  'sluice.alloc.rillford.gain': 'Household channel recovers; the mill returns to restricted service.',
  'sluice.alloc.rillford.cost': 'Quarry operations pause. Foreman Kest and his unpaid crew will be unhappy.',
  'sluice.alloc.rillford.kind': 'Emergency allocation — it lapses unless it is reviewed.',
  'sluice.alloc.quarry.gain': 'Quarry resumes limited work; the estate delivery stays possible.',
  'sluice.alloc.quarry.cost': 'The mill stays closed and households keep rationing. Rillford will protest.',
  'sluice.alloc.quarry.kind': 'Emergency allocation — it lapses unless it is reviewed.',
  'sluice.alloc.rotation.gain': 'Mill and households by day, quarry by night: both get something.',
  'sluice.alloc.rotation.cost': 'Neither meets full demand. Supervision costs labor, and night shifts cost sleep.',
  'sluice.alloc.rotation.kind': 'Recognized under the Accord: witnessed by the reeve, the foreman and the waterkeeper.',
  'sluice.alloc.rotation.need.evidence_both_needs': 'You must have seen both what the village needs and what the quarry needs.',
  'sluice.alloc.rotation.need.consent_mara': 'The reeve has not agreed to a rotation.',
  'sluice.alloc.rotation.need.consent_edda': 'The waterkeeper has not agreed to stand as witness.',
  'sluice.alloc.rotation.need.consent_darin': 'The foreman has not agreed to a rotation.',
  'sluice.alloc.caretaker': 'One decision-maker is gone: a caretaker will stand in, and the rotation carries less weight.',
  'sluice.brace.working': 'Bracing the gate…',

  /* ---------- Noticeboard ---------- */
  'board.title': 'RILLFORD NOTICES',
  'board.bell_drought': 'The drought bell has been rung. Households: one bucket a day at the well until further notice. — M. Venn, Reeve',
  'board.gate_jammed': 'The upper sluice gate has been forced and is jammed. It needs a brace and a careful hand.',
  'board.gate_braced': 'The upper sluice gate is braced. The reeve will announce how the flow is to be shared.',
  'board.alloc_rillford': 'By emergency allocation the household channel and mill take priority. The quarry pauses.',
  'board.alloc_quarry': 'By emergency allocation the quarry takes priority under the estate contract. Households ration.',
  'board.alloc_rotation': 'ROTATION: mill and households by day, quarry by night. Witnessed by the reeve, the foreman and the waterkeeper.',
  'board.alloc_rotation_partial': 'ROTATION: mill and households by day, quarry by night. Witnessed by the decision-makers who remain and by a caretaker standing in for the one who is absent.',
  'board.public_statement': 'A decision-maker is absent. This allocation is recorded here in their place and acknowledged by a caretaker.',
  'board.account_flood_only': 'Account of the shortage: the late-thaw flood damaged the sluice. (Nothing further is recorded.)',
  'board.rotation_witnesses': 'The old rotation is honored. The record is open to anyone who wishes to read it.',
  'board.emergency_expires': 'An emergency allocation lapses unless it is reviewed. Review to be called by the reeve and the waterkeeper.',

  /* ---------- Visible details ---------- */
  'detail.channel_full': 'The household channel runs full.',
  'detail.mill_turning': 'The mill wheel is turning.',
  'detail.quarry_idle': 'The quarry crew is idle and unpaid.',
  'detail.quarry_working': 'Stone is being cut and loaded.',
  'detail.mill_still_queue': 'The mill is still and the well has a queue.',
  'detail.contract_guard': 'A contract guard holds the sluice door.',
  'detail.schedule_posted': 'A rotation schedule is posted.',
  'detail.alternating_work': 'Mill by day, quarry by night.',
  'detail.tired_night_crew': 'The night crew looks tired.',

  /* ---------- Inspect notices ---------- */
  'inspect.arrival_wreckage': 'Splintered boards. Salt-stiff rope. No name left on the hull. You remember none of it.',
  'inspect.templar_waymarker': 'Trail notches cut into mossed stone. The worn track continues inland beneath the canopy.',
  'inspect.dry_channel': 'The channel behind the mill is dry to the mud. Cracked banks, a stranded reed bucket — households have been drawing from the well only.',
  'inspect.spring_sediment': 'Grey flood silt lies thick across the intake channels. The spring itself still wells up — the flow is thin because the channels are choked, not because the spring has failed.',
  'inspect.town_diversion': 'A small side gate above the fields has been cut into the bank, its timbers fresh. It takes a steady share of what reaches the village.',
  'inspect.quarry_seep': 'Water weeps from the quarry cut into the seep channel. The rock nearby is cracked; the cutting has been extended past the old line.',
  'inspect.sluice_crack': 'The stone support beside the gate has fresh fractures, pale against weathered stone. The gate leaf sits askew against it. It would not survive being forced.',
  'inspect.inspection_log': 'The waterkeeper’s inspection log skips the week before the thaw. The next entry was written after the flood.',
  'inspect.noticeboard': 'The noticeboard has several notices.',
  'inspect.wetland_fish': 'Fish nests in the shallows have been left bare and dry along the edge. The wetland is getting less water than it needs.',
  'inspect.saltward_kit': 'A brass measuring level and a marked staff, annotated in an angular southern hand. The notes explain how to read safe operating levels and alternating service periods.',

  /* ---------- Items ---------- */
  'item.coin': 'Coin',
  'item.coin.desc': 'Small change from three regions.',
  'item.rusted_sword': 'Rusted sword',
  'item.rusted_sword.desc': 'A plain arming sword from the wreck on the strand, pitted by salt. Equip it to carry it on your hip and draw it in a fight.',
  'item.sluice_brace': 'Spare sluice brace',
  'item.sluice_brace.desc': "Rillford's spare timber brace, lent to the quarry. Sets against a cracked support.",
  'item.gate_wrench': 'Gate wrench',
  'item.gate_wrench.desc': 'A long iron wrench for turning the sluice wheel. Not used up.',
  'item.archive_key': 'Archive key',
  'item.archive_key.desc': "Warden Harrow's key, borrowed on your word.",
  'item.votive_reed': 'Votive reed',
  'item.votive_reed.desc': 'A blessed reed for the spring rite. There is no second.',
  'item.poultice': 'Poultice',
  'item.poultice.desc': 'A clean cloth dressing of crushed herbs. Restores 40 health; consumed on use.',
  'item.shore_apple': 'Shore apple',
  'item.shore_apple.desc': 'A small tart apple from the coastal groves. Restores 8 health; consumed on use.',
  'item.bread': 'Brown bread',
  'item.bread.desc': 'A rough barley loaf, still good beneath its crust. Restores 16 health; consumed on use.',
  'item.healing_herb': 'Healing herb',
  'item.healing_herb.desc': 'Tender leaves gathered for a fresh dressing. Restores 24 health; consumed on use.',
  'item.field_mushroom': 'Field mushroom',
  'item.field_mushroom.desc': 'A firm edible mushroom from the woodland verge. Restores 10 health; consumed on use.',
  'item.iron_scrap': 'Iron scrap',
  'item.iron_scrap.desc': 'Weathered iron worth carrying. A material; no crafting or use action is available yet.',
  'item.league_sash': 'Hearth League sash',
  'item.league_sash.desc': 'Worn by those the village recognizes.',
  'item.contract_band': 'Marcher contract band',
  'item.contract_band.desc': 'Identifies a hand who kept the estate contract running.',
  'item.witness_cord': "Witness's cord",
  'item.witness_cord.desc': 'A woven cord from the rotation signing. Recognized by both sides.',
  'pickup.brace': 'Spare sluice brace',
  'pickup.wrench': 'Gate wrench',
  'pickup.cache': 'Hidden cache',
  'pickup.wreck_blade': 'Rusted sword',
  'prompt.pickup': 'Take {name}',
  'skill.steady_guard': 'Steady Guard',
  'skill.steady_guard.desc': 'Holding your guard costs 40% less stamina.',

  /* ---------- Journal ---------- */
  'journal.title': 'Journal',
  'journal.observed': 'Observed',
  'journal.reported': 'Reported',
  'journal.concluded': 'Concluded',
  'journal.questions': 'Open questions',
  'journal.places': 'Places',
  'journal.people': 'People',
  'journal.status': 'Where things stand',
  'journal.empty': 'Nothing yet.',
  'journal.place.verified': 'Visited',
  'journal.place.claimed': 'Told of (approximate)',
  'journal.place.unknown': 'Unknown',
  'journal.person.met': 'Met',
  'journal.person.unmet': 'Not yet met',
  'journal.person.absent': 'Absent',
  'journal.status.unseen': 'You have just arrived. Something is wrong with the water.',
  'journal.status.arrival': 'You woke alone on the strand with no memory of your name or passage. Find a way inland.',
  'journal.status.investigating': 'You are learning why the water has failed and who needs it.',
  'journal.status.decision_ready': 'The gate holds. It is time to decide how the reduced flow is shared.',
  'journal.status.committed': 'The arrangement is in place. See it reach the village.',
  'journal.status.settled': 'The valley has a settled arrangement, and you have earned your place in it.',
  'journal.lead.arrival': 'A worn track leaves the empty shore and enters the old woodland. You can move at your own pace and record what you find.',
  'journal.lead.bell': 'You reached an inland settlement with a still mill and thinning channels. Look at the watercourse.',
  'journal.lead.sluice': 'You came across the damaged sluice above the village. Find out who depends on it.',
  'journal.lead.dry_channel': 'A dry channel behind the mill shows what the village has lost.',
  'journal.lead.spring': 'The spring intake is choked. You began at the source.',
  'journal.lead.diversion': 'You found a side channel drawing water from the village stream.',
  'journal.lead.seep': 'You found a seep in the quarry cut.',
  'journal.lead.worker': 'Someone is stranded at the Cut and needs help.',
  'journal.lead.reeve': 'Reeve Mara Venn told you what has happened to Rillford.',
  'journal.lead.steward': 'Sister Edda Sorn told you about the spring.',
  'journal.lead.quarry_worker': 'The quarry crew is stopped for want of water.',
  'journal.lead.gate': 'You put your hands on the sluice gate.',
  'journal.lead.evidence': 'You found something worth writing down.',
  'journal.ev.dry_channel.observed': 'The household channel behind the mill is dry; Rillford has a real shortage.',
  'journal.ev.dry_channel.reported': 'The reeve says households are down to a bucket a day and the mill stands idle.',
  'journal.ev.reduced_spring_flow.observed': 'Flood silt chokes the spring intake. The flow is thin because the channels are obstructed, not because the spring is failing.',
  'journal.ev.reduced_spring_flow.reported': 'Ila saw silt across the intake and a spring that still wells up: the flow is obstructed.',
  'journal.ev.diversion_and_seep.observed': 'Both a village side gate and quarry seepage draw on the same reduced flow.',
  'journal.ev.diversion_and_seep.reported': 'Both the reeve and the foreman admit their share in the shortage.',
  'journal.ev.cracked_sluice.observed': 'The support beside the sluice gate is cracked. Forcing the gate open is dangerous.',
  'journal.ev.cracked_sluice.reported': 'Sister Edda says the support cracked in the flood and the gate could give way.',
  'journal.ev.rotation_ledger.observed': 'An old ledger shows a rotation between mill and quarry that was once kept and witnessed.',
  'journal.ev.rotation_ledger.reported': 'An old rotation between mill and quarry is said to have existed.',
  'journal.ev.worker_testimony.observed': "Ila Rusk's account of the gate: brace first, quarter turns from downstream.",
  'journal.ev.worker_testimony.reported': 'Ila Rusk says fresh fractures, silt at the intake, and the seep feeding the wrong channel — and how to close the gate safely.',
  'journal.claim.claim_foreman_spring_failing': 'The foreman says the spring is failing.',
  'journal.claim.claim_steward_sediment': 'Sister Edda says sediment, not failure, is choking the spring.',
  'journal.claim.claim_reeve_promised_relief': 'The reeve says she promised more relief than the flow can carry.',
  'journal.claim.claim_reserve_sufficient': 'The estate steward says the repair reserve is sufficient.',
  'journal.claim.reserve_empty': 'The estate steward admits the repair reserve is empty.',
  'journal.claim.edda_admits_deferral': 'Sister Edda admits she deferred the sluice inspection.',
  'journal.claim.reeve_admits_diversion': 'The reeve admits opening a side gate without witnesses.',
  'journal.claim.foreman_admits_seep': 'The foreman admits extending the cutting after permission ran out.',
  'journal.claim.told_ledger': 'The recorder says an old rotation ledger sits in the shrine archive.',
  'journal.obs.saw_seep': 'Water seeps from the quarry cut into the seep channel.',
  'journal.obs.saw_diversion': 'A fresh side gate on the village stream draws off water above the fields.',
  'journal.obs.saw_inspection_gap': 'The sluice inspection log skips the week before the thaw.',
  'journal.obs.saw_fish_nests': 'The wetland shallows are drying at the edge; fish nests lie bare.',
  'journal.obs.saw_saltward_kit': 'A Saltward measuring kit describes safe levels and alternating service periods.',
  'journal.obs.arrival_wreckage': 'A small stranded hull is broken and nameless. Nothing on it recalls the voyage to me.',
  'journal.obs.templar_waymarker': 'Someone maintained this woodland path. Old notches mark its direction beneath moss and roots.',
  'journal.q.spring_failing_or_silted': 'The foreman says the spring is failing. Is it failing — or obstructed? Look at the intake.',
  'journal.q.reserve': 'The steward called the reserve “sufficient”, then admitted it was empty. Who pays for the repair?',
  'journal.q.relief': 'The reeve promised relief the flow cannot carry. What will actually happen if the gate is braced?',
  'journal.c.sediment_not_failure': 'The spring is silted, not failing: the foreman was wrong about the cause.',
  'journal.c.one_diversion_insufficient': 'Closing one diversion cannot restore the former supply.',
  'journal.c.brace_first': 'The gate must be braced before anyone opens it.',
  'journal.c.gate_jammed': 'The gate is jammed. It still needs bracing — and the shortage is worse for now.',
  'journal.c.gate_stable': 'The gate holds. The reduced flow now has to be shared.',
  'journal.c.precedent': 'A rotation has been kept before. It can be again.',
  'journal.c.alloc_rillford': 'You gave Rillford priority. The quarry pays for it.',
  'journal.c.alloc_quarry': 'You gave the quarry priority. The village pays for it.',
  'journal.c.alloc_rotation': 'You set a witnessed rotation. Both sides give something up.',
  'journal.c.emergency_expires': 'Emergency allocations lapse unless reviewed; nobody owns the water for having held the gate.',
  'journal.c.account_misleading': 'The public account leaves out what you found. It is not the whole truth.',
  'journal.c.caretaker_witness': 'A caretaker stood in as witness for an absent decision-maker.',

  /* ---------- Inventory and skills ---------- */
  'inv.title': 'Inventory',
  'inv.empty': 'Nothing carried.',
  'inv.use': 'Use',
  'inv.skills': 'Skills',
  'inv.noskills': 'No training yet.',

  /* ---------- Map ---------- */
  'map.title': 'The Grey Strand, Deepwood and Bellwether Vale',
  'map.you': 'You',
  'map.suggested': 'Suggested next stop',
  'map.approx': 'approximate',
  'map.note': 'Hand-drawn from what you have seen and been told.',
  'place.shore': 'The Grey Strand',
  'place.lantern_point': 'Lantern Point',
  'place.deepwood': 'The Deepwood',
  'place.overlook': 'The Overlook',
  'place.rillford': 'Rillford',
  'place.ford': 'The Ford',
  'place.spring_shrine': 'Spring Shrine',
  'place.sluice': 'The Sluice',
  'place.quarry': 'The Quarry',
  'place.the_cut': 'The Cut',
  'place.archive': 'The Archive',

  /* ---------- Dialogue UI ---------- */
  'dlg.continue': 'Continue',
  'dlg.leave': 'Leave',
  'dlg.intent.ask': 'Ask',
  'dlg.intent.offer': 'Offer',
  'dlg.intent.warn': 'Warn',
  'dlg.intent.persuade': 'Persuade',
  'dlg.intent.accuse': 'Accuse',
  'dlg.intent.agree': 'Agree',
  'dlg.intent.leave': 'Leave',
  'dlg.intent.train': 'Train',
  'dlg.intent.commit': 'Commit',
  'dlg.failed': 'That did not work: {reason}',
  'dlg.choose': 'Choose a reply',

  /* ---------- Requirements ---------- */
  'req.evidence': 'You have: {name}',
  'req.fact': 'You have seen or learned: {name}',
  'req.item': 'You carry: {name}',
  'req.item.n': 'You carry {n}× {name}',
  'req.trust': 'They trust you more',
  'req.any': 'One of: {list}',
  'req.not': 'A condition is not yet met',
  'req.anyDefeated': 'You have proven yourself against something dangerous',
  'req.skill': 'You have learned the skill',
  'req.phase': 'The dispute has progressed further',
  'req.generic': 'Something you have not yet done',
  'req.fact.saw_diversion': 'the village side channel',
  'req.fact.saw_seep': 'the quarry seep',
  'req.fact.saw_sluice_damage': 'the damaged sluice',
  'req.fact.saw_inspection_gap': 'the missing inspection entry',
  'req.fact.edda_permission': "Sister Edda's permission",
  'req.fact.darin_humiliated': 'a rift with the foreman',
  'evidence.dry_channel': 'A dry household channel',
  'evidence.reduced_spring_flow': 'Reduced spring flow',
  'evidence.diversion_and_seep': 'Town diversion and quarry seepage',
  'evidence.cracked_sluice': 'A cracked sluice support',
  'evidence.rotation_ledger': 'The old rotation ledger',
  'evidence.worker_testimony': "Ila's testimony",

  /* ---------- Guidance hints ---------- */
  'hint.search_wreck': 'You have nothing to fight with. Search the old wreck on the beach, north of where you woke.',
  'hint.find_woodland_track': 'Follow the worn track inland, toward the old trees.',
  'hint.follow_woodland_track': 'Stay with the woodland track. A clearing lies further inland.',
  'hint.walk_to_rillford': 'Follow the road down into Rillford.',
  'hint.look_around': 'Look at the channel behind the still mill.',
  'hint.see_dry_channel': 'Look at the dry channel behind the mill.',
  'hint.see_spring': 'Go up to the spring and look at the intake.',
  'hint.see_sluice': 'Look at the damaged sluice above the village.',
  'hint.see_quarry': 'Follow the village diversion and the quarry seep.',
  'hint.get_brace': 'A spare brace and a wrench lie in the quarry yard.',
  'hint.stabilize': 'Bring the brace and wrench to the sluice and set the gate.',
  'hint.decide': 'At the sluice controls, decide how the reduced flow is shared.',
  'hint.check_result': 'Go and see the water reach the village.',
  'hint.settled': 'The valley is settled. Explore the woodland — or stay a while.',
  'hint.jammed': 'The gate is jammed. Brace it at the sluice.',
  'hint.rescue': 'Someone is stranded at the Cut.',

  /* ---------- Settings ---------- */
  'set.title': 'Settings',
  'set.display': 'Display and comfort',
  'set.text': 'Text size',
  'set.reduced': 'Reduced motion',
  'set.reduced.desc': 'Steadier camera; freezes falling leaves, water waves and menu animation.',
  'set.contrast': 'High-contrast interface',
  'set.contrast.desc': 'Opaque panels and stronger outlines.',
  'set.effects': 'Reduced effects',
  'set.effects.desc': 'Simpler water reflections and solid interface surfaces.',
  'set.brightness': 'Night and shade brightness',
  'set.quality': 'Graphics quality',
  'set.quality.low': 'Low',
  'set.quality.medium': 'Medium',
  'set.quality.high': 'High',
  'set.quality.note': 'Changing quality reloads the valley (your position is kept).',
  'set.guidance': 'Show suggested next step',
  'set.fps': 'Show frame timing',
  'set.framecap': 'Limit to 60 frames a second',
  'set.framecap.desc': 'Keeps a fast display from working the graphics card harder than the game needs.',
  'set.barks': 'Show ambient remarks',
  'set.captions': 'Captions for important sounds',
  'set.controls': 'Input',
  'set.sensitivity': 'Look sensitivity',
  'set.invert': 'Invert vertical look',
  'set.toggleSprint': 'Sprint is a toggle',
  'set.toggleBlock': 'Block is a toggle',
  'set.audio': 'Sound',
  'set.vol.master': 'Master',
  'set.vol.music': 'Music',
  'set.vol.effects': 'Effects',
  'set.vol.ambience': 'Ambience',
  'set.vol.dialogue': 'Dialogue',
  'set.bindings': 'Key bindings',
  'set.bindings.hint': 'Select an action, then press a key or mouse button. Controller layout is fixed.',
  'set.reset': 'Reset to defaults',
  'set.press': 'Press a key…',
  'set.unbound': 'Unbound',
  'set.cancelhint': 'Press the new key or button. Esc or a left click cancels.',
  'set.swapped': '{other} now uses {key}.',
  'set.unbound_other': '{other} is now unbound.',

  'action.forward': 'Move forward',
  'action.back': 'Move back',
  'action.left': 'Move left',
  'action.right': 'Move right',
  'action.sprint': 'Sprint',
  'action.jump': 'Jump',
  'action.interact': 'Inspect / interact',
  'action.skin': 'Skin',
  'action.grab': 'Lift / drop a loose object',
  'action.throw': 'Throw a held object',
  'action.attack': 'Attack / draw bow',
  'action.heavy': 'Heavy attack',
  'action.block': 'Block / aim bow',
  'action.dodge': 'Evasive step',
  'action.heal': 'Use poultice',
  'action.journal': 'Journal',
  'action.map': 'Map',
  'action.inventory': 'Inventory',
  'action.camLeft': 'Turn camera left',
  'action.camRight': 'Turn camera right',
  'action.quicksave': 'Quicksave',
  'action.quickload': 'Quickload',
  'action.pause': 'Pause / back',

  'controls.title': 'Controls',
  'controls.pad': 'Controller: left stick move · right stick look · A interact · X melee attack · Y heavy · B evasive step · LT block / aim bow · RT sprint / hold to draw bow, release to shoot · LB jump · RB poultice · Back map · Start pause · D-pad ↑ journal · D-pad ↓ inventory · D-pad ← Skin. Menus: D-pad or left stick to move focus, A confirm, B back.',

  /* ---------- Debug ---------- */
  'debug.title': 'Debug and benchmark',
  'debug.note': 'For developers and playtest harnesses. Not part of the ordinary interface.',

  /* ---------- NPC titles and sleeping places ---------- */
  'npc.title.caravan_master': 'Caravan master',
  'npc.title.rillford_reeve': 'Reeve of Rillford · Hearth League',
  'npc.title.spring_steward': 'Waterkeeper of the spring · Templar',
  'npc.title.quarry_foreman': 'Quarry foreman · Marcher contract',
  'npc.title.maintenance_worker': 'Seasonal stoneworker · Rimeward',
  'npc.title.estate_steward': 'Estate steward · Marcher estate',
  'npc.title.ash_recorder': 'Recorder · Ash Witness',
  'npc.title.shrine_warden': 'Shrine warden · Templar',
  'npc.title.mill_hand': 'Mill hand · Rillford',
  'npc.title.quarry_hand': 'Quarry hand',
  'npc.title.village_baker': 'Baker · Rillford',
  'npc.title.trail_hunter': 'Hunter and provisioner · Rillford road',
  'npc.sleeps.hunter': 'A bedroll at the hunter’s roadside camp.',
  'npc.sleeps.wagon': 'Sleeps in his wagon on the strand.',
  'npc.sleeps.reeve': 'Sleeps in the reeve’s house at the east end of the village.',
  'npc.sleeps.steward': 'Sleeps in the cell beside the shrine hall.',
  'npc.sleeps.foreman': 'Sleeps in the crew bunks at the quarry.',
  'npc.sleeps.worker': 'Sleeps at the inn in Rillford, once safe.',
  'npc.sleeps.steward_estate': 'Lodges in the office by the quarry gate.',
  'npc.sleeps.recorder': 'Camps near the ford.',
  'npc.sleeps.warden': 'Sleeps in the guard post beside the shrine hall.',
  'npc.sleeps.mill': 'Lives beside the mill.',
  'npc.sleeps.crew': 'Sleeps in the crew bunks at the quarry.',
  'npc.sleeps.baker': 'Lives above the bakery.',
};

const ALL: Record<string, string> = { ...EN, ...DIALOGUE_STRINGS };

/** Look up display text; missing keys are shown as the key so they are noticed, never silently blank. */
export function S(key: string, params?: Record<string, string | number>): string {
  let t = ALL[key];
  if (t === undefined) {
    if (typeof console !== 'undefined') console.warn(`missing string: ${key}`);
    return key;
  }
  if (params) for (const [k, v] of Object.entries(params)) t = t.replaceAll(`{${k}}`, String(v));
  return t;
}

export function hasString(key: string): boolean {
  return ALL[key] !== undefined;
}
