#!/usr/bin/env node
/**
 * Regenerate src/presentation/assets/modelFiles.ts: the size and SHA-256 of every GLB under public/models (A68).
 *
 *   node tools/model-files.mjs
 *
 * The game uses the table to keep unchanged models in the browser's Cache Storage across deploys (hosted models have a
 * new address with every build). tests/presentation/modelFiles.test.ts fails while the table and the files disagree:
 * run this after adding, replacing or removing a model.
 */
import { createHash } from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const models = path.join(root, 'public', 'models');

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(full) : entry.name.endsWith('.glb') ? [full] : [];
  });
}

const rows = walk(models)
  .map((file) => {
    const data = fs.readFileSync(file);
    return [path.relative(models, file).split(path.sep).join('/'), createHash('sha256').update(data).digest('hex'), data.length];
  })
  .sort((a, b) => (a[0] < b[0] ? -1 : a[0] > b[0] ? 1 : 0));

const body = rows.map(([file, sha256, bytes]) => `  '${file}': ['${sha256}', ${bytes}],`).join('\n');
const source = `// Generated by tools/model-files.mjs: run \`node tools/model-files.mjs\` after changing any model. Do not edit by hand.
/** Every GLB under public/models: SHA-256 and size in bytes, by its path there (A68). */
export const MODEL_FILES: Readonly<Record<string, readonly [sha256: string, bytes: number]>> = {
${body}
};
`;
fs.writeFileSync(path.join(root, 'src', 'presentation', 'assets', 'modelFiles.ts'), source);
console.log(`${rows.length} models, ${(rows.reduce((sum, row) => sum + row[2], 0) / 1e6).toFixed(1)} MB`);
